docs/guide/src/pcli/install.md
Just went through the process of installing `pcli` and got the following error:
> failed to select a version for `ibc-proto` which could resolve this conflict
Fixed it by updating the `rustc` version to `1.7.3`. Perhaps specifying it in the docs will save others some time.
=> specifying `rustc` version requirement in `pcli` installation docs

tools/summonerd/src/storage.rs, tools/summonerd/src/storage/old-to-new-migration.sql, tools/summonerd/src/storage/schema-new.sql
=> summonerd: add new schema separating blob data

crates/bin/pd/src/main.rs, deployments/charts/penumbra-node/templates/deployment.yaml
This PR adds a `--simulate-trade-service` flag to `pd` that activates the DEX trade simulation service, which allow users to send `SimulateTrade` RPCs. The service is disabled by default, because it can be onerous to run it against a rich orderbook, and therefore is a potential DoS vector.
=> pd: add `--enable-expensive-rpc` flag

tools/summonerd/src/participant.rs
Basically, we should treat this as a rare but expected thing, and blame and strike the participant for this, rather than bring down the server as if it were an unexpected failure.
This oversight seems to have been the cause off a crash at 2023-11-12T06:49:56Z.
=> Summonerd: gracefully handle participant message channel closing

tools/summonerd/src/coordinator.rs, tools/summonerd/src/participant.rs, tools/summonerd/src/server.rs
This improves the ban error message, and also adds an error message for timeouts, versus just closing the connection.
=> Summonerd friendlier error messages

crates/bin/pcli/src/command/view/balance.rs, crates/view/src/client.rs, crates/view/src/storage.rs, crates/view/src/sync.rs, crates/wasm/src/storage.rs
View: removes code to skip storage of output notes of value 0, adds code to include transaction ids for incoming swaps to filtered blocks.
Closes #2547
Closes #3214
=> Fix broken list-tx-hashes function for swap claims

.github/workflows/release.yml, Cargo.toml
In this commit we move from cargo-dist 0.0.4 to 0.4.2. The tooling updates are considerable, as the version number implies. To test, I regenerated the workflow YAML and run it many times in a private fork of the repo. With the notable change that we're no longer building binaries for Windows (#3298), everything else looks to work pretty well. Even better, the runtime for the workflow has decreased from ~60m to ~20m, with the biggest win skipping Windows builds.
Refs #3279, #3298.
=> ci: update cargo-dist for performing releases

deployments/config/grafana/dashboards/Client Info.json, deployments/config/grafana/dashboards/Transactions.json, deployments/config/grafana/dashboards/sync.json
A few grafana charts have gone dark, as a result of the underlying metric being renamed. Here are a few quick fixes. H/t to @hdevalence for catching the CB block rename.
=> fix(metrics): rename grafana metrics to catch up

crates/wasm/src/planner.rs, crates/wasm/src/storage.rs, crates/wasm/src/wasm_planner.rs
Closes https://github.com/penumbra-zone/penumbra/issues/3333
Changes this PR will entail in web repo -  https://github.com/penumbra-zone/web/pull/245
=> added source control support to wasm planner

.github/workflows/buf-pull-request.yml, .github/workflows/deploy-preview.yml, .github/workflows/deploy-testnet.yml, .github/workflows/release.yml, Cargo.toml, crates/bin/pcli/src/command/debug.rs, crates/bin/pcli/src/command/view/transaction_hashes.rs, deployments/ci.sh, deployments/scripts/gha-repository-dispatch
This PR prepares the upcoming `v0.63.2` point release. See context in https://github.com/penumbra-zone/penumbra/issues/3182#issuecomment-1809402338. As described there, most of these changes are CI related, geared toward providing working binary builds again. There are also two (2) QoL pcli improvements. 
After this PR is merged into the `release/0.63.x` branch, the usual `cargo release` steps will be performed on that branch, including a tag, to trigger the point release.
=> Prepare 0.63.2 release

.github/workflows/rust.yml, crates/storage/src/snapshot.rs, crates/storage/src/snapshot_cache.rs, crates/storage/src/storage.rs, crates/storage/tests/migration.rs, crates/storage/tests/substore_tests.rs
Chain operators need to be able to migrate their chain state. Previously, our state model maintained a single merkle tree with a global prefix. With the addition of substores, we now maintain multiple trees for each configured prefix, "mounting" them in the main store (see #3131). To maintain continuity between cometbft block height, compact block height, and merkle tree versions, we need to allow commit to storage that does not increase the state's version.  This PR extends support for this type of migration to substores.
=> storage: enable migration for substores

.github/workflows/disable-faucet.yml
Adds a GHA workflow to destroy the Galileo deployment. Since starting the summoning ceremony, load has been very high on Galileo. Despite perf improvements, the bot can still act up. This action allow a one-time action to destroy the bot deployment.
=> ci: add workflow for disabling faucet

.github/workflows/buf-pull-request.yml, .github/workflows/buf-push.yml, .github/workflows/containers.yml, .github/workflows/deploy-preview.yml, .github/workflows/deploy-testnet.yml, .github/workflows/notes.yml, .github/workflows/npm.yml, .github/workflows/rust.yml, .github/workflows/smoke.yml, .github/workflows/summoner_smoke.yml
We were using checkout v2 & and v3 in a few places, when v4 is the latest. v2 shows a deprecation warning:
The following actions uses node12 which is deprecated
and will be forced to run on node16: actions/checkout@v2.
For more info:
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
=> ci: update checkout actions to v4

.github/workflows/deploy-preview.yml
Don't cancel mid-run, as an interrupted `helmfile sync` can create broken release states in the kube API server that require manual cleanup.
=> ci: serialize preview deploys

deployments/config/grafana/dashboards/ABCI.json, deployments/config/grafana/dashboards/Penumbra.json, deployments/config/grafana/dashboards/Transactions.json, deployments/config/grafana/dashboards/Validators.json, deployments/config/grafana/dashboards/sync.json
Two changes to address issues I had when reusing the Grafana dashboards for a full node and validator:
- The ABCI dashboard relies on a metric that CometBFT emits with a name that now includes the unit (seconds)
- The Sync, Transactions, and Penumbra dashboards have at least some hardcoded Prometheus plugin UID's. Turning this into a parameter makes the dashboard reusable, and is the approach the other dashboards take.
- The Validators dashboards looks for a `role` label with the value `consensus` on the validator counts that is not emitted
- The Penumbra dashboard looks for a `worker` label with the value `consensus` on the validator counts that is not emitted - it also creates a panel that performs a group operation over `workers` filtered to `consensus` value, which, if present, would …
=> Update Grafana Dashboards

crates/wasm/Cargo.toml, crates/wasm/src/error.rs, crates/wasm/src/planner.rs, crates/wasm/src/storage.rs, crates/wasm/src/tx.rs, crates/wasm/src/wasm_planner.rs, crates/wasm/tests/test_build.rs
References #3406. 
For testing purposes, we can conditionally mock a sample `IdbDatabase` database using the `mock-database` feature. This enables stripping out unnecessary business logic from the production code. The command to run the test suite is `wasm-pack test --chrome -- --test test_build --target wasm32-unknown-unknown --release --features "mock-database"`
=> refactor(wasm): clean up split-up build

Cargo.lock, crates/bin/pd/Cargo.toml, crates/bin/pd/src/main.rs, deployments/charts/penumbra-node/values.yaml
We want to enable use of pd's gRPC services in arbitrary web contexts, including between localhost and a published website, for debugging. Refs #3281.
=> feat(pd): add permissive cors headers

tools/summonerd/src/participant.rs
The better code pattern for this would be to blanket-handle errors in the method, but at the moment it seems better to just fix the current issue.
=> summonerd: don't bail out on bad contribution data

crates/core/component/ibc/src/prefix.rs, crates/storage/src/snapshot.rs, crates/storage/src/store/multistore.rs, crates/storage/src/store/substore.rs, crates/storage/tests/migration.rs, crates/storage/tests/substore_tests.rs, crates/wasm/tests/test_build.rs
According to the ICS24 spec, substore prefixes are identifiers. This means that they "MUST" follow precise requirements:
```
An Identifier is a bytestring used as a key for an object stored in state, such as a connection, channel, or light client.
Identifiers MUST be non-empty (of positive integer length).
Identifiers MUST consist of characters in one of the following categories only:
Alphanumeric
., _, +, -, #
[, ], <, >
```
This means that our decision to include a trailing delimiter for our IBC prefix is technically incompatible with the spec. This is unfortunate, because it greatly simplifies the routing logic. However, in practice this could become a problem if a counterparty IBC implementation decides to enforce this requirement.
This PR adds support for removing delimiters from our …
=> storage(substore): add delimiter handling

crates/core/component/stake/Cargo.toml
@conorsch during your cleanup of the commit history, I think one of the dev dependencies in the `penumbra-stake` crate was unnecessarily kept in and snuck into master. To completely resolve the circular dependency bug, that needs to be removed as well.
=> fix: circular dependency cleanup

crates/core/transaction/src/lib.rs, crates/core/transaction/src/plan/action.rs, crates/core/transaction/src/plan/build.rs, crates/core/transaction/src/witness_data.rs, crates/wasm/Cargo.toml, crates/wasm/publish/package.json, crates/wasm/publish/run.ts, crates/wasm/src/build.rs, crates/wasm/src/lib.rs, crates/wasm/src/wasm_planner.rs, crates/wasm/tests/test_build.rs
References #3431 and https://github.com/penumbra-zone/penumbra/issues/3400.
=> refactor(wasm): modularize wasm crate logic

.github/workflows/rust.yml, Cargo.lock
Adding a "git diff" check to ci, in an attempt to catch a situtation where dependencies were modified in Cargo.toml files, but the Cargo.lock file wasn't regenerated.
Also prunes an unused "check" job that was modified in #3022.
=> ci: check for uncommitted lockfiles

.dockerignore, Cargo.lock, crates/bin/pcli/Cargo.toml, crates/bin/pcli/build.rs, crates/bin/pcli/src/command/debug.rs, crates/bin/pcli/src/opt.rs, crates/bin/pclientd/Cargo.toml, crates/bin/pclientd/build.rs, crates/bin/pclientd/src/lib.rs, crates/bin/pd/Cargo.toml, crates/bin/pd/build.rs, crates/bin/pd/src/info.rs, crates/bin/pd/src/main.rs, crates/core/app/Cargo.toml, crates/core/component/stake/Cargo.toml, crates/custody/Cargo.toml, crates/custody/build.rs, crates/misc/measure/Cargo.toml, crates/misc/measure/build.rs, crates/misc/measure/src/main.rs, crates/narsil/narsil/Cargo.toml, crates/narsil/narsil/build.rs, crates/narsil/narsil/src/bin/narsild.rs, crates/view/Cargo.toml, crates/view/build.rs, crates/view/src/storage.rs, deployments/containerfiles/Dockerfile, tools/summonerd/Cargo.toml, tools/summonerd/build.rs, tools/summonerd/src/main.rs
We remove the `vergen` build dependency from all crates in the workspace, in order to speed up local builds, and slightly improve CI cache performance. The only downside to this change is that version strings are now hardcoded, based on the version specified in `Cargo.toml`,  e.g. `v0.63.2`.
Refs #3436.
=> build: stop using vergen

crates/wasm/Cargo.toml
Follow-up to #3432. Shutting this customization off, because it was being ignored anyway, and generated a warnig:
warning: profiles for the non root package will be ignored,
specify profiles at the workspace root
We should discuss whether keeping the wasm crate inside the workspace is the right move.
=> build: remove unused wasm profile

crates/core/keys/src/keys/diversifier.rs
This commit changes the Rust code to omit the `randomizer` field if it is zero-valued, so that the protobuf notion of default values aligns with the application-level notion of default values.
=> keys: Align AddressIndex proto serialization

crates/core/component/sct/src/component/view.rs, crates/core/component/sct/src/event.rs
This allows indexers to report on SCT roots and anchors. As a side effect, this also means that there will be at least one event fired in every single `EndBlock`, so every block will have at least one event sent to the indexer.
cc @ejmg
=> sct: add ABCI events for SCT roots

crates/view/src/storage.rs
Closes #3329
This restores configurations we had prior to migrating to rusqlite.
Even on MacOS this results in speed improvements syncing the chain with a newly generated wallet:
```
~/c/p/penumbra3 ((v0.63.1)|✔) $ cargo run --quiet --release --bin pcli -- --home /tmp/pcli-scratch-sync-test/ view sync
Scanning blocks from last sync height 0 to latest height 241904
[28s] ██████████████████████████████████████████████████  241904/241904  8429/s ETA: 0s
```
vs
```
~/c/p/penumbra2 (sqlite-pragmas|✔) $ cargo run --quiet --release --bin pcli -- --home /tmp/pcli-scratch-sync-test/ view sync
2023-11-15T05:52:24.778662Z ERROR r2d2: database is locked
2023-11-15T05:52:24.778666Z ERROR r2d2: database is locked
Scanning blocks from last sync height 0 to latest height 241981
[18s] …
```
=> Try restoring SQLite pragmas

crates/crypto/proof-params/src/lib.rs, crates/wasm/src/keys.rs
The purpose of `try_load_unchecked` is to bypass the expensive hash [operation](https://github.com/penumbra-zone/penumbra/pull/3337/commits/cb83595b52d3e58b6aca6d2afcca804f8127ad1d#diff-4d79c375b208fed2ca0ad42ad928b14507df16e1569c0895594b278be7aff0e4R59) used for fingerprinting the proving keys in WASM. This reduces the `load_proving_key` call times by **80%**.
=> refactor(wasm): try_load_unchecked method

crates/bin/pcli/src/command.rs, crates/bin/pcli/src/command/init.rs, crates/bin/pcli/src/command/threshold.rs, crates/bin/pcli/src/config.rs, crates/bin/pcli/src/main.rs, crates/bin/pcli/src/opt.rs, crates/bin/pcli/src/terminal.rs, crates/crypto/decaf377-frost/src/keys.rs, crates/custody/src/threshold.rs, crates/custody/src/threshold/config.rs, crates/custody/src/threshold/sign.rs
Closes #3343.
Closes #3344.
Closes #3345.
Probably want to merge #3383  first, then switch this PR to be based on main, and review it.
=> Add threshold custody commands to pcli

deployments/helmfile.d/penumbra-testnet.yaml
After five weeks running Testnet 63 Rhea (#3182), the PL-run nodes filled up their available disk storage, which is 100G per node. (Of that, roughly 90% is pd, 10% cometbft.) To recover, we manually edited the PVCs to grow to 200G, and this change locks that new config into version control, for use in future testnets.
=> deploy: increase node storage 100G -> 200G

crates/view/src/storage.rs, deployments/config/grafana/dashboards/ABCI.json, deployments/config/grafana/dashboards/Client Info.json, deployments/config/grafana/dashboards/Penumbra.json, deployments/config/grafana/dashboards/Transactions.json, deployments/config/grafana/dashboards/Validators.json, deployments/config/grafana/dashboards/sync.json
This PR prepares the upcoming v0.63.3 point release. The changes proposed are:
* fixes to grafana metrics dashboards
* faster sync performance on linux, thanks to use of sqlite pragmas
=> Prepare 0.63.3 point release

crates/bin/pd/src/main.rs, crates/bin/pd/src/testnet/generate.rs, deployments/charts/penumbra-network/templates/job-generate.yaml, deployments/charts/penumbra-network/values.yaml
During testing of upgrades, it's been handy to reduce the default, static value of "24h" for voting on a given proposal, so that a proposal can be made, voted on, and passed, all within e.g. 1h. This setting greatly accelerates testing on devnets.
Also includes customization var in deploy scripts for `epoch_duration`, which we're not currently overriding, but now we can if we want to.
Ideally we'd set these customizations by just overriding the `pd testnet generate` command, but given that the cmd requires a storage dir arg that's non-standard, it's more straightforward to stick with the clunky vars-based approach for now.
=> feat(pd): custom voting periods testnet generate

.github/workflows/deploy-preview.yml, .github/workflows/deploy-testnet.yml, .github/workflows/disable-faucet.yml
The prior versions of our GHA helpers were throwing an error on deploy:
The v0 series of google-github-actions/auth is no longer maintained.
It will not receive updates, improvements, or security patches.
Please upgrade to the latest supported versions
Patching both the /auth and /get-gke-credentials GHA helpers.
=> ci: fix gke auth actions

Cargo.lock, crates/core/component/shielded-pool/src/component/action_handler/ics20_withdrawal.rs, crates/core/component/shielded-pool/src/component/transfer.rs
This should close the remaining balance of payments task in #981.
=> ics20: implement balance of payments for non-penumbra origin assets

crates/bin/pd/src/main.rs, crates/bin/pd/src/upgrade.rs
This PR makes the `SimpleUpgrade` migration script generate a fresh validator state file to populate comet's view of the validator data. It also adds an optional `--genesis-start` flag to `pd upgrade` to help testing with multinode setups.
=> pd(upgrade): create fresh validator state and accept `--genesis-start`

crates/bin/pd/src/upgrade.rs
After an upgrade, a migrated genesis files contains the root hash of the application's merkle tree, and an arbitrary bytestring which can be used to perform component-specific health checks. Although the field is a no-op in the simple upgrade scenario, it is a bit confusing that it contains `[32u8; 32]` instead of the application hash. This PR fixes this.
=> pd(upgrade): use checkpoint in simple upgrade

.github/workflows/notes.yml
We were lagging pretty far behind on the GHA helper we use for firebase deploys. Let's try the latest.
=> ci: fix firebase deploy

crates/core/component/ibc/src/component/client_counter.rs
Since we're using two JMT specs now, we need to extend the legacy mode to allow both to have no `prehash_key_before_comparison`.
=> ibc: extend prehash_key_before_comparison hack for new substore spec

docs/guide/src/dev/protobuf.md, docs/guide/src/pd/install.md, docs/guide/src/pd/join-testnet.md, docs/protocol/src/concepts/batching_flows.md, docs/protocol/src/crypto/flow-encryption/dkg.md, docs/protocol/src/crypto/flow/ideal.md, docs/protocol/src/governance.md, docs/protocol/src/ibc.md, docs/protocol/src/zswap/swap.md, docs/rustdoc/README.md
I've made a series of updates to the project documentation to enhance clarity and correct minor typographical errors. Below is a summary of the changes:
1. *Fix Typos in Various Sections:*
- Corrected a typo in the 'Algorithms and Protocols' section.
- Addressed a typo in the NOTE section of 'flow-encryption/dkg.md'.
- Fixed a typo in the 'Maintaining protobuf specs' section.
- Corrected a typographical error in the installation instructions.
- Addressed a typo in the 'Privacy for Market-Takers' section.
- Fixed an orthographic mistake in the Rustdoc README file.
- Corrected a typo in the governance documentation.
- Addressed a typo in the IBC protocol documentation.
2. *Enhance Phrasing and Grammar:*
- Improved phrasing in the 'Updating your validator' section.
- Corrected redundant …
=> Improvements to Documentation Clarity and Accuracy

crates/core/component/dex/src/swap_claim/proof.rs
=> test: add randomized `BatchSwapOutputData` in `SwapClaim` proptests

.github/workflows/buf-pull-request.yml, .github/workflows/containers.yml, .github/workflows/notes.yml, .github/workflows/release.yml, .github/workflows/rust.yml, .github/workflows/smoke.yml, .github/workflows/summoner_smoke.yml, Cargo.toml
We were building binaries on Ubuntu 20.04, which made using those binaries on newer platforms (e.g. Debian Stable 12 Bookworm) throw ssl shared object errors. A few folks reported this problem in Discord. Building on the new runners resolves this problem, at least for Debian Stable. I haven't done a full matrix of platform compatibility, nor do I plan to: listening to reports in Discord is data enough for now.
Also bumps cargo-dist 0.4.2 -> 0.5.0.
Trying to stay on top of cargo-dist version changes, so we don't get surprised by a large diff. Already tested this version in a private fork and it worked great.
=> ci: upgrade runners ubuntu-2004 -> ubuntu-2204

crates/custody/Cargo.toml
Our CI actions were alleging this was invalid TOML. The consequence was that the crate wasn't being cached, which doens't matter much, but I want to silence the warning so future runs are clean and quiet.
[skip ci]
=> lint: fix comma in custody cargo toml

deployments/helmfile.d/penumbra-testnet-cuiloa.yaml
We've added a new cuiloa [0] deployment for the testnet environment, available at https://cuiloa.testnet.penumbra.zone. This change handles the fullnode and sidecar postgres indexing setup required to back the cuiloa app deployment (config for which is managed elsewhere).
This change has already been deployed.
[0] https://github.com/penumbra-zone/cuiloa
=> feat: cuiloa-testnet fullnode

docs/guide/src/pcli/transaction.md
Ran through the relayer setup for Hermes, documented here: https://guide.penumbra.zone/main/dev/ibc.html . Hermes is currently running on the old, forked version of code. We haven't yet rebased Hermes against latest upstream main (#3477).
=> docs: update ibc channel for titan

crates/proto/src/protobuf.rs, proto/penumbra/penumbra/core/component/compact_block/v1alpha1/compact_block.proto, proto/penumbra/penumbra/core/component/sct/v1alpha1/sct.proto
Found this bug while testing the IBC implementation with Hermes. Previously it was writing an `Any` type to state at the client_state/consensus_state storage locations, but the type Hermes was expecting was the `ibc_proto` `ClientState`/`ConsensusState`. This resulted in a proto decoding error in these locations:
https://github.com/informalsystems/hermes/blob/master/crates/relayer/src/client_state.rs#L127
https://github.com/informalsystems/hermes/blob/master/crates/relayer/src/consensus_state.rs#L59
These are called in the `Endpoint` `query_client_state`/`query_consensus_state` methods (for example here https://github.com/informalsystems/hermes/blob/b98ca86991fc1cc6d3f6c595918251a34eb6f1db/crates/relayer/src/chain/cosmos.rs#L1238)
specifically the error I got from Hermes was …
=> fix(proto): update `DomainType::Proto` for `ClientState/ConsensusState`

Cargo.lock, crates/bin/pcli/Cargo.toml, crates/bin/pclientd/Cargo.toml, crates/bin/pd/Cargo.toml, crates/cnidarium/Cargo.toml, crates/core/app/Cargo.toml, crates/core/component/chain/Cargo.toml, crates/core/component/ibc/Cargo.toml, crates/core/component/shielded-pool/Cargo.toml, crates/core/transaction/Cargo.toml, crates/proto/Cargo.toml, crates/view/Cargo.toml, crates/wasm/tests/test_deserialize.rs, tools/proto-compiler/Cargo.toml
Unblocks: https://github.com/penumbra-zone/web/issues/248 which requires the updated protojson serialization methods
=> Bump ibc-types deps

.github/workflows/deploy-preview.yml, .github/workflows/deploy-testnet.yml
We've disabled Osiris, likely indefinitely, so let's remove it from the CI workflows. Otherwise, preview deploys report as failed, even though the preview environment was created succesfully. In the medium term, we hope to have a Hummingbot service running, which will serve a similar role to Osiris.
Also removes the unused relayer reboot, as we're using Hermes for IBC now.
=> ci: disable osiris handling

deployments/helmfile.d/vars/penumbra-devnet-nodes-ips.yml, deployments/helmfile.d/vars/penumbra-preview-nodes-ips.yml, deployments/helmfile.d/vars/penumbra-testnet-nodes-ips.yml, deployments/scripts/get-lb-ips, testnets/names.txt
We've shipped testnets for the Jovian and Saturnine moons. Now, we add the Mars of moons, only two (2). If we need more than this, we can follow up with the moons of Neptune for more headroom.
Also updates the names of fullnodes in the CI deployment, which were previously set to moons of Mars and Neptune. Now moon names are only used to refer to testnets, and the fullnode monikers are notable asteroids.
=> ci: add moons of mars to testnet names

docs/guide/src/resources.md
Consolidating talk URLs from a few different places, such as onboarding docs, Discord, and of course this guide.
=> docs: add more talk urls

docs/guide/src/pcli/transaction.md
Follow up to 41345e5958840fd2e8a0b7f16f2a8fd7181bcbd6, which updated the IBC info, but didn't update the testnet name from Rhea to Titan.
=> docs: update testnet name for ibc 63 -> 64

deployments/helmfile.d/penumbra-testnet-cuiloa.yaml
The testnet fullnodes had their storage increased in [0], and the fullnode backing the testnet cuiloa instance should have the same allotment. Also pinning a specific version of penumbra container, so that newer (and incompatible) versions aren't pulled on restart.
[0] bff43e609e7a2a1730728ee7a310e4c8eeb603d4
=> ci: increase cuiloa testnet storage

flake.lock, flake.nix
this defines a development environment for developers using nix flakes. a `flake.nix` and an accompanying `flake.lock` lockfile is included.
this can be started by running `nix develop`; see the [nixos manual], ["zero to nix"][zero-to-nix] and [these][lime] [posts][jvns] for more information about nix flakes.
[nixos manual]: https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-develop
[zero-to-nix]: https://zero-to-nix.com/concepts/flakes
[lime]: https://fasterthanli.me/series/building-a-rust-service-with-nix/part-10
[jvns]: https://jvns.ca/blog/2023/11/11/notes-on-nix-flakes/
=> feat: 🥐 nix flake development environment

docs/guide/src/pd/validator.md
I've been following the instructions for running a full node and setting up a validator. During this process, I noticed that in the section for delegating to a validator, the documentation provides an example command with a specific address. Here is the current command:
```console
pcli tx delegate 1penumbra --to penumbravalid1g2huds8klwypzczfgx67j7zp6ntq2m5fxmctkf7ja96zn49d6s9qz72hu3
```
While executing these steps quickly, I inadvertently used the example address in the command without realizing it. This might be a common oversight for others who are also setting up their nodes and validators in a similar manner.
To prevent such mistakes, I propose we use a placeholder for the validator's identity key, similar to how it's done in the governance section of the Penumbra guide: …
=> refactor: Use Placeholder for Validator Identity Key in Documentation

deployments/relayer/configs/penumbra-preview.json, deployments/relayer/configs/penumbra-testnet.json, docs/guide/src/pcli/transaction.md
Intentionally created a second channel via Hermes, still on Testnet 64 Titan, in an attempt to restore relaying functionality.
=> docs: update testnet 64 ibc channel

crates/bin/pd/src/main.rs
A common problem for node operators is sorting out which ports are required to be available on the system prior to running. We've recently improved the documentation to be more explicit about this [0], but here we add explicit error messages when binds fail. This addition should make reasoning about network surface more straightforward, and eliminate guessing games to figure out which port needs to be overridden or freed.
[0] c0445f34752f64a253b672188f3a6d8f5f58c116
=> feat(pd): report bind errors on startup

.github/workflows/buf-pull-request.yml
Follow up to #3292, which incorrectly used `pull_request_target` rather than `pull_request` to restrict workflow runs to PRs targeting main. We still want to skip the buf workflows if the PR is targeting a feature branch.
Closes #3570.
=> ci: fix buf workflow on PRs

crates/bin/pcli/src/command/ceremony.rs, crates/bin/pcli/src/command/view/balance.rs, crates/bin/pcli/src/command/view/staked.rs
I don't quite know when this regression was introduced, but it's related to unused variables and imports.
=> Fix unused variable / import warnings in pcli

.github/workflows/rust.yml, crates/core/component/governance/src/metrics.rs, crates/core/component/ibc/src/component/metrics.rs, crates/core/component/shielded-pool/src/component/metrics.rs, crates/crypto/decaf377-frost/src/traits.rs, crates/crypto/tct/src/internal.rs, crates/view/src/metrics.rs
Satisfies the latest cargo lints. I took the easy way out, preserving the existing function sigs, rather than performing a deeper refactor. Ignored the checks on the re-export of metrics code across components.
Holding off on adding `--all-targets` to the check command, because there's some cleanup to do in the benchmarks, related to #3556.
Revert "ci: disable -D warnings"
This reverts commit 4e7c77b7404e69ab279d8d273a56935e7dba53c7.
Refs #3543.
=> chore: cargo lint

crates/core/component/ibc/src/component/rpc/client_query.rs
update the `consensus_state` gRPC method to handle height in the request properly.
=> fix(ibc): fix `consensus_state` gRPC method to properly handle height

crates/bin/pcli/src/command/query/ibc_query.rs, crates/bin/pcli/src/command/tx.rs
Closes #3206 . Won't work until we have implemented the remaining IBC queries (currently all the channel ones are missing)
=> pcli: use a default timeout height for ibc withdrawals

.github/workflows/rust.yml
As of #3579 we can now enable `cargo check --all-targets` to ensure that even benchmarks are included in `cargo check`.
Closes #3543.
=> ci: cargo check all targets

crates/wasm/tests/test_build.rs
Fixes breaking changes from https://github.com/penumbra-zone/penumbra/pull/3527 and https://github.com/penumbra-zone/penumbra/pull/3579
=> wasm(fix): failing unit test

crates/core/app/src/action_handler/actions/submit.rs, crates/core/app/src/action_handler/transaction.rs, crates/core/transaction/src/memo.rs, crates/core/transaction/src/plan.rs, crates/core/transaction/src/plan/auth.rs, crates/custody/src/soft_kms.rs, crates/custody/src/threshold.rs, crates/custody/src/threshold/sign.rs, crates/wasm/src/tx.rs
identified a panic when working on web transactions.
added checks to verify text length is under maximum when deserializing from `pbt::MemoPlaintext` or `Vec<u8>`, to prevent the creation of impossible memos. perhaps `MemoPlaintext` should use private fields and a constructor to enforce format limitations that cannot be specified by protobuf, but this is a smaller change.
ultimately the source of the panic was an `expect` used in `TransactionPlan::effect_hash` to unwrap a potential error, this is now bubbled as `anyhow::Result`
=> MemoPlaintext string length enforced, TransactionPlan panic avoided

crates/bench/benches/output.rs, crates/bench/benches/swap.rs, crates/bench/benches/swap_claim.rs, crates/bin/pcli/tests/proof.rs, crates/core/component/dex/src/component/action_handler/swap.rs, crates/core/component/dex/src/component/action_handler/swap_claim.rs, crates/core/component/dex/src/swap/plan.rs, crates/core/component/dex/src/swap/proof.rs, crates/core/component/dex/src/swap_claim.rs, crates/core/component/dex/src/swap_claim/plan.rs, crates/core/component/dex/src/swap_claim/proof.rs, crates/core/component/shielded-pool/src/component/action_handler/output.rs, crates/core/component/shielded-pool/src/output.rs, crates/core/component/shielded-pool/src/output/plan.rs, crates/core/component/shielded-pool/src/output/proof.rs, crates/core/component/stake/src/action_handler/undelegate_claim.rs, crates/core/component/stake/src/undelegate_claim/mod.rs, crates/core/component/stake/src/undelegate_claim/plan.rs, crates/core/component/stake/src/undelegate_claim/proof.rs
=> Implement remaining public x private refactorings for circuits

crates/bin/pcli/src/command/ceremony.rs, crates/bin/pcli/src/command/tx.rs, crates/core/transaction/src/memo.rs, crates/core/transaction/src/plan.rs, crates/core/transaction/src/plan/memo.rs, crates/core/transaction/src/transaction.rs, crates/view/src/service.rs, crates/view/src/storage.rs, crates/wasm/src/tx.rs
This also has the side effect of making PCLI more robust to users placing a plaintext that's too large.
=> Make MemoPlaintext have an opaque constructor

crates/core/component/ibc/src/component.rs, crates/core/component/ibc/src/component/client_counter.rs, crates/core/component/ibc/src/component/ics02_validation.rs, crates/core/component/ibc/src/component/msg_handler/connection_open_ack.rs, crates/core/component/ibc/src/component/msg_handler/connection_open_try.rs, crates/core/component/ibc/src/component/msg_handler/create_client.rs, crates/core/component/ibc/src/component/msg_handler/misbehavior.rs, crates/core/component/ibc/src/component/msg_handler/update_client.rs
nb: this branch strictly contains plain code motion. it does not make any
changes to the code being moved.
this branch performs two simple transformations, broken into two commits:
`ics02_validation` contains some important code for interfacing with
tendermint/cometbft. while this submodule lives beneath the client counter
logic, its contents are used in our message handling code related to e.g.
misbehavior.
this hoists this submodule up one level, to be a child of
`penumbra_ibc::component`.
while validate_penumbra_client_state was not originally placed in the ics02_validation submodule,
it feels like it is more connected to that validation logic than the
surrounding client counter types.
this bears out to be true; it is `pub`, the client counter code isn't changed,
and affected imports …
=> ibc: ⛅ hoist ics02 validation out of client_counter

docs/protocol/src/protocol/addresses_keys/spend_key.md
Quick typo fix in docs (surmised based on [the official implementation](https://github.com/penumbra-zone/penumbra/blob/main/crates/core/keys/src/keys/spend.rs#L67-L75)).
=> typo: PRF takes input 1 (not 0) when deriving `nk`

docs/guide/src/dev.md, docs/guide/src/resources.md
Reorganized the dev docs resources to include URLs to the public project boards where tickets are organized for development sprints. This gives us a single resource to update as workflows change.
=> docs: add work planning urls to guide

crates/core/component/stake/src/action_handler/validator_definition.rs, crates/core/component/stake/src/validator.rs
Close #2066, adds a 70, 140, and 280 characters limit on website/name/description respectively.
=> staking: length-limit validator definition strings

crates/bin/pclientd/src/lib.rs
The `--help` docs are a bit unclear about what should be passed to the `--view` option. This change makes it clear that the argument should be a full viewing key.
```
$ cargo run --bin pclientd init --help
...
pclientd-init
Generate configs for `pclientd` in view or custody mode
USAGE:
pclientd init [OPTIONS]
OPTIONS:
--view <VIEW>
If provided, initialize in view mode with the given full viewing key
--custody <CUSTODY>
If provided, initialize in custody mode with the given seed phrase.
If the value '-' is provided, the seed phrase will be read from stdin.
--bind-addr <BIND_ADDR>
Sets the address to bind to to serve gRPC
[default: 127.0.0.1:8081]
--grpc-url <GRPC_URL>
Sets the URL of the gRPC endpoint used to talk to pd
[default: https://grpc.testnet.penumbra.zone]
-h, --help
Print help …
```
=> Set the value_name for the pclientd --view option

crates/core/component/dex/src/swap/plaintext.rs, crates/core/component/dex/src/swap/proof.rs, crates/core/component/dex/src/swap_claim/proof.rs, crates/core/component/shielded-pool/src/output/proof.rs
=> test: add proptests of remaining circuits vs an in rust impl

crates/bin/pcli/src/command/tx.rs, crates/bin/pcli/tests/network_integration.rs
Turns out the spooky failure of the tx sweep integration test was just that sweeping was taking slightly longer, and `pcli tx sweep`was still using a naive sleep, rather than the more robust await-confirmation logic that we've built into the planner.
This reverts commit 5b4fb169266e5bd46052ae53a0d29321859a73a5.
Closes #3621.
=> ci: re-enable transaction sweep test

crates/bin/pcli/src/command/tx.rs, crates/bin/pcli/src/command/tx/liquidity_position.rs, crates/bin/pcli/src/network.rs, crates/bin/pcli/tests/network_integration.rs, crates/core/app/src/action_handler/transaction/stateful.rs, crates/core/component/fee/src/gas.rs, crates/core/component/fee/src/genesis.rs, crates/core/transaction/src/gas.rs, crates/core/transaction/src/plan.rs, crates/view/src/planner.rs, crates/view/src/service.rs, crates/wasm/src/planner.rs
This fixes some issues discovered when end-to-end testing fees in the extension and pcli.
* Fee signs were flipped
* Change notes were not properly accounted for
There are potential footguns in this implementation that are commented and should be addressed in a followup issue:
```rust
// Since paying the fee possibly requires adding additional Spends and Outputs
// to the transaction, which would then change the fee calculation, we multiply
// the fee here by a factor of 8 and then recalculate and capture the excess as
// change outputs.
//
// TODO: this is gross and depending on gas costs could make the gas overpayment
// ridiculously large (so large that the account may not have notes available to cover it)
// or too small. We may need a cyclical calculation of fees on the transaction …
```
=> Handle change note fees

crates/core/keys/src/test_keys.rs
This makes development easier by allowing copy pasting of the encoded FVK.
=> keys: add string for test account FVK

crates/bin/pcli/src/command/tx.rs, crates/bin/pcli/src/network.rs, crates/core/app/src/action_handler/transaction/stateful.rs, crates/core/component/fee/src/gas.rs, crates/core/component/fee/src/genesis.rs, crates/view/src/planner.rs, crates/wasm/src/planner.rs
In #3624, the default gas prices were changed to have nonzero values, in order to test client functionality with nonzero fees. However, we *don't* want to make this the default until we've ported all the client software over, and even then, we should make the gas price setting be part of the `AppParameter`s, rather than changing the default value. (We want the default value for `GasPrices` to align with the proto default value).
=> fee: fix regression in #3624

crates/bin/pcli/src/command/ceremony.rs
As plan to transition to phase 2 of the summoning ceremony along with the release of Testnet 65. Here we update the default value for `pcli ceremony contribute --phase` to be `2`, rather than a required arg. The summoning website already displays an explicit example command, and the value for "phase" is determined by the phase of the coordinator server, so no changes needed there.
=> feat(pcli) default to phase 2 for ceremony

crates/wallet/src/build.rs
This change was necessary in order to build `penumbra-wallet` directly, e.g. via `cargo build -p penumbra-wallet -r`. After this change, the entire workspace can be built across all feature combinations. Verify this with:
cargo check-all-features --workspace --all-targets
That command will take ~30m wall time, depending on specs, and somewhere between 50-100GB on disk. We don't run this task in CI, see #2210 for context.
=> fix(wallet): update non-parallel tx building

crates/bin/pd/src/consensus.rs, crates/core/app/src/app/mod.rs
Previously, the handling of `{Prepare, Process}Proposal` messages was done in the consensus service. This is confusing, because although we do not do implement any meaningful proposer-based logic, the application interface is the natural place for those methods to be implemented.
=> app: add interface for prepare/process proposal

deployments/charts/penumbra-node/templates/ingressroute.yaml
Follow-up to 1d688c2d1ebc18fab4cf2172d9078513e05be37b, observed post-deploy that the public HTTPS endpoints weren't responding. We're preserving the old service names for convenience's sake, so let's reuse them throughout.
Other than this fix, the only manual interaction required for the preview deployment to heal after the rewrite was to remove the `app=` selector label from each p2p lb. Will do that manually on testnet when the time comes, as well.
=> ci: fix ingress svc name

crates/bin/pd/src/main.rs
while working on #3627, i found that a conditional hinges on the wrong option.
this changes pd to follow what the comments and documentation state as the
intent of this code: change the default grpc address based on whether we
have an auto-managed https domain.
a second commit refactors the control flow for the default address. the `parse`
calls only refer to hardcoded values defined in the source. let's define our
defaults as constants, so that we do not have error-handling logic that only
refers to what ought to be known-good addresses.
=> 🩹 pd: fix auto-https default grpc address

crates/core/component/stake/src/action_handler/undelegate_claim.rs, crates/core/component/stake/src/action_handler/validator_definition.rs, crates/core/component/stake/src/component.rs, crates/core/component/stake/src/params.rs
This PR fixes an issue with a missing transition (`Active` -> `Defined`) and adds context for each transition case. With that said, writing this code makes me think that we might be better off by limiting the amount of possible transitions, removing `Active -> Defined` and `Jailed -> Defined` transition, and use end-epoch processing to "sweep" inactive validators into the precursor `Defined` state.
Since I am in the middle of an assurance blitz for #3640, I will abstain from making more changes. But this is currently top-of-mind for me. Moreover, manual testing seems to surface issues with Unbonded/Unbonding (observed on `v0.64.0` as well) so I plan to look into that as well.
=> staking: validator state transition fix

.github/workflows/rust.yml, crates/wasm/README.md, crates/wasm/tests/test_build.rs
=> chore(wasm): add CI workflow 

.github/workflows/smoke.yml, deployments/scripts/smoke-test.sh
This PR change the smoke test workflow to independently capture and display logs produced by `cometbft`, `pd`, and the `pcli`/`pclientd` integration tests. This makes it easy to visualize and isolate the source of a smoke test failure.
It also sets a baseline of `info` level debugging for tracing statements, and `debug` level for `network_integration` tests.
Finally, it offers the opportunity for users to run the integration tests with maximum logging level by detecting if debug mode is enabled for this action run (see screenshot).
=> ci: improve smoke test logging

docs/guide/src/pcli/transaction.md
Hermes stopped relaying. One problem is that we needed to raise the gas limits, the diff for which in the Hermes config.toml looks like:
```diff
-gas_price = { price = 0.0026, denom = 'uosmo' }
+gas_price = { price = 0.2, denom = 'uosmo' }
gas_multiplier = 1.1
clock_drift = '20s'
+max_gas = 900000
```
Hermes is up and running on this new info.
=> docs: update ibc channel for testnet 64

.github/workflows/smoke.yml, .gitignore, deployments/scripts/smoke-test.sh
I think I introduced an indentation error, this should fix it!
=> ci: fix smoke test

Cargo.lock, crates/bin/pcli/Cargo.toml, crates/core/asset/Cargo.toml, crates/core/component/chain/Cargo.toml, crates/core/component/distributions/Cargo.toml, crates/core/component/fee/Cargo.toml, crates/core/component/ibc/Cargo.toml, crates/core/component/sct/Cargo.toml, crates/core/keys/Cargo.toml, crates/core/num/Cargo.toml, crates/core/transaction/Cargo.toml, crates/crypto/proof-params/Cargo.toml, crates/misc/measure/Cargo.toml, crates/proto/Cargo.toml, crates/test/tct-property-test/Cargo.toml, crates/view/Cargo.toml, crates/wallet/Cargo.toml, tools/summonerd/Cargo.toml
The command used to generate the list of unused deps was:
cargo +nightly udeps --all-targets --all-features --workspace
Trimmed things back accordingly, including some light feature pruning.
=> chore: prune unused dependencies

crates/wasm/src/dex.rs, crates/wasm/src/lib.rs
Related to https://github.com/penumbra-zone/web/pull/367 
We need a function to compute `PositionId` since `PositionId` is not stored in `Position` (most likely to optimize on-chain storage). 
`PositionId` is needed as a unique position identifier and is also used to update `PositionState` ( see usage https://github.com/penumbra-zone/web/pull/367/files#diff-ccb0493c986b958cf859e773170457e5ff59a4a2e0d742698492247f6ae872da. )
discussion 
https://discord.com/channels/824484045370818580/938328380917559326/1199461586927112283
=> [wasm] Compute position_id

tools/summonerd/src/web.rs
We've passed 10k, we'll never pass 50, seems alright
=> Bump display limit to 50k in summoning ceremony

crates/bin/pd/src/cli.rs, crates/bin/pd/src/lib.rs, crates/bin/pd/src/main.rs
this commit is pure code motion. this moves the `Opt` clap argument parser and option/command definitions to a `pd::cli` submodule. this will help with integration testing of `pd` someday, and helps keep our entrypoint tidy. (_see #3588 for other work related to future integration tests_)
=> pd: 👏 cli commands and options live in `pd::cli`

Cargo.lock, crates/bin/pd/Cargo.toml, crates/bin/pd/src/auto_https.rs, crates/bin/pd/src/main.rs
fixes #3627.
this reorganizes the logic in pd's startup code related to automatically
managed https functionality.
this PR, besides cleaning up the `rustls-acme`-related auto-https logic, is
also interested in *creating a state-of-affairs that will dovetail into
pr #3522*. in particular, this expression to start the GRPC serve given a
bound listener...
```rust
tokio::task::Builder::new()
.name("grpc_server")
.spawn(grpc_server.serve_with_incoming(tls_incoming))
.expect("failed to spawn grpc server")
```
...should be adjusted so as to work with an `axum::Router`.
quoth the #3627 description, citing an earlier comment:
> In the ~year since this code was written, there may be better options.
> `tokio-rustls-acme` seems promising
\- <https://github.com/penumbra-zone/penumbra/pull/3522#discussi …
=> pd: 🔨 rework RootCommand::start auto-https logic

crates/core/component/dex/src/circuit_breaker/execution.rs, crates/core/component/dex/src/circuit_breaker/mod.rs, crates/core/component/dex/src/circuit_breaker/value.rs, crates/core/component/dex/src/component/arb.rs, crates/core/component/dex/src/component/router/path_search.rs, crates/core/component/dex/src/component/router/route_and_fill.rs, crates/core/component/dex/src/component/rpc.rs, crates/core/component/dex/src/lib.rs
This adds a circuit break mechanism to the DEX that bounds the maximum number of path searches and position executions for any given batch swap during a block, to prevent potentially unbounded looping.
Closes #3303
=> Add execution circuit breaker

crates/core/component/dex/src/circuit_breaker/execution.rs
The constructor may eventually be used by tests
=> Allow dead code for currently unused ExecutionCircuitBreaker constructor

deployments/scripts/smoke-test.sh
this is a small cross-platform compatibility change needed to run the smoke tests locally on my machine.
=> smoke-test: 🐚 use `env` to find bash path

crates/core/component/ibc/src/component/msg_handler/update_client.rs
this diff is best viewed ignoring whitespace; use `-w`, or the "_hide whitespace_" option in github (the gear icon in the "_files changed_" tab).
this inverts our early return, so that we do not need to wrap the whole function body within a conditional block. this is a pure refactor that should have no visible changes to behavior.
=> penumbra-ibc: ⏎  invert early return condition

Cargo.lock, crates/bin/pd/src/main.rs, crates/core/app/Cargo.toml, crates/core/app/src/rpc.rs, deployments/scripts/smoke-test.sh
this addresses a todo comment found in the `pd` entrypoint. we are now using `tonic` 0.10 so we can have the `penumbra-app` crate assemble a `Routes`, sparing us the recitation of every service.
=> pd: 📬 create tonic router in penumbra-app

crates/core/component/governance/src/delegator_vote/proof.rs, crates/core/component/shielded-pool/src/nullifier_derivation.rs, crates/core/component/shielded-pool/src/spend/proof.rs
This adds negative proptest strategies for the `SpendCircuit`, `DelegatorVoteCircuit`, and `NullifierDerivationCircuit` towards #3565
=> test: add negative proptest strategies for first three circuits

crates/core/component/dex/src/swap/proof.rs, crates/core/component/dex/src/swap_claim/proof.rs, crates/core/component/shielded-pool/src/convert.rs, crates/core/component/shielded-pool/src/output/proof.rs
=> test: add negative proptest strategies for remaining circuits

Cargo.lock, crates/core/asset/Cargo.toml, crates/core/asset/src/balance.rs, crates/core/asset/src/balance/imbalance.rs, crates/core/component/dex/Cargo.toml, crates/core/component/dex/src/circuit_breaker/mod.rs, crates/core/component/dex/src/circuit_breaker/value.rs, crates/core/component/dex/src/component/mod.rs, crates/core/component/dex/src/component/position_manager.rs, crates/core/component/dex/src/component/router/route_and_fill.rs, crates/core/component/dex/src/state_key.rs
This adds a value circuit breaker to the `PositionManager` logic.
Whenever a position is stored, the total reserve amounts (across _all_ positions) are tracked by the `ValueCircuitBreaker`. If after storing a position the reserve balance ever becomes negative ("required"), this implies that more value was taken out of positions than was stored in them, and an error is bubbled up.
Closes #2986
=> Implement value circuit breaker

crates/wasm/src/planner.rs
After some recent changes to the non-WASM/"regular" planner, the WASM planner was out of sync as regards fee handling. This PR gets it back in sync.
This was hard to test because of some issues in Penumbra core. Steps I took to test it:
- Rebase this PR onto commit https://github.com/penumbra-zone/penumbra/commit/1d368d404cdacda54d231a91728679abb4b73570 per [this Discord discussion](https://discord.com/channels/824484045370818580/930529119165362196/1201634636556664893) about a broken state in core's `main` branch
- Set fees in `crates/core/component/fee/src/genesis.rs`:
```diff
fn default() -> Self {
Self {
fee_params: FeeParameters::default(),
-            gas_prices: GasPrices::default(),
+            gas_prices: GasPrices {
+                block_space_price: 1,
+ …
```
=> Fix fees in WASM planner

docs/protocol/src/concepts/addresses_keys.md, docs/protocol/src/concepts/transactions.md, docs/protocol/src/protocol.md
Just a couple things I noticed while reading the Penumbra protocol.
=> Fix a few mistakes in the Penumbra Protocol docs

crates/bin/pcli/Cargo.toml, crates/bin/pd/Cargo.toml, crates/core/app/Cargo.toml, crates/core/component/community-pool/Cargo.toml, crates/core/component/compact-block/Cargo.toml, crates/core/component/dex/Cargo.toml, crates/core/component/distributions/Cargo.toml, crates/core/component/funding/Cargo.toml, crates/core/component/governance/Cargo.toml, crates/core/component/ibc/src/component/client.rs, crates/core/component/shielded-pool/Cargo.toml, crates/core/component/stake/Cargo.toml, crates/core/transaction/Cargo.toml, crates/custody/Cargo.toml, crates/misc/measure/Cargo.toml, crates/view/Cargo.toml, crates/wallet/Cargo.toml
=> chore: 🧹 remove dangling references to `penumbra-chain`

Cargo.lock, crates/bin/pcli/Cargo.toml, crates/bin/pcli/src/main.rs, crates/bin/pcli/src/opt.rs, crates/proto/Cargo.toml, crates/proto/src/box_grpc_svc.rs, crates/proto/src/lib.rs
We want to make this utility accessible, in order to make interacting with the grpc services easier for callers, in particular the Hermes relayer
=> proto: move box_grpc_svc to proto crate

.github/workflows/containers.yml
The fork repo for hermes was reset, so the referenced workflow no longer exists. This was causing an HTTP 422 in the build logic. Removing hermes references to sidestep the problem and unbreak preview deploys.
=> ci: remove hermes build

crates/core/app/Cargo.toml, crates/core/app/src/lib.rs
this is a small bit of cleanup, as i've been reading through the app crate. add crate metadata present elsewhere in our workspace, and polish the top-level `lib.rs` file.
=> chore(app): 🏴 organize `lib.rs`, metadata for `Cargo.toml`

crates/bin/pd/src/cli.rs, crates/bin/pd/src/main.rs
Follow up to https://github.com/penumbra-zone/penumbra/pull/3705, which was subtly broken: the `--acme-staging` flag was *always* set to true, so I was getting staging certs even when I wanted prod ones. The problem was mistaken use of `default_value` in the clap derive markers. Simply setting the arg type as bool is sufficient; neither `default_value` nor `default_value_t` are appropriate here.
=> fix(pd): acme-staging flag should default to false

crates/view/src/worker.rs
Currently, any transient error in the view worker permanently stops the server forever. Instead, restart after a delay.
=> view: auto-restart view worker on error

crates/bin/pcli/src/command/ceremony.rs, tools/summonerd/src/web.rs, tools/summonerd/templates/main.html
During Phase 1 of the summoning ceremony, some contributors were confused about the `--coordinator-address` flag, and incorrectly overrode it to a wallet address they control. Let's set a sane default value for that arg, and remove its display from the web page.
=> feat(pcli): default coordinator address for ceremony

Cargo.lock, crates/bin/pclientd/Cargo.toml, crates/bin/pd/Cargo.toml, crates/bin/pd/src/mempool.rs, crates/bin/pd/src/metrics.rs, crates/cnidarium/Cargo.toml, crates/cnidarium/src/metrics.rs, crates/cnidarium/src/snapshot.rs, crates/core/app/Cargo.toml, crates/core/component/community-pool/Cargo.toml, crates/core/component/compact-block/Cargo.toml, crates/core/component/compact-block/src/component/metrics.rs, crates/core/component/compact-block/src/component/rpc.rs, crates/core/component/dex/Cargo.toml, crates/core/component/dex/src/component/action_handler/swap.rs, crates/core/component/dex/src/component/arb.rs, crates/core/component/dex/src/component/dex.rs, crates/core/component/dex/src/component/metrics.rs, crates/core/component/dex/src/component/router/fill_route.rs, crates/core/component/dex/src/component/router/path_search.rs, crates/core/component/fee/Cargo.toml, crates/core/component/governance/Cargo.toml, crates/core/component/ibc/Cargo.toml, crates/core/component/sct/Cargo.toml, crates/core/component/shielded-pool/Cargo.toml, crates/core/component/stake/Cargo.toml, crates/core/component/stake/src/component.rs, crates/core/component/stake/src/component/metrics.rs, crates/util/tendermint-proxy/Cargo.toml, crates/view/Cargo.toml
=> penumbra: use `metrics@0.22`

.github/workflows/deploy-preview.yml, deployments/charts/penumbra-metrics/templates/configmap.yaml, deployments/config/grafana/dashboards/ABCI.json, deployments/config/grafana/dashboards/Consensus.json, deployments/config/grafana/dashboards/P2P.json, deployments/config/grafana/dashboards/sync.json, testnets/cometbft_config_template.toml
Updates the generated CometBFT config to use the "cometbft" namespace for emitted metrics. Accordingly, updates the Grafana panels that incorporate those metrics.
Also attempts to make the grafana panels more legible, by bundling up the pd & cometbft scrape points into a single job, either "Fullnode" or "Validator". We'll still have the ability to discriminate by "instance" which includes the address scraped, e.g. "penumbra-testnet-fn-0:9000" for pd.
=> fix(metrics): rename tendermint -> cometbft

crates/core/component/stake/src/component/epoch_handler.rs, crates/core/component/stake/src/component/stake.rs, crates/core/component/stake/src/component/validator_handler.rs, crates/core/component/stake/src/component/validator_handler/validator_manager.rs, crates/core/component/stake/src/component/validator_handler/validator_store.rs
This PR implement fixes that were surfaced during a validator state-machine
review:
- Double tombstoning: Previously, we disallowed the state transition
`Tombstoned -> Tombstoned` implicitly assuming that a validator
node can only commit byzantine behavior once.  This is, of course,
not a reasonable assumption. A malicious validator can equivocate
as many times as they want. Therefore, we need to be able to support
`T-> T` transitions
- Missing transitions: We did not implement the `Defined <-> Disabled`
transition. This is a bug in #2921.
=> staking: make multi-tombstoning a no-op and a state machine fix

crates/core/app/src/action_handler/actions/submit.rs, crates/core/transaction/src/auth_data.rs, crates/core/transaction/src/plan/auth.rs, crates/custody/src/threshold.rs, crates/custody/src/threshold/sign.rs
Allows web's `WitnessAndBuildRequest` to not pass `authorizationData` as a field. Needed for cases like `swapClaim` where no auth is required to building.
=> Make effect hash optional

.github/workflows/notes.yml, .github/workflows/rust.yml
Refs #3750. Follow-up to #3749, which updated the per-PR CI workflow, but not the deploy-on-merge-to-main workflow.
=> ci: fix docs build nightly version

crates/core/component/stake/src/component/epoch_handler.rs, crates/core/component/stake/src/component/stake.rs, crates/core/component/stake/src/component/validator_handler/validator_manager.rs, crates/core/component/stake/src/component/validator_handler/validator_store.rs, crates/core/component/stake/src/state_key.rs
This is the final chunk of work for #3615.
This PR:
- remove duplicates in the staking state keys
- picks a namespacing format that leaves room for future optimization
- organize state keys into a module hierarchy
Overall, there aren't dramatic changes, but a series of modest attempts at future-proofing our state key format.
=> staking: namespace state keys and remove dups

docs/guide/src/dev/devnet-quickstart.md, docs/guide/src/dev/rpc.md, docs/guide/src/pcli/transaction.md, docs/guide/src/pclientd/build_transaction.md, docs/guide/src/pclientd/rpc.md
=> docs: update devnet guide for new pcli syntax

deployments/helmfile.d/penumbra-testnet.yaml
Follow-up to #3699, which introduced a YAML typo I overlooked. Will need to be backported to release branch for 65 if we want to use the automated deploy pipeline.
=> ci: fix yaml typo in testnet manifest

crates/core/component/stake/src/component/validator_handler/validator_manager.rs
There is a bug in the current v0.65.0 release. `Defined` validators are not transitioning out of the precursor state into `Inactive`. The reason is that we are not actually effecting the validator state. This had been previously fixed in a follow-up #2921, but somehow slipped back in.
=> staking: add missing effect for `Defined <> Inactive`

Cargo.lock, crates/bin/pd/Cargo.toml, crates/bin/pd/src/lib.rs, crates/bin/pd/src/main.rs, crates/bin/pd/src/metrics.rs, crates/core/app/Cargo.toml, crates/core/app/src/consensus.rs, crates/core/app/src/lib.rs, crates/core/app/src/mempool.rs, crates/core/app/src/metrics.rs
see #3588, #3787. we'll need these in the `penumbra-app` crate to instantiate a test node. this is plain code motion.
=> refactor(pd): 🏋️ hoist `Consensus` and `Mempool` into `penumba-app`

Cargo.lock, crates/bin/pcli/Cargo.toml, crates/bin/pcli/src/command/query/validator.rs
Using the `colored` crate for readable ANSI color schemes. We also get free tty detection, so this command is now readable:
pcli query validator list | less
That's a command I run a lot, particularly since we've had a sharp increase in validator interest, coinciding with phase 1 of the summoning ceremony (~2023-12).
In 1676879ee365d72d35883be391ef9d10aa5c5e31 we ensured that pcli only colorizes log output where appropriate, but the validator query list wasn't using logging interfaces.
=> feat(pcli): smart colorization for pcli output

crates/core/component/funding/src/component.rs, crates/core/component/stake/src/component/epoch_handler.rs, crates/core/component/stake/src/component/validator_handler/validator_store.rs, crates/core/component/stake/src/funding_stream.rs, crates/core/component/stake/src/state_key.rs
Submitted for independent review and testing, should fix #3802. 
Testing that this change work is a little bit tricky, here are the steps that I have taken just now:
1. I setup a devnet with short block time (300ms), and short epoch durations (50 blocks).
2. The default validator has 100% of the total active stake and a 100% commission rate.
3. On the `v0.66.0` tag, this experimental setups leads to a chain halt on epoch 2 (~ 25 seconds after start).
=> staking: use validator exchange rate to compute rewards

Cargo.lock, Cargo.toml, crates/bin/pd/Cargo.toml
In #3745, we bumped the `metrics` crate to use `0.22`.
However, we missed a couple of its helper crates such as:
- `metrics-utils`
- `metrics-exporter-prometheus`
- `metrics-tracing-context`
This is problematic, and apparently frequent cause of breakage, because ones need to use the same version of metrics across crates that register recorders in order for it to work.
One way to detect this mismatch is running this command on the workspace directory:
```
cargo tree -i metrics
```
Later, we discovered that - unfortunately - the `metrics-utils@0.16.0` crate had pinned of its dependency (`hashbrown@0.13.2`) in order to enforce its MSRV policy (!), effectively locking us - and astria - out of completing our migration to `22`.
Fortunately, after some outreach a new release removing the pinned …
=> penumbra: fix metrics by bumping helper crates

crates/core/component/stake/src/component/action_handler/validator_definition.rs, crates/core/component/stake/src/funding_stream.rs
=> staking: add limit on number of validator funding streams

crates/core/component/stake/src/params.rs
Lowering the limit since the faucet only gives out so many tokens, and we have received feedback that this made it time-consuming to experiment with the application if one wants to setup a validator as well.
=> staking: lower `StakeParameters::min_threshold_stake` to 1penumbra

deployments/compose/docker-compose.yml
pd-node have to know correct address JSON-RPC of cometbft node to work correctly gRPC request to 8080 will fail if pd can't send request to cometbft node RPC port
=> Add cometbft-addr to docker-compose.yml

Cargo.lock, crates/core/app/tests/common/mod.rs, crates/core/app/tests/mock_consensus.rs, crates/test/mock-consensus/Cargo.toml, crates/test/mock-consensus/src/builder.rs, crates/test/mock-consensus/src/builder/init_chain.rs, crates/test/mock-consensus/src/lib.rs
this is a follow-on to #3807. this makes the
`mock_consensus_can_send_an_init_chain_request` test pass.
see #3588.
add an app state field to the builder, thread that through to the abci request. log this after the response is received.
```
; RUST_LOG="penumbra-app=debug,info" cargo test --package penumbra-app init_chain -- --nocapture
running 1 test
2024-02-13T15:18:01.770473Z  INFO cnidarium::storage: snapshot dispatcher task has started
at crates/cnidarium/src/storage.rs:208
2024-02-13T15:18:01.880291Z  INFO penumbra_app::server::consensus: genesis state is a full configuration
at crates/core/app/src/server/consensus.rs:143
2024-02-13T15:18:01.883007Z  INFO penumbra_app::server::consensus: finished init_chain, consensus_params: Params { block: Size { max_bytes: 1, max_gas: 1, …
```
=> tests: ✨ provide app state in genesis request

Cargo.lock, crates/core/app/src/metrics.rs, crates/core/component/funding/Cargo.toml, crates/core/component/funding/src/component.rs, crates/core/component/funding/src/component/metrics.rs
Close #3815, this PR:
- removes the `panic!` branch if the total validator rewards are greater than the epoch budget
- adds metrics to make the funding component observable via prometheus
=> funding: make reward budget a soft limit

crates/core/component/stake/src/component/action_handler/undelegate_claim.rs, crates/core/component/stake/src/component/validator_handler/validator_manager.rs, crates/core/component/stake/src/component/validator_handler/validator_store.rs, deployments/scripts/smoke-test.sh
This PR:
- fixes a bug with the unbonding epoch validation rule (claims are allowed _after_ the target epoch has been reached)
- simplifies the unbonding delay calculation logic
=> staking(undelegate_claim): fix unbonding check condition

deployments/helmfile.d/penumbra-preview.yaml, deployments/helmfile.d/penumbra-testnet.yaml
We're starting work on a new webapp that will provide a visual frontend for the DEX. That work is currently housed in [0]. Similar to cuiloa [1], we must enable CometBFT indexing to Postgres, so the application (yet to be written) can query those events. Strictly speaking, it's possible to reuse a db connection across multiple apps, particularly if we're careful about ensuring read-only access, but duplicating the node config per-app will simplify debugging in the near-term.
These changes have been manually applied for both environments. URLs may change in the future.
[0] https://github.com/penumbra-zone/dex-explorer
[1] https://github.com/penumbra-zone/cuiloa
=> ci: add indexing node for dex-explorer

Cargo.lock, Cargo.toml, crates/core/component/dex/Cargo.toml, crates/core/component/dex/src/swap_claim/proof.rs, crates/test/mock-consensus/Cargo.toml
see https://github.com/penumbra-zone/penumbra/issues/3777 for more information. this replaces the `Result::expect` statements with error variants that are propagated to the caller.
:heart_decoration: some gardening is done along the way to make this code a little more visually consistent. refactoring changes are intentionally kept in separate commits, to facilitate ease of review.
=> dex: 🏒  `SwapClaimProof::verify` is fallible

docs/guide/src/pcli/install.md, docs/guide/src/pd/install.md
This is a common question in the Discord, from folks trying to install the precompiled binaries on an LTS OS like Ubuntu 20.04. We only build one set of binaries per architecture, and we don't want to start building per-OS, so let's just be clear about what we know works.
=> docs: stipulate support for precompiled binaries

Cargo.lock, crates/core/component/governance/Cargo.toml, crates/core/component/governance/src/delegator_vote/proof.rs
see https://github.com/penumbra-zone/penumbra/issues/3777.
this changes `DelegatorVoteProof::verify` so that it is fallible. errors will be propagated to the caller, rather than inducing a panic.
* #3777
* #3829
as with #3829, i've applied some tlc to the code as i've addressed the core issue at hand (_panics_). noop code transformations are applied in distinct commits, to facilitate ease of review.
=> governance: 🎾 `DelegatorVoteProof::verify` is fallible

Cargo.lock, crates/core/component/shielded-pool/Cargo.toml, crates/core/component/shielded-pool/src/spend/proof.rs
see https://github.com/penumbra-zone/penumbra/issues/3777.
this changes `DelegatorVoteProof::verify` so that it is fallible. errors will be propagated to the caller, rather than inducing a panic.
* #3777
* #3829
* #3833
as with #3829 and #3833, i've applied some tlc to the code as i've addressed the core issue at hand (_panics_). noop code transformations are applied in distinct commits, to facilitate ease of review.
=> shielded-pool: 🏊 `SpendProof::verify` is fallible

crates/core/app/tests/mock_consensus.rs, crates/test/mock-consensus/src/block.rs, crates/test/mock-consensus/src/builder/init_chain.rs, crates/test/mock-consensus/src/lib.rs
this makes changes to the mock consensus engine so that the generated `Block`s have monotonically increasing height.
see also:
* #3588
* #3788
an example, running the
`mock_consensus_can_send_a_sequence_of_empty_blocks` test:
```
; RUST_LOG="penumbra_mock_consensus=info" cargo test --package penumbra-app sequence_of_empty_blocks -- --nocapture
Compiling penumbra-mock-consensus v0.67.1
Compiling penumbra-app v0.67.1
Finished test [unoptimized + debuginfo] target(s) in 9.10s
Running unittests src/lib.rs (target/debug/deps/penumbra_app-1e86f1775ec8d9a7)
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 3 filtered out; finished in 0.00s
Running tests/mock_consensus.rs (target/debug/deps/mock_consensus-caa27518a071c6af)
running 1 test
2024-02-16T21:18:58.850646Z  INFO …
```
=> mock-consensus: 💹 generated blocks' height increases

crates/core/app/tests/mock_consensus.rs, crates/test/mock-consensus/src/block.rs
`tendermint::evidence::List` implements `std::default::Default`. so, let's use that instead of mandating that an empty evidence list be provided each time that we build a new block.
https://github.com/penumbra-zone/penumbra/pull/3840#discussion_r1493025098
Reference: https://github.com/penumbra-zone/penumbra/issues/3588
Reference: https://github.com/penumbra-zone/penumbra/issues/3792
Reference: https://github.com/penumbra-zone/penumbra/pull/3840
=> mock-consensus: 💇 use `evidence::List::default`

Cargo.lock, crates/core/app/Cargo.toml, crates/core/app/src/server/consensus.rs, crates/core/app/tests/common/mod.rs, crates/core/app/tests/mock_consensus.rs
this is a bit of polish for the mock consensus tests. `Consensus` provides its `tower::Service` implementation via `tower-actor`, which makes naming a `TestNode<_>` slightly verbose. this introduces a `ConsensusService` type alias, and outlines our test node startup into a shared function in `common`.
in the future we'll probably extend this `start_test_node` to allow for callers to override particular settings on the test node builder. for now, that is elided. our primary goal is to provide an ergonomic "_start a test node backed by temporary storage_" button to reduce test boilerplate.
* #3588
* #3788
=> mock-consensus: 🙂 simplify test node startup

crates/bin/pcli/src/command/tx/proposal.rs, crates/bin/pcli/src/network.rs, crates/bin/pcli/src/terminal.rs, crates/bin/pclientd/tests/network_integration.rs, crates/core/app/src/action_handler/actions/submit.rs, crates/core/transaction/src/lib.rs, crates/core/transaction/src/plan/auth.rs, crates/custody/src/policy.rs, crates/custody/src/pre_auth.rs, crates/custody/src/request.rs, crates/custody/src/soft_kms.rs, crates/custody/src/threshold.rs, crates/custody/src/threshold/sign.rs, crates/view/src/client.rs, crates/view/src/service.rs, crates/wallet/src/build.rs, crates/wallet/src/plan.rs
as the crate's documentation points out, `TransactionPlan` is one of the critical types provided by this library.
let's `pub use` it in `lib.rs`, alongside `Transaction`.
=> transaction: 🚪 reëxport `TransactionPlan`

.github/workflows/smoke.yml, crates/bin/pd/src/main.rs, crates/bin/pd/tests/network_integration.rs, deployments/scripts/smoke-test.sh
This change restores the serving of CORS headers in HTTP responses by pd. During the refactor of auto-https logic in #3652, we overlooked that the tower [CorsLayer](https://docs.rs/tower-http/0.4.4/tower_http/cors/struct.CorsLayer.html#) was no longer being carried through after type conversions between tower, tonic, and axum. Simply moving the layer attachment to the already-built axum router, rather than the previously constructed tonic router, resolves the problem.
We now include an integration test to check for the headers, so we don't inadvertently drop them again.
Closes #3865.
=> fix(pd): re-add cors headers

deployments/charts/penumbra-node/values.yaml
As a temporary measure, we've added ratelimiting on the gRPC endpoint for pd, via Traefik middleware. We plan to add similar ratelimiting functionality to pd itself, so that solo node operators can benefit from limited DoS protection. For now, we add this so that a subsequent CI deploy (e.g. #3784) doesn't remove the protection that's currently live.
=> ci: enable ratelimiting via traefik

crates/core/app/tests/common/mod.rs
debug logs are rather noisy as a default log level. use info for the default level, callers can opt in to higher verbosity with `RUST_LOG`.
cherry-picked from #3866.
=> mock-consensus: 📵 raise default tracing log level in tests

crates/core/app/src/app/mod.rs
this adds additional context to errors, so that an invalid transaction error includes more information about why it was invalid, and where that error occured.
=> app: 🌸 add context messages to assorted errors

.gitattributes, Cargo.lock, assets/minifront.zip, assets/node-status.zip, crates/bin/pd/Cargo.toml, crates/bin/pd/src/lib.rs, crates/bin/pd/src/main.rs, crates/bin/pd/src/zipserve.rs
This is an experiment towards bundling the web frontend code into the fullnode, with the goal that users who run `pd` nodes can self-host a complete Penumbra frontend, on their custom domain with auto-HTTPS, with just one command: `pd start`.
To do this, we
- add a new `zipserve` module in `pd`, which takes a `&'static [u8]` with archive data and produces an `axum::Router`;
- bundle an `assets/frontend.zip` (tracked with git-lfs) into the `pd` crate;
- use `axum::Router::merge` to combine the GRPC and frontend endpoints.
To make this work for real, we'd need to:
These seem pretty doable, and it'd be really cool to be able to have easily self-hosted frontends!
=> pd: allow bundling the web frontend into the fullnode

Cargo.toml
From looking at the CI history, it seems like deployments have been failing since #3871; this seems like it might be the cause, so I'll try reverting it and seeing if that fixes the problem.
=> ci: try restoring testnet-preview deployments

crates/core/component/stake/src/component/action_handler/delegate.rs, crates/core/component/stake/src/component/action_handler/validator_definition.rs, crates/core/component/stake/src/component/epoch_handler.rs, crates/core/component/stake/src/component/stake.rs, crates/core/component/stake/src/component/validator_handler/validator_manager.rs, crates/core/component/stake/src/component/validator_handler/validator_store.rs
Close #3853 
This PR:
- removes the `Defined -> Inactive` transition from the delegate action execution
- ensure that the first delegation to a validator pool must be at least `min_validator_stake`
- add a `try_precursor_transition` method to the validator state machine to safely drive transitions in/out of the `Defined` state
=> staking: add a `min_validator_stake` first delegation requirement

crates/core/component/dex/src/component/dex.rs
In #3893 we encountered a bug in arb search logic that caused a chain halt. While that bug shouldn't exist, it also shouldn't have stopped the entire chain. Rather, we should continue operating without performing arbitrage.
This commit does not fix the bug in #3893, but it does mean that the effect of that bug is just to stop arb from occurring rather than halting the chain.
=> dex: avoid chain halts in case of arb failures

Cargo.lock, crates/core/app/src/action_handler/transaction/stateful.rs, crates/core/app/tests/mock_consensus.rs, crates/core/app/tests/spend.rs, crates/core/app/tests/swap_and_swap_claim.rs, crates/core/transaction/src/memo.rs, crates/test/mock-client/Cargo.toml, crates/test/mock-client/src/lib.rs, crates/test/mock-consensus/src/builder/init_chain.rs, crates/test/mock-consensus/src/lib.rs
fixes #3788.
this branch builds upon the work in #3857 and #3866, filling out the remaining holes in the transaction plan. this now performs a spend, using the mock consensus engine.
=> app: 💸 a mock consensus spend is performed

crates/core/app/tests/spend.rs
addresses this compiler warning:
```
warning: argument must be of the form: `expected = "error message"`
--> crates/core/app/tests/spend.rs:97:1
|
97 | #[cfg_attr(
| ^
|
= note: errors in this attribute were erroneously allowed and will become a hard error in a future release
```
=> app: 🤠 address warning

crates/core/component/dex/src/component/action_handler/position/open.rs
Closes #3855.
Also adds an extra sanity check that opened positions are in the `Opened` state.
=> Add intra-transaction duplicate position-id check

crates/bin/pcli/src/command/query/ibc_query.rs
Closes #3905 
This PR makes the pcli channel queries more useful to the end user, displaying relevant channel metadata (like chain ID) instead of just dumping the protocol level struct to console as JSON.
Before:
After:
=> pcli: improve pcli ibc channel queries

crates/core/keys/src/keys/spend.rs
this saves us a needless length check if we already have an array in-hand.
this would be useful for my work in #3902. (x-ref #3816)
=> keys: 🍴 `SpendKeyBytes: From<[u8; SPENDKEY_LEN_BYTES]>`

Cargo.lock, Cargo.toml
Switch to the latest release of `ibc-types@0.12`
=> penumbra: use `ibc-proto@0.41` and `ibc-types@0.12`

Cargo.lock, Cargo.toml
(cherry picked from commit 5863116e3a2e0a0ee379eb22818316e40c4be275)
=> penumbra: use `ibc-proto@0.41` and `ibc-types@0.12` (#3927)

crates/core/component/fee/src/gas.rs
Closes https://github.com/penumbra-zone/penumbra/issues/3941
=> Add serde derives for GasPrices

crates/core/component/dex/src/component/router/route_and_fill.rs, crates/core/component/dex/src/swap_execution.rs
Testnet 68 halted at height 100736, with an `.expect` here:
https://github.com/penumbra-zone/penumbra/blob/1c99e24ad5cf1ecc2855849d66221ecec25f9235/crates/core/component/dex/src/component/dex.rs#L66
This hit an error bubbled up from here:
https://github.com/penumbra-zone/penumbra/blob/1c99e24ad5cf1ecc2855849d66221ecec25f9235/crates/core/component/dex/src/component/router/route_and_fill.rs#L277
The error occurs in this method, which is only ever used at that callsite:
https://github.com/penumbra-zone/penumbra/blob/1c99e24ad5cf1ecc2855849d66221ecec25f9235/crates/core/component/dex/src/swap_execution.rs#L18
It's a little unclear why that method has double fallibility. Unfortunately, the answer may not be easily determined. It was added here …
=> dex: fix chain halt in testnet 68

crates/core/component/dex/src/component/router/route_and_fill.rs, crates/core/component/dex/src/swap_execution.rs
Testnet 68 halted at height 100736, with an `.expect` here:
https://github.com/penumbra-zone/penumbra/blob/1c99e24ad5cf1ecc2855849d66221ecec25f9235/crates/core/component/dex/src/component/dex.rs#L66
This hit an error bubbled up from here:
https://github.com/penumbra-zone/penumbra/blob/1c99e24ad5cf1ecc2855849d66221ecec25f9235/crates/core/component/dex/src/component/router/route_and_fill.rs#L277
The error occurs in this method, which is only ever used at that callsite:
https://github.com/penumbra-zone/penumbra/blob/1c99e24ad5cf1ecc2855849d66221ecec25f9235/crates/core/component/dex/src/swap_execution.rs#L18
It's a little unclear why that method has double fallibility. Unfortunately, the answer may not be easily determined. It was added here …
=> dex: 🌸 apply "fix chain halt in testnet 68" to main

crates/core/component/dex/src/component/position_manager.rs, crates/core/component/dex/src/lp/position.rs
Per the discussion in #3850, this PR removes the handling of limit orders in the dex, which cuts scope and removes the specific issue found by Zellic.
=> dex: disable limit orders

crates/bin/pd/src/main.rs
this adds a small tracing event including the version of pd that is running, before proceeding to handle the CLI command.
this should help operators identify when they are running a stale version of pd.
=> pd: 📦 add a tracing event with cargo version

crates/bin/pcli/src/command/view/address.rs, crates/core/keys/src/address.rs, crates/proto/src/serializers/bech32str.rs
Bech32 (non-m) encoded addresses are the standard in the broader cosmos ecosystem. [Noble requires that withdrawal addresses be encoded as bech32](https://github.com/noble-assets/noble/blob/757b3111d15ef2ee8640639af60edef1b7712c6d/app/ante.go#L155), and attempting to transfer to a bech32m address (such as a penumbra address) results in a decoding error. This issue is acknowledged by the broader ecosystem. In the mean time, we can fix this on our end and enable testing with Noble or other similarly constrained cosmos chains by introducing a 'compat' address encoding `penumbracompat1`, that uses Bech32(non-m). 
This PR adds the compat encoding, adds a pcli flag to `view address` to allow you to see it, and changes the FromStr impl for address to detect and use the compat encoding.
=> add compat addresses that use bech32 (non-m) for compatibility with noble IBC

Cargo.lock, crates/bin/pcli/Cargo.toml, crates/bin/pcli/src/command/query/ibc_query.rs
Improves `ibc q channel(s)` so that it will show the status as 'CLIENT EXPIRED' if the underlying client for a channel has expired.
=> ibc: show client expiry status in channel query

crates/cnidarium-component/src/action_handler.rs, crates/core/app/src/action_handler.rs, crates/core/app/src/action_handler/actions.rs, crates/core/app/src/action_handler/actions/submit.rs, crates/core/app/src/action_handler/transaction.rs, crates/core/app/src/action_handler/transaction/stateless.rs, crates/core/app/src/app/mod.rs, crates/core/app/src/lib.rs, crates/core/app/tests/spend.rs, crates/core/app/tests/swap_and_swap_claim.rs, crates/core/component/community-pool/src/component/action_handler/community_pool_deposit.rs, crates/core/component/community-pool/src/component/action_handler/community_pool_output.rs, crates/core/component/community-pool/src/component/action_handler/community_pool_spend.rs, crates/core/component/dex/src/component/action_handler/position/close.rs, crates/core/component/dex/src/component/action_handler/position/open.rs, crates/core/component/dex/src/component/action_handler/position/withdraw.rs, crates/core/component/dex/src/component/action_handler/swap.rs, crates/core/component/dex/src/component/action_handler/swap_claim.rs, crates/core/component/governance/src/action_handler/delegator_vote.rs, crates/core/component/governance/src/action_handler/deposit_claim.rs, crates/core/component/governance/src/action_handler/validator_vote.rs, crates/core/component/governance/src/action_handler/withdraw.rs, crates/core/component/shielded-pool/src/component/action_handler/ics20_withdrawal.rs, crates/core/component/shielded-pool/src/component/action_handler/output.rs, crates/core/component/shielded-pool/src/component/action_handler/spend.rs, crates/core/component/stake/src/component/action_handler/delegate.rs, crates/core/component/stake/src/component/action_handler/undelegate.rs, crates/core/component/stake/src/component/action_handler/undelegate_claim.rs, crates/core/component/stake/src/component/action_handler/validator_definition.rs, crates/view/src/service.rs
This renames the previous `check_stateful` method to `check_historical`,
renames `execute` to `check_and_execute`, and by default moves all of the
content of `check_stateful` into `check_and_execute`, unless there's an obvious
and LOCAL reason why it's safe to do so that can be written into the body of
the method.
IMO it's still worth it to have the method in the trait. We may wish to take
advantage of it later, when we can spend more time carefully reasoning about
performance.
=> component: eliminate TOCTOU bug factory

crates/core/app/Cargo.toml
performs the same cleanup as #3895, but for the `penumbra-app` crate's manifest.
=> chore(app): 🧹 tidy dependency list

crates/view/src/storage.rs
here, we are within an `if let Some(_)` clause that has already bound the contents of the storage path. so, let's just pass that to `Self::load` instead of unwrapping it again.
=> view: 🌯 remove frivolous `Option::expect` call

docs/protocol/src/protocol/action_descriptions/delegator_vote.md, docs/protocol/src/protocol/action_descriptions/outputs.md, docs/protocol/src/protocol/action_descriptions/spend.md, docs/protocol/src/protocol/action_descriptions/swap.md, docs/protocol/src/protocol/action_descriptions/undelegate_claim.md
Related to #3867, updating the protocol docs with respect to the changes made to the circuits in the last few months
=> spec: update proof statements

deployments/terraform/modules/node/v1/gke.tf
Performed this upgrade in two stages:
* 1.27.5-gke.200 -> 1.27.8-gke.1067004
* 1.27.8-gke.1067004 -> 1.28.3-gke.1286000
which was intentionally cautious. These changes have been applied manually, and this patch is included to document the current state of the infra. As such, closes #3974.
=> ci: update k8s version to latest 1.28.x

crates/core/component/stake/src/component/action_handler/validator_definition.rs, crates/core/component/stake/src/component/epoch_handler.rs, crates/core/component/stake/src/component/stake.rs, crates/core/component/stake/src/component/validator_handler/validator_manager.rs
This PR:
- fix a bug that would cause unjailed validators to not be re-added to the consensus index
- simplify the validator state machine, and in particular:
- move the state effect outside of the `match` implementation
- unify valid, but no-op, branches (e.g. `Disabled <> Defined`)
- improve and elaborate comments
=> stake: fix missing index and simplify state machine

docs/protocol/src/protocol/action_descriptions/delegator_vote.md, docs/protocol/src/protocol/action_descriptions/outputs.md, docs/protocol/src/protocol/action_descriptions/spend.md, docs/protocol/src/protocol/action_descriptions/swap.md, docs/protocol/src/protocol/action_descriptions/swap_claim.md, docs/protocol/src/protocol/action_descriptions/undelegate_claim.md
This PR adds a description of the various bounds checks that are done in the circuits, i.e. verifying that a given value fits in N bits
Related to #3867
=> protocol spec: describe bounds checking in circuits

.gitignore
this is generated by running the network integration tests.
this adds it to the gitignore, alongside `deployments/logs/`.
=> chore(gitignore): 🤔 ignore proposal.toml

crates/bin/pcli/tests/network_integration.rs
there are two issues at hand:
- we log `undelegation_result` twice
- `undelegation_result` can be many thousands of lines long
this means that the `delegate_and_undelegate` pcli network integration test thrashes the test output somewhat severely, and test logs aren't fully viewable in e.g. tmux, when running this locally.
https://github.com/penumbra-zone/penumbra/actions/runs/8210700115/job/22458602964#step:11:18
as of `main` at the time of writing, this CI job logs an event that is...
```
; xclip -o -selection clipboard | wc --bytes
243775
```
243Kb is disruptively long. (_let alone 486Kb!_)
so, let's make this field an opt-in field to display. we only log it once, and do so at the trace level.
=> tests(pcli): 🔇 make large tracing event trace-level

deployments/charts/penumbra-node/templates/statefulset.yaml, deployments/charts/penumbra-node/values.yaml, deployments/helmfile.d/penumbra-preview.yaml, deployments/helmfile.d/penumbra-testnet.yaml
External developers on e.g. the DEX explorer need a database with testnet events that they can develop against. Rather than instructing them how to set up a fullnode on their dev workstations, we'll provide an external URL and creds so that they can use the cloud-hosted db directly in their local dev workflows.
To support this, a few changes were necessary to the configs:
* optionally reference pre-existing Secret for db creds
* optionally reference pre-existing Secret for TLS certs
Additionally, IPs and DNS were configured out of band, one per environment (e.g. preview & testnet).
=> ci: public ingress for postgres db

crates/core/app/tests/mock_consensus.rs, crates/test/mock-consensus/src/lib.rs
fixes #3933.
this introduces a `fast_forward` method to a test node, allowing tests using the mock consensus engine (#3588) to fast forward a certain number of blocks.
the existing `mock_consensus_can_send_a_sequence_of_empty_blocks` test is rewritten to make use of this method.
this is done in service of #3995.
---
* #3588
* #3933
* #3995
=> mock-consensus: 🔀 test node can `fast_forward`

crates/test/mock-consensus/src/block.rs, crates/test/mock-consensus/src/lib.rs
fixes #3936. based upon #4002. see #3588.
this changes the type of the block builder's `data`, allowing it to be implicitly kept empty. this is useful when e.g. fast forwarding a number of blocks _(see #4002)_. this spares us the need to call `with_data(vec![])`, and additionally means that the block builder is never in an uninitialized state _(making #4003 needless)._
* #3936
* #4002
* #3588
=> mock-consensus: 👷 block data is implicitly empty, can be appended

crates/core/app/src/app/mod.rs
fixes a comment in `App::end_block`. cherry-picked from #4001.
=> app: 🤓 fix grammar in comment

crates/core/component/stake/src/component/stake.rs
this makes some small logging additions to the staking component. delegation changes will be logged at the trace level.
=> refactor(staking): 😊 tracing telemetry for delegation changes

crates/core/app/src/server/consensus.rs
`Consensus::end_block` never returns an `Err(_)` value, so it does not need to return a `Result<T, E>`.
cherry-picked out ouf #4001.
=> app: 🦅 `Consensus::end_block` never errors

crates/core/app/tests/spend.rs
Add a comment and a missing `assert!` to enforce the post-condition
=> app: add `assert!` to dummy spend test

crates/core/app/src/app/mod.rs, crates/core/component/compact-block/src/component/manager.rs, crates/core/component/stake/src/component/action_handler/delegate.rs, crates/core/component/stake/src/component/epoch_handler.rs, crates/core/component/stake/src/component/mod.rs, crates/core/component/stake/src/component/stake.rs, crates/core/component/stake/src/lib.rs
this is a group of improvements to the telemetry in the staking component, cherry-picked out of #4001. this improves the logs seen in tests, and additionally takes the time to make some other small gardening tweaks: consolidating imports, adding documentation comments, etc. this is another branch in the spirit of #4009.
the changes here are itemized into distinct, small code transformations to facilitate review, and demonstrate that these are noop changes. you can start [here](https://github.com/penumbra-zone/penumbra/pull/4017/commits/f7f78b91e7b368377b55cdfba1e84ea7459609a9).
* f33196474 - feat(staking): ❗ traces for invalid or missing parameters 
* d33598d94 - docs(staking): 🤝 add a doc comment 
* f6c60a8bb - staking: 🙂 remove needless `Ok(_)` 
* fd4b8da09 - feat(staking): 💬 log when …
=> staking: 🎁 add additional tracing telemetry

docs/guide/book.toml, docs/guide/src/dev/ibc.md, docs/guide/src/pcli/transaction.md
We had a few chain halts on the `v0.68.x` release series. As of `v0.69.0`, "channel-0" is the correct value for relaying to Osmosis testnet. Added mention of the slick new `pcli query ibc channels` to the docs.
Also overhauled the dev docs for how to test IBC functionality interactively, since that knowledge has mostly been communicated via pairing session, but not yet fully written down. We no longer use `rly`, neither for running relayer instances nor for ad-hoc CLI transfers.  Instead, we can use `hermes` for both roles.
Linked out to wiki docs on the high-churn hermes relayer config steps, since we're updating those frequently. Therefore review should also include eyes on https://github.com/penumbra-zone/penumbra/wiki/Updating-Hermes
=> docs: update deimos ibc channel for osmosis

crates/core/app/src/app/mod.rs, deployments/charts/penumbra-network/values.yaml, deployments/charts/penumbra-node/values.yaml, deployments/compose/docker-compose.yml, deployments/scripts/install-cometbft
Increments the minor version of CometBFT used in deployments. This commit changes the CometBFT version everywhere, except in the guide docs. After we confirm on preview that the version bump works fine, then we can update the docs, and mention in subsequent release notes.
Refs #4021.
=> ci: bump cometbft v0.37.2 -> v0.37.5

crates/bin/pd/src/testnet/generate.rs, crates/core/app/src/action_handler/actions/submit.rs, crates/core/component/governance/src/action_handler/deposit_claim.rs, crates/core/component/governance/src/action_handler/withdraw.rs, crates/core/component/governance/src/component/view.rs, crates/core/component/shielded-pool/src/component.rs, crates/core/component/shielded-pool/src/component/assets.rs, crates/core/component/shielded-pool/src/component/note_manager.rs, crates/core/component/shielded-pool/src/component/rpc.rs, crates/core/component/shielded-pool/src/component/shielded_pool.rs, crates/core/component/shielded-pool/src/component/supply.rs, crates/core/component/shielded-pool/src/component/transfer.rs, crates/core/component/shielded-pool/src/state_key.rs, crates/core/component/stake/src/component/action_handler/undelegate.rs, crates/core/component/stake/src/component/action_handler/validator_definition.rs, crates/core/component/stake/src/component/epoch_handler.rs, crates/core/component/stake/src/component/stake.rs, crates/core/component/stake/src/component/validator_handler.rs, crates/core/component/stake/src/component/validator_handler/validator_manager.rs, crates/core/component/stake/src/component/validator_handler/validator_store.rs, crates/core/component/stake/src/identity_key.rs, crates/core/component/stake/src/state_key.rs
=> shielded-pool: delegate supply tracking to components

crates/core/num/src/amount.rs
this expands on the existing `u32` and `u64` implementations, which themselves delegate down to `u128`.
https://doc.rust-lang.org/stable/std/primitive.u128.html#impl-From%3Cu16%3E-for-u128 https://doc.rust-lang.org/stable/std/primitive.u128.html#impl-From%3Cu8%3E-for-u128
=> feat(num): ✨ `Amount` is `From<u8>` and `From<u16>`

crates/test/mock-consensus/src/abci.rs, crates/test/mock-consensus/src/lib.rs
fixes #4005.
this tweaks the fast-forward facilities (#3933, #4002) so that we record
the height as a span field per-loop iteration, not as a field in the
encompassing `#[instrument]` span.
see #4005 for an example of the misleading `height: 0` logs this would
generate.
this patches the mock consensus `TestNode::end_block` method so that the
height of these requests does not stay at 1.
this is needed for staking tests, see #3995.
* #3588
* #4001
* #3995
* #3840
=> fix(mock-consensus): 🍰 fix two height bugs in mock consensus tests

crates/bin/pd/src/cli.rs, crates/bin/pd/src/main.rs, crates/bin/pd/src/testnet/generate.rs, deployments/scripts/smoke-test.sh
Follow-up to changes made in [0], where we settled on "unbonded delay" rather than "unbonding epochs" to describe how many blocks must elapse until undelegated stake becomes claimable. The `pd` CLI options are only used by developers, so I'm not worried about breaking operator scripts in the wild.
[0] https://github.com/penumbra-zone/penumbra/pull/3923
=> fix(pd): rename unbonding epochs -> delay

deployments/helmfile.d/penumbra-testnet.yaml
Temporary testnet fullnode to unblock prototyping on the gov dashboard project. We'll circle back and clean this up in a few weeks, so that the fullnode config backing the webapp lives alongside the webapp deployment, wherever it's hosted.
Follow-up to 829dc64a3939f54ac0630023b8240251cdc5d78e.
=> ci: add dedicated indexer node for gov dashboard

crates/bin/pcli/src/network.rs, crates/core/transaction/src/plan.rs
This helps slightly in case there are many many actions, currently the user only finds out how many there were _after_ doing all the proving.
=> pcli: show action / proof count before building

crates/core/app/tests/common/mod.rs, crates/core/app/tests/common/test_node_builder_ext.rs, crates/core/app/tests/mock_consensus.rs, crates/core/app/tests/mock_consensus_staking.rs, crates/core/component/stake/src/component/action_handler/validator_definition.rs, crates/core/component/stake/src/component/stake.rs, crates/test/mock-consensus/src/block.rs, crates/test/mock-consensus/src/builder.rs, crates/test/mock-consensus/src/builder/init_chain.rs, crates/test/mock-consensus/src/keyring.rs, crates/test/mock-consensus/src/lib.rs
fixes #3966. fixes #3908. fixes _part of_ #3995.
this branch introduces the first steps towards mock consensus (#3588) testing of the staking component (#3845).
this defines a validator after genesis, and then shows that it does _not_ enter the consensus set. #3966 is addressed in this branch so that the existing genesis validator correctly enters the consensus set, and so that we can successfully progress to the second epoch.
subsequent changes will exercise delegating to this validator in the `mock_consensus_can_define_and_delegate_to_a_validator`.
* alters `with_penumbra_auto_app_state` so that it adds an allocation of delegation tokens to the shielded pool component's genesis content.
* extends `generate_penumbra_validator` so that it generates a real spend key, and returns an …
=> tests: 🏃 mock consensus can exercise staking component

crates/core/component/stake/src/component/action_handler/undelegate_claim.rs, crates/core/component/stake/src/component/validator_handler/validator_manager.rs, crates/core/component/stake/src/component/validator_handler/validator_store.rs, crates/core/component/stake/src/rate.rs, crates/core/component/stake/src/validator.rs
This PR modifies the staking module logic responsible for determining the unbonding schedule, in particular it:
- returns the current height if a pool is unbonded
- change the `compute_unbonding_height` API to return an `Option<u64>` to allow callers to detect an unbonded pool
One tricky aspect of our unbonding mechanism is that we want to:
1. Bind unbonding notes to the economic effect of validator misbehavior for some window of blocks
2. Leave it to the application to decide when a note is allowed to be claimed
One thing to note is that this mechanism works relative to the _current_ bonding state of the pool. This is generally fine for the protocol security because this leads the application to "overshoot" the penalty window range since it cannot know the exact moment a note was allowed …
=> staking: change `compute_unbonding_height` api

.github/workflows/deploy-standalone.yml, deployments/scripts/redeploy-ci-fullnode-via-remote, deployments/scripts/redeploy-ci-fullnode-via-runner
These changes build on #3709, specifically:
* consuming ssh privkey & hostkey material from GHA secrets
* creates a dedicated workflow
So far this only targets preview. Will run the job ad-hoc a few times and make changes as necessary before porting to testnet env and hooking up to the automatically-triggered release workflows.
Refs #3336.
=> ci: standalone pd node workflow

crates/core/app/tests/mock_consensus_staking.rs, crates/test/mock-consensus/src/lib.rs
in #4001 we added a test for the staking component (_see also #3995, and #3588_).
this shortens the epoch length, so that this test runs in less time, and importantly, so that debugging test failures does not entail sifting through many log lines.
* manually construct an `AppState` so that we use a shorter epoch. this test involves waiting for multiple epochs to pass, which takes many seconds with the default length of 719, see: <https://github.com/penumbra-zone/penumbra/blob/8be8e8266b312c2a9eb1b1522a937e8df12f3a4f/crates/core/component/sct/src/params.rs#L41>
* `TestNode<C>::fast_forward` now accepts a u64, mirroring the type used in the sct parameters.
on `main`...
```
Starting 1 test across 1 binary
PASS [  12.646s] penumbra-app::mock_consensus_staking …
```
=> tests(app): ⌛ shorten epoch length in staking test

crates/core/component/shielded-pool/src/nullifier_derivation.rs
add note for future maintainers to only use the `NullifierDerivationCircuit` on the client-side, since the nk is not actually demonstrated to be associated with the address on the note in circuit (related issue #3978)
=> add comment to use `NullifierDerivationCircuit` client-side only

deployments/charts/penumbra-node/values.yaml
The ratelimiting on the HTTPS RPC frontend was getting dropped on chain resets, due to duplicated vars. I've been keeping an eye on performance and re-adding post-deploy, but only just identified the root cause, via manual lints. This oversight caused problems during a deploy of v0.68.0, during which an ad-hoc solo node was set up to sidestep the load. See #3336 for more work towards automatic solo nodes.
=> ci: fix middleware vars

crates/core/app/tests/mock_consensus_staking.rs, crates/core/component/stake/src/delegate.rs, crates/core/component/stake/src/undelegate.rs
see https://github.com/penumbra-zone/penumbra/issues/3995.
this test now delegates to, and then undelegates from, a validator.
this does not yet include all of the assertions we would like to
exercise in this test, but it does show that a validator correctly
progresses through the active and defined states.
in further work, we will fill out the other assertions described
in https://github.com/penumbra-zone/penumbra/issues/3995, particularly w.r.t. voting power and validator uptime.
=> tests(app): 🎇 mock consensus delegates, and undelegates, to a validator

crates/core/component/stake/src/penalty.rs, crates/core/component/stake/src/undelegate.rs
This fix an obsolete varname and comment.
=> staking(undelegate): remove obsolete comment in balance impl

crates/core/app/tests/mock_consensus_staking.rs
addresses §7.b in #3995.
this introduces new assertions so that the
`mock_consensus_can_define_and_delegate_to_a_validator` test exercises that the staking component is calculating different rates for validators that were created at different times.
=> tests(app): 🍖 compare new and existing validator rates

crates/bin/pd/src/migrate.rs, crates/bin/pd/src/testnet/generate.rs
We moved the `chain_id` when we did #3617. This broke the stub migration script, but it should work now.
=> pd(migrate): fix decoding error in stub migration script

crates/core/app/tests/app_tracks_uptime_for_genesis_validator_missing_blocks.rs, crates/core/app/tests/app_tracks_uptime_for_validators_only_once_active.rs, crates/core/app/tests/common/test_node_builder_ext.rs, crates/core/component/stake/src/uptime.rs
=> tests(app): 🎤 uptime tracker tests for validators missing blocks

.github/workflows/docs-lint.yml, .github/workflows/notes.yml, .github/workflows/rust.yml, docs/guide/book.toml, docs/protocol/book.toml
Runs `mdbook-linkcheck` [0] on PRs, ensuring that docs are checked for broken links prior to merge. We don't want to slow down per-PR CI runs, so it's important these steps run in parallel, from a warm cache. The cargo test workflow takes ~5m, so as long as we're under that, we should be good.
There's another subtle change in here: we reduce the number of CI vCPUs dedicated to these docs-building jobs, ensuring there's more compute available for the CPU-intensive jobs like cargo test. This allows more CI runs in parallel as multiple PRs are modified concurrently. Overall, the per-PR CPU reservation has changed from 80 -> 68. After observing the effect on CI runtimes, I suspect we can finetune further, and even bump up cargo test up to a 32-cpu runner if we gain back enough headroom.
Refs …
=> ci: use mdbook-linkcheck for docs linting

.github/workflows/notes.yml
Follow-up to #4062, which broke the deploy-docs workflow. By introducing mdbook-linkcheck, we inadvertently changed the output dir structure emitted by `mdbook build`: rather than `docs/guide/book/<docroot>`, we now have `docs/guide/book/html/<docroot/` and
`docs/guide/book/linkcheck/`. The same is true of the protocol docs.
=> ci: fix docs build

crates/core/component/stake/src/component/validator_handler/validator_manager.rs, crates/core/component/stake/src/component/validator_handler/validator_store.rs, crates/core/component/stake/src/state_key.rs
Sketch solution to #4067, this gives a starting point to provide a justification why this solve epoch grinding and TCT index overflows.
=> staking: add delay to reenable a validator

deployments/charts/penumbra-network/templates/statefulset.yaml, deployments/charts/penumbra-node/templates/statefulset.yaml
While testing upgrades as part of [0], updating the docs in [1], it became clear that during manual maintenance for munging state during chain upgrades procedures, we want all the nodes to be reset together. Therefore if maintenanceMode=true, we'll also disable the readinessProbes, otherwise the rollout will be staged, forcing us to upgrade each node in term, rather than being able to parallelize them. Now, we can `pd export` and backup state, then update the statefulset to bump the container version (to the post-upgrade version), and restart it in maintenance mode to continue with the `pd migrate` step and resulting copying around of emitted files.
[0] https://github.com/penumbra-zone/penumbra/pull/4055
[1] https://github.com/penumbra-zone/penumbra/wiki/Performing-upgrades
=> ci: disable readinessProbes in maintenanceMode

deployments/charts/penumbra-node/templates/statefulset.yaml
Follow-up to #4074, after additional migration testing of indexer nodes.
=> ci: fix readinessprobe on postgres container

deployments/charts/penumbra-network/templates/statefulset.yaml, deployments/charts/penumbra-node/templates/statefulset.yaml, deployments/ci.sh
Slightly smarter CI logic, which will block until all pods are marked Ready post-deployment. Due to an oversight, the "part-of" label wasn't applied to the fullnode pods, so the deploy script exited after the validators were running, but before the fullnodes were finished setting up. That was fine, until #3336, which tacked on a subsequent deploy step that assumes the RPC is ready to rock.
Also updates the statefulsets to deploy the child pods in parallel, rather than serially, which shaves a few minutes off setup/teardown. Only really affects preview env, which has frequent deploy churn.
=> ci: wait for all pods ready post-deploy

Cargo.lock, Cargo.toml, crates/cnidarium/Cargo.toml, crates/cnidarium/src/storage.rs, crates/cnidarium/src/store/multistore.rs, crates/cnidarium/src/store/substore.rs, crates/cnidarium/tests/migration.rs
Close #3506, this PR:
- use `jmt@0.10` which includes the `migration` feature
- bump `borsh` to `1.3.0` to be able to serialize jmt nodes
- revamp the substore migration tests to include basic tests and a proptest strategy
- notably, the proptest integration tests lay the groundwork for deeper/more targeted strategies
=> cnidarium: use incremental jmt migration

Cargo.lock, crates/bin/pd/Cargo.toml, crates/bin/pd/src/cli.rs, crates/bin/pd/src/main.rs, crates/bin/pd/src/migrate.rs, crates/bin/pd/src/testnet/join.rs
Enables opt-in archive generation when performing:
* pd export
* pd migrate
The goal is to provide a standardized bottling-up of pd state, specifically the rocksdb directory. In the context of upgrades, only the "pd migrate" functionality change is what we care about: we want the archived dir to contain both rocksdb data and the modified genesis file.
Accordingly, `pd testnet join` is modified to support an optional archive URL. If set, the remote tar.gz archive will be downloaded and extracted, clobbering the cometbft config. A remote bootstrap node is still contacted, to learn about peers, otherwise the newly created node wouldn't be able to talk to the network.
=> feat(pd): support archives for migrate and join

crates/bin/pd/src/cli.rs, deployments/charts/penumbra-node/templates/statefulset.yaml, deployments/charts/penumbra-node/values.yaml
Follow-up to [0]. We've tested several times the creation and use of archive urls via cli, but hadn't yet added logic to deploy new nodes from archive URLs, as well. This change worked for adding a new-joining node to a bespoke devnet post-upgrade.
[0] https://github.com/penumbra-zone/penumbra/pull/4055
=> fix: allow fetching archive-url from env var

crates/cnidarium/src/storage.rs, crates/cnidarium/src/store/substore.rs
This PR is a prelude to implementing "staged" writes to our storage layer (cc @noot #4095 ). Specifically, it:
- inline the `write_node_batch` logic inside of `SubstoreStorage::commit`
- make sure that nodes are inserted into the `rocksdb::WriteBatch` rather than immediately written to disk
The last point was a bug, we want to commit to a set of writes atomically, but the tree changes were written ahead of the rest of the transaction. By inserting a `panic!` statement between the tree write and the `write(node_batch` statement and restarting the full node I was able to observe a consistency discrepancy. This PR fixes this.
=> cnidarium: use `WriteBatch` when writing jmt nodes

crates/core/component/stake/src/component/stake.rs, crates/core/component/stake/src/component/stake/address.rs, crates/core/component/stake/src/component/validator_handler.rs, crates/core/component/stake/src/component/validator_handler/uptime_tracker.rs, crates/core/component/stake/src/component/validator_handler/validator_manager.rs
this is a small collection of noop refactors, cherry-picked out of #4070.
most importantly, this hoists `track_uptime` into a standalone extension trait. additionally, some improvements to telemetry helped make debugging tests in #4070 easier.
=> refactor(staking): 🌹 hoist uptime tracking into `ValidatorUptimeTracker` extension trait

Cargo.lock, crates/core/app/tests/app_tracks_uptime_for_genesis_validator_missing_blocks.rs, crates/core/app/tests/app_tracks_uptime_for_genesis_validator_signing_blocks.rs, crates/core/app/tests/app_tracks_uptime_for_validators_only_once_active.rs, crates/test/mock-consensus/Cargo.toml, crates/test/mock-consensus/src/abci.rs, crates/test/mock-consensus/src/block.rs, crates/test/mock-consensus/src/block/signature.rs
**NB:** this is based on #4099.
this adds test coverage, complementary to the work in #4061, which asserts that we properly track the _affirmative_ case of validators signing blocks.
fixes #4040. see #3995.
=> tests(app): 🧪 test that uptime tracks signed blocks

crates/core/component/stake/src/component/validator_handler/uptime_tracker.rs
in #4099, merging won a race with review. this applies suggestions from:
* https://github.com/penumbra-zone/penumbra/pull/4099/files/6fbc35c26ced0ebf7b751aee076c342de94a5427#r1538264796
* https://github.com/penumbra-zone/penumbra/pull/4099/files/6fbc35c26ced0ebf7b751aee076c342de94a5427#r1538253529
=> staking: 🏁 ex post facto #4099 review comments

crates/bin/pcli/src/command/tx.rs, crates/core/component/shielded-pool/src/ics20_withdrawal.rs
**this is a consensus-breaking change**
Fixes #4064
=> ibc: add withdrawal timestamp rounding chain rule

crates/core/app/src/action_handler/transaction/stateful.rs
Fix #4106.
@hdevalence I remember discussing with you making the `fee` method return a `Value`, but I don't recall why we decided against it.
=> app: check asset id in fee stateful check

crates/core/component/dex/src/component/action_handler/position/open.rs, crates/core/component/dex/src/component/action_handler/position/withdraw.rs, crates/core/component/dex/src/component/circuit_breaker/value.rs, crates/core/component/dex/src/component/position_manager.rs, crates/core/component/dex/src/component/router/fill_route.rs, crates/core/component/dex/src/component/router/path_search.rs, crates/core/component/dex/src/component/router/tests.rs, crates/core/component/dex/src/component/tests.rs, crates/core/component/dex/src/event.rs, crates/core/component/dex/src/lp/position.rs
This implements an API suggestion originally made by @cronokirby to expose context-specific methods for updating positions.
We maintain a single `put_position` method on the `Inner` trait so that we're
able to have a single point where we edit any necessary indexes, but this is
now not exposed to callers. Instead they call a scope-specific method that
calls `put_position` internally.
Currently there's still room to improve the API safety but we'll want to
potentially change the signature of `put_position` to ensure that this remains
efficient. It would be ideal if it were possible to do all reads up front and
concurrently. Further investigation on this point would be desirable.
This commit has a security-critical change in that the logic for position
withdrawals' balance commitment …
=> dex: streamline `PositionManager`

crates/core/app/src/action_handler/actions.rs
this uses the existing outbound_ics20_transfers_enabled to gate ics20 withdrawals
=> ibc: use outbound_ics20_transfers_enabled chain parameter

crates/core/transaction/src/plan/action.rs
=> feat(transaction): 📩 `ActionPlan: From<UndelegateClaimPlan>`

crates/bin/pcli/src/command/tx.rs
The rounding math was wrong previously (it wasn't actually rounding)
=> pcli: fix ics20 withdrawal timeout rounding

docs/guide/src/SUMMARY.md, docs/guide/src/pd/chain-upgrade.md, docs/guide/src/pd/join-testnet.md
Adds documentation for the specific steps to be performed by a node operator in order to participate in a chain upgrade. These docs are largely based on the existing wiki notes [0], adapted for a generalized Penumbra setup.
Similarly, sketched out some corresponding changes to the `pd testnet join` docs, but left them commented out for now: those docs are only relevant for joining a chain that has already been upgraded. If things go well with #4087, we'll uncomment those docs and start using them.
Finishes and therefore closes #3841.
[0] https://github.com/penumbra-zone/penumbra/wiki/Performing-upgrades
=> docs: chain upgrade procedure, for operators

crates/core/component/dex/src/component/dex.rs, crates/proto/src/state/write.rs
Close #4084, please do not merge.
=> dex: move `SwapExecution`s to NV storage

crates/bin/pd/src/main.rs, crates/bin/pd/src/migrate.rs
This implements a migration for #4084 and makes it the default command in `pd migrate`.
=> upgrades: write a migration script for #4084

COMPATIBILITY.md, crates/core/app/src/app/mod.rs, crates/core/app/src/lib.rs
This increments the `TOTAL_HALT_COUNTER` for `v0.71.0`
>  This is an internal counter.
=> app: increment halt counter

assets/minifront.zip, assets/node-status.zip
Pulls in the build outputs of the node-status and minifront apps.
=> Update minifront/node-status apps

.github/workflows/rust.yml, deployments/scripts/check-wasm-compat.sh
This add a quick `cargo check` to avoid leaking platform specific dependencies in our workspace, and breaking downstream dependencies like the `wasm` crate used by the extension.
The script itself could be refactored into a one-liner, but the current structure makes it easy to observe which crate fails to build for the special target.
=> ci: add component contract check

assets/minifront.zip, assets/node-status.zip, crates/bin/pd/tests/network_integration.rs
The previous .zip files had a subdirectory of the same name as the file itself. These updated files don't.
We should be creating zip files via a script — see https://github.com/penumbra-zone/web/issues/857. This will avoid issues like this in the future.
> No code related to consensus
=> fix(pd): minifront asset directory subpath

crates/core/app/tests/app_can_define_and_delegate_to_a_validator.rs
see #3995.
this addresses points 10b and 11a in #3995. this adds additional assertions to the `app_can_define_and_delegate_to_a_validator` test, which ensure that the validator's voting power changes as expected.
> test changes only
=> tests(app): 🏓 add voting power assertions to staking tests

Cargo.lock, crates/core/app/tests/app_can_undelegate_from_a_validator.rs, crates/core/component/stake/src/component/action_handler/undelegate.rs, crates/test/mock-client/Cargo.toml, crates/test/mock-client/src/lib.rs
this introduces additional test coverage for the staking component, examining the mock client's notes during delegation, the unbonding period, and after claiming an undelegation.
* #4115
* #3995
=> tests(app): ✨ add integration test coverage for undelegation

crates/bin/pcli/src/command/tx/liquidity_position.rs, crates/core/component/dex/src/component/circuit_breaker/value.rs, crates/core/component/dex/src/component/router/mod.rs, crates/core/component/dex/src/component/router/tests.rs, crates/core/component/dex/src/component/tests.rs
#4128 notes that we use the wrong terminology within the DEX, this PR fixes this by using a more precise nomenclature that reflects that each position is an AMM.
> client side changes
=> dex: fix incorrect nomenclature

crates/core/keys/src/keys/wallet_id.rs
Domain types implement the trait `DomainType` which adds proto encoding/decoding to the struct. This PR adds it for `WalletId`. This is helpful in the wasm crate when we pass over the wasm-javascript boundary: https://github.com/penumbra-zone/web/pull/846#discussion_r1543488080
=> Add WalletId domain impl

crates/core/component/stake/src/component/action_handler/validator_definition.rs, crates/core/component/stake/src/component/stake.rs, crates/core/component/stake/src/component/stake/tests.rs, crates/core/component/stake/src/component/validator_handler/validator_manager.rs, crates/core/component/stake/src/component/validator_handler/validator_store.rs
This PR adds a unit-test to the staking component to capture that we must "never"[^1] delete a `comet verification key -> identity key` entry from the consensus key index. This is because we always want to be able to do byzantine evidence attribution even if a validator has rotated the consensus key that they used to equivocate.
Keeping old entries around enables the evidence processor to resolve a consensus key to a persistent validator identity, and slash it / record a penalty.
More context in: https://github.com/penumbra-zone/penumbra/issues/4144 
> This is an internal refactor.
[^1]: fwiw - this is probably fine to prune after one or two unbonding windows have elapsed
=> staking: enshrine consensus key indexing requirement in unit-test

crates/cnidarium/src/lib.rs, crates/cnidarium/src/snapshot.rs, crates/cnidarium/src/storage.rs, crates/cnidarium/src/store/multistore.rs, crates/cnidarium/src/store/substore.rs, crates/cnidarium/src/write_batch.rs, crates/cnidarium/tests/write_batch.rs
refactor `commit` into `prepare_commit` and `commit_batch`. this allows a `StagedWriteBatch` to be prepared via `prepare_commit` and the actual writing the `StagedWriteBatch` to disk to occur in `commit_batch`. this allows us to get the root hash of the changes without requiring the data to be fully committed.
closes  #4095
=> cnidarium: implement deferred commits via `StagedWriteBatch`

.github/workflows/notes.yml
Docs builds broke after merge of [0], not because its settings were incompatible, but because its inclusion of a `rust-toolchain.toml` file busted the CI cache, and caused the `mdbook` dep to be freshly installed, rather than retrieved from cache. We don't version-lock mdbook and friends, and the latest version evidently bumped MSRV to 1.74, which is newer than what we set for MSRV. We should probably bump MSRV too, but I'll do that separately. This commit is to unbreak the docs builds.
[0] https://github.com/penumbra-zone/penumbra/pull/4145
> CI-only, docs-building logic.
=> ci: use nightly rust for mdbook installation

crates/bin/pcli/src/command/validator.rs, crates/bin/pcli/tests/proof.rs, crates/bin/pd/src/testnet/generate.rs, crates/core/app/tests/app_can_define_and_delegate_to_a_validator.rs, crates/core/app/tests/app_tracks_uptime_for_validators_only_once_active.rs, crates/core/app/tests/common/test_node_builder_ext.rs, crates/core/component/stake/src/component/action_handler/validator_definition.rs, crates/core/component/stake/src/component/stake/tests.rs, crates/core/component/stake/src/delegation_token.rs, crates/core/component/stake/src/identity_key.rs, crates/core/component/stake/src/rate.rs, crates/core/component/stake/src/state_key.rs, crates/core/component/stake/src/unbonding_token.rs, crates/core/component/stake/src/undelegate_claim/proof.rs
fixes #2304.
> only changes internal representation
=> stake: `VerificationKeyBytes` in `IdentityKey`

Cargo.lock, crates/bin/pcli/Cargo.toml
Bump the version of colored_json used by pcli to 4.1.
> This is a dependency upgrade that mainly just removes subdependencies and bumps the edition to 2021.
=> pcli: bump colored_json to 4.1

crates/util/tower-trace/src/lib.rs, crates/util/tower-trace/src/v038/request_ext.rs
implement support for ABCI v038 for the tower-trace util crate. required for eventual upgrade to ABCI v038 :)
n/a 
it only affects the tower-trace util crate
=> feat(utils): implement v038 for tower-trace

.cargo/config, crates/bin/pd/src/main.rs, crates/cnidarium/src/snapshot.rs, crates/cnidarium/src/storage.rs, crates/cnidarium/src/store/substore.rs
We use named tasks in `pd` and `cnidarium` via `tokio::task::Builder`. This is a great feature that improves `tokio-console` rendering and has proved valuable in the past. However, since tracing integration in tokio is still unstable, using this requires a special cargo configuration to run rustc with a special `tokio_unstable` flag.
We have received a lot of direct feedback that this is 1/ surprising 2/ cumbersome, and since it seem like there are no immediate plans to stabilize tracing in tokio, we are removing it for now.
> Internal only.
=> penumbra: remove `Builder` factory

crates/core/component/dex/src/component/action_handler/position/open.rs, crates/core/component/dex/src/component/circuit_breaker/value.rs, crates/core/component/dex/src/component/mod.rs, crates/core/component/dex/src/component/position_counter.rs, crates/core/component/dex/src/component/position_manager.rs, crates/core/component/dex/src/state_key.rs
Working towards achieving #4077.
This PR adds a `PositionCounter` extension trait which implements a `TradingPair` scoped position counter. I am not totally sold on a `u16` for the counter type, yet, but it's useful for testing anyway.
> This is consensus-breaking because it introduces a new implicit validation rule: a hard-limit on the number of position opened for each trading pair (via counter overflow). It could also be consensus breaking if there was a bug in the DEX that allowed closed positions to be updated, but my assumption is that it's not the case.
=> dex: track total number of positions per pair

tools/summonerd/src/main.rs
The `tokio-console` flag for `summonerd` defaults to `"false"` which evaluates to `true`. I'm leaving the console subscriber so that we can activate the unstable flag on a whim, but we should not have it run by default. 
> Internal CLI change
=> summonerd: disable console by default

crates/core/app/src/genesis.rs, crates/core/app/tests/app_can_define_and_delegate_to_a_validator.rs, crates/core/app/tests/app_can_undelegate_from_a_validator.rs, crates/core/app/tests/app_tracks_uptime_for_genesis_validator_missing_blocks.rs, crates/core/app/tests/app_tracks_uptime_for_genesis_validator_signing_blocks.rs, crates/core/app/tests/app_tracks_uptime_for_validators_only_once_active.rs, crates/core/app/tests/common/mod.rs, crates/core/component/stake/src/component/validator_handler/validator_store.rs
this branch adds some small tweaks to cut down on common boilerplate code found
in many of the staking component tests. this allows us to (a) easily set the
epoch duration, (b) fast forward to the end of an epoch, and (c) obtain the
identity keys of the currently defined validators. 
this is some common glue code in integration tests for the staking component.
in order to smooth the inspection of component logic that runs at epoch
boundaries, the defaults for `AppState`'s inner settings for e.g. epoch
duration are overriden to shorter values.
as is, this requres stating object literals that are somewhat verbose, even
with `..T::default()` elision. this commit adds some small `with_` helpers to
allow test cases to manipulate these settings succinctly.
this adds an extension method that can …
=> tests(app): 😌 deduplicate staking test boilerplate

.github/workflows/rust.yml, crates/core/component/compact-block/Cargo.toml, crates/core/component/compact-block/src/component/manager.rs, crates/misc/measure/Cargo.toml, crates/test/mock-consensus/Cargo.toml, deployments/scripts/check-crate-feature-sets
Suggested by @erwanor, based on the Astria CI config [0]. The goal is to ensure that our default feature sets actually work, by compiling each crate in the workspace individually.
[0] https://github.com/astriaorg/astria/blob/6cc8e2b828f8f5ee65e03c2b3383c4252b4c6b81/.github/workflows/test.yml#L64-L68
> The changes to crate content are explicitly declaring which imports should be activated based on feature sets. The rest of the diff is CI-only logic.
=> ci: add per-crate checks via cargo-hack

Cargo.lock, Cargo.toml, crates/bin/pd/Cargo.toml, crates/bin/pd/src/cli.rs, crates/bin/pd/src/main.rs, tools/summonerd/Cargo.toml, tools/summonerd/src/main.rs
This completely removes `console-subscriber` and the associated flag, on second thought it is worse to leave it around if it requires knowing about a secret compile flag to actually exercise. This also fix the summoner smoke test... 
> Internal change.
=> penumbra: completely remove `console-subscriber`

crates/test/mock-consensus/src/builder.rs
fixes #3937.
* #3937
* #3588
this adds a `two_validators` method to the test node builder, so that tests may set up a test node that has two validator keys.
> only adjusts test facilities
=> mock-consensus: 🫛 `two_validators` adds two keys

crates/core/component/dex/src/component/position_counter.rs, crates/core/component/dex/src/component/position_manager.rs, crates/core/component/dex/src/state_key.rs
This PR implements an inventory index, together with #4167, this PR works toward #4077 which contain the full eviction mechanism along with the adequate protocol specification update.
The state key added:
- $\text{I}_{A \rightarrow B} \coloneqq \text{prefix} \Vert BE(R_A) \Vert \text{id}$
- $\text{I}_{B \rightarrow A} \coloneqq \text{prefix} \Vert BE(R_B) \Vert \text{id}$
each corresponding to an index of position `Id`s ordered by reserves (ascending).
I plan to immediately follow-up this PR with a proposal to refactor the inner `PositionManager` index implementations.
> It adds a state key to nonverifiable storage, and absent the actual eviction mechanism, this isn't actually consensus breaking.
=> dex: add an eviction index based on position reserves

crates/test/mock-consensus/src/block.rs, crates/test/mock-consensus/src/builder.rs, crates/test/mock-consensus/src/builder/init_chain.rs, crates/test/mock-consensus/src/lib.rs, deployments/scripts/rust-docs
fixes #4181. see #3588.
this makes a pass through the `penumbra-mock-consensus` library and further documents various interfaces. one other small tweak, logging a warning if a caller may be inadvertently discarding transactions, is made while we are here.
these docs may be rendered by running:
`cargo doc --package penumbra-mock-consensus --open`
=> docs(mock-consensus): 🦅 document various testing interfaces

crates/core/app/tests/app_rejects_validator_definitions_with_invalid_auth_sigs.rs
fixes #4050. see also #3588.
this introduces a test case that demonstrates that transactions' validator definition actions must have a valid authentication signature, or the validator will not be added to the set of known validators.
> this is a test case.
=> tests(app): 🙅 app rejects invalid auth signatures

.github/workflows/buf-pull-request.yml, .github/workflows/containers.yml, .github/workflows/deploy-preview.yml, .github/workflows/deploy-testnet.yml, .github/workflows/disable-faucet.yml, .github/workflows/notes.yml, .github/workflows/smoke.yml, .github/workflows/summoner_smoke.yml
Changes made:
* docker/login-action v2 -> v3
* docker/metadata-action v4 -> v5
* docker/build-push-action v3 -> v5
* get-gke-credentials v1 -> v2
* helmfile v1 -> v2
* migrate actions-rs/toolchain -> dtolnay/rust-toolchain
* remove docker/setup-qemu-action
* remove battila7/get-version-action
* removes unused container builds
All of these were showing warnings. These upgrades *should* have zero side-effects for our CI, but I'll check post-merge and confirm that.
Refs #3769, but does not close it: follow-up may be necessary post-merge, plus corresponding updates should be made across our repos.
> CI-only, no code changes
=> ci: update several eol actions

.github/workflows/new-issues-labeled-needs-refinement.yml
the Penumbra team meets regularly to refine and discuss our backlog of tasks. this adds a workflow so that newly opened issues are accordingly labeled `needs-refinement`, so that they can be easily filtered in our refinement meeting.
this workflow is heavily inspired by the example workflow shown here: https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues
> only changes github workflows
=> feat(ci): 🔖 add `needs-refinement` label to new issues

Cargo.lock, Cargo.toml, crates/core/app/Cargo.toml, crates/core/app/tests/common/mod.rs, crates/test/tracing-subscriber/Cargo.toml, crates/test/tracing-subscriber/src/lib.rs
in #4193, @zbuc is working on some changes to the dex component. in the `penumbra-app` crate, we have a helpful utility to define a tracing subscriber that correctly interacts with `libtest`'s output capturing, and can be configured via `RUST_LOG` when running tests.
this is a tremendously helpful aid in debugging issues during feature development, and is not specific to the `penumbra-app` crate.
this commit hoists that test utility into a standalone library in `crates/test/`, so that other components like the dex can also create a guard to capture traces in tests.
now we can share this, by doing this:
```rust
#[tokio::test]
async fn example_test_case() -> anyhow::Result<()> {
// Install a test logger...
let guard = set_tracing_subscriber();
// Test logic here...
drop(guard);
Ok(())
}
``` …
=> tests: 🤝 hoist test subscriber into a standalone library

docs/guide/src/pcli/wallet/threshold.md
This augments the guide with a section describing the pcli threshold custody commands.
> Just a docs change
=> Add pcli threshold custody guide

crates/core/component/dex/src/component/circuit_breaker/value.rs, crates/core/component/dex/src/component/mod.rs, crates/core/component/dex/src/component/position_manager.rs, crates/core/component/dex/src/component/position_manager/base_liquidity_index.rs, crates/core/component/dex/src/component/position_manager/counter.rs, crates/core/component/dex/src/component/position_manager/inventory_index.rs, crates/core/component/dex/src/component/position_manager/price_index.rs, crates/core/component/dex/src/component/router/path.rs, crates/core/component/dex/src/state_key.rs
This PR:
- break out indexing methods from the `Inner` position manager trait into submodules with crate visibility
- refactor `update_position` to delegate indexing checks to `update_*_index` methods
- add a redundant guard against invalid transitions in `PositionManager::update_position`
- streamline the base liquidity index, fixing a bug with double counting closed positions
This PR contain changes to critical parts of the DEX engine internals.
> This is technically consensus breaking because we fix a bug in the base liquidity index logic, which could trickle down into different DEX execution in some rare cases.
=> dex: refactor internal indexing into ext traits

Cargo.lock, crates/core/asset/src/asset/registry.rs, crates/core/component/auction/Cargo.toml, crates/core/component/auction/src/auction.rs, crates/core/component/auction/src/auction/dutch.rs, crates/core/component/auction/src/auction/dutch/actions/end.rs, crates/core/component/auction/src/auction/dutch/actions/mod.rs, crates/core/component/auction/src/auction/dutch/actions/schedule.rs, crates/core/component/auction/src/auction/dutch/actions/withdraw.rs, crates/core/component/auction/src/auction/nft.rs, crates/core/transaction/src/is_action.rs, docs/protocol/src/transactions/actions.md
This PR:
- add `auctionnft`s to the asset registry
- augment `AuctionNft` with denom metadata
- implements `DutchAuctionDescription::id`
- implements value `balance` for each action
- implements computing the balance commitment for the withdraw action
This is a prelude to #4212 
> This isn't connected to the rest of the app yet.
=> auction: define action balances

crates/core/component/dex/src/component/action_handler/position/open.rs, crates/core/component/dex/src/component/action_handler/swap.rs
Closes #4078 
Unsure if `anyhow::bail!` is the ideal behavior for swaps & position opens when the dex is disabled, but it seems right to display an explanatory message as to why the swap or open does not occur.
https://github.com/penumbra-zone/penumbra/issues/4078
> This will alter the dex behavior across the change boundary (acceptance/rejection of swaps & position opens) so it should break consensus between versions.
=> dex: add checks to disable swaps and opening positions when the dex is disabled

crates/core/component/dex/src/component/position_manager/base_liquidity_index.rs
This slipped when doing #4188. I'm not completely sure yet why CI didn't catch this. 
> Internal
=> dex(base_liq): add `async_trait` to `BaseLiquidityIndex`

Cargo.lock, crates/core/component/auction/Cargo.toml, crates/core/component/auction/src/auction/dutch.rs, crates/core/component/auction/src/component/action_handler/dutch/end.rs, crates/core/component/auction/src/component/action_handler/dutch/schedule.rs, crates/core/component/auction/src/component/action_handler/dutch/withdraw.rs, crates/core/component/auction/src/component/auction.rs, crates/core/component/auction/src/component/auction_store.rs, crates/core/component/auction/src/component/dutch_auction.rs, crates/core/component/auction/src/component/mod.rs, crates/core/component/auction/src/state_key.rs
This PR adds validation logic for:
- `ActionDutchAuctionSchedule`
- `ActionDutchAuctionEnd`
- `ActionDutchAuctionWithdraw`
and a component implementation, on a model similar-but-simpler to the DEX:
- a `DutchAuctionManager` extension trait defines a crate-level API to effect a validated action
- an `Inner` internal implementation manages writing to the state
- internal data can be accessed via a general `AuctionStoreRead` trait which manage tentatively deserializing raw auction state (wkt `Any`) into a useful domain type.
#4211 
> Those actions are not integrated in our transaction system, our application impl.
=> auction: `ActionDutchAuction*` validation and component impl

.github/workflows/release.yml, Cargo.toml, crates/bin/pd/Cargo.toml, deployments/containerfiles/Dockerfile, docs/guide/src/dev/build.md
Use of async fns in traits was stabilized in Rust 1.75 [0], git-bisect showed that [1] began breaking container builds, where we pin an explicit version of rust.
We recently added a `rust-toolchain.toml`; perhaps we should hard-code a specific version of rust there, to avoid surprises. Not doing that now.
[0] https://blog.rust-lang.org/2023/12/21/async-fn-rpit-in-traits.html
[1] c8c980da4b922ce2914cd5237b2debeef156c0c0
> No source code changes, only CI and build logic.
=> build: bump msrv 1.73 -> 1.75

docs/guide/book.toml
Follow-up to #4215, in which we reorganized the guide for readability. Some of the existing content got shuffled into subroutes, and already one person in Discord has pointed out that we broken URLs. Tacking on some http redirects via mdbook [0].
[0] https://rust-lang.github.io/mdBook/format/configuration/renderers.html#outputhtmlredirect
> docs-only, no code changes.
=> docs: add a few redirects

crates/core/app/src/action_handler/actions.rs, crates/core/app/src/action_handler/actions/submit.rs, crates/core/transaction/src/action.rs, crates/core/transaction/src/gas.rs, crates/core/transaction/src/plan/action.rs, crates/core/transaction/src/transaction.rs
Add `GasCost` vectors for DA actions, add`Action` / `ActionPlan` skeletons, and make gas fee costs consistent with protobuf encodings (https://github.com/penumbra-zone/penumbra/issues/3940)
References #4212
=> auction: add `GasCost` impls for actions

Cargo.lock, Cargo.toml, crates/bin/pcli/Cargo.toml, crates/bin/pcli/src/terminal.rs
When reading input from the terminal in `pcli threshold` commands, circumvent OS-imposed restrictions on line length (required for interactive editing and notably low on MacOS) by dropping into "raw mode", reading the input a byte at a time and manually printing out the read byte to the user, then return to "cooked mode" (yes, that's what it's called) after detecting `\n` or `\r`.
Closes #4230, which I confirmed through my own testing.
> only changes to `pcli` terminal handling
=> pcli: fix terminal input in pcli threshold

crates/core/app/src/app/mod.rs
fixes #3739.
the `App` only ever invokes the Sct component's `init_chain` and `begin_block` hooks.
this isn't currently a bug, since its `end_block` and `end_epoch` hooks are noöps, but could easily lead to a surprising outcome in the future, if more logic was introduced to those trait methods.
> while this **does** change the control flow of consensus-critical logic, this does **not**
change the execution of incoming data. the hooks introduced here are noöps.
=> feat(app): 🎋 add missing `Sct` component hooks

crates/core/app/src/app/mod.rs
see #3739, and #4246.
while wiring up a pair of missing component hooks for the `Sct` component, i found another (noöp) hook that we do not include in the `App`'s control flow.
this isn't currently a bug, since `<Dex as Component>::begin_block()` is a noöps but could easily lead to a surprising outcome in the future, if more logic was introduced to that trait method.
> while this **does** change the control flow of consensus-critical logic, this does **not**
change the execution of incoming data. the hooks introduced here are noöps.
=> feat(app): 🎣 add missing `Dex` component hook

Cargo.lock, crates/view/Cargo.toml, crates/view/src/planner.rs
Add planner support for auctions
References https://github.com/penumbra-zone/penumbra/issues/4241
=> auction(planner): add actions to planner

docs/guide/src/node/pd/chain-upgrade.md
Follow-up to #4097. We performed a chain upgrade on Penumbra for v0.71.0. Based on feedback from the community validators, we've refined the procedure somewhat. Substantive changes to the docs are as follows:
* backup the entire pd & cometbft data dirs, as a precaution
* upgrade to new pd early, prior to running export, for simplicity's sake
* only move the exported rocksdb directory, which allows preservation of other dirs in pd state, e.g. acme tls info
* do not reset priv validator state
* amend custom find command to preserve `tx_index.db`
Not yet included in these docs are specifics about the upcoming release; we'll add those soon.
Finishes and therefore closes #1812.
> docs-only, no code changes
=> docs: clarify chain upgrade procedure

crates/bin/pd/src/cli.rs, crates/bin/pd/src/main.rs, crates/bin/pd/src/testnet/generate.rs, deployments/scripts/smoke-test.sh
Adds a new CLI flag for `pd testnet generate`, to opt in to non-zero gas
prices. It's a bit of a shortcut to reuse the same numeric value across
all of them, but we can always add more CLI flags later to finetune.
Closes https://github.com/penumbra-zone/penumbra/issues/4154.
> Adds opt-in behavior, and modifies CI runs, but does not touch application code.
The simplest way to validate the new behavior here is:
0. check out this feature branch
1. `cargo run --bin pd -- testnet generate --gas-price-simple 5`
2. start cometbft/pd to serve the local devnet
3. configure pcli to use http://locahost:8080 as grpc_addr
4. run `pcli --home <path> view balance` and confirm you have multiple denoms
5. run `pcli --home <path> tx send --to <different_addr_in_same_wallet> 1test_usd`
6. run `pcli --home …
=> feat(pd): add --gas-price-simple flag to generate

crates/bin/pcli/src/transaction_view_ext.rs, crates/core/component/dex/src/swap/view.rs, crates/core/transaction/src/is_action.rs, crates/proto/src/gen/penumbra.core.component.dex.v1.rs, crates/proto/src/gen/penumbra.core.component.dex.v1.serde.rs, proto/penumbra/penumbra/core/component/dex/v1/dex.proto
Many of the "opaque" variants of our view messages don't have any extra data other than the raw action. This turns out to be insufficient, because often there's additional data that's practically necessary to understand the public parts of the action.
For instance, in this case, the `SwapView`, we want to correctly and nicely render the public parts of the swap, which include:
- the input amounts, which are transparent;
- the pro-rata output amounts, which are computable given public information.
However, this information can't be easily rendered just from the underlying `Swap`, because:
- it doesn't contain the asset `Metadata` about the values, only the amount and asset IDs;
- it doesn't contain the `BatchSwapOutputData` with the (public) results of the batch swap;
- it doesn't have …
=> proto: add extra metadata fields to `SwapView.Opaque`

docs/guide/src/node/pd/chain-upgrade.md
We recently removed mention of zeroing-out `priv_validator_state.json` for CometBFT as part of the chain upgrade docs. During migration testing on a private fork today, though, several of us observed that without this change, the network would not resume. More research required to understand the root cause here.
Refs #4245, #4239.
> docs-only :sunglasses:
=> docs: re-add priv val state munging for upgrades

docs/guide/src/node/pd/join-testnet.md
Refs #4239, #4271.
> docs-only
Try to join the network by running the testnet join command in the docs. You must use `v0.72.0` in order for it to work, otherwise your local copy of pd won't be compatible. Then verify you can actually join the network and grab blocks.
=> docs: update archive url for joining testnet

docs/guide/src/node/pd/chain-upgrade.md
Folks in the validator community reported frequent failures of the `--migrate-archive` flag. I was able to use it during upgrades, and posted the results on snapshots.penumbra.zone, but it's not actually required for the chain upgrade, so let's remove it in order to keep the process on rails.
docs-only
=> docs: exclude migrate-archive during chain upgrade

crates/core/app/tests/app_can_define_and_delegate_to_a_validator.rs, crates/core/app/tests/app_can_disable_community_pool_spends.rs, crates/core/app/tests/app_can_propose_community_pool_spends.rs, crates/core/app/tests/app_can_undelegate_from_a_validator.rs, crates/core/app/tests/app_rejects_validator_definitions_with_invalid_auth_sigs.rs, crates/core/app/tests/app_tracks_uptime_for_genesis_validator_missing_blocks.rs, crates/core/app/tests/app_tracks_uptime_for_genesis_validator_signing_blocks.rs, crates/core/app/tests/app_tracks_uptime_for_validators_only_once_active.rs, crates/core/app/tests/common/mod.rs, crates/core/app/tests/common/validator_read_ext.rs, crates/core/app/tests/mock_consensus_can_define_a_genesis_validator.rs, crates/core/component/stake/src/component/rpc.rs, crates/core/component/stake/src/component/validator_handler/validator_store.rs
see #3846.
**NB:** this branch performs a refactor away from `validator_definitions()` and subsequently moves the definition of that method. this is done in distinct commits, which reviewers are encouraged to examine independently.
> The staking component query service provides a ValidatorInfo RPC that returns
> the list of registered validators, optionally filtering Inactive validators.
>
> The way this method is implemented is by using an internal
> ValidatorDataRead::validator_definitions methods which returns every single
> definition ever submitted to the chain. This is problematic because this list
> will inevitably grow quite large, turning usage of a benign-looking method
> into an onerous source of I/O and expensive rendering.
this refactors the `validator_definitions()` method …
=> staking: 🥞 `get_validator_info()` uses consensus set

Cargo.lock, Cargo.toml, crates/bin/pcli/Cargo.toml, crates/bin/pcli/src/terminal.rs
Cherry picks 1376d4b4f47f44bcc82e8bbdf18262942edf461e onto the 0.73 release branch so that we can deploy a patch release of pcli ahead of a network upgrade.
#4230 
> only changes the pcli terminal handling
=> Cherry-pick `pcli threshold` fix onto 0.73 release branch

.cargo/config, .github/workflows/buf-pull-request.yml, .github/workflows/docs-lint.yml, .github/workflows/notes.yml, .github/workflows/release.yml, .github/workflows/rust.yml, .github/workflows/smoke.yml, .github/workflows/summoner_smoke.yml, Cargo.toml, deployments/containerfiles/Dockerfile, docs/guide/src/dev/build.md, rust-toolchain.toml
Bumps the cargo-dist dependency, and regenerates the relevant CI files. Tested these changes in a private fork, so we can be confident they won't break builds.
Motivated by deprecation warnings in cargo-dist declaring that pinning rust versions should use `rust-toolchain.toml`, updated ours to pin 1.75. Standardizing on the toolchain file lets us remove repeated versions from a few different places, such as the containerbuild. Removed custom action helpers from Rust CI workflows, because GHA runners already come with rustup, and will honor the toolchain file. This change ensures that our dev, build, and test environments all use the same version of rust, which should minimize surprises like we saw in #4231.
Included in the release artifacts now is a complete source tarball with associated …
=> ci: update cargo-dist 0.5.0 -> 0.13.3

.dockerignore
Follow-up to #4282, ensuring that the rust-toolchain.toml makes it into the container image, otherwise it'll throw an error on image build. Observed this on the post-merge preview deploy.
> ci/build only
=> ci: fix rust-toolchain.toml in container

crates/bin/pcli/src/command/ceremony.rs, crates/bin/pcli/src/command/tx.rs, crates/bin/pclientd/tests/network_integration.rs, crates/core/app/src/action_handler/transaction.rs, crates/core/app/tests/app_can_define_and_delegate_to_a_validator.rs, crates/core/app/tests/app_can_disable_community_pool_spends.rs, crates/core/app/tests/app_can_propose_community_pool_spends.rs, crates/core/app/tests/app_can_spend_notes_and_detect_outputs.rs, crates/core/app/tests/app_can_undelegate_from_a_validator.rs, crates/core/app/tests/app_tracks_uptime_for_validators_only_once_active.rs, crates/core/app/tests/swap_and_swap_claim.rs, crates/core/component/dex/src/swap/plaintext.rs, crates/core/component/governance/src/delegator_vote/proof.rs, crates/core/component/shielded-pool/src/component/note_manager.rs, crates/core/component/shielded-pool/src/note.rs, crates/core/component/shielded-pool/src/output/plan.rs, crates/core/component/shielded-pool/src/spend/proof.rs, crates/core/component/stake/src/funding_stream.rs, crates/core/keys/src/address.rs, crates/core/keys/src/address/r1cs.rs, crates/core/keys/src/address/view.rs, crates/core/transaction/src/memo.rs, crates/core/transaction/src/plan.rs, crates/view/src/planner.rs, crates/view/src/service.rs, crates/wallet/src/plan.rs, tools/summonerd/src/participant.rs, tools/summonerd/src/queue.rs, tools/summonerd/src/server.rs
fixes #1957.
the last remaining item mentioned in #1957 is that currently, while `Address`
_caches_ the diversified base point, it eagerly computes it when
`Address::from_components()` is called.
we can defer this action until the base point is needed, using `OnceLock<T>`.
in order to do that, we must revoke the `Copy` derivation. essentially, this
branch makes the following change(s) to `Address`:
```diff
-#[derive(Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
+#[derive(Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(try_from = "pb::Address", into = "pb::Address")]
pub struct Address {
d: Diversifier,
/// cached copy of the diversified base
-    g_d: decaf377::Element,
+    g_d: OnceLock<decaf377::Element>,
/// extra invariant: the bytes in pk_d should be the canonical …
```
=> keys: 🥰 `Address` defers computation of diversified base

.dockerignore, .github/workflows/buf-pull-request.yml, .github/workflows/docs-lint.yml, .github/workflows/notes.yml, .github/workflows/release.yml, .github/workflows/rust.yml, .github/workflows/smoke.yml, .github/workflows/summoner_smoke.yml, Cargo.toml, deployments/containerfiles/Dockerfile, docs/guide/src/dev/build.md, rust-toolchain.toml
Ports the CI fixes in https://github.com/penumbra-zone/penumbra/pull/4282 & https://github.com/penumbra-zone/penumbra/pull/4286 to the release branch for the current testnet. Doing this so that today's point release for https://github.com/penumbra-zone/penumbra/pull/4284 will include new build artifacts. 
Involved some manual conflict-resolution, particularly around RUSTFLAGS, preserving the overrides since we haven't dropped the requirement for the tokio unstable flag in the release branches yet. Made sure to test the latest copy of the release workflow on a private fork.
> build/ci only
=> Cherry-pick ci fixes to release/v0.73.x branch

crates/core/asset/src/asset/denom_metadata.rs
Closes #4191 - small PR to check a box on testing - we have an assert in play here in the conversion, but this test captures that the conversion does in fact error when these fields aren't consistent. Round-trip test added as a sanity check, not essential to the PR.
=> metadata: add tests for decoding failure when asset_id and denom don't match and simple roundtrip encoding test

crates/bin/pd/src/migrate.rs, crates/bin/pd/src/migrate/testnet74.rs, crates/core/component/dex/src/component/arb.rs, crates/core/component/dex/src/component/tests.rs
This extends the existing arbitrage test to ensure that the created `SwapExecution` has the expected trace and input/output values, as well as fixes the bug described in #3790 where `SwapExecution`s were created with incorrect `Output` values.
#3790
This will require a migration to update the existing `SwapExecution` structures. The migration should be as simple as adding the `input` to the `output` for each of them.
=> Add test for and fix arbitrage swap execution output amount

crates/proto/src/state/read.rs
This fix incorrect comments on `StateReadProto` nv methods.
> Comments
=> penumbra-proto: fix comments on `StateReadProto` nv methods

README.md
We have an email alias set up for team leads, so that external parties have a single entrypoint to disclose security-related issues. Once we settle on language here, we can duplicate this notice in other Penumbra-related repositories.
> docs-only
=> docs: add security email info to readme

crates/core/app/src/action_handler/transaction.rs, crates/core/app/src/action_handler/transaction/stateful.rs, crates/core/app/src/genesis.rs, crates/core/app/tests/app_can_define_and_delegate_to_a_validator.rs, crates/core/app/tests/app_can_deposit_into_community_pool.rs, crates/core/app/tests/app_can_disable_community_pool_spends.rs, crates/core/app/tests/app_can_propose_community_pool_spends.rs, crates/core/app/tests/app_can_spend_notes_and_detect_outputs.rs, crates/core/app/tests/app_can_undelegate_from_a_validator.rs, crates/core/app/tests/app_rejects_validator_definitions_with_invalid_auth_sigs.rs, crates/core/app/tests/app_tracks_uptime_for_genesis_validator_missing_blocks.rs, crates/core/app/tests/app_tracks_uptime_for_genesis_validator_signing_blocks.rs, crates/core/app/tests/app_tracks_uptime_for_validators_only_once_active.rs, crates/core/app/tests/mock_consensus_can_define_a_genesis_validator.rs, crates/core/app/tests/mock_consensus_can_send_a_sequence_of_empty_blocks.rs
Resolves #4308.
**This is a consensus-breaking change.**
=> Add stateful checks for chain ID and expiry height

.github/workflows/smoke.yml, crates/bin/pcli/tests/network_integration.rs, deployments/compose/process-compose-smoke-test.yml, deployments/scripts/smoke-test.sh, docs/guide/src/dev/devnet-quickstart.md, justfile
A while back we ditched using containers for the smoke tests, mostly because the caching on the container-build story was atrocious, so test re-runs took a really long time. And frankly, container ergonomics on dev workstations, particularly macOS, are not awesome. Instead, let's assume the dev env can run processes for cargo, pd, and cometbft. If so, that's all we need to wire up our integration testing. Enter [process-compose](https://github.com/F1bonacc1/process-compose).
The new smoke test setup ditches the bash script and delegates to process-compose for orchestrating processes:
0. pre-building binaries and test artifacts
1. testnet config generation
2. running pd and cometbft
3. running `cargo test` for each binary's integration tests
4. reporting output
The wrapper script uses tty …
=> feat(tests): faster smokes via process-compose

crates/core/component/stake/src/component/validator_handler/uptime_tracker.rs
We were inappropriately `increment`ing a gauge to track missed blocks, when instead we should have been clobbering the value via `set`, as we know the precise number from the state machine. This fixes a broken metric for missed blocks that was growing too fast, emitting wrong values.
Refs #3746.
_Not_ included in this small patch is a rework of the other validator-related metrics. As described in #3746, we should migrate those metrics to use Events instead. 
> metrics-only, no logic changes
=> fix(metrics): validator missed blocks, inc -> set

crates/core/app/src/action_handler/actions.rs, crates/core/component/ibc/src/component/action_handler/ibc_action.rs, crates/core/component/ibc/src/component/client.rs, crates/core/component/shielded-pool/src/component/action_handler/ics20_withdrawal.rs
This is a mechanical refactor to fold the ibc/ics20 historical checks into a more visible place (their action handler implementations).
> Mechanical refactor
=> app: fold ibc stateful/historical check into their AHs

crates/bin/pd/src/migrate.rs, crates/bin/pd/src/migrate/testnet74.rs
@hdevalence noticed that we were missing a migration for the `AuctionParameters`. This PR adds a migration to write the parameters to the app state.
This was a miss in #4259
> This is a migration
=> pd(migrate): add auction parameters to chain state for `Testnet74`

.github/workflows/docs-lint.yml, crates/bin/pd/src/migrate.rs, crates/bin/pd/src/migrate/testnet74.rs
Closes #4344. Hat tip to @erwanor for spotting the omission.
> Code change fixes migration behavior, so is very relevant to not breaking consensus.
This change is a bit tricky to test manually, but the rationale in #4344 is sound. I'd like to get it in, so we can rebase #4337 on top of it, and go back to debugging #4340.
=> fix(migration): release storage locks

docs/guide/src/node/pd/requirements.md, docs/guide/src/pcli/wallet.md
Tweak the description of validator key management to clarify the roles of the different keys
> docs changes
=> docs: update guide for validator custody

crates/core/transaction/src/action_list.rs, crates/core/transaction/src/lib.rs, crates/view/src/planner.rs
Reorganize the `ActionList` struct, enabling the web code to use the same structure when updating its rust dependencies. 
References https://github.com/penumbra-zone/penumbra/issues/4332
=> view: reorganize planner components

.github/workflows/rust.yml, crates/bin/pd/src/migrate/testnet74.rs
Fixes a chain halt due to changes introduced in #4188.
Previously, aggregate liquidity lookups in non-verifiable storage (i.e. "how much liquidity is available for trading pair `(A, B)`?") were stored as raw big-endian encoded values. In #4188 the DEX state accessors were refactored and part of that was adjusting the accessors for aggregate liquidity lookups to use `nonverifiable_put`/`nonverifiable_get` instead of the `_raw` methods they were using previously.
**Manually testing the values were changed appropriately is actually quite difficult currently as `pcli` doesn't support querying values from non-verifiable storage, and returned values need to be parsed correctly into the `Amount` data type.**
- Create a devnet on v0.73.1
- Watch for changes to the aggregate liquidity prefix: …
=> fix(dex): migration for dex trait proto encodings

Cargo.lock, crates/view/Cargo.toml, crates/view/src/service.rs, crates/view/src/storage.rs, crates/view/src/worker.rs
this introduces some additional `tracing` instrumentation, used while debugging
integration with the view server in mock consensus tests. because these events
may be useful more broadly, and aren't strictly tied to testing, this is
cherry-picked out of that work for separate consideration.
* #3913
this branch only makes changes to tracing spans and events. as this is
only altering telemetry, this is not consensus-breaking.
=> view: 👀 introduce more tracing instrumentation

crates/core/app/src/rpc.rs
This adds missing middleware to the auction query service
> query server change
=> auction(rpc): support `grpc-web` in the auction query service

Cargo.lock, crates/bin/pcli/src/command/init.rs, crates/bin/pcli/src/command/threshold.rs, crates/bin/pcli/src/config.rs, crates/bin/pcli/src/opt.rs, crates/bin/pcli/src/terminal.rs, crates/custody/Cargo.toml, crates/custody/src/encrypted.rs, crates/custody/src/lib.rs, crates/custody/src/terminal.rs, crates/custody/src/threshold.rs, crates/custody/src/threshold/sign.rs, docs/guide/src/pcli/wallet.md, docs/guide/src/pcli/wallet/softkms.md, docs/guide/src/pcli/wallet/threshold.md
This adds a new option to encrypt the `soft-kms` and `threshold` custody backends with a password, so that spend-key related material is encrypted at rest. This is implemented by:
1. Having a `pcli init --encrypted` flag that applies to both of these backends, which prompts a user for a password (and confirmation) before using that to encrypt the config.
2. Having a `pcli init re-encrypt` command to read an existing config and encrypt its backend, if necessary, to allow importing existing configs.
This is also implemented internally in a lazy way, so that a password is only prompted when the custody services methods are actually called, allowing us to not need a password for view only commands.
Closes #4293.
> This is a client-only change.
=> Add an encrypted config option to pcli

flake.lock
this updates the `flake.lock` lockfile, via running `nix flake update`.
n/a
> this is only a change to developer tooling, specifically, a lockfile
> recording the versions of e.g. nixpkgs in use in the development shell.
=> chore(flake): 🥐 update lockfile

Cargo.lock, crates/bin/pcli/src/command/init.rs, crates/bin/pcli/src/command/threshold.rs, crates/bin/pcli/src/config.rs, crates/bin/pcli/src/opt.rs, crates/bin/pcli/src/terminal.rs, crates/custody/Cargo.toml, crates/custody/src/encrypted.rs, crates/custody/src/lib.rs, crates/custody/src/terminal.rs, crates/custody/src/threshold.rs, crates/custody/src/threshold/sign.rs
Backports the following to 0.73.x:
- #4343
- #4352
#4345
> only pcli custody changes
=> Backport custody improvements

crates/bin/pcli/src/main.rs
this isn't anything interesting. it organizes the imports in `pcli`'s entrypoint, separating imports from the `crate::{}` namespace from those that import from external crates.
=> chore(pcli): 🧹 tidy entrypoint imports

crates/cnidarium/src/rpc.rs
This changes the `pcli query watch` command to fix a bug and improve usability.
Previously, the `nv_key_regex` was implemented incorrectly. This PR also makes the watch command disable watching the other storage type if only a single regex is supplied.
There is a slight drawback in the current implementation in that you cannot enable filtering the watch command for one of the regexes while supplying an empty regex for the other to view all matches, however changing this would require a change to the proto interface: `rpc Watch(WatchRequest) returns (stream WatchResponse);`
Closes #4360
> Only affects RPC return
=> Better handle regex in `pcli query watch`

docs/guide/src/node/pd/chain-upgrade.md
Fixed indented list. Explicitly mention backup. Remove recommendation, even optionally, to use `pd export` on post-migration state, because `pd export` won't generate an archive that's suitable for use with `pd testnet join`. We'll do that manually as part of post-release follow-up.
> docs-only!
=> docs: refine migrate steps

.gitignore, crates/bin/pcli/src/command/ceremony.rs, crates/bin/pd/src/main.rs, deployments/scripts/smoke-summoner.sh, flake.nix
this provides some small changes needed for running the summoner smoke test locally.
fixes #4321.
fixes #4370.
> this branch only changes testing infrastructure and development tooling.
=> ci: 🚭 fix summonerd smoke tests

crates/core/app/src/app/mod.rs
Follow-up to 0f349704c7af88f997d2a23bf2e939a1f5ca18f0, which claimed to reset this value, but did not actually.
Refs: 
* https://github.com/penumbra-zone/penumbra/pull/4375
* https://github.com/penumbra-zone/penumbra/issues/4374
> Very relevant to shipping migrations.
=> fix: reset TOTAL_HALT_COUNT

deployments/scripts/smoke-summoner.sh
addendum to #4358.
> this only makes a change to ci scripts.
=> ci: 🩹 add missing `"` to pid expansion

crates/core/component/dex/src/component/action_handler/swap.rs, crates/core/component/dex/src/component/dex.rs, crates/core/component/dex/src/component/position_manager.rs, crates/core/component/dex/src/component/router/tests.rs, crates/core/component/dex/src/state_key.rs
This PR extends arbitrage routing to route against assets involved in swaps and positions opened during the current block.
#4177
=> dex: Extend arbitrage routing

deployments/scripts/rust-docs
This will let us browse them on `rustdoc.penumbra.zone`
> ci change to doc build
=> ci: add `penumbra-mock-*` to rustdoc build list

crates/core/asset/src/asset/id.rs
add method to `asset::Id` that gives the base64 encoding of the inner bytes
Closes #4192
> It's just a helper method
=> feat: add method to `asset::Id` that gives the base64 encoding of the inner bytes

crates/bin/pd/src/cli.rs, crates/bin/pd/src/main.rs, crates/bin/pd/src/migrate.rs, crates/bin/pd/src/migrate/reset_halt_bit.rs, crates/bin/pd/src/migrate/simple.rs, crates/bin/pd/src/migrate/testnet72.rs, crates/bin/pd/src/migrate/testnet74.rs, crates/core/app/src/app/mod.rs, crates/core/app/src/app/state_key.rs, crates/core/component/governance/src/component/view.rs, crates/core/component/governance/src/state_key.rs, crates/proto/src/state/read.rs, crates/proto/src/state/write.rs
This PR implements #4373 
> This is consensus breaking because it deprecates the application halt counter stored within the verifiable chain state. However, it does not require a state migration because the switch starts in the "off" (i.e. `false`) position. As a result, everything else being equal, using a new upgraded binary should be sufficient.
=> app: switch halt counter with halt bit

Cargo.lock, Cargo.toml
fixes #4392.
in #4392, we found an issue with gRPC reflection when recent versions of `grpcurl` were used to list supported endpoints.
this was tracked down and fixed in #hyperium/tonic#1701, in collaboration with @conorsch. that pr targets the more recent 0.11 tonic release however, which we are not yet using.
eventually we should upgrade to tonic 0.11 (see #4400). as a short-term measure, but we want to unblock engineers from Skip working on an integration with Penumbra. this commit patches the `tonic` dependencies used to point to a temporary fork of the `tonic` repo, where i have backported that patch (and some ci-related fixes) to the 0.10 release.
see also:
* https://github.com/hyperium/tonic/pull/1701
* https://github.com/penumbra-zone/tonic/pull/1
* …
=> tonic: 🍸 patch tonic dependencies

crates/bin/pd/src/main.rs, crates/bin/pd/src/migrate.rs, crates/bin/pd/src/migrate/testnet76.rs, crates/cnidarium/src/lib.rs, crates/cnidarium/src/snapshot.rs, crates/cnidarium/src/storage.rs, crates/cnidarium/src/write_batch.rs, crates/core/app/Cargo.toml, crates/core/app/tests/app_reproduce_testnet_75_vcb_close.rs, crates/core/app/tests/common/mod.rs, crates/core/component/auction/src/component/action_handler/dutch/end.rs, crates/core/component/auction/src/component/auction.rs, crates/core/component/auction/src/component/auction_store.rs, crates/core/component/auction/src/component/dutch_auction.rs, crates/core/component/auction/src/component/mod.rs, crates/core/component/auction/src/component/rpc.rs, crates/core/component/auction/src/state_key.rs, crates/core/component/dex/src/component/circuit_breaker/value.rs, crates/core/component/dex/src/component/dex.rs, crates/core/component/dex/src/component/position_manager.rs, crates/core/component/dex/src/component/position_manager/base_liquidity_index.rs, crates/core/component/dex/src/component/position_manager/inventory_index.rs, crates/core/component/dex/src/component/router/path.rs, crates/core/component/dex/src/component/router/path_search.rs, crates/test/tracing-subscriber/src/lib.rs
> This is consensus-breaking and state-breaking. Migration WIP.
=> auction: credit VCB when ending an auction

Cargo.lock, Cargo.toml
No tag associated with this increment. Making the change to the local Cargo.toml files specifically to differentiate versions explicitly while testing upgrades and migrations from the previous stable tag of v0.75.0.
Refs #4402.
> no code changes, version bump only.
=> chore: bump version to 0.76.0-alpha.1

crates/core/component/dex/src/component/arb.rs, crates/core/component/dex/src/component/circuit_breaker/execution.rs, crates/core/component/dex/src/component/circuit_breaker/mod.rs, crates/core/component/dex/src/component/circuit_breaker/value.rs, crates/core/component/dex/src/component/dex.rs, crates/core/component/dex/src/component/mod.rs
Close #4113
> This is consensus-breaking and state-breaking, but does not require any migration to heal the dex vcb
=> dex: deduct arb surplus from component VCB

.github/workflows/rust.yml
Bumping up the size of the runner, since we added more compute-intensive logic back in [0]. The logic is still serialized, but now it should complete faster. I've noticed the cache getting evicted faster lately, due to multiple large PRs, so the extra compute will help offset the delay caused by cache busting.
[0] f7234c0299b3732a6a7119c13a2eafaa6196bc7a
> ci-only
=> ci: faster cargo check features

crates/core/component/ibc/src/component/msg_handler/channel_open_ack.rs, crates/core/component/ibc/src/component/msg_handler/connection_open_ack.rs, crates/core/component/ibc/src/component/msg_handler/timeout.rs, crates/core/component/ibc/src/component/msg_handler/upgrade_client.rs, crates/core/component/ibc/src/component/proof_verification.rs
This PR contains a set of fixes for the higher sev issues from the recent audit of the penumbra-ibc codebase, that are specific to the state machine side of things (as opposed to `ibc-types`, there will be a follow up PR for ibc-types and a new release for the relevant fixes there).
closes #4421 
closes #4420 
closes #4419 
closes #4418
=> ibc: audit fixes

crates/bin/pd/src/migrate.rs, crates/bin/pd/src/migrate/testnet76.rs
Closes #4430. 
Temporarily included testing setup from #4337, because that's how I've been validating behavior locally. Dropped that, will focus on making the logic reusable in that PR.
> highly relevant to breaking changes, given that this refines the logic. fixes the bug described in #4430
=> fix: release storage locks on testnet76 migration

crates/bin/pcli/src/command/tx.rs
Closes #4414 
Changes a pcli error message to be more helpful
> Only changes pcli output text
=> pcli: improve error message for delegation failure to suggest pcli tx sweep

crates/bin/pd/src/migrate/testnet76.rs
This sets the halt flag to `false` after running the `Testnet76` migration. 
> Migration change
=> pd(migrate): set halt flag to false

.github/workflows/smoke.yml, Cargo.lock, crates/bin/pd/Cargo.toml, crates/bin/pd/tests/network_integration.rs, deployments/scripts/install-grpcurl, deployments/scripts/smoke-test.sh
Refs #4392. We want to ensure that server reflection remains working, despite changes to the tonic dependencies (#4400) and proto compiling logic #4422. While the most effective test is exercising all these protos regularly, we currently lack solid coverage, so this superficial integration test is a sanity-check to save time versus building locally and inspecting the output manually.
> tests-only
=> test(pd): add integration test for grpc reflection

crates/bin/pd/src/cli.rs, crates/bin/pd/src/main.rs, crates/core/app/src/app/mod.rs, crates/core/app/src/server.rs, crates/core/app/src/server/consensus.rs, crates/core/app/src/server/mempool.rs, crates/core/app/tests/common/temp_storage_ext.rs
Previously, the halting logic was structured such that full nodes would partially crash two of their four ABCI services (`Consensus` and `Mempool`); relying on future CometBFT consensus requests to crash the node.
This PR adds an `App::is_ready` method that callers (pd) SHOULD call in order to make sure that the application is ready, so that they can avoid to spin up any services unless an override flag (`--force`) is specified.
Fix #4432 
> Full node mechanical refactor
=> pd: refuse to bootstrap services if the app is not ready

crates/bin/pd/src/main.rs, crates/core/app/src/app/mod.rs, crates/core/app/src/server.rs, crates/core/app/src/server/consensus.rs, crates/core/app/src/server/mempool.rs, crates/core/app/tests/common/temp_storage_ext.rs
Backports changes from #4436, towards #4448.
> This code was carefully resolved to _avoid_ breaking changes, so that we can ship a chain migration safely (#4402).
=> pd: refuse to bootstrap services if the app is not ready (#4436)

crates/core/component/dex/src/component/action_handler/swap.rs, crates/core/component/dex/src/component/metrics.rs, crates/core/component/dex/src/component/rpc.rs
This removes the "swap" RPC, which was not useful (processing swaps is ~free)
> metrics changes
=> dex: add duration metric for SimulateTrade RPC

crates/view/src/storage.rs, crates/view/src/worker.rs
This doesn't solve the problem that the metadata will be missing, but it does at least avoid corrupting the database.
Closes #4452
> only changes client code
=> view: don't record invalid and corrupted Metadata

crates/bin/pcli/src/command/query/validator.rs
Make it easier to understand by changing a double negative word to a positive word. So instead of:
```
Active validator: as of block 217267
Unmissed signing: 100.00% = 10000/10000 most-recent blocks
Required signing:   5.00% =   500/10000 most-recent blocks
Salient downtime:   0.00% =     0/10000 most-recent blocks ~ 0s cumulative downtime
Unexpended grace: 100.00% =  9500/10000 forthcoming blocks ~ 13h 11m 40s at minimum before penalty
Downtime penalty:   1.00% - if downtime exceeds 95.00%, penalty will be applied to all delegations
```
It will be
```
Active validator: as of block 217267
Successful signing: 100.00% = 10000/10000 most-recent blocks
Required signing:     5.00% =   500/10000 most-recent blocks
Salient downtime:     0.00% =     0/10000 most-recent blocks ~ 0s cumulative …
```
=> Change "unmissed signing" to "successful signing" in console output

crates/bin/pd/src/main.rs, crates/core/app/src/rpc.rs
instead of accepting a `url::Url` and constructing specifically the "real" `TendermintProxy`, tweak the signature of the router function so that it accepts a `T: TendermintProxyService`.
in the future, this will allow mock consensus test cases to run an rpc endpoint for the view server, without running a Tendermint/CometBFT process.
see #3913.
> this is a like-for-like refactoring, changing a function
> signature.
=> app: 👐 `rpc::router(..)` accepts a `TendermintProxyService`

docs/guide/src/node/pd/chain-upgrade.md
Refs #4402. Due to changes in the halt-bit logic (#4413), the `--force` flag is necessary on the migration specifically for `v0.76.0`.
> docs-only, although highly relevant to managing consensus-breaking changes correctly, via migration.n
=> docs: use pd migrate "force" for testnet 76

crates/bin/pcli/src/command/query/validator.rs
The downtime penalty is 0.01%, not 1% as previously displayed. This corrects the erroneous calculation which previously displayed an incorrect figure by a 100x factor.
This adds a `/ 100.0` to correct the missing factor, and an explanatory comment.
> This is a display fix for `pcli`.
=> Correct display of downtime in `pcli validator query uptime`

COMPATIBILITY.md, crates/core/app/src/lib.rs
We're not actually using this value in storage yet (#4365), but we still update it for clarity about compatibility.
> docs and logging-only app version, does not affect how node comes to consensus
=> pd: bump app_version 4 -> 5

crates/core/component/dex/src/component/action_handler/swap.rs, crates/core/component/dex/src/component/metrics.rs, crates/core/component/dex/src/component/rpc.rs
Backports #4454 for inclusion in v0.76.0. Refs #4402. Closes #4457. (cherry picked from commit e1d8b2c60b984942d310dcd32698919a2817638c)
> metrics emission, no changes to consensus logic
=> dex: add duration metric for SimulateTrade RPC (#4454)

docs/guide/src/node/pd/join-testnet.md
Refs #4402. Documents new archive url for testnet 76, which is required for any nodes joining the network after the upgrade boundary. Already confirmed I could join, peer, and stream blocks from this via localhost.
> docs-only
=> docs: archive url for testnet 76

crates/bin/pcli/src/command/query/validator.rs
The alignment for the CLI output was broken by #4461. This changes the wording to "Achieved signing" which is still slightly incorrect (a new validator has signed nothing but has a 100% uptime) but aligns correctly.
N/A
> Tiny tweak to CLI output
=> Fix alignment for validator uptime printout

crates/core/app/tests/app_can_define_and_delegate_to_a_validator.rs, crates/core/app/tests/app_can_disable_community_pool_spends.rs, crates/core/app/tests/app_can_spend_notes_and_detect_outputs.rs, crates/core/app/tests/app_can_undelegate_from_a_validator.rs, crates/core/app/tests/app_reproduce_testnet_75_vcb_close.rs, crates/core/app/tests/app_tracks_uptime_for_validators_only_once_active.rs, crates/core/transaction/src/plan.rs
this would be helpful in many mock consensus tests. to avoid short-lived `plan` bindings, and mutable plans, add a builder-style method to call `populate_detection_data()` on a `TransactionPlan`.
> this only makes changes to test code.
=> transaction: 🧁 `TransactionPlan::with_populated_detection_data()`

crates/bin/pcli/src/network.rs, crates/view/src/service.rs
while debugging my work integrating mock consensus tests with the view server,
it was helpful to add additional instrumentation to some relevant parts of the
`penumbra-view` crate. this branch adds some useful spans and events.
this branch contains preliminary changes related to #3913. see also, #4447.
> this only makes changes to tracing events, and makes a small syntactic
> change. no behavior changes here should affect consensus.
=> view: 🔎 add tracing telemetry to view server

crates/test/mock-consensus/src/lib.rs
while refactoring the test node, i found that this is an assumption that isn't explicitly upheld, but is often expected by test code.
to prevent future changes/additions from breaking these properties, add some compile-time assertions that a `TestNode<()>` is both `Send` and `Sync`.
> this only makes compile-time assertions on test code.
=> mock-consensus: ⭐ assert that `TestNode<C>` is `Send + Sync`

crates/cnidarium/src/rpc.rs
We need to bind server resource usage to the lifetime of a connection. Currently, the way client connection termination is percolated to the state watcher task is that sending over the channel would fail as soon as the receive handler is dropped. However, this is insufficient because we only send over the channel in specific cases. Instead, we should be checking unconditionally.
> Mechanical change
=> cnidarium(watch): always check that the channel is open

deployments/config/grafana/dashboards/DEX.json
Adds a new hand-written dashboard to display DEX event durations. We're still massaging the bucketing logic, but getting this dashboard into version-control immediately, so we can iterate on it.
Refs #4464.
> no app code changes, metrics display only
=> metrics: add dex dashboard

crates/bin/pcli/src/command/query/auction.rs, crates/bin/pcli/src/command/tx/auction/dutch.rs, crates/bin/pcli/src/command/view/auction.rs, crates/view/src/client.rs, crates/view/src/planner.rs, crates/view/src/service.rs, crates/view/src/storage.rs
Changes the `pcli tx auction` commands to support "end all", "withdraw all" rather than requiring specific auction IDs
> Only client-side changes
=> pcli: auction end-all, withdraw-all

docs/guide/src/dev/build.md, flake.nix
first, the cool part: here are incremental build timings for `cargo build -p cnidarium` filtering for compilation units that took > 1.5 seconds to compile.
on my machine, this improved incremental build times by 72.92% :heart: 
**before** :weary: 
**after** :heart_eyes: 
`librocksdb-sys(build)` is a somewhat infamous source of lengthy build
times when engineers are working in the monorepo. this is a crate whose
build script, clones and builds the rocksdb database from source,
statically linking against the generated `librocksdb.a` file.
this interacts poorly with a Cargo workspace like ours, which contains a
number of different features. because features are additive, running
commands like `cargo build --workspace` and `cargo build --package penumbra-app`
can result in different feature …
=> chore: 🪨 improve incremental builds by linking to rocksdb

crates/bin/pcli/src/command/tx.rs, crates/bin/pcli/src/command/tx/liquidity_position.rs
This PR makes the pcli tx lp close/withdraw to take multiple position IDs.
Closes #4217
=> refactor: pcli tx lp close/withdraw to accept multiple position IDs

crates/bin/pd/src/cli.rs, crates/bin/pd/src/main.rs
Adds a new flag to `pd migrate --ready-to-start` that makes an in-place edit to local state, setting an enabled halt bit to false.
Refs #4494.
> This code directly munges local state, via a migration, and therefore deserves careful scrutiny.
=> feat(pd): add --ready-to-start flag to pd migrate

deployments/charts/penumbra-network/values.yaml, deployments/helmfile.d/penumbra-devnet.yaml, deployments/scripts/k8s-deploy-point-release, deployments/scripts/k8s-disable-maintenance-mode, deployments/scripts/k8s-enable-maintenance-mode, deployments/scripts/k8s-perform-chain-upgrade-via-pd-migrate
These changes record the scripted migration approach that was used for releasing Testnet 76 (#4402). These scripts aren't yet tied into CI workflows, but that's fine: I've been using this scripted flow to deploy chain upgrades, and I want to do that several more times before enshrined it as final in CI. Also includes some foundation for E2E testing of migration flows targeting the cluster. 
Related to testing ask in #4323, although there's more work in progress leveraging these scripts, and thus I want these to land in main.
> Testing-only, no application logic changes.
=> ci: automate chain upgrades on k8s deployments

COMPATIBILITY.md, crates/bin/pd/src/main.rs, crates/bin/pd/src/migrate.rs, crates/bin/pd/src/migrate/reset_halt_bit.rs, crates/bin/pd/src/migrate/testnet77.rs, crates/core/app/src/lib.rs, docs/guide/src/node/pd/chain-upgrade.md
Adds a new migration, which resets the halt bit. No other migration logic is required, as no state-breaking changes are slated for testnet 77. This way, we preserve `pd migrate` as the default invocation for node operators. Also changed here are the APP_VERSION and corresponding docs entries.
Refs #4497.
> Updates migrations, in order to ensure previously merged consensus-breaking changes are handled correctly.
=> pd: add migration for testnet77

crates/bin/pd/src/migrate/testnet77.rs
Encountered CometBFT failure while testing chain resumption after applying testnet77 migration. Paired with @erwanor to resolve.
Refs #4497.
> fixes a migration for upcoming release, based on migration testing
=> fix(pd): reset app height in testnet 77 migration

crates/core/component/compact-block/src/component/manager.rs, crates/core/component/dex/src/component/action_handler/swap.rs, crates/core/component/dex/src/component/arb.rs, crates/core/component/dex/src/component/chandelier.rs, crates/core/component/dex/src/component/circuit_breaker/value.rs, crates/core/component/dex/src/component/dex.rs, crates/core/component/dex/src/component/eviction_manager.rs, crates/core/component/dex/src/component/mod.rs, crates/core/component/dex/src/component/position_manager.rs, crates/core/component/dex/src/component/position_manager/counter.rs, crates/core/component/dex/src/component/router/params.rs, crates/core/component/dex/src/component/router/route_and_fill.rs, crates/core/component/dex/src/component/router/tests.rs, crates/core/component/dex/src/component/swap_manager.rs, crates/core/component/dex/src/component/tests.rs, crates/core/component/dex/src/state_key.rs, repro.sh
This PR:
Final step to implement #4077 
> Consensus breaking
=> dex: evict excess of liquidity positions

crates/core/component/dex/src/component/arb.rs, crates/core/component/dex/src/component/dex.rs, crates/core/component/dex/src/component/tests.rs
Fix #4513, this change the arbitrage method signature to return `Result<Option<Value>>`, and avoid logging that an arbitrage run is "successful" if the state fork gets discarded. 
> Mechanical refactor
=> dex: less awkward logging if no arbs are found

crates/core/component/auction/src/component/dutch_auction.rs, crates/core/component/shielded-pool/src/component/fmd.rs
when [galileo](https://github.com/penumbra-zone/galileo) is built against the current contents of `main`, these warnings appear:
```
warning: method `init` is never used
--> /penumbra/crates/core/component/shielded-pool/src/component/fmd.rs:79:8
|
78 | pub(crate) trait ClueManagerInternal: ClueManager {
|                  ------------------- method in this trait
79 |     fn init(&mut self) {
|        ^^^^
|
= note: `#[warn(dead_code)]` on by default
warning: `penumbra-shielded-pool` (lib) generated 1 warning
warning: method `get_position_count` is never used
--> /penumbra/crates/core/component/dex/src/component/position_manager/counter.rs:14:14
|
11 | pub(super) trait PositionCounterRead: StateRead {
|                  ------------------- method in this trait
...
14 |     async fn …
```
=> misc: 🟢 address warnings from galileo build

crates/core/component/shielded-pool/src/component/rpc/bank_query.rs
This changes the `TotalSupply` query to skip including assets when there is no denom metadata available, for example liquidity position NFTs. This is okay since these are mostly of interest to a single user rather than the market as a whole.
I validated that the error when querying on the current v0.77.0 testnet goes away.
```
$ grpcurl -plaintext -vv localhost:8080 cosmos.bank.v1beta1.Query/TotalSupply
```
> Changes RPC output only
=> Exclude IBC assets from TotalSupply if their denom metadata is nonexistent

crates/core/component/shielded-pool/src/component/rpc/bank_query.rs
This PR backports https://github.com/penumbra-zone/penumbra/pull/4518 for prep as `0.77.1` point release, to unblock the Skip team, working on IBC integrations.
(cherry picked from commit 785ac6adaba475db66ef128fcaa792537b0eec0e)
> Changes RPC output only
=> backport: exclude IBC assets from TotalSupply

crates/core/app/src/rpc.rs, crates/core/component/dex/src/component/rpc.rs, crates/core/component/dex/src/component/rpc/stub.rs
if the `--enable-expensive-rpc` is not given, cryptic errors can be found on the client side. this adds a stub service that can be used in lieu of the expensive service, returning a helpful error message.
> only changes rpc services.
=> dex: 🌱 add a `SimulationsDisabled` stub for dex queries

crates/core/component/dex/src/component/arb.rs
We noticed there were no metrics being emitted for the cost of the arb search when no arb was found.
This fixes that, and should be backported into the next point release.
> Only changes metrics emission
=> dex: correct placement of arb metrics emission

crates/bin/pcli/src/command/view/staked.rs, crates/view/src/planner.rs
#4533 
> only changes client code
=> Graceful handling of missing validator data in pcli

crates/bin/pcli/src/command/tx.rs, crates/bin/pcli/src/command/tx/auction/dutch.rs, crates/bin/pcli/src/command/tx/liquidity_position.rs, crates/bin/pcli/src/command/tx/proposal.rs, crates/core/component/fee/src/fee.rs
We recently enabled fees on Testnet 77 (#4306), and in the process broke a few things, such as Galileo. While working on adding FeeTier support to Galileo, Galileo's clap setup wanted Display and FromStr. Added those to satisfy the build, and then circled back to pcli to reuse the same impls, which allowed us to snip out some duplicative code.
> no changes to app logic, just adding more impls
=> feat(fee): add FromStr, Display impls for FeeTier

crates/core/component/dex/src/component/arb.rs
This backport #4535 into the v0.77.x feature branch so that we can release into `v0.77.2`
> Change to metrics emission
=> dex: backport arb execution metric fix to `v0.77.x`

crates/bin/pcli/src/command/tx.rs, crates/bin/pcli/src/command/tx/auction/dutch.rs, crates/bin/pcli/src/command/tx/liquidity_position.rs, crates/bin/pcli/src/command/tx/proposal.rs, crates/core/component/fee/src/fee.rs
backports https://github.com/penumbra-zone/penumbra/pull/4539 for inclusion in forthcoming 0.77.2. Refs #4306.
(cherry picked from commit 8035e29f19a9fa1a3460ba8429634501ecafe2ac)
> only friendly impls and cli changes, no changes to consensus logic
=> backport penumbra-fee string impls for 0.77.x

deployments/scripts/redeploy-ci-fullnode-via-remote
The solo node, run outside the cluster, was being fully reset on point releases, due to the aggressive reset logic that was written during the days of frequent chain resets. We're performing point-releases more regularly now, so let's make sure to avoid resetting the solo node in those cases. Still unsupported is chain-migration logic specifically for the solo node, but that's fine: we're handling chain upgrades out of band for now anyway.
Closes #4459.
> ci-only, no application changes
=> ci: support point-releases to solo node

crates/bin/pcli/src/command/validator.rs, crates/core/app/tests/view_server_can_be_served_on_localhost.rs, crates/view/src/planner.rs, crates/wallet/src/plan.rs
Closes #4555 and fixes fee inclusion in validator definition upload, validator vote casting, and tx sweep.
This also introduces some protection for future planner invocations. The `Planner`'s `gas_prices` field has been changed to an `Option` type and if it's not set it will return an error during planning:
```
$ cargo run --bin pcli --release -- --home ~/.local/share/pcli-preview/ validator definition upload --file validator.toml
...
Error: planner instances must call set_gas_prices prior to planning
```
> should be limited to addressing client-side failures on tx submission, so shouldn't change consensus on which
=> Change Planner to use optional gas prices field and error if unset

deployments/scripts/redeploy-ci-fullnode-via-remote
Backports PR #4551 for 0.77.2 (#4545).
> ci-only
=> backports point-release support for solo node

crates/bin/pcli/src/command/validator.rs, crates/view/src/planner.rs, crates/wallet/src/plan.rs
Backports two PRs for 0.77.2 (#4545):
* https://github.com/penumbra-zone/penumbra/pull/4510
* https://github.com/penumbra-zone/penumbra/pull/4554
The planner changes in the latter are crucial to point-release. The former less so, but including those changes reduced conflicts on the cherry-pick, and the client-side improvement is a nice-to-have as we focus on resolving #4540.
> client-side changes only, no changes to consensus logic
=> backport fixes to planner gas prices & validator voting

.github/workflows/rust.yml, .github/workflows/smoke.yml, .github/workflows/summoner_smoke.yml
I want to keep the docs up to date, and sometimes that requires fussy management of version numbers, particularly as we invest in multi-branch workflows to support point releases (e.g. #4545). If *only* the docs changed, skip the long-running rust tests, because we don't need to validate rust functionality on docs changes.
> ci-only
=> ci: don't run long tests on docs-only PRs

deployments/charts/penumbra-node/templates/statefulset.yaml, deployments/charts/penumbra-node/values.yaml
Due to an oversight in the volume-mount path, out postgres databases for indexing ABCI events via CometBFT's psql indexer setup were not persisting across node restarts. This was due to the fact that the upstream `postgres` container image declares its own VOLUME at `/var/lib/postgresql/data`, visible here:
❯ podman inspect docker.io/postgres:16-bookworm | jq '.[0].Config.Volumes'
{
"/var/lib/postgresql/data": {}
}
which clobbered our manual mount at `/var/lib/postgresql`, a level up. We must override the volume mountpoint in order for the PVC to take precedence over the anonymous volume. Done by adding the fullpath to that exact mount, and then overriding PGDATA to use a subdir therein.
Also pins a stable version of the container image tag, so we don't get surprised by postgres jumps. …
=> ci: fix persistence for indexing dbs

Cargo.lock, crates/bin/pcli/Cargo.toml, crates/bin/pcli/src/command/tx/auction/dutch/gda.rs
This aligns the pcli gda sampling method on the one used by minifront. First, the current parameters are incorrect for 48h, and second, this means we don't have two codepaths to maintain in sync.
fix mistakes in recipe parameters by erwanor · Pull Request #1207 · penumbra-zon…
> Client changes
=> pcli(gda): apply web fixes to pcli recipes

crates/bin/pcli/Cargo.toml, crates/bin/pcli/src/command/init.rs, crates/bin/pcli/src/command/threshold.rs, crates/bin/pcli/src/opt.rs, crates/bin/pcli/src/terminal.rs
This converts the plan into a view, using dummy values, so that we can reuse the existing formatting.
This only handles outputs and spends, but that should be enough for 90% of use cases, the rest of which can look at the JSON.
Closes #3444.
> Just changes how pcli prints stuff to stdout
=> Pretty print transaction plan in threshold custody using view

crates/bin/pd/src/main.rs, crates/core/component/governance/src/component/view.rs, crates/core/component/ibc/src/component/client.rs, crates/core/component/ibc/src/component/ics02_validation.rs, crates/core/component/ibc/src/component/msg_handler/upgrade_client.rs
Closes #4549
Closes #4552
Closes #4553 
Closes #4550 
Closes #4546
=> ibc: remediate remaining monorepo issues from zellic audit

crates/view/src/worker.rs
This should fix an issue wherein a load balanced RPC can cause data corruption by delivering the same block twice in the stream.
This should close #4577.
> Just a client change
=> View Service: Don't sync the same block twice

crates/bin/pcli/src/command/view/address.rs
Adding a couple utility flags to `pcli v address` to assist in FVK verification (i.e. Alice can send Bob an FVK, Bob can send a message in a transaction memo to an address associated with that FVK, Alice can successfully read that memo with her FVK and return the same message to Bob, confirming the round-trip communication)
> only changes `pcli` output, doesn't submit any activity
=> pcli: add options to pcli v address for displaying an FVK or generating a payment address from a provided FVK

crates/bin/pd/src/lib.rs, crates/bin/pd/src/main.rs, crates/bin/pd/src/metrics.rs, crates/bin/pd/src/metrics/sleep_worker.rs
this introduces a submodule to `pd::metrics`, which observes tokio scheduler latency and records it for the Prometheus exporter.
the core idea in this worker is that it will invoke `tokio::time::sleep(..)` to put the task to sleep for one second. upon being woken up by the scheduler, it will check the *new* wall-clock time and calculate the actual amount of time it spent waiting. if this took longer than expected, it increments the `pd_async_sleep_drift_milliseconds` counter by the observed latency, measured in milliseconds.
as the module-level docs note, this is a very useful tool to identify when the runtime is being disrupted by blocking I/O or other expensive computation.
> metrics emission
=> pd: 💤 a sleep worker, tracking scheduler latency

crates/bin/pcli/src/command/utils.rs, crates/core/component/dex/src/lp/order.rs
This PR fixes a crash currently occurring when viewing withdrawn LPs in `pcli`. It also makes the display of positions involving unknown assets more consistent.
> only pcli display changes
=> Fix crash in positions --include-closed and display multi-sided LPs consistently

crates/bin/pcli/src/command/init.rs, crates/bin/pcli/src/opt.rs
when a pcli user initializes their configuration, they provide the `init` command with the grpc url of a fullnode, which is stored in pcli's configuration file. by default, this is found at `~/.local/share/pcli/config.toml`.
if that fullnode is later encountering issues, this can render many pcli commands unusable, without a clear workaround. this is a small patch, providing a top-level `--grpc-url` option that will override the config file's GRPC url.
this can help users temporarily send requests to a different fullnode, until their preferred default comes back online.
> only client-side changes
=> pcli: 🌷 add a top-level `--grpc-url` override

crates/view/src/storage.rs
This fixes the issue described in #4587 where the `Balances` view service API was in an in-between state between providing per-note balances and per-account index balances. This fixes the API to properly provide per-account index/asset balances (summing all notes on a per account/asset basis).
The only places the `Balances` API are used are in prax and the Hummingbot integration. `pcli` uses a different API to retrieve balances.
Closes #4587 
> only affects view service
=> 4587: Adjust balances to sum like notes on a per-account index basis

crates/view/src/planner.rs
This improves the error message when a user does not have the required notes to cover a spend.
Closes #4557
> change only made to error strings
=> Use friendlier denom rather than asset IDs in error

crates/bin/pd/src/migrate.rs, crates/bin/pd/src/migrate/reset_halt_bit.rs, crates/bin/pd/src/migrate/simple.rs, crates/bin/pd/src/migrate/testnet72.rs, crates/bin/pd/src/migrate/testnet74.rs, crates/bin/pd/src/migrate/testnet76.rs, crates/bin/pd/src/migrate/testnet78.rs, crates/bin/pd/src/testnet/generate.rs, crates/core/component/governance/src/change.rs, crates/core/component/governance/src/proposal.rs, crates/core/component/governance/src/proposal_state.rs, crates/core/component/governance/src/validator_vote/action.rs, crates/core/component/stake/src/validator.rs, crates/core/component/stake/src/validator/definition.rs
This follows the suggestion from @hdevalence in https://github.com/penumbra-zone/penumbra/issues/3620#issuecomment-2141013858 to add validation of user-supplied `String` lengths to the various `TryFrom` protobuf deserialization implementations.
The user-supplied `String` values concerned are found within the governance and staking crates, concerning governance proposals and validator definitions.
**This is consensus breaking** as historic data **may not comply with the new limitations**. Thus there may be unexpected panics when trying to retrieve and deserialize data from storage.
An additional migration has been included to truncate any existing data that does not adhere to the new limits.
The strings are configured to use **byte length limits** rather than **character length limits**. …
=> Enforce string limits for deserialization

Cargo.lock, Cargo.toml, crates/util/auto-https/Cargo.toml
This updates penumbra-auto-https to use rustls 0.21.
#4591
rustls 0.20.x is no longer receiving updates upstream. Updating to rustls 0.21 also consolidates all the penumbra crates to use a single version of rustls, instead of a mix of 0.21 + one holdout on 0.20, compiling two different versions of the same crate.
=> update rustls 0.20 -> 0.21

Cargo.lock, Cargo.toml, crates/bin/pd/Cargo.toml, crates/bin/pd/src/main.rs, crates/core/component/dex/Cargo.toml, crates/core/component/dex/src/component/metrics.rs, crates/core/component/dex/src/component/router/path_search.rs
this makes a few changes to the dex component's prometheus metrics.
see #4464 for previous context.
importantly, this adds a new metric that tracks the time spent processing a
distinct, individual path. this specific metric is configured to use a larger
set of buckets on the upper end, so that we can capture and observe latencies
observed running pd on a testnet while positions are being routed.
this is a sibling metric to the existing path search metric, which records the
time spent finding the final output path. as a part of this branch, we also
fix a small bug, which is that the duration is still recorded if a dead-end
is reached, and no path could be found.
finally, the configuration of the prometheus metrics builder is tweaked so that
we can add counters to this component in the …
=> dex: 🔖 instrument search path relaxation

crates/core/component/compact-block/src/component/rpc.rs
Wraps the mpsc used to transmit compact blocks with a stateful wrapper that tracks the expected next block height and rejects the send if it mismatches. This should act as a guard against any problem where the node misses or duplicates blocks in the response stream, by converting those to internal server errors that cause the stream to terminate and the client to reopen the connection.
Related to #4577
> rpc changes only
=> compact-block: try to ensure response consistency

crates/core/component/dex/src/component/metrics.rs, deployments/compose/metrics.yml
This re-centers the DEX buckets around the expected latency region
=> dex(metrics): set buckets around expected latency region

crates/bin/pd/src/main.rs, crates/bin/pd/src/migrate/testnet78.rs
Configure migrations to run testnet 78 migration, add more logging, fix bug with validator migration
> consensus breaking because it's a migration
=> Minor fixes to testnet 78 migration

crates/bin/pd/src/testnet/generate.rs
Reduce `tendermint::block::Size::max_bytes` from 21MiB to 1MiB.
Closes #4595
Consensus parameters are not part of consensus but could affect network liveness.
=> pd: configure cometbft with `max_bytes` to 1MiB

testnets/cometbft_config_template.toml
Lower the default value for `max_txs_bytes` from 1GiB to 10MiB. Upstream also substantially lowered this default recently. 
https://github.com/cometbft/cometbft/pull/2767
See also the [new `nop` mempool type](https://github.com/cometbft/cometbft/pull/1643) they added to deal with the mempool being a potential DoS vector a la [p2p-storms](https://github.com/notional-labs/placid).
The mempool and its configuration are outside consensus.
=> pd: use 10MB as mempool limit in comet config template

crates/bin/pd/src/cli.rs, crates/bin/pd/src/main.rs, crates/bin/pd/src/testnet/join.rs
Small change to add a `--leave-archive` flag to `pd join` (defaults to false) to optionally leave behind the  downloaded archive file.
> local to `pd` nodes only
=> Add `leave-archive` flag to `pd join`

deployments/charts/penumbra-node/templates/statefulset.yaml, docs/guide/src/SUMMARY.md, docs/guide/src/node/pd/indexing-events.md
Makes a few changes:
* raises db storage 1GB -> 10GB
* leaves db running in maintenanceMode, for dump/restore
* increases available shm size for db container
Ideally we'd make the db persistence customizable, but this is good enough for now. Looks like 500k blocks maps to roughly 3.5GB of dbdump. We can adjust over time if we plan to keep running long-lived testnet chains.
The increased shm size is specifically to support large joins by e.g. the dex explorer frontend, otherwise db connection was reporting "could not resize shared memory segment".
Also includes indexing docs, to satisfy #4566.
Closes #4526. Closes #4566.
> ci/docs only, no changes to app logic
=> ci: db persistence for large index dbs

crates/bin/pd/src/migrate.rs, crates/bin/pd/src/migrate/testnet78.rs, crates/core/component/dex/src/component/circuit_breaker/value.rs, crates/core/component/dex/src/component/position_manager.rs, crates/core/component/dex/src/component/position_manager/base_liquidity_index.rs, crates/core/component/dex/src/component/position_manager/counter.rs, crates/core/component/dex/src/component/position_manager/inventory_index.rs, crates/core/component/dex/src/component/position_manager/price_index.rs, crates/core/component/dex/src/component/router/fill_route.rs, crates/core/component/dex/src/component/router/path.rs, crates/core/component/dex/src/component/router/tests.rs, crates/core/component/dex/src/component/rpc.rs, crates/core/component/dex/src/state_key.rs
This PR:
- fold `Position` records into the DEX price indexes
- remove extra hashing of positions (to compute `Id`s)
- adds a migration script to population the nonconsensus idx
> This is consensus breaking, AND requires a migration.
=> dex: fold `Position`s into the price indexes

Cargo.lock, Cargo.toml, crates/bin/pcli/Cargo.toml, crates/core/app/Cargo.toml, crates/core/app/tests/app_can_sweep_a_collection_of_small_notes.rs, crates/core/app/tests/view_server_can_be_served_on_localhost.rs, crates/test/mock-client/src/lib.rs, crates/wallet/src/plan.rs
this introduces a mock consensus test, showing that the `tx sweep` command
works as expected for a simple case, when a wallet contains `SWEEP_COUNT + 1`
notes.
#4601 more directly tracks the issue of the `note commitment missing` error,
which i believe affects more than just sweeping. similarly, #4586 and #4578
fixed the issue of seeing `not a valid SCT root` errors, which could also occur
when sweeping notes, because it is effectively performing the same action of
performing many transactions in a hot loop, sending funds to oneself.
while this might not "fix" #4574 strictly speaking, this does introduce some
foundational test coverage so that we can write more robust regression tests
against the core logic responsible for sweep planning.
* #4574
* #4586
* #4578
* #4577 …
=> misc: 🍱 add a mock consensus test exercising `penumbra_wallet::plan::sweep()`

crates/bin/pcli/src/lib.rs, crates/bin/pcli/src/main.rs
currently, types and interfaces defined in the workspace's `pcli` crate are only available within the `pcli` binary itself. this means that the client functionality provided by this crate cannot be depended on as a library, or otherwise used in unit tests.
this state of affairs is a significant part of why our tests for pcli are contained in the `crates/bin/pcli/tests/network_integration.rs` test suite, which rely on shelling out via a `std::process::Command` wrapper and invoking the compiled `pcli` binary.
to facilitate future unit testing, this commit introduces a `lib.rs` file to the `pcli` crate. the `App` structure is moved there as part of this change, but is not changed in this commit.
* #4238 …
=> pcli: 💿 crate can be used as a library

testnets/cometbft_config_template.toml
`mempool.type` was [added](https://github.com/cometbft/cometbft/blob/v0.37.x/CHANGELOG.md#v0374) in v0.37.4 (penumbra updated to 0.37.5 in #4024). Set it to its default value explicitly.
> no functionality change
=> add mempool.type to cometbft config template

testnets/cometbft_config_template.toml
Set the individual transaction size limit to be smaller than the entire block size, but to a still lax, permissive value.
#4629
> the mempool is outside consensus; and this only edits a template file
=> template(comet): lower mempool.max_tx_bytes from 1MiB to 30KiB

crates/core/component/dex/src/component/rpc.rs
The `SwapExecutions` RPC was retrieving results from the JMT, but historic `SwapExecution`s are actually stored in nonverifiable storage.
Closes #4618 
> Only changes RPC response
=> Retrieve SwapExecutions from nonverifiable storage in RPC

crates/bin/pd/src/main.rs
We automatically append a hex randomizer to devnet/preview chain ids, to avoid collisions. Client tooling may expect that suffix to be a revision number, a behavior we want to avoid. Let's stick an 'x' in the randomizer to prevent this behavior.
Follow-up to #4558. Revisits and therefore closes #4552.
> no changes to app logic, only affects generation of new test chains
=> fix(pd): adjust chain id randomizer for devnets

crates/core/component/shielded-pool/src/note.rs
Closes #4569
> This is only used by the view service
=> crypto: check ck_d is consistent with d, pk_d provided on a note

crates/core/component/dex/src/component/arb.rs, crates/core/component/dex/src/component/router/route_and_fill.rs, crates/core/component/dex/src/component/rpc.rs
This PR:
- makes `route_and_fill` return a `Result<Option<SwapExecution>>`
- avoid recording ambiguous `SwapExecution`s with no input or output
- simplify the `handle_batch_swap` logic
- modify the simulate trade RPC to return a failed precondition error if it simulates a trade that doesn't result in any execution
> Not consensus breaking
=> dex: avoid recording null `SwapExecution`s

crates/bin/pd/src/testnet/generate.rs, crates/core/component/sct/src/params.rs, crates/core/component/stake/src/params.rs
=> pd: review pass on config template defaults

crates/core/component/ibc/src/component/packet.rs
This is a UX problem noticed in finding the root cause of #4634; packets were allowed to be sent with timeout timestamps that were already expired. We previously prevented packets with already-timed-out timeout heights, this change adds a similar check for timeout timestamps.
=> ibc: prevent packet sends with timeout timestamp in the past

crates/bin/pcli/src/command/tx.rs
The `pcli tx position close-all` and `pcli tx position withdraw-all` commands were failing to plan for me when I had a significant (100+) number of positions.
This PR splits them into chunks, currently 30 positions, and fixed the planning failures for me.
> pcli only
=> Split CloseAll/WithdrawAll iteration into chunks to prevent planner failures

crates/core/component/auction/src/component/action_handler/dutch/schedule.rs, crates/core/component/auction/src/component/dutch_auction.rs, crates/core/component/dex/src/component/position_manager.rs
Close #4599 
> Consensus breaking, does not require a migration.
=> auction: dex-enabled check during LP allocation

crates/cnidarium/src/read.rs
The documentation was contradicting itself since #2563.
=> cnidarium: fix outdated docs for StateRead::object_get()

Cargo.lock, crates/bin/pd/Cargo.toml, crates/bin/pd/src/main.rs, crates/bin/pd/src/metrics.rs, crates/bin/pd/src/metrics/cpu_worker.rs, deployments/compose/justfile, deployments/compose/metrics.yml, deployments/config/grafana/dashboards/pd-performance.json, deployments/config/prometheus.yml, deployments/containerfiles/Dockerfile-grafana, docs/guide/src/dev/metrics.md, justfile
Pulls in the `metrics-process` crate [0] to bolt on CPU usage and other OS-level info to the metrics emitted by pd. Doing so will support a better first-run experience for node operators who lack a comprehensive pre-existing setup for monitoring node health, so they can get a sense of how much load pd is under.
[0] https://docs.rs/metrics-process/2.0.0/metrics_process/index.html
None, was discussed briefly during sprint-planning recently. 
> metrics-only, doesn't change app logic
=> metrics: add os-level cpu stats to pd

crates/bin/pd/src/migrate.rs, crates/bin/pd/src/migrate/testnet78.rs
We've already updated the CometBFT config template, but running nodes on the current testnet will still be using the prior value, generated at time of join. Let's update the value as part of `pd migrate`, logging a warning if we fail to do so.
Refs #4594, #4582.
> relevant to consensus-breaking logic and how it's handled via migrations
=> migration: update cometbft tx size for t78 migration

crates/bin/pd/src/migrate/testnet78.rs, crates/core/component/ibc/src/component/channel.rs
The IBC spec calls for deletion of packet commitments after a successful acknowledgement, in order to avoid double-acknowledgements.
Previously, our implementation accomplished this deletion by writing an empty byte slice vec![] to the commitment path.
However, this will cause nonexistence proofs by exclusion (the standard NX-proof type used in ics23) of adjacent keys to fail, since ics23 does not support existence proofs of empty values. We observed this when timeouts from osmosis testnet failed to verify the NX proofs from penumbra testnet.
This PR changes `delete_packet_commitment` to actually delete the commitment, and introduces a migration for testnet 78 that will delete all of the previously overwritten commitments.
=> ibc: delete packet commitments instead of writing empty values

crates/bin/pd/src/main.rs, crates/util/auto-https/src/lib.rs
when auto-https is enabled, we spawn a task in the background to handle https certificate resolution, via `rustls_acme::AcmeState`.
if that task encounters errors, they should be propagated up to the daemon, so that `pd` does not rapidly retry lookups, potentially hitting rate-limits and causing service interruptions.
this changes the `pd` entrypoint, binding the [`JoinHandle`] to a variable and polling upon that future in the `tokio::select` block that represents the core steady-state event loop of the daemon.
> while this does change node behavior, none of the components changed are consensus-critical.
=> pd: 🙏 propagate errors from ACME worker

crates/core/component/ibc/src/component/msg_handler/timeout.rs
Previously, when processing timeouts, we used the `client_processed_height` and `client_processed_timestamp` data to determine if a timeout duration had elapsed:
https://github.com/penumbra-zone/penumbra/blob/c9d778c0ad573b0aabfe4f3d7334eaa9778185e5/crates/core/component/ibc/src/component/msg_handler/timeout.rs#L70
However, those refer to a height and timestamp *on penumbra* when any client update for that client had last been processed:
https://github.com/penumbra-zone/penumbra/blob/c9d778c0ad573b0aabfe4f3d7334eaa9778185e5/crates/core/component/ibc/src/component/client.rs#L168
This comparison is invalid, we should instead be checking against the timestamp and height of the last consensus state from the counterparty client. This PR does that. This was verified to fix the interchain test …
=> ibc: fix timeouts: use client height and timestamp

crates/bin/pd/src/migrate/testnet78.rs, crates/cnidarium/src/snapshot.rs, crates/cnidarium/tests/substore_tests.rs
This PR contains a minimal reproduction for a bug in cnidarium's prefix query handling. It also contains a sketch for a fix that we can workshop. The bug was introduced in the original substore implementation PR (#3131).
**Context**
`cnidarium`, our storage layer, supports prefix storage.
This allows users to configure independent storage units, each with
their own merkle tree, nonverifiable sidecar, and separate namespace.
Routing is done transparently without the user having to worry about
the details.
**Overview**
Prefix queries return tuples of (key, value)s, but instead of
returning the full key, they return the substore key. This is a layering
violation, and indeed causes a bug in the cache interleaving logic.
**Terminology**
- a `full_key`:  a key that contains a substore prefix, a …
=> cnidarium: prefix queries over substores are hazardous

crates/core/app/src/app/mod.rs, crates/core/app/src/server/consensus.rs, crates/core/app/src/server/mempool.rs
This is a draft PR that removes the stateful mempool from the application, replacing it with:
- a stateless mempool that gates inclusion on validity against the latest version of the app state
- a prepare proposal implementation that filters for valid transactions
- a process proposal implementation that validates block quality and lays the groundwork to do optimistic execution
> Consensus breaking
=> app: drop stateful mempool

COMPATIBILITY.md, Cargo.lock, Cargo.toml, crates/core/app/src/lib.rs
Also bumps crate versions to 0.78.0-alpha.1. There's no corresponding tag or release object with this alpha, but updating the crate versions helps us to differentiate during testing while we get close to shipping Testnet 78.
Refs #4582.
> version-info only, no changes to consensus logic
=> chore: bump app_version to 7

crates/core/app/src/app/mod.rs
This PR adds a tx size check in the proposal preparation logic so that the application always build valid blocks even in the even of a cometbft misconfiguration.
> This is not consensus breaking, but makes the prepare proposal logic more robust to misconfiguration.
=> app: make prepare proposal more robust to comet misconfiguration

crates/bin/pcli/src/command.rs, crates/bin/pcli/src/command/tx.rs, crates/bin/pcli/src/lib.rs, crates/bin/pcli/src/network.rs, crates/bin/pcli/src/opt.rs
This adds:
- `pcli tx --offline <FILE> <COMMAND>`
- `pcli tx broadcast <FILE>`
The first will save the transaction to a file after signing, the second will broadcast the result of the first command.
Closes #4660.
> Client side only
=> Add transaction saving and broadcasting feature

docs/guide/src/node/pd/join-testnet.md
Refs https://github.com/penumbra-zone/penumbra/issues/4582
Also relevant is #4525 which the archive referenced in this PR does _not_ account for; 4524 is still outstanding.
To test this, one should be able to join the post-upgrade Testnet 78 with v0.78.0 of pd and sync blocks.
> docs-only
=> docs: update archive url for testnet 78

crates/bin/pd/src/cli.rs
this tidies up the cli options to pd, so that the subcommands use consistent
whitespace.
n/a, chore/nit.
> whitespace
=> chore(pd): 🧹 tidy cli options for consistent whitespace

docs/guide/src/SUMMARY.md, docs/guide/src/tutorials.md, docs/guide/src/tutorials/running-frontend.md
Adding a "tutorial" explaining how a user can self-host a frontend, for use with Prax or whatever else. This content is basically a copy/paste of the guide written by @grod220 and initially stored in the minifront repo [0].
[0] https://github.com/penumbra-zone/web/blob/a5d58b2787e6f90f86aed38eaee62a00311ddd59/apps/minifront/README.md.
> docs-only
=> docs: tutorial for self-hosting frontend

crates/bin/pclientd/src/lib.rs, crates/bin/pd/src/cli.rs, crates/bin/pd/tests/network_integration.rs, crates/core/component/dex/src/component/router/tests.rs
remove duplicate words in comment
no
=> chore: remove duplicate words

crates/core/component/distributions/src/component.rs, crates/core/component/distributions/src/params.rs
We were scaling this before using the default metadata, which is more brittle, and less precise.
> This will change how the parameter is interpreted.
=> Use raw amount for staking issuance parameter

crates/bin/pd/src/network/generate.rs, crates/core/app/src/app/mod.rs
`pd network generate` and the application use consensus parameters defined in two different places which is confusing and error-prone.
This PR makes `pd network generate` import constants from the app.
> This only affects new runs of `pd network generate`.
=> pd(generate): use constants from `penumbra_app`

crates/misc/measure/src/main.rs, crates/view/src/worker.rs
This PR sets the max decoding size of the compact block client to 12MB.
=> view: set `MAX_CB_SIZE_BYTES` to 12MB

deployments/compose/docker-compose.dev.yml, deployments/compose/docker-compose.yml
- Clones the testnet docker compose file for use in launching a local devnet. Changes the `join` command to `generate` to -generate a local devnet config. 
- Specifies the platform property in the `pd` and `pd-init` services to be `linux/amd64` to be able to run compose on ARM machines (Apple Silicon).
=> feat: add devnet docker compose

crates/bin/pd/src/cli.rs, crates/core/app/src/rpc.rs
This PR makes pd's `--enable-expensive-rpc` flag a no-op and expose the application's trade simulation service by default.
Close #4696 
> Configuration change
=> app(rpc): expose simtrade service by default

docs/guide/src/node/pd/requirements.md
=> docs: add security limits to node-running guide

deployments/systemd/cometbft.service
According to [document](https://guide.penumbra.zone/node/pd/join-network.html#running-pd-and-cometbft), cometbft path will be `~/.penumbra/network_data`, not `~/.penumbra/network`
=> fix typo in cometbft default path

docs/guide/src/privacy.md
Starting this as a place to document the privacy features and invariants of the protocol. An example would be that trades are private as long as there are at least two in a batch.
This should serve as a one-stop point for _regular users_ (not developers, node operators or other technical users of the protocol) to learn about what actions are private, and under what condition.
=> Create Privacy section in the guide

Cargo.lock, crates/bin/pindexer/Cargo.toml, crates/bin/pindexer/src/indexer_ext.rs, crates/bin/pindexer/src/lib.rs, crates/bin/pindexer/src/main.rs, crates/bin/pindexer/src/shielded_pool/fmd.rs, crates/bin/pindexer/src/stake.rs, crates/bin/pindexer/src/stake/delegation_txs.rs, crates/bin/pindexer/src/stake/missed_blocks.rs, crates/bin/pindexer/src/stake/slashings.rs, crates/bin/pindexer/src/stake/undelegation_txs.rs, crates/bin/pindexer/src/stake/validator_set.rs, crates/core/app/src/genesis.rs, crates/core/component/stake/src/genesis.rs, crates/core/component/stake/src/identity_key.rs, crates/core/component/stake/src/validator.rs, crates/util/cometindex/examples/fmd_clues.rs, crates/util/cometindex/src/index.rs, crates/util/cometindex/src/indexer.rs, crates/util/cometindex/src/opt.rs
This PR drives the `pindexer` development forward with worked examples of staking-related data -- using https://penumbra.today as an example use case. With these changes, it should be possible for all of the data on that site to be rendered directly out of Postgres, without any RPC calls.
We should figure out how to test this -- it should be amenable to testing since we have a good source of event data (mainnet) and expectations about what it should look like -- but this is less critical at this instant.
> Only changes to code outside `pindexer` are convenience methods.
=> Drive `pindexer` forward with staking example

crates/core/component/governance/src/component/view.rs
Uses saturating_sub as a defense in depth mechanism
> defense in depth in a codepath that has not been executed
=> gov: use saturating_sub as a defence-in-depth

docs/guide/src/tutorials/running-frontend.md
With the addition of the [minifront deployer repo](https://github.com/penumbra-zone/minifront-deployer), we have a very easy way for community members to host a fresh version of minifront. This PR adds this info to the penumbra guide.
=> Add info about minifront deployer to guide

docs/guide/src/dev/build.md
In the current docs for linking against `libsrockdb`, building `libsnappy.a` will fail because of an error thrown while building its third party benchmarks which are enabled by default.
This PR adds the CMake CLI option to the docs so that snappy's optional benchmarks are disabled by default.
NA
This is a one line change to developer docs for linking against a crate dependency.
=> Added CMake command to dev docs for linking against `librocksdb` 

crates/bin/pcli/src/lib.rs, crates/bin/pcli/src/opt.rs, crates/bin/pclientd/src/lib.rs
Changes the location and exposure of the `default_home` functions in `pcli`/`pclientd` so they can be accessed when used as libraries.
> minor change to client code organization
=> Make pclientd/pcli default_home accessible when using them as libraries

crates/core/component/dex/src/component/rpc.rs
Fixes the behavior of the simulation RPC for pairs with no liquidity, so that the simulation results correspond to what would happen if there were a swap.
> rpc only changes
=> pd: fix behavior of simulation RPC

docs/guide/src/SUMMARY.md, docs/guide/src/dev/ibc.md, docs/guide/src/node/relayer.md, docs/guide/src/node/relayer/hermes.md, docs/guide/src/pcli/transaction.md, docs/guide/src/web.md
Ported the contents from the old wiki page (since cleaned up) on configuring Hermes to the proper dev guide, beside the other node operator docs. Most of the advice is "use this fork" and "add these specific" options, but at least now there's a single URL to collect that info. We can revise once the relevant Penumbra-compatibility changes in the fork are upstreamed.
N/A
> docs-only
=> docs: add hermes setup steps to guide

crates/core/component/dex/src/component/rpc.rs
Backports the RPC fix in https://github.com/penumbra-zone/penumbra/pull/4731 to the `release/v0.79.x` branch, in preparation for `v0.79.2`.
Only https://github.com/penumbra-zone/penumbra/pull/4731
> RPC-only changes, already reviewed in #4731, and should be exactly the same here.
=> [backport] pd: fix behavior of simulation RPC 

crates/core/component/dex/src/swap/ciphertext.rs, crates/core/keys/src/symmetric.rs, crates/core/transaction/src/is_action.rs
This removes the `LegacySwap` symmetric encryption that is no longer used in Penumbra
Closes #4501
> Swaps were not encrypted using this `LegacySwap` method on mainnet
=> cleanup `LegacySwap` swap decryption path

Cargo.lock, crates/bin/pindexer/Cargo.toml, crates/bin/pindexer/src/block.rs, crates/bin/pindexer/src/lib.rs, crates/bin/pindexer/src/main.rs, crates/bin/pindexer/src/shielded_pool/fmd.rs, crates/bin/pindexer/src/stake/delegation_txs.rs, crates/bin/pindexer/src/stake/missed_blocks.rs, crates/bin/pindexer/src/stake/slashings.rs, crates/bin/pindexer/src/stake/undelegation_txs.rs, crates/bin/pindexer/src/stake/validator_set.rs, crates/util/cometindex/examples/fmd_clues.rs, crates/util/cometindex/src/index.rs, crates/util/cometindex/src/indexer.rs, crates/util/cometindex/src/lib.rs, crates/util/cometindex/src/opt.rs
We don't expose cometindex as a library, but we do pindexer, and this adds a few tweaks to make pindexer possible to run inside an external piece of Rust code. This is useful, because it allows people to colocate their indexer and their block explorer, for example. 
> Doesn't touch the core protocol.
=> Make pindexer more easily embeddable as a library

Cargo.lock, crates/bin/pindexer/Cargo.toml, crates/bin/pindexer/src/dex/dex.sql, crates/bin/pindexer/src/dex/mod.rs, crates/bin/pindexer/src/indexer_ext.rs, crates/bin/pindexer/src/lib.rs, crates/bin/pindexer/src/sql.rs
This implements a basic dex indexing component for the value circuit breaker; more importantly, this adds some basic scaffolding that other dex related indexing can latch onto.
> client code only, no event changes
=> pindexer: implement dex value circuit breaker indexing

Cargo.lock, crates/bin/pindexer/Cargo.toml, crates/bin/pindexer/src/dex/dex.sql, crates/bin/pindexer/src/dex/mod.rs, crates/bin/pindexer/src/lib.rs
Merge #4753 first.
This implements indexing for arb executions in pindexer.
Closes #4736.
> indexing changes only
=> pindexer: Implement indexing of arb executions

deployments/containerfiles/Dockerfile
Adding pindexer to the default container build, to make the built binary accessible in testing and deploy environments.
N/A
> only affects ci builds of containers; no changes to application logic
=> ci: add pindexer to penumbra container

crates/bin/pindexer/src/block.rs
Every block has a unique height, we almost always want to join with other tables based on block height, the serial ID has no meaning: ergo, we should get rid of the id, and just use height as the primary key.
There was no index on height either, which would have made joining on it slow.
Also removed unwraps and expects and as in favor of actual errors.
> Indexer changes
=> Tweak block indexing to use height as the primary key

assets/minifront.zip, assets/node-status.zip
Been a few weeks since an update with the bundled frontends. Updating to latest main from `penumbra-zone/web`.
=> Update to latest frontends

crates/bin/pindexer/src/dex/dex.sql, crates/bin/pindexer/src/dex/mod.rs, flake.nix
Fixes some SQL statements in the prior commit which were not valid postgres.
> Only indexer changes.
=> pindexer: repair SQL syntax for create type/create domain

crates/util/cometindex/src/indexer.rs
We use this row id as a watermark, and update it after every ingestion of an event. Previously, we were iterating over things in an undefined order, and effectively sometimes ingesting events out of order, causing bad things to happen to the watermark, leading to much FUN.
> indexing
=> Fix: index events according to their local row id

.github/workflows/containers.yml
We'd previously been triggering container builds on every merge to main, via the testnet deploy workflows, which were removed in #4678. Let's add triggers to build containers regularly, even though we're not deploying them automatically. Also cleans up unused builds like for galileo and grafana.
N/A
> ci-only, no code changes
=> ci: build containers on merge or tag

crates/bin/pindexer/README.md, crates/bin/pindexer/src/block.rs, crates/bin/pindexer/src/dex/mod.rs, crates/bin/pindexer/src/lib.rs
adds some explanation for a common issue with pindexer
fixes #4765 
indexer-only changes
=> docs: create pindexer readme and mention pindexer<>pd compat in errors

crates/core/component/dex/src/lp/order.rs
The parsing looked for the first occurrence of the slash for
nX@nY/fee
but if X or Y contains a slash, this will be incorrect.
This fixes this somewhat, by looking for the last slash, and only considering that a fee if it ends with bps.
This will not correctly handle a denom containing both a slash and ending with bps, but beyond that we'll need to change the format probably.
> client side change only, for pcli
=> Bug: correctly handle denoms with `/` in pcli tx lp

Cargo.lock, crates/bin/pindexer/Cargo.toml, crates/bin/pindexer/src/dex/mod.rs, crates/bin/pindexer/src/sql.rs
I tried and tried to actually use Numeric directly in a smart way, instead the hack is to just cast text into it in the SQL query. Oh well.
> pindexer bug fix
=> fix(pindexer): correct encoding of Amount into Postgres

crates/bin/pindexer/src/block.rs
this sets timestamp to default for blocks without one to
fixes https://github.com/penumbra-zone/penumbra/issues/4761
indexer changes only
=> fix: don't crash pindexer on blocks without a timestamp

crates/bin/pindexer/src/block.rs, crates/bin/pindexer/src/dex/dex.sql, crates/bin/pindexer/src/dex/mod.rs, crates/bin/pindexer/src/lib.rs
implements lp positions and execution indexing
TODO from reviews:
fixes #4739 
indexer-only changes
=> feat: lp indexing

crates/core/component/dex/src/component/position_manager.rs
There are currently two ways for a position to get closed:
1. automatically by the DEX, for an auto-close position,
2. at the end of the block, after being *queued* for closure in the in the action handler.
For 2., we weren't emitting the event.
This commit changes things so that we do, in fact, emit the event in this case, for a position that has not yet been closed.
> Only adds new events.
=> events: record `EventPositionClose` when closing positions manually

assets/minifront.zip, assets/node-status.zip
Contains updates in minifront that allow to workaround fee issues w/ prax v11.9 (v11.10 in review)
=> Update frontends to latest 957ab2a

docs/protocol/src/community_pool.md
An example command in the documentation says `Community Pool` instead of `community-pool`.
N/A
> documentation-only change
=> Write command for querying community pool balance correctly

deployments/compose/process-compose-dev-tooling.yml, flake.nix, justfile
Adds a version of grpcui to the local nix dev env. Includes logic to build the go binary from source, via nix, because the released version of grpcui upstream still uses the old v1alpha reflection API, which is incompatible with current versions of `pd`.
Refs #4392.
> dev tooling only, no changes to app logic
=> feat(dev): add grpcui to nix dev env

crates/core/component/governance/src/component/view.rs
`StateWriteExt::signal_upgrade` is infallible and doesn't await on anything, so its function signature can be simplified to not be async and not return a `Result<()>` that's always `Ok(())`.
Also fixes a comment referring to `TOTAL_HALT_COUNT`, which is now a boolean and not a count.
> No change to behavior
=> refactor(governance): update StateWriteExt::signal_upgrade comment

crates/bin/pindexer/src/dex/dex.sql, crates/bin/pindexer/src/dex/mod.rs
implements indexing of swaps to satisfy the `/api/swaps` endpoint
fixes #4744
Indexer-only changes
=> feat: swaps indexing

crates/bin/pcli/src/command/tx.rs
Resolves issue #4792 
Prints the position Id when creating a new liquidity position
=> Print the position id when generating a position

crates/bin/pcli/src/opt.rs, crates/core/app/tests/app_can_sweep_a_collection_of_small_notes.rs, crates/core/app/tests/view_server_can_be_served_on_localhost.rs, crates/core/asset/src/asset/denom_metadata.rs, crates/view/src/service.rs, crates/view/src/storage.rs, crates/view/src/storage/schema.sql
This makes a minimal set of changes to allow `pcli` to make use of the Prax registry. In order to not pre-empt more comprehensive planning about how such an integration should work, this PR just changes `pcli` so that if the registry is placed in a `registry.json` file in the `pcli` home directory, it will be imported into the view database on startup.
> client-side changes only
=> pcli: add un-advertised support for importing Prax registry data

crates/bin/pcli/src/command/tx/replicate.rs, crates/bin/pcli/src/command/tx/replicate/linear.rs, crates/bin/pcli/src/command/tx/replicate/xyk.rs
Closes #4112 
Description TK
This strategy is the line labeled "demo", and it's simpler to implement than UniV3 but with a similarly shaped PVF
=> linear liquidity strategies in pcli

crates/bin/pcli/src/command/tx.rs, crates/bin/pcli/src/command/tx/replicate.rs, crates/bin/pcli/src/command/tx/replicate/linear.rs, crates/bin/pcli/src/command/tx/replicate/xyk.rs, crates/bin/pcli/src/opt.rs, crates/core/app/tests/app_can_sweep_a_collection_of_small_notes.rs, crates/core/app/tests/view_server_can_be_served_on_localhost.rs, crates/core/asset/src/asset/denom_metadata.rs, crates/view/src/service.rs, crates/view/src/storage.rs, crates/view/src/storage/schema.sql
Refs #4804. Includes cherry-picked commits porting the three (3) PRs referenced in that release issue.
See #4804 for additional detail.
> Careful attention has been paid to ensure that only client changes are included.
The review should confirm that this PR
1) is based on the `v0.80.0` tag, via the `release/v0.80.x` branch
2) includes _all_ changes from the PRs listed in #4804
3) includes no other changes beyond the PRs listed in #4804
4) is fully compatible with `v0.80.0`
=> Prepare v0.80.1 changeset

flake.nix
Adds a comprehensive allow-list of file extensions to the nix build context. Includes zip files, which will fail a build as of #4782, and other flat file inputs like CSV and JSON for testnet generation. Also adds the `pindexer` binary to the nix-build outputs.
Refs #4782. Doesn't close it, because it'd be nice to tack on a CI job that guards against breakage. Will follow up with that separately.
> build logic only, no changes to app code
1. Make sure you've got nix installed (see [dev env docs](https://guide.penumbra.zone/dev/dev-env) if you need help)
2. Run `nix build` in the repo root
3. Ensure no errors, exits 0.
=> build: fix nix-build via allowing asset files

crates/bench/benches/arkworks.rs, crates/bench/benches/decaf377.rs
=> modify arkworks and decaf377 suite

crates/bin/pcli/src/transaction_view_ext.rs
This adds a rudimentary view for viewing transactions containing auctions without panicking.
**Schedule**
**End**
**Withdraw**
Closes #4813.
> pcli only
There seems to be some issues in how auction views get produced, because this was an auction for "gm" on a devnet, which displays fine in other circumstances, but produces a "passet" here. Also, the reserves are empty, when I would've expected them to be populated.
=> pcli: add display for auction transactions

crates/view/src/service.rs
This populates the transaction perspective using the asset ids present in an auction, which improves display of auctions in transactions.
See #4815.
One thing missing to close the issue is that we don't correlate in the reserve information, but I'm not sure of a straightforward small change to do that.
> view code only
=> view: populate asset ids from dutch auction schedule / withdraw

Cargo.lock, crates/core/app/tests/app_blocktimes_increment.rs, crates/test/mock-consensus/src/block.rs, crates/test/mock-consensus/src/block/signature.rs, crates/test/mock-consensus/src/builder.rs, crates/test/mock-consensus/src/builder/init_chain.rs, crates/test/mock-consensus/src/lib.rs, crates/test/mock-tendermint-proxy/Cargo.toml, crates/test/mock-tendermint-proxy/src/proxy.rs
This enhances test code reproducibility by allowing a fixed timestamp and block timing to be set rather than using system time.
#3759
> only affects tests
=> Add ability to set fixed time and block duration callback in test node

crates/core/app/tests/app_can_define_and_delegate_to_a_validator.rs, crates/core/app/tests/app_can_deposit_into_community_pool.rs, crates/core/app/tests/app_can_disable_community_pool_spends.rs, crates/core/app/tests/app_can_propose_community_pool_spends.rs, crates/core/app/tests/app_can_spend_notes_and_detect_outputs.rs, crates/core/app/tests/app_can_sweep_a_collection_of_small_notes.rs, crates/core/app/tests/app_can_undelegate_from_a_validator.rs, crates/core/app/tests/app_check_dex_vcb.rs, crates/core/app/tests/app_rejects_validator_definitions_with_invalid_auth_sigs.rs, crates/core/app/tests/app_reproduce_testnet_75_vcb_close.rs, crates/core/app/tests/app_tracks_uptime_for_genesis_validator_missing_blocks.rs, crates/core/app/tests/app_tracks_uptime_for_genesis_validator_signing_blocks.rs, crates/core/app/tests/app_tracks_uptime_for_validators_only_once_active.rs, crates/core/app/tests/common/temp_storage_ext.rs, crates/core/app/tests/mock_consensus_can_define_a_genesis_validator.rs, crates/core/app/tests/mock_consensus_can_send_a_sequence_of_empty_blocks.rs, crates/core/app/tests/spend.rs, crates/core/app/tests/swap_and_swap_claim.rs, crates/core/app/tests/view_server_can_be_served_on_localhost.rs
This adds a `new_with_penumbra_prefixes` function to the `TempStorageExt` trait, so that a `TempStorage` can be instantiated with the same storage prefixes that a real chain would use. It was added to the extension trait to avoid polluting the implementation inside the cnidarium crate with penumbra-specific details.
All existing tests have been changed to use the correct prefixes.
> Only affects tests
=> Add `new_with_penumbra_prefixes` to the `TempStorageExt`

crates/proto/src/protobuf/tendermint_compat.rs, crates/test/mock-tendermint-proxy/src/proxy.rs, crates/util/tendermint-proxy/src/tendermint_proxy.rs
This PR cleans up the tendermint proxy code by removing the usage of tonic error types and fixes a bug in the proxy timestamp handling.
> The timestamp handling change does not affect consensus because it only affects values returned to clients via the tendermint proxy, which is mostly unused. Any usage of these incorrect timestamps would be noticed as frequent and random failures which haven't been reported.
=> Cleanup tendermint proxy code, fix proxy timestamp handling

crates/misc/measure/src/main.rs
adds a utility command to extract a compact block
> only measurement utility code
=> add utility to fetch a compact block

Cargo.lock, crates/core/app/tests/app_tracks_uptime_for_genesis_validator_missing_blocks.rs, crates/core/app/tests/common/test_node_builder_ext.rs, crates/core/app/tests/mock_consensus_block_proving.rs, crates/core/component/ibc/src/lib.rs, crates/test/mock-client/src/lib.rs, crates/test/mock-consensus/Cargo.toml, crates/test/mock-consensus/src/abci.rs, crates/test/mock-consensus/src/block.rs, crates/test/mock-consensus/src/block/signature.rs, crates/test/mock-consensus/src/builder.rs, crates/test/mock-consensus/src/builder/init_chain.rs, crates/test/mock-consensus/src/lib.rs, crates/test/mock-tendermint-proxy/Cargo.toml, crates/test/mock-tendermint-proxy/src/proxy.rs
This updates the mock tendermint to properly perform block signing and header generation.
Tests should probably be added that the mock tendermint performs as expected.
> tests only
=> Generate block headers properly in tests

crates/bin/pcli/src/command/view/balance.rs, crates/core/asset/src/asset/denom_metadata.rs
pcli no longer displays withdrawn auction NFTs when running ```pcli view balance```
#4820 
> After completing a number of auctions, viewing my balances through pcli has become increasingly difficult due to all of my previously withdrawn auction NFTs. I decided to not filter out closed auction positions so they can serve as a reminder to withdraw them, matching the default behavior of the swap frontend.
=> No longer display withdrawn auction NFTs when viewing balance in pcli

crates/core/app/tests/common/ibc_tests/node.rs
Follow-up to #4747. Noticed the new tests were flaking across multiple runs. Turns out they were fighting for port binds, as described already in #4517. Let's just use a unique port pair for the MockRelayers and call it a day for now.
Refs #4517.
> tests only
=> fix(tests): bind to unique ports in ibc tests

crates/core/app/tests/common/ibc_tests/node.rs, crates/core/app/tests/common/ibc_tests/relayer.rs, crates/core/app/tests/ibc_handshake.rs
This extends the IBC state machine tests to perform a channel handshake after the successful connection handshake. This is the final prerequisite to performing IBC transfers between chains in tests.
> tests only
=> Perform channel handshake in IBC state machine tests

assets/minifront.zip, assets/node-status.zip
Updated to latest minifront and node-status apps from the penumbra-zone/web repo, commit a8a5f41f7d791059e47f873c6948a26a057e674b.
N/A
> front-end assets only, no changes to consensus logic
=> chore: update minifront bundled assets

crates/core/component/dex/src/component/position_manager.rs
This PR includes a single cherry-picked commit for event emission, that we intend to release as a backport to the 0.79.x series. 
See #4840.
> Careful attention was paid _not_ to break consensus with the v0.79.x release series. Reviewers should confirm this assumption.
Reviewers should pay special attention to the structure of this PR and its merge targets, to ensure it is released correctly:
1. The PR targets `release/v0.79.x-contd`, not `main`.
2. The branch `release/v0.79.x-contd` is branched directly from the `v0.79.3` tag
3. The `v0.79.3` tag is the correct and appropriate place to branch from to release this fix.
4. No other changes have been included.
After approval and merge, I will append a `v0.79.4` commit and tag directly on the `release/v0.79.x-contd` branch, thereby …
=> Prepare v0.79.4 changeset

crates/bin/pcli/src/command.rs, crates/bin/pcli/src/command/migrate.rs, crates/bin/pcli/src/main.rs
initial attempt at implementing a balance migration function for pcli - does not currently handle non-zero fees correctly, but that seems to be the only remaining thing to correctly implement
> client/planner only changes
=> pcli: add balance migration command

crates/bin/pcli/src/command/migrate.rs
This changes the migrate balance command to replicate the balances of each asset per account, as required.
Previously, the command would move all the values into the 0 account.
This will pull fees from the account with the most amount of the staking / fee token.
This differs slightly from iterating through account numbers starting from 0, but is much much simpler.
Closes #4831.
> Client change only.
=> pcli migrate balance: replicate account structure

crates/core/component/shielded-pool/src/component/rpc/bank_query.rs
This fixes an issue in the `TotalSupply` API where tokens minted on Penumbra and received from different counterparties weren't correctly summing together.
It should be noted that this API returns two subtly different values depending on the asset:
* For a Penumbra-minted token, it's really the "Total Outstanding IBC Supply" API rather than the "Total Supply" API -- it will return the amount of the token that has been sent to and remains on other chains
* For an externally-originating token, it indicates the total supply of the token transferred into and remaining on the Penumbra chain
> no consensus changes
=> Properly sum Penumbra-minted values returned in total supply API

Cargo.toml
Updates the email address used for the Penumbra Labs team in the cargo manifest. There's only one point of update, because the crates all reference the top-level workspace fields. Other crates outside the protocol monorepo will need to be updated separately.
N/A
> package metadata only, no changes to app code
Here's a concise list of similar changes across other repositories, to aid in review:
- https://github.com/penumbra-zone/tower-abci/pull/54
- https://github.com/penumbra-zone/jmt/pull/118
- https://github.com/penumbra-zone/standard-penumbra-explorer/pull/1
- https://github.com/penumbra-zone/schemata/pull/1
=> chore: update team email address

crates/bin/pindexer/Cargo.toml, crates/core/app/tests/common/temp_storage_ext.rs, crates/core/app/tests/common/test_node_ext.rs, crates/core/app/tests/common/validator_read_ext.rs, crates/core/component/auction/src/component/auction.rs, crates/core/component/auction/src/component/auction_store.rs, crates/core/component/governance/src/proposal.rs, crates/core/component/governance/src/vote.rs, crates/crypto/proof-setup/Cargo.toml, crates/util/tower-trace/src/trace/service_span.rs, flake.lock, justfile, rust-toolchain.toml
Cleans up some unused cfg_attrs that weren't previously generating warnings. All are cosmetic, and don't affect application functionality.
Also adds the `rust-analyzer` component the rust-toolchain toml, ensuring that the correct version of rust-analyzer (corresponding to the channel specified in toolchain.toml) is used, so that developers can easily hook up their IDEs.
N/A
> no change to app behavior: updates build tooling, and removes unused config-attributes in source code.
=> build: bump rust to 1.80

crates/util/cometindex/src/indexer.rs, crates/util/cometindex/vendor/schema.sql
This improves the performance of cometindex significantly, especially when many events need to be indexed.
Two accidental problems:
1. we forgot to add an index between attributes and events, to efficiently get the attributes associated with an event
This alone caused quadratic query performance, which is really bad.
2. Postgres was doing sorting and hashing to join each attribute + event with the blocks and transactions, before grouping attributes.
First of all, we only want to join the blocks and transactions after already having grouped the attributes together, to avoid adding a constant factor overhead, since some events may have a handful of attributes.
Second of all, we shouldn't be sorting or hash merging at all.
The query should be linear and streaming in complexity, and operate …
=> Cometindex performance improvements

crates/bin/pindexer/src/dex/dex.sql, crates/bin/pindexer/src/dex/mod.rs
This fixes a bug where we assumed there was only one swap per block, ignoring the fact that each trading pair will have a different batch swap.
=> pindexer: Allow for multiple BatchSwaps in a single block

crates/bin/pindexer/src/governance.rs
The governance indexer doesn't use the BlockRoot event, and so this change avoids triggering and running the indexer on that event, which wastes a noticeable amount of time.
> indexing
=> pindexer: remove unused event dependency in governance

crates/core/transaction/src/action_list.rs
public getters that return immutable reference to fields in the [ActionList](https://github.com/penumbra-zone/penumbra/blob/main/crates/core/transaction/src/action_list.rs#L21) struct.
=> planner: implement getters for action list

crates/util/cometindex/src/indexer.rs
Instead of creating one transaction for each event we need to index, we instead only close this transaction every 1000 events (or when when we've caught up to the database).
This gives about a 5x performance in catch up speed.
=> cometindex: speedup by committing event changes in batches of 1000

crates/core/component/ibc/src/component/rpc/client_query.rs, crates/core/component/ibc/src/component/rpc/connection_query.rs, crates/core/component/ibc/src/component/rpc/consensus_query.rs
previously, the IBC gRPC server was accessing penumbra-specific state. this updates the server to use `HostInterface` for all block height reads.
n/a
> only affects gRPC server responses
=> fix(ibc): use `HostInterface` for all block height reads in ibc server

crates/bin/pcli/src/main.rs
Removes the testnet-specific warning message from `pcli`. I remember merging this months ago but it is not in the main branch.
> `pcli` changes only
=> pcli: disable warning post-mainnet

crates/core/component/governance/src/proposal.rs
This PR modifies the governance code to check the IBC `ClientId` is valid prior to creating the `Proposal` domain type
> This validation is already performed, just later in the handling of the `Proposal` in `component/view.rs`
=> governance: validate client ID earlier than component/view.rs

Cargo.lock, crates/bin/pindexer/Cargo.toml, crates/bin/pindexer/src/indexer_ext.rs, crates/bin/pindexer/src/lib.rs, crates/bin/pindexer/src/main.rs, crates/bin/pindexer/src/supply.rs
=> total supply indexer

Cargo.lock, crates/bin/pindexer/Cargo.toml, crates/bin/pindexer/src/supply.rs
This adjusts the total supply indexer to account for whether or not value is locked in the dex, the auction component, or locked away after fees and arbitrage.
This matters because a significant amount of the native token has been locked in arbitrage, so this affects the end result by about 50% (in terms of net new supply)
Merge https://github.com/penumbra-zone/penumbra/pull/4863 first.
> indexing only.
=> pindexer supply with destruction

crates/bin/pindexer/src/ibc/ibc.sql, crates/bin/pindexer/src/ibc/mod.rs, crates/bin/pindexer/src/indexer_ext.rs, crates/bin/pindexer/src/lib.rs
This implements indexing for IBC transfer events.
Merge #4874 first.
=> Transfer events indexing

crates/core/asset/src/asset/denom_metadata.rs
This fixes a bug in the `ibc_transfer_path` method that did not properly handle all IBC denoms, specifically those containing slashes, for example `transfer/channel-4/factory/osmo1q77cw0mmlluxu0wr29fcdd0tdnh78gzhkvhe4n6ulal9qvrtu43qtd0nh8/shitmos`.
Discovered when investigating #4834 however this doesn't close out the issue.
> affected method only called in display formatting right now
=> Fix IBC asset regex in denom metadata

crates/proto/src/event.rs
This allows creating domain types for each of the events, e.g. `EventBatchSwap`, and then doing `EventBatchSwap::try_from_event(&event)`, which makes the pindexer app views much more ergonomic, especially because we can avoid having to duplicate event parsing logic across views.
In subsequent PRs, we should create domain types for each component.
We can probably do this as needed, when we write app views touching particular components.
> Just an internal refactor to events code, so doubly non breaking.
=> proto: add extension trait for easier parsing of domain types

crates/core/component/dex/src/component/action_handler/position/close.rs, crates/core/component/dex/src/component/action_handler/swap.rs, crates/core/component/dex/src/component/action_handler/swap_claim.rs, crates/core/component/dex/src/component/arb.rs, crates/core/component/dex/src/component/circuit_breaker/value.rs, crates/core/component/dex/src/component/dex.rs, crates/core/component/dex/src/component/position_manager.rs, crates/core/component/dex/src/event.rs
Towards #4869; since doing that requires parsing some dex events, I took the opportunity to fill out the rest of the events in the dex.
> event emission only
Some sanity checks that this PR doesn't accidentally change how events are emitted would be nice.
=> 4869(ish) dex rich events

Cargo.lock, crates/bin/pindexer/Cargo.toml, crates/bin/pindexer/src/dex_ex/mod.rs, crates/bin/pindexer/src/dex_ex/schema.sql, crates/bin/pindexer/src/indexer_ext.rs, crates/bin/pindexer/src/lib.rs, crates/core/component/sct/src/component/tree.rs, crates/core/component/sct/src/event.rs
Merge #4893 first!
Closes #4869.
This implementation isn't as fast as it could probably be, but more than enough to be real time, which is all that really matters.
(Maintaining the summary is annoying and kind of tricky, especially if you want to correctly handle a "frozen price" for pairs where no activity is happening)
=> feat(pindexer): add dex candlestick support to schema

.github/pull_request_template.md
Updates the PR github template to include mention of testing steps. Including those in a form template will help with organizing review and reducing review backlog.
N/A
> docs-only, no code changes
=> docs: add testing steps to PR template

Cargo.lock, crates/bin/pindexer/Cargo.toml, crates/bin/pindexer/src/indexer_ext.rs, crates/bin/pindexer/src/insights/mod.rs, crates/bin/pindexer/src/insights/schema.sql, crates/bin/pindexer/src/lib.rs, crates/core/component/fee/src/component.rs, crates/core/component/fee/src/event.rs, crates/core/component/funding/src/component.rs, crates/core/component/funding/src/event.rs, crates/core/component/shielded-pool/src/component/action_handler/output.rs, crates/core/component/shielded-pool/src/component/action_handler/spend.rs, crates/core/component/shielded-pool/src/component/transfer.rs, crates/core/component/shielded-pool/src/event.rs, crates/core/component/stake/src/component/action_handler/delegate.rs, crates/core/component/stake/src/component/action_handler/undelegate.rs, crates/core/component/stake/src/component/stake.rs, crates/core/component/stake/src/component/validator_handler/uptime_tracker.rs, crates/core/component/stake/src/component/validator_handler/validator_manager.rs, crates/core/component/stake/src/component/validator_handler/validator_store.rs, crates/core/component/stake/src/event.rs, crates/core/component/stake/src/lib.rs
Closes #4896.
This adds the requisite tables, with a component parametrized by the numeraire for price information. Price information uses candlestick data for generating the price, so the recently added event will need to be used there.
This also backfills in rich domain types into old crates as necessary, for convenience.
Also closes #4883, since at this point we've refactored out all requisite schemas.
=> pindexer: indexing for insights dashboard

crates/bin/pcli/src/command/view.rs, crates/bin/pcli/src/command/view/lps.rs
Closes #4825.
This adds a command: `pcli v lps` which displays all open liquidity positions owned by the wallet.
To test, try, e.g:
```
pcli tx position replicate linear --lower
-price 0.4 --upper-price 0.8 penumbra:gm 100gm --current-price 0.5
pcli v lps
```
> PCLI only.
=> Add a command to query all open positions in a PCLI wallet

crates/bin/pindexer/src/supply.rs
Closes #4906.
This allows the dex and auction components of the old supply app view to become temporarily negative until the end of a block, so that the order of debits and credits within a block doesn't matter.
This should unblock the currently crashing pindexer on mainnet, and one can verify that the dex supply never goes below 0 empirically.
> pindexer only.
=> bug: pindexer: allow dex and auction supply to be temporarily negative

crates/bin/pindexer/src/dex_ex/mod.rs, crates/bin/pindexer/src/dex_ex/schema.sql, crates/bin/pindexer/src/indexer_ext.rs
Closes #4914.
The internal architecture of the app view tries to make use of batch processing to the extent possible, which simplifies a lot of the logic.
The price charts remain unchanged, but I collapsed the two tables into one for performance and simplicity.
I also **did not** implement insertion of empty candles ; if there are gaps in the events, there will be gaps in the resulting database as well.
The main addition and where I spent most of my time on this is the addition of summaries of information over arbitrary windows. The idea behind the architecture here is that any time a change to liquidity, trade count, or a candle for a directed pair happens in a block, that block then gets a "snapshot" inserted, with the current price, liquidity, volume in that block, etc. At the end of …
=> pindexer: flesh out dex-explorer indexer

crates/bin/pd/src/cli.rs, crates/bin/pd/src/main.rs, crates/bin/pd/src/migrate/mainnet1.rs, crates/core/app/src/app/state_key.rs, crates/core/app/src/app_version.rs, crates/core/app/src/app_version/component.rs, crates/core/app/src/lib.rs
This implements UIP 6, creating an "app version safeguard", to try and prevent the wrong version of PD from being started against existing state, or running the wrong version of PD.
This code should be immediately implementable as a non-breaking *point-release*, which should *immediately* provide a safeguard against forgetting to upgrade to the next major version of the software before the next migration.
This should happen because nodes running the point release will start writing, to non-consensus state, the app version they have. The current migration in 0.80 will refuse to run unless this app version key is empty, or exactly the *previous version*, preventing forgetting to upgrade to the next version pre migration. Furthermore, the next migration should do the same, but with the next …
=> UIP-6: App Version Safeguard

Cargo.lock, crates/core/keys/Cargo.toml, crates/core/keys/src/address.rs
Updates the old git dependency to a suitable published version from crates.io. To review, see the diff review posted in #4921. I'd prefer that reviewers replicate that work, and confirm that 1) the procedure used for obtaining relevant sources was sound; and 2) the code changes in the dep introduced by this diff are acceptable.
Refs #4921.
> The dep appears to function the same in pre and post version bump, as does our modified error handling of its return values. Reviewers should confirm those statements are true, and if so, then there's no affect on consensus.
=> chore: update f4jumble to 0.1.0

Cargo.lock, Cargo.toml, tools/parameter-setup/Cargo.toml
The parameter-setup crate was broken due to outdated dependencies. The options here are:
1. add this tool to the workspace
2. keep the dependencies updated instead of using workspace inheritance
Option 1 is more maintainable. Even though the parameters are fixed now due to mainnet, folks may try to use this crate for debugging - the scenario that motivated this commit.
To test: I followed the steps in https://guide.penumbra.zone/dev/parameter_setup to ensure we could run the parameter setup. 
This was discovered while debugging #4927
> this is a dev only change
=> fix: update dependencies in parameter-setup crate

crates/bin/pindexer/src/insights/mod.rs
Previously, these were being added to the supply, instead of subtracted.
This causes the supply in the insights dashboard to be slightly inflated.
To test, run pindexer and compare the following queries:
```
SELECT (
SELECT SUM(um) as staked_um
FROM (
SELECT * FROM supply_validators
) validators
LEFT JOIN LATERAL (
SELECT um
FROM supply_total_staked
WHERE validator_id = id
ORDER BY height DESC
LIMIT 1
) staked_lateral ON TRUE)
+ um + auction + dex FROM supply_total_unstaked ORDER BY height DESC LIMIT 1;
```
```
SELECT total FROM insights_supply ORDER BY height DESC LIMIT 1;
```
> Pindexer only
=> pindexer: insights: correctly handle Arb and Fees

crates/bin/pindexer/src/insights/mod.rs
This corrects the calculation of the total value shielded. Previously, were were adding the absolute value of outbound transfers, as well as refunds to the total. Instead, we just need to consider deposits.
To test, we should look at current mainnet data, and make sure that the total for USDC is changing appropriately.
Closes #4925
=> pindexer: insights: correct calculation of total value shielded

.dockerignore
Follow-up to #4930, in which we inadvertently broken container builds, due to a workspace dependency being introduced. We don't build container images on every PR push, so CI passed fine, only failing when trying to build/deploy post-merge. Tacked on a small change to address.
For testing, leave it to me: I'll re-deploy after this lands to get it going. 
Refs #4933.
> build logic only, no changes to consensus
=> ci: fix container build for parameter-setup

Cargo.lock, tools/parameter-setup/Cargo.toml
Updates the package metadata for the `parameter-setup` crate, which was recently pulled into the workspace. Without these changes, `cargo-release` was failing to add a version number to the automatically generated commit message.
Refs #4928, #4930.
If you care to verify the results locally, you can:
```
git checkout -b my-feature-branch
cargo release 0.80.9 --execute # this won't push anything, but will require cleanup
git show # to view the commit message
```
Make sure that the generated commit message says "chore: release version 0.80.9", _not_ "chore: release version {{version}}". If you ran these steps, **you must clean up**:
```
git checkout main
git tag -d v0.80.9
git branch -D my-feature-branch
```
If you forget to delete the tag, then when 0.80.9 is actually released, you won't be …
=> ci: fix cargo-release version interpolation

COMPATIBILITY.md, crates/bin/pd/src/main.rs, crates/bin/pd/src/migrate.rs, crates/bin/pd/src/migrate/mainnet2.rs, crates/core/app/src/app_version.rs, crates/core/app/src/app_version/component.rs
This implements a migration to version 0.81.0, which doesn't require any logic.
This will break PD, but targets the new release branch.
=> pd: implement no op migration to v0.81.0

crates/bin/pindexer/src/dex_ex/mod.rs
Now charts implement price information from both directions of a pair.
This is needed for correct rendering on the dex explorer.
For testing, run a local copy of the dex explorer and notice that now both charts are better inverses of each other.
> indexing
=> pindexer: implement symmetrization of charts

crates/bin/pindexer/src/dex_ex/mod.rs, crates/bin/pindexer/src/dex_ex/schema.sql
This allows the dex explorer to read it out, which makes having separate testnet / mainnet logic easier.
This makes it easier to swap between mainnet and testnet data.
For testing, run pindexer, verify that the metadata is there.
=> pindexer: store indexing denom in dex explorer metadata table

crates/bin/pindexer/src/dex_ex/mod.rs, crates/bin/pindexer/src/indexer_ext.rs
There was previously a bug here, where we used the wrong price for converting the volumes to USDC, resulting in an absurdly large purported aggregate volume.
This corrects the usage of denoms so that the number we get is reasonable.
To test, run the indexer and read out the aggregate summary table, and look for odd values
> indexing
=> pindexer: dex_ex: correct denom conversion in aggregate summary

Cargo.lock, Cargo.toml, crates/bin/pindexer/src/dex_ex/mod.rs, crates/bin/pindexer/src/dex_ex/schema.sql, crates/core/asset/src/asset/id.rs, crates/util/cometindex/src/indexer/indexing_state.rs
These changes index the states of individual positions, allowing the dex explorer to render position timelines, allowing users to inspect their position history.
This also updates sqlx along the way.
Once these changes are merged, we'll need to trigger a reindex on the dev indexer.
> indexer changes only
=> Add pindexer support for position timelines in the DEX explorer

crates/cnidarium/tests/migration.rs
Corrected the typo "infaillible" to "infallible" across the codebase. This change ensures proper spelling and alignment with standard English usage. There are no functional changes, only textual corrections.
This is a minor textual correction and does not correspond to a specific issue ticket.
- This change only involves correcting a typo in comments and strings, without modifying the code logic or behavior.
=> fix: Correct typo in 'infaillible' to 'infallible'

crates/bin/pd/src/main.rs, crates/core/app/src/app_version.rs, crates/core/app/src/app_version/component.rs, crates/core/app/src/server/consensus.rs
**Describe your changes**
This PR:
- fixes a bug in the app version safeguard logic that would cause discrepancies between JMT state versions and block height
- refactors some of the inner logic to avoid writing any state unless it is necessary (i.e, no safeguard was found)
**Testing this:**
To observe the state discrepancy and test remediation:
1. Checkout the commit that only contains the extra tracing statement: `git checkout a8c51f0cacb64304a6b1781226d6f74376800af7`
2. Create a local devnet
3. Restart the devnet N times
4. Observe that the state version and block height have offset=N
To test that this fixes it:
1. Run this patch
2. Restart the node
3. Observe that the state version stays stable.
> Not consensus breaking.
=> pd: use `commit_in_place` to write app safeguard

crates/core/component/ibc/src/component/rpc/connection_query.rs, crates/core/component/ibc/src/component/rpc/consensus_query.rs, crates/core/component/ibc/src/component/rpc/utils.rs
This PR:
- instruments IBC gRPC spans on `DEBUG`
- prefer using the `HostInterface` trait to hardcoding height/revision for gRPC responses
- systematically defer to the query height hint (in the gRPC headers) for **every API that returns a proof** (extending #4905, cc @noot)
We will be able to rip out all of the header selection logic once `https://github.com/cosmos/ibc-go/pull/7303` is merged.
> RPC
=> ibc(rpc): always do snapshot selection for proof apis

crates/bin/pindexer/README.md, docs/protocol/src/addresses_keys/spend_key.md, docs/protocol/src/dex/routing.md, docs/protocol/src/setup/contributions.md
This pull request addresses several minor typos and grammatical improvements across multiple documentation files.
- Corrected the article "A" to "An" in the **pindexer README** file, where it was incorrectly used before a word starting with a vowel sound.
- Fixed a spelling issue in the **spend_key.md** file, where "organizational" was written without the hyphen.
- Updated the **routing.md** file to fix a similar article issue, changing "a index" to "an index."
- Corrected missing hyphen in the compound adjective "right hand" in **contributions.md**.
- No related ticket.
- Review the changes in the respective markdown files and ensure that the grammar and spelling adjustments align with standard English conventions.
=> Fix typos and improve grammar in documentation files

crates/bin/pd/src/cli.rs, crates/bin/pd/src/migrate.rs, crates/core/app/src/server/consensus.rs
This PR:
- logs state divergences when processing `EndBlock` messages
- prevents `pd` operators from migrating corrupted state unless `--force` is on
=> pd(migrate): trace and check state version divergence

crates/bin/pcli/src/command/query/chain.rs
This adds a `pcli query chain detect-desync` command which detect if a full node is affected by state desync (#4954).
> Client change
=> pcli: implement `DetectDesync` using ABCI queries

crates/bin/pd/src/network/join.rs
- Fixed a typo in the `join.rs` file where "generted" was incorrectly used instead of "generated."
- **Before**:
```rust
// The data is generted during the process
```
- **After**:
```rust
// The data is generated during the process
```
- Improved code comments by correcting the typo for better readability and understanding.
- Enhanced code quality and maintainability through accurate documentation.
=> typo-Update join.rs

testnets/078-deimos-8/README.md
Corrected `allocations first used Testnet 75` to `allocations first used in Testnet 75`
=> fix: typos in documentation files

crates/bin/pcli/Cargo.toml, crates/bin/pcli/tests/testnet.rs
This test is off-by-default, given that it talks to a remote endpoint, and is rather slow. It can be run directly via:
cargo nextest run --release -p pcli --features integration-testnet sync_wallet_on_public_testnet
As usual, make sure to include the `--release` flag, otherwise it'll be much slower.
Related to changes described in #4978. Specifically, there were changes made in #4973 that broke ClientTls configs for tonic connections, but our test suite didn't catch that. 
1. Check this branch out locally and run `cargo nextest run --release -p pcli --features integration-testnet sync_wallet_on_public_testnet`
2. Confirm that test passes!
It's also worth considering clicking this on in CI so we get assurance; I left it off by default but plan to ask for it to be used in subsequent testing …
=> test(pcli): sync wallet against testnet

crates/bin/pindexer/src/dex_ex/mod.rs
This fixes two bugs in pindexer:
1. Volumes in aggregate and per pair summary were far too high.
2. The different windows of the aggregate summary all reported the same value.
Bug 1. stemmed from multiplying by a price rather than dividing by it when mixing two directions of a candle.
Bug 2. was just a missing filter in an SQL query.
To test, run pindexer again, and do some sanity checks on the aggregate summary, and pair summaries for pairs like USDC / UM.
=> Pindexer metrics fix

Cargo.lock, crates/bin/pindexer/Cargo.toml, crates/bin/pindexer/src/insights/mod.rs
Use I256 values in pindexer.
N/A
I've already validated that the patch works when indexing against testnet; now I'd like to have @cronokirby's eyes on it to confirm it's a sane approach. 
> indexing-only
=> fix(pindexer): support big amounts

.github/workflows/rust.yml, Cargo.lock, crates/bin/pclientd/Cargo.toml, crates/bin/pclientd/tests/testnet.rs, crates/bin/pmonitor/Cargo.toml, crates/bin/pmonitor/tests/testnet.rs, crates/misc/measure/Cargo.toml, crates/misc/measure/tests/testnet.rs, justfile
While working on the tonic version bumps in #4980, we discovered that the HTTPS client support can break without failing CI. This PR builds on the new tests in #4979, trying to establish a baseline sanity check that "yes, the programs can talk to https endpoints" so that during a large refactor, we can easily confirm no regressions.
Refs 
* #4980
* #4979
* #4400
Check out this branch, run `just integration-testnet` and confirm all checks pass.  I also tacked on a commit enabling these new tests in CI, which I consider temporary, but useful for the immediate near-term.
It'd also be helpful to point out any places that might use HTTPS clients that aren't covered yet.
> tests/CI only, no app code changes
=> test: add integration tests for https functionality to binaries

crates/core/component/dex/src/component/action_handler/position/close.rs, crates/core/component/dex/src/component/position_manager.rs
This commit fixes the chain halt that occurred on 2025-01-18 at block 3093519.
A transaction was submitted that contained both `PositionClose` and `PositionWithdraw` actions for the same position `P`, which had been auto-closed by the DEX. In `DeliverTx`, the `PositionClose` action queued the position for closure by ID, and the `PositionWithdraw` action checked that the position state was closed and then updated it to Withdrawn. Later, in `EndBlock`, the queued position closure was executed. The position state was not Opened or Closed, triggering an assertion.
- Mempool tx checking does not execute end block so this didn't get filtered out
- The position closure method allows the position closure to be a no-op, but only for positions in the closed state
- Because the position was …
=> dex: hotfix for 2025-01-18 chain halt (alternative)

crates/core/component/dex/src/component/action_handler/position/close.rs, crates/core/component/dex/src/component/position_manager.rs
This PR backports #4993, which was made against the `release/v0.81.x` branch, to the `main` branch, so it's included in ongoing development.
=> backport: dex: hotfix for 2025-01-18 chain halt

.github/workflows/new-issues-labeled-needs-refinement.yml
This comments out the refinement workflow for now, rather than remove it, since it's a good example for future process work using actions.
=> ci: disable refinement workflow for now

Cargo.lock, crates/bin/pcli/Cargo.toml, crates/bin/pcli/src/command/tx.rs
Adds a `pcli tx delegate-many` command that allows delegations based on a CSV file.
Example CSV file:
```
penumbravalid10n2srs5257a6nxq9x3fhcsqyc0wh8q2lp7f80qd7wlmzdm6znypse23mmh,0.123
penumbravalid1aglayhqq2ec5yfgx8ljqrd9ypnma5uu46hsd0d77dakgu4nywuyqk29d0m,0.201
penumbravalid1lr6rqawqmwetsr8dvdefrpeh7zuamj2ka9jgmesn2xxfgf49hsys79rz9j,0.256
```
Transaction: f7d386906f5fabc88a5eb051d31bfd45cb51049a7f92f231ed33be3ef6314151
- Can check the supplied tx
> Client-side changes to pcli only.
=> pcli: add delegate-many transaction command reading from a CSV file

crates/core/asset/src/asset/denom_metadata.rs
Extends the `Inner` struct in `denom_metadata.rs` to include a `coingecko_id` field. Updates related methods to handle the new field, including `From`, `TryFrom`, `Debug`, and default initialization.
https://github.com/prax-wallet/registry/issues/121
=> asset: add `coingecko_id` to `Metadata` struct

Cargo.lock, Cargo.toml, crates/bin/pd/Cargo.toml, crates/bin/pd/tests/network_integration.rs, deployments/compose/process-compose-smoke-test.yml
Depends on https://github.com/penumbra-zone/cnidarium/pull/9, let's just merge it once the release gets tagged and published. CI won't pass until then.
Fix #5004 
Check `localhost:9000`
> metrics bug fix
=> penumbra: use `cnidarium@0.83`

Cargo.lock, crates/bin/pindexer/Cargo.toml, crates/bin/pindexer/tests/network_integration.rs, crates/core/app/src/server/events.rs, deployments/compose/process-compose-postgres.yml
We missed this on reviewing #4963 which causes a series of unfortunate events in the data pipeline: #4999 
The important diff:
```
-set_index(false)
+set_index(true)
```
I have not tested this change. To test it we can run `pd` and check if events are making it to the comet pg indexer.
> event indexing layer
=> app: fix broken event indexing

Cargo.lock, Cargo.toml, crates/bin/pd/Cargo.toml, crates/bin/pd/tests/network_integration.rs, crates/bin/pindexer/Cargo.toml
In bumping the various metrics-related crates recently, we overlooked that the specific metrics emitted by the `metrics-process` crate had vanished. Bumping the dependency resolves.
Updates the pd metrics tests to check for more patterns. These checks were failing on the main branch, specifically the `pd_process_*` patterns.
Also refactors the metrics test to use `rstest`, for more granular output.
Refs #5021
I've already confirmed that the new tests failed on main, so CI passing is enough to merge here.
> metrics and tests only, does not affect consensus logic
=> fix(pd): restore metrics-process emission

Cargo.lock, crates/bin/pcli/src/command/view/balance.rs, crates/core/component/sct/Cargo.toml, crates/core/component/sct/src/source.rs, crates/proto/src/gen/penumbra.core.component.sct.v1.rs, crates/proto/src/gen/penumbra.core.component.sct.v1.serde.rs, proto/penumbra/penumbra/core/component/sct/v1/sct.proto
- new commitment source kind to track the providence of LQT reward notes
references https://github.com/penumbra-zone/penumbra/issues/5011
=> sct: extend commitment source with LQT variant

crates/core/component/distributions/src/component.rs, crates/core/component/distributions/src/component/state_key.rs, crates/core/component/distributions/src/component/view.rs
Implements the LQT rewards comprising the total reward pool size for an epoch. 
references https://github.com/penumbra-zone/penumbra/issues/5025
> adds new logic for computing LQT issuance
=> distributions: LQT pool budget

deployments/scripts/noble_ibc_test.sh
This adds a test script that performs bidirectional IBC transfers between Penumbra and Noble.
Prerequisites:
* A Noble account with uusdc funds
* A Penumbra account with UM funds to pay fees
* A checkout of [the Noble SDK](https://github.com/noble-assets/noble/)
* A working `pcli` installation in the `$PATH`
* `jq`
This should be integrated into a GitHub workflow. It's not clear if it belongs in the existing smoketest workflow or a new workflow.
> test only
=> test: add Noble/Penumbra IBC smoke test script

crates/core/app-tests/tests/spend.rs, crates/core/app/src/app/mod.rs, crates/core/component/funding/src/component.rs, crates/core/component/funding/src/component/liquidity_tournament/mod.rs, crates/core/component/funding/src/component/liquidity_tournament/nullifier/mod.rs, crates/core/component/funding/src/component/state_key.rs, crates/core/component/funding/src/component/view.rs, crates/core/transaction/src/transaction.rs, crates/core/txhash/src/context.rs
state key for epoch-scoped nullifier set (mapping nullifiers with their associated transaction id), serving as a precursor for performing the necessary stateful [nullifier check](https://github.com/penumbra-zone/penumbra/pull/5033/files#diff-a0986b8d223ab5b1c5536ba06bde1ede6d08f635eb97b386549ecfb55a4f2a4bR112). Additionally, augments the transaction context with `TransactionId`. 
references https://github.com/penumbra-zone/penumbra/issues/5029
> LQT branch
=> funding: LQT nullifier set for epoch

crates/core/component/funding/Cargo.toml, crates/core/component/funding/src/action_handler/liquidity_tournament/mod.rs, crates/core/component/funding/src/component.rs, crates/core/component/funding/src/component/liquidity_tournament/mod.rs, crates/core/component/funding/src/component/liquidity_tournament/nullifier/mod.rs, crates/core/component/funding/src/component/liquidity_tournament/votes/mod.rs, crates/core/component/funding/src/component/state_key.rs, crates/core/component/funding/src/liquidity_tournament/action/mod.rs
Closes #5032.
The check and execute logic for the action handler is still missing the nullifier check, but there's an obvious insertion point for adding that logic.
=> Implement check and execute for LQT votes

Cargo.lock, crates/core/component/dex/src/component/position_manager.rs, crates/core/component/funding/Cargo.toml, crates/core/component/funding/src/component/liquidity_tournament/bank.rs, crates/core/component/funding/src/component/liquidity_tournament/mod.rs
This trait is responsible for the actual accounting of moving funds around, to be later consumed by the end epoch handler, which figures out what portion of the rewards needs to go where. The bank will just actually move fractions of its budget in the community pool to the requested locations, atomically.
> yes indeed
=> Implement "Bank" extension trait for liquidity tournament

crates/core/app/src/action_handler/transaction.rs, crates/core/component/dex/src/component/action_handler/swap.rs, crates/core/component/dex/src/component/action_handler/swap_claim.rs, crates/core/component/sct/src/component/source.rs, crates/core/component/sct/src/source.rs, crates/core/component/shielded-pool/src/component/action_handler/output.rs, crates/core/component/shielded-pool/src/component/action_handler/spend.rs
Right now this is only ever a transaction id, and for LQT work, we need to be able to just use a transaction ID, so it's better to reify that, and change a few uses to wrap it in a source, versus having to unwrap it, introducing a spurious failure case
Smoke tests should be sufficient.
> This state is always initialized before being read, so there's no issue in changing the type we store under this state key ; reviewers should double check this.
=> Modify get/put current source to take in just a transaction ID

crates/core/app-tests/tests/spend.rs, crates/core/component/funding/src/action_handler/liquidity_tournament/mod.rs, crates/core/transaction/src/transaction.rs, crates/core/txhash/src/context.rs
This uses the newly added ambient tx id to populate the LQT nullifier key, making the logic in check and execute final.
This also removes the addition of the tx id to the TransactionContext. My understanding was that this was thought to be necessary to plumb the tx id for this action. Not particularly opposed to keeping that though.
=> Plumb transaction id into LQT vote action handlers

Cargo.lock, crates/core/component/dex/src/component/position_manager/volume_tracker.rs, crates/core/component/funding/Cargo.toml, crates/core/component/funding/proptest-regressions/component/liquidity_tournament/rewards/gauge.txt, crates/core/component/funding/src/component.rs, crates/core/component/funding/src/component/liquidity_tournament/bank.rs, crates/core/component/funding/src/component/liquidity_tournament/mod.rs, crates/core/component/funding/src/component/liquidity_tournament/rewards/gauge.rs, crates/core/component/funding/src/component/liquidity_tournament/rewards/mod.rs, crates/core/component/funding/src/component/liquidity_tournament/votes/mod.rs, crates/core/component/funding/src/component/state_key.rs, crates/core/num/src/percentage/mod.rs
This integrates the recent work in the funding component, providing a full implementation of the reward calculation and distribution logic, running at the end of each epoch.
There are some unit and prop tests for some core tallying logic, but we'll need to do manual testing of the various RPCs an what not later.
=> Implement LQT reward distribution

deployments/compose/docker-compose.dev.yml, deployments/compose/docker-compose.yml, deployments/scripts/install-cometbft, flake.nix
The cometbft version bump is to include patches to security issues. See details in [0]. We already updated the project documentation in [1].
[0] https://github.com/cometbft/cometbft/blob/v0.37.15/CHANGELOG.md#v03715
[1] https://github.com/penumbra-zone/guide/pull/52
> no changes to app code, bumping deps for related tooling
=> chore: bump cometbft version to 0.37.15

crates/core/transaction/src/gas.rs
This is probably the most important one to get right.
Previously this was zero, but this commit changes it to be the same cost as an output action.
This is because, in the worst case scenario, each vote results in minting a note.
Fewer notes can be minted because we cap the number of voters each asset will tally,
but in practice we might be well under this limit.
No testing needed.
Closes #5053.
=> Add compact block cost to LQT vote action

.github/workflows/buf-pull-request.yml, .github/workflows/buf-push.yml, .github/workflows/docs-lint.yml, .github/workflows/notes.yml
We want to publish the protobuf changes in `protocol/lqt_support` (#5010) to unblock web integrations. In order to run the workflow ad-hoc on a branch, we need to permit `workflow_dispatch` runs. The `workflow_call` additions are not currently used, but have been in the past, and permit triggering via cross-repo API.
While authoring these changes, I noticed that the protobuf lint job is _not_ running against feature branches, meaning the PRs into `protocol/lqt_support` have skipped that check. We've been careful in authoring the proto changes, but we should still verify that check passes on the feature branch, prior to publishing.
Refs #5010. 
> no code changes, only affects CI. will result in new protobuf changes to published to the repo.
=> ci: make workflows runnable ad-hoc

deployments/compose/process-compose-smoke-test.yml, deployments/scripts/smoke-test.sh
Follow-up to #5009, in which these tests were introduced, and #5048, which refactored the smoke tests to make additions like this easier.
See above.
The tests were already merged, this is just enabling them in CI, so CI passing, specifically on the smoke-test job, is enough.
> tests/ci only, no changes to application code
=> ci: enable pindexer integration tests

crates/core/component/dex/src/component/position_manager.rs
**Overview**
In this PR, we:
- Relax the inner guard to allow withdrawn LP updates without `seq+1`
- Simplify the reward deposit logic so that it sticks to depositing rewards
**Context**
Before updating position states, the DEX engine runs an inner guard to defend against
ostensibly invalid state transitions (e.g, Closed -> Open).
In particular, since there was no mechanism to update an LP without also updating its
sequence number, that particular transition was disallowed. This is no longer the case
with the implementation of epoch-scoped LQTs.
**Other validation**
The guard is relaxed and removes a third layer of defense, the other two are: 1. The
`withdraw_position` entrypoint called by the action handler 2. Ordinary check that the
transaction value balances (burn, mint inc. seq)
This …
=> dex: relax inner guard for withdrawn LP updates

crates/core/component/funding/src/action_handler/liquidity_tournament/mod.rs
lqt: fix epoch <=> start position comparison
This allows planners to correctly use the first position in the epoch.
This works because the ZK proof verifies that the start position is strictly less.
c.f. https://github.com/penumbra-zone/penumbra/blob/7869803be0b844f09c8c5efeeaa92384b8a6ba35/crates/core/component/governance/src/delegator_vote/proof.rs#L234
=> LQT: fix start position <=> epoch comparison

COMPATIBILITY.md, Cargo.lock, Cargo.toml, crates/bin/pd/Cargo.toml, crates/bin/pmonitor/Cargo.toml, crates/core/app/src/app_version.rs, crates/core/app/src/app_version/component.rs, crates/custody/Cargo.toml
Bumps the protocol version to denote the addition of LQT functionality. Also bumps the crate versions from 1.0.x -> 2.0.x, as an alpha. No tag has been created, to avoid triggering the formal release workflows, since we're still testing.
#5010.
I'm submitting this PR ahead of a planned testnet upgrade, so we'll shortly learn how effective the overall upgrade process is. However, special attention should be given to the proposed versions strings. In particular, the transition from `0.81.x` to `1.0.x` maintained compatibility with APP_VERSION 9, and that may present difficulties during the upgrade for nodes on one or the other version.
> explicitly denotes consensus-breaking changes, and therefore targets a protocol feature branch, rather than main
=> chore: bump app version 9 -> 10

Cargo.lock, Cargo.toml, crates/bin/pd/Cargo.toml, crates/bin/pd/src/main.rs, crates/bin/pd/src/migrate.rs, crates/bin/pd/src/migrate/mainnet3.rs, crates/bin/pmonitor/Cargo.toml, crates/core/app/src/app_version/component.rs, crates/custody/Cargo.toml
Follow-up to #5073, which should have included a no-op migration.
Towards #5010. 
This work will  be used to perform a chain upgrade on the PL testnet. Once that's done, we should expect CI to pass fully on this PR, in particular the "testnet-integration" suite.
> provides migration logic for proposed protocol-breaking changes
=> pd: add no-op migration for APP_VERSION 10

crates/core/component/funding/src/liquidity_tournament/action/mod.rs
Seems like the effect hash calculation for LQT votes was wrong, in that it erroneously included the authorization data and proof, which would make such actions effectively impossible to construct.
This corrects things so that the effect hash is only calculated over the actual body of the vote.
> This breaks consensus not only with main, but also with the tentatively applied testnet upgrade :grimacing:
=> Bugfix: LQT effect hash calculation

crates/core/app/src/action_handler/actions.rs
Previously we had a todo!() there, woops.
I've actually tested that this, combined with changes in another staged pr, allow one to submit votes.
> Consensus breaking relative to testnet too.
=> lqt: wire action handlers for vote action

Cargo.lock, Cargo.toml, crates/bin/pd/Cargo.toml, crates/bin/pmonitor/Cargo.toml, crates/custody/Cargo.toml
Bumps the version in the LQT branch. Doing this to disambiguate between active versions, in order to roll out https://github.com/penumbra-zone/penumbra/pull/5075 to the active testnet.
Refs #5010, #5075.
> version info only, no code changes
=> chore: bump lqt version to 2.0.0-alpha.2

crates/core/component/funding/src/component/liquidity_tournament/bank.rs, crates/core/component/funding/src/component/liquidity_tournament/rewards/mod.rs
I found these debug traces very useful when messing around with stuff, and I think the LQT code paths were a bit light on tracing before.
Testing shouldn't be necessary, just adds tracing.
> Just adds more logging
=> Add some more tracing to LQT code paths

crates/core/component/distributions/src/component.rs, crates/core/component/distributions/src/event.rs
This adjusts the issuance budget every block, incrementing it by the issuance per block, every block, rather than clobbering the current value with `issuance_per_block * how_long_the_epoch_was` at the end of an epoch. This has the effects of:
- making the value always match that claimed by the events, simplifying indexing,
- seamlessly rolling over un-issued rewards to the next epoch,
- simplifying the code.
I also pushed a small change to use a proper Event struct.
> This breaks consensus, but I think this can be applied to the testnet just by pushing the change to the majority validator, which will then issue the incorrect reward amount for exactly one epoch. This has no bearing on any eventual mainnet upgrade. We could avoid this by using a second state key, but …
=> LQT: adjust budget every block

crates/bin/pcli/src/command/tx.rs
This fixes an edge-case in `pcli tx undelegate-claim` that would compute an invalid penalty range for dated delegation tokens.
Instead of using the current epoch as the end of the penalty range, we compute a more precise bound using the block delay chain parameter. This fixes processing old delegation tokens bound to a validator that transitioned in and out of penalty states.
Later, we could expose an RPC method to simplify client-side logic. 
> pcli
=> pcli: fix edge-case in undelegate-claim

Cargo.lock, crates/bin/pindexer/Cargo.toml, crates/bin/pindexer/src/dex_ex/mod.rs, crates/bin/pindexer/src/dex_ex/schema.sql
WIP pairing
https://github.com/penumbra-zone/dex-explorer/issues/338
=> pindexer: add dex block summary

crates/bin/pindexer/src/dex_ex/mod.rs, crates/bin/pindexer/src/indexer_ext.rs, crates/bin/pindexer/src/lib.rs, crates/bin/pindexer/src/main.rs
This adds two flags:
```
--indexing-denom <INDEXING_DENOM>
The denom to use for indexing related components, of the form passet1... [default:
passet1w6e7fvgxsy6ccy3m8q0eqcuyw6mh3yzqu3uq9h58nu8m8mku359spvulf6
```
for setting the denom used for indexing (instead of USDC)
and
```
--dex-ex-min-liquidity <DEX_EX_MIN_LIQUIDITY>
The minimum liquidity for the indexing denom in the dex explorer app view [default:
100000000]
```
for overriding the minimum liquidity in terms of that asset for a pair to be considered in the aggregate dex explorer summary.
Closes #4920.
For testing, we can try running this against the testnet with different values.
> indexing
=> pindexer: implement override for hardcoded values in app views

.github/workflows/smoke.yml
The testnet integration tests are failing PRs targeting main, because the checks assume the code being tested is compatible with the live testnet endpoints. That's not currently the case, due to ongoing LQT development #5010.
Refs https://github.com/penumbra-zone/penumbra/pull/5063#issuecomment-2657853174
> ci-only, no changes to app code.
=> ci: disable testnet integration tests

crates/bin/pindexer/src/dex_ex/mod.rs, crates/util/cometindex/src/index.rs, crates/util/cometindex/src/indexer.rs, crates/util/cometindex/src/indexer/indexing_state.rs
This tweaks the indexing logic in cometindex to add a bit of extra robustness against indexing the same block twice. The current logic is to generate batches of events, which are then sent over to logical threads for each app view, the idea being to only read each batch once, avoiding duplicate database fetching work from each thread, while allowing parallel processing. One potential race condition which might have been the cause of some oddities we've seen around duplicate processing is that each thread would process the entire batch as long as the next height it needed to index was somewhere inside of that batch. In practice, if the threads were in sync, this would be fine, but if for whatever reason they got desynced (e.g. one app view crashes because there's a bug or some weird data …
=> Some cometindex robustness improvements

crates/bin/pindexer/src/lqt/mod.rs, crates/bin/pindexer/src/lqt/schema.sql
I expect that we'll want to get rid of this code when we have an actually useful presentation of the data, but in the meantime, this provides a useful stub of indexing LQT stuff, and is useful in testing that the end to end flow of events works.
I ran this on a devnet, and saw events matching what I saw in pcli, and with the parameters I had set for rewards.
> Indexing only
=> lqt: implement basic indexing for testing purposes

crates/util/cometindex/src/indexer.rs
some suggested changes to #5101
=> pindexer: avoid std::process::exit in catchup mode

crates/bin/pcli/src/command/tx.rs, crates/view/src/planner.rs, crates/view/src/service.rs
Now we can use `pcli tx withdraw <id>` to withdraw a position multiple times, increasing its sequence. We fetch the reserves on every try so that the balance commitment is always accurate.
To view the output, use `pcli v balance --by-note` this is unfortunate but wontfix now.
#5069 
=> pcli: support multiple lp withdrawals

crates/util/cometindex/src/indexer.rs, crates/util/cometindex/src/opt.rs
For running batch jobs managing indexing pipelines, it'd be convenient to instruct pindexer to exit after it's finished processing the events that's available to it. This situation arises frequently in batch processing, where pindexer will be pointed at a source db that was restored from a db. Having pindexer exit 0 on success, else non-zero on error, will aid in building out test infrastructure.
N/A
> only affects runtime options for `pindexer`, no changes to protocol or consensus logic
=> feat(pindexer): optional exit-on-catchup

.github/workflows/crates.yml
Adds a simple workflow to handle publishing the workspace's crates to crates.io. Will run whenever a new tag is pushed to the repo, and publish the crates under that tag.
Closes #5005. Refs #5104, #4978.
I've been handling the publication step manually, locally, after tagging release, to ensure that the script is stable enough to stick in automation. It's been well behaved for the past few minor releases, so let's try it out in automation. I'll handle verifying behavior post-merge, post-release.
> ci-only, no code changes
=> ci: workflow for publishing crates

crates/core/component/ibc/src/component.rs, crates/core/component/ibc/src/component/client.rs
exported `ClientStatus` and `ConsensusStateWriteExt` types within the IBC component. these were already marked `pub`, but weren't exported outside of the module as `client` was private.
n/a
> does not change any code logic, just exports types/adds derives
=> export `ClientStatus` and `ConsensusStateWriteExt` in ibc component

deployments/scripts/rust-docs
Eventually all the docs will be published on crates.io, but right now the binaries in particular aren't published from the workspace, so we'll continue to use `rustdoc` as a catch-all reference for developers learning the Rust API.
N/A
CI passing is enough: post-merge we should see the new docs on https://rustdoc.penumbra.zone.
> docs/CI only, no code changes
=> docs: add pindexer and cometbft to rustdoc

Cargo.toml
Modifies the `cargo-release` config to permit releasing from the `HEAD` checkout created by GHA in CI. By default, cargo-release disallows `HEAD` via the `!HEAD` match, see docs at [0].
[0] https://github.com/crate-ci/cargo-release/blob/f7c2975325afc6d6fc1793544802a5578d9ef256/docs/reference.md
Refs #5005.
I need this change to land on main in order for it to be active in the release workflow. Shortly I'll publish 1.2.0 and observe behavior then. As long as CI is green on this PR, we're good to merge, then I'll follow up on next steps.
> CI/release logic only, no changes to app code
=> ci: publish crates even from HEAD

crates/core/component/governance/src/voting_receipt_token.rs, crates/core/component/stake/src/unbonding_token.rs
1. Corrected outdated references to "delegation token" in `voting_receipt_token.rs` and `unbonding_token.rs`.
2. Updated descriptions to reflect the correct token purpose:
- `VotingReceiptToken`: Represents proof of participation in governance votes.
- `UnbondingToken`: Represents staking tokens undergoing the unbonding process.
3. Ensured terminology aligns with the asset registry definitions.
=> Fix token documentation and naming consistency

crates/bin/pindexer/src/block.rs, crates/bin/pindexer/src/dex_ex/mod.rs, crates/bin/pindexer/src/governance.rs, crates/bin/pindexer/src/ibc/mod.rs, crates/bin/pindexer/src/insights/mod.rs, crates/bin/pindexer/src/stake/delegation_txs.rs, crates/bin/pindexer/src/stake/missed_blocks.rs, crates/bin/pindexer/src/stake/slashings.rs, crates/bin/pindexer/src/stake/undelegation_txs.rs, crates/bin/pindexer/src/stake/validator_set.rs, crates/bin/pindexer/src/supply.rs, crates/util/cometindex/src/index.rs, crates/util/cometindex/src/indexer.rs
Right now, every indexer gets called with a batch, with no good way of knowing whether or not more batches will follow. This creates unnecessary work. For example, the the dex explorer component, some tables exist only to provide a *current* summary of information. These only need to be computed once we've caught up to the tip of the chain. Any time we compute them before is wasted.
On the first 1_000_000 blocks, avoiding this summary computation saves 9 minutes, going from 21 minutes to 12.
The component (and others) could probably be re-architected in other ways to take advantage of this.
To test, run pindexer again, check that the results are the same, just computed a bit faster.
=> pindexer: add context to indexing calls, to allow deferring work to after catchup

crates/util/cometindex/src/index.rs, crates/util/cometindex/src/indexer.rs, crates/util/cometindex/src/indexer/indexing_state.rs
Closes #5125.
After this change, one final `dropdb penumbra` will be necessary, and then from now on, pindexer will be able to manage resetting itself, and do so in a minimally destructive way, reducing indexing times on changes. This works by having each 
index know it's version, with each breaking schema change inducing an increment to the version. Then, on startup, pindexer can figure out which particular app views need to be reset based on their version changes. App views with a version > 0 will need to implement a means of actually effecting this reset. This method should delete all tables any versions of the index might have created. In hindsight, every app view should have been putting things in a schema, like the proposed view in #5113 does. This makes the reset particularly easy: …
=> pindexer: allow self-reset on schema changes

crates/util/cometindex/src/indexer/indexing_state.rs
This adjusts the queries to make sure that only events and txes from the correct height range are returned, removing the assumption that block rowids are monotonic.
The query is also faster than it was before, from what I can tell.
This should paper over #5135 for now, but that might indicate an issue with our reindexing we should investigate.
Currently doing a pindexer run using this PR, that should be enough to test.
> Indexing only
=> cometindex: be strict about event heights

Cargo.lock, crates/bin/pindexer/Cargo.toml, crates/bin/pindexer/src/main.rs, crates/util/cometindex/src/database.rs, crates/util/cometindex/src/indexer.rs, crates/util/cometindex/src/indexer/indexing_state.rs, crates/util/cometindex/src/integrity.rs, crates/util/cometindex/src/lib.rs, crates/util/cometindex/src/opt.rs
This adds a new command, reachable via `pindexer -s <DATABASE> integrity-check` which runs basic integrity checks on the raw database. Right now this can check that:
- there are no missing blocks,
- there are no missing events.
This also makes the indexing command `pindexer -s <DATABASE> index`, because I couldn't find a way to preserve the default command.
This can be run against known good database, and shouldn't fail.
=> Add an integrity check to cometindex / pindexer

crates/bin/pindexer/tests/network_integration.rs
I observed some flakiness in the test because of this, where it was behind by 3 on one run, and fine on another. I think moving it to 4 is sensible. I also replaced the use of a vec with a more efficient range check.
Smoke tests should be sufficient here.
> tests only
=> Bump pindexer lag allowance in integration test

crates/core/keys/src/keys/fvk.rs
This is already basically implemented for the proto deserialization, but having direct access is useful for ledger support. Should this be using a proto instead? Yeah, probably, but it doesn't, so.
Smoke tests should be sufficient, also this is a pretty simple refactor.
> Behavior should be identical
=> keys: Add `TryFrom<&[u8]>` to FullViewingKey

.github/workflows/docs-lint.yml, .github/workflows/notes.yml, deployments/scripts/rust-docs, flake.lock, flake.nix
Updates the nix flake setup to provide an optional devshell for nightly rust. This is mostly useful for the "rustdocs"" build, which requires use of rust nightly for the combined index landing page. Also updates the CI workflows to use the nix env for building rustdocs.
See related discussion in https://github.com/penumbra-zone/penumbra/pull/5140#issuecomment-2758892215. 
Certainly we want CI to pass. As a bonus, it's worth confirming that executing the script `./deployments/script/rust-docs` works both inside and outside of a nix shell. 
> CI/build logic only, no changes to application code
=> ci: add nightly rust to nix dev shell

crates/bin/pcli/src/command/tx.rs
Currently, `pcli` can't set the memo to the ICS-20 packet when `withdraw`.
This PR adds a new option to `withdraw` command and sets it to the `Ics20Withdrawal`.
=> Set memo to ICS-20 packet data via pcli

crates/bin/pindexer/src/dex_ex/mod.rs
This is a stop gap we probably want to revert, but can unblock testing.
Pindexer should no longer crash against the testnet.
> Indexing only
=> UGLY: turn position execution crash into warning

crates/bin/pindexer/src/dex_ex/mod.rs
This reverts commit fa7032674383aa00b29be55d61263d534a6eaa7c, from PR #5147. That was a stopgap measure to facilitate working with ABCI events on the testnet pipeline. We've since [reindexed](https://github.com/penumbra-zone/reindexer/pull/42) the testnet data and the data is sound again—there was _not_ a bug in pindexer.
Refs #5147. Closes #5144.
> no changes to consensus code, just a reversion of a stopgap commit to pindexer
=> Revert "UGLY: turn position execution crash into warning"

COMPATIBILITY.md, crates/bin/pd/src/main.rs, crates/bin/pd/src/migrate.rs, crates/bin/pd/src/migrate/mainnet3.rs, crates/core/app/src/app_version.rs, crates/core/app/src/app_version/component.rs
Updates the default `pd migrate` behavior to apply mainnet migration 3, a no-op migration to coordinate dependency updates related to IBC handling.
See #5150.
The changes presented here are necessary, but not sufficient. Once the suitable fixes have been released, we'll need to add them here, and likely also in [ibc-types](https://github.com/penumbra-zone/ibc-types), and bump local references. Then we'll exercise the upgrade logic on a devnet created for this purpose.
> This PR will affect consensus and therefore provides a migration to aid in applying the consensus-breaking change safely.
=> chore: add migration for mainnet3

.github/workflows/notes.yml
Properly uses the `nix develop` invocation to ensure that `mdbook` exists on the PATH. Historically mdbook was installed via `cargo install` and so was present in the CI rust cache. That cache has been evicted, so the workflow recently started failing.
Refs #5156.
The workflow in question only runs on main, so we'll need to merge and then observe again. That's why I've marked as "refs" rather than "closes" the linked issue.
> ci logic only, affects docs presentation, but no app code has changed.
=> ci: fix protocol docs build

crates/core/component/compact-block/src/compact_block.rs
fix requires_scanning doc typo
requires_scanning returns true if the block is **not** empty! Corrected typo
=> chore: fix typo

crates/core/app/src/app_version/component.rs
This was confusing a lot of people, reading the Discord backscroll.
Now, if you run `pd` and find that the previous version is set, we prompt the user to try running pd migrate.
A lot of people ran into this exact scenario and were confused that the error message was merely telling them to run `pd v1.4.0` but they indeed had that version ready, but had forgotten to migrate first.
> Error messages only.
=> Improve error message when you don't run pd migrate

Cargo.lock, Cargo.toml, crates/bin/pcli/Cargo.toml, crates/bin/pcli/src/command/init.rs, crates/bin/pcli/src/config.rs, crates/bin/pcli/src/opt.rs, crates/core/transaction/src/auth_data.rs, crates/custody-ledger-usb/Cargo.toml, crates/custody-ledger-usb/src/device.rs, crates/custody-ledger-usb/src/lib.rs, deployments/containerfiles/Dockerfile, deployments/scripts/rust-docs, flake.nix
This implements a new custody backend which communicates with a ledger device locally, using the app in https://github.com/Zondax/ledger-penumbra/. I tested that this works as you might expect, and it does, except for an update to the protos that affects the effect hash that needs to be merged into an alpha release in that repo.
I'm not super happy with the quality of the crates I used to communicate with ledger generically, but they get the job done.
You can use `pcli init ledger` to setup pcli with this backend, and then everything should "just work".
Some more polish could be needed in terms of providing informative error handling, but for now I think this code is 90% of what we need.
I also added a default implementation of `AuthorizationData` so that we can easily rebase the lqt …
=> Add ledger as a custody option to pcli

Cargo.lock, Cargo.toml, crates/bin/pcli/Cargo.toml, crates/bin/pclientd/Cargo.toml, crates/bin/pclientd/src/lib.rs, crates/bin/pclientd/tests/network_integration.rs, crates/bin/pclientd/tests/testnet.rs
Updates `pclientd` to prompt for key material interactively, via a masked prompt, or else read from stdin, rather than accepting key material as CLI args.
Closes #5171.
I updated the integration tests to exercise the CLI invocations, so CI passing is sufficient assurance her.
> CLI-args only, no changes to app code
=> pclientd: read key material interactively

crates/bin/pindexer/src/lqt/schema.sql
This fixes some issues with the calculation of the summary view for delegators.
- The epochs voted in was calculated incorrectly.
- Rewards were not being tallied correctly, leading to overstatement of them.
- In case the user had a continuous streak of voting, without any gaps, the streak would be reported incorrectly.
To test, it should be possible to simply run pindexer again, with no need to reset the database (being able to change views on the fly paying off!), and one should observe much more reasonable results with:
```sql
select epochs_voted_in, total_rewards / 10^6, total_voting_power / 10 ^ 6, streak from lqt.delegator_summary;
```
=> pindexer: lqt: fix issues with delegator summary

Cargo.lock, crates/core/asset/Cargo.toml, crates/core/asset/src/asset/denom_metadata.rs, crates/core/component/shielded-pool/src/component/rpc/transfer_query.rs
This fix a bug in the Cosmos query service that would prevent certain IBC assets from being returned by `ibc.applications.transfer.v1.Query/DenomTraces`
Querying the total supply:
```bash
echo "{}" | grpcurl -plaintext penumbra-1-skip-grpc.polkachu.com:21990 cosmos.bank.v1beta1.Query/TotalSupply | grep 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
```
Returns:
```
"denom": "transfer/channel-0/transfer/08-wasm-1369/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
```
as expected.
But querying the denom traces:
```bash
echo ‘{}’ | grpcurl -plaintext penumbra-1-skip-grpc.polkachu.com:21990 ibc.applications.transfer.v1.Query/DenomTraces | grep 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
```
does not return anything (unexpected).
With this fix, it should return the denom trace as well.
> RPC change
=> asset: fix ibc transfer path parsing

crates/core/app/src/app/mod.rs, crates/core/app/src/event.rs
Closes #5186
I think this is the only location where the change happens.
For testing it could be useful to try running the reindexer off of this branch, and checking that we see the event appear in the testnet.
> event emission only
=> fix: Emit EventAppParametersChange

crates/core/app/src/app/mod.rs, crates/core/app/src/event.rs
=> Backport AppParameter event fix from 1.5.1 to v0.80.x

crates/bin/pindexer/src/lqt/mod.rs, crates/bin/pindexer/src/lqt/schema.sql
This augments the `lqt.summary` view to have information about the start and end block (predicted or actual) along with an estimate of when the block will end, in seconds (matching the Figma design). This also changes the way rewards are presented in the summary to reflect the amount of rewards we *project* to be available during the epoch.
Closes #5178.
I tested this by inspecting the data on testnet after these changes.
=> pindexer: lqt: augment lqt.summary with epoch prediction

crates/bin/pindexer/src/lqt/mod.rs, crates/bin/pindexer/src/lqt/schema.sql
Fixes two bugs:
- avoids a division by 0 by excluding lps with 0 points from being included in the lp table (thus avoiding epochs where no rewards were given out)
- uses `INTEGER` consistently for heights and epoch indices
Check that `\d lqt.summary` doesn't show BIGINT as a type for `end_block`.
Check that `select * from lqt.lps` runs successfully against the testnet.
=> pindexer: further LQT fixes

crates/bin/pindexer/src/lqt/mod.rs, crates/bin/pindexer/src/lqt/schema.sql
- Fixes an issue where you had multiple entries in the delegator history each epoch.
- Fixes an issue where the projected rewards for an unfinished epoch were too low, not taking into account leftover rewards from the previous epoch.
=> pindexer: lqt: fix a couple more bugs

crates/bin/pindexer/src/lqt/schema.sql
We were incorrectly selecting for the most recent non-zero gap,
by not handling the most recent epoch a given delegator has voted in.
In that case, there's no "end" to the gap, and we need to handle
the value being NULL.
The effect of this change is that streaks are now calculated correctly,
with the weird behavior of seeing a streak larger than the number
of epochs voted in not appearing.
Closes https://github.com/penumbra-zone/web/issues/2334
=> pindexer: lqt: handle an edge case in streak calculation properly

crates/bin/pcli/tests/network_integration.rs, crates/core/transaction/src/view.rs
Using only the outputs runs into some niche issues for certain transactions, this method always works.
Closes #5200.
Now, `pcli v list-tx-hashes` should not error out again.
> client only
=> fix: use swap claim address for transaction summary

Cargo.lock, crates/bin/pcli/src/command/tx.rs, crates/bin/pcli/tests/network_integration.rs, crates/core/app/src/rpc.rs, crates/core/component/community-pool/Cargo.toml, crates/core/component/community-pool/src/component.rs, crates/core/component/community-pool/src/component/rpc.rs
We've been advertising this RPC in the protobuf docs, and even in the pcli subcommands, but it hasn't ever worked. To resolve, this PR:
* hooks up the missing CommunityPool RPC in `pd`
* exercises the already-existing `pcli q community-pool balance` logic via integration tests
* adds a fix for `pcli tx community-pool-deposit` to require a value, along with tests
Closes #4381. 
I added tests to CI, so give them a visual review as a sanity-check, but green on CI is good enough to merge.
> Wires up documented by missing RPC; no changes to consensus logic.
=> fix: add community-pool rpc support

crates/bin/pcli/src/command/tx/proposal.rs
The `--deposit-amount` flag is required when running `pcli tx proposal submit`, but the clap settings weren't enforcing that, and the resulting error message was quite vague. Now, running `pcli tx proposal submit` without providing a `--deposit-amount` flag emits a helpful error message:
error: The following required arguments were not provided:
--deposit-amount <DEPOSIT_AMOUNT>
The parsing the amount, e.g. "10penumbra", remains unchanged.
A visual inspection of the diff is good enough: we already have integration tests that exercise the `--deposit-amount` flag is parsed correctly. Here's a before and after.
```
❯ cargo run -q --release --bin pcli -- --home ~/.local/share/pcli-localhost/ tx proposal submit --file prop.toml
2025-05-21T20:07:32.356691Z  INFO pcli::opt: using software KMS …
```
=> fix(pcli): require deposit when submitting proposal

crates/core/transaction/src/view.rs
Only on the spend and output actions for now. We'll need to think a bit more about how to handle swaps.
- balance attribution for swaps isn't clear to me,
- we either need to pass an FVK, or augment the swap view with a decoded claim address.
This doesn't solve #5205 yet, but I think this already provides value for spend and output actions, which are a lot of the actions, and so I think merging it in this form is a good idea while we figure out the other salient points.
For testing, looking at the resulting pcli changes should be enough.
> view only
=> feat: wip: use address views in tx summary

Cargo.lock, crates/bin/pindexer/Cargo.toml, crates/bin/pindexer/src/dex_ex/mod.rs, crates/bin/pindexer/src/indexer_ext.rs, crates/bin/pindexer/src/insights/mod.rs, crates/bin/pindexer/src/insights/reset.sql, crates/bin/pindexer/src/lib.rs, crates/util/cometindex/src/index.rs, crates/util/cometindex/src/indexer.rs, crates/util/cometindex/src/indexer/indexing_state.rs, crates/util/cometindex/src/opt.rs, deployments/compose/process-compose-postgres.yml
This also creates a backwards compatible mechanism to allow app views to automatically reset themselves if relevant options change. In this case, this allows this change to run on top of an existing indexed database, with the result (test this) of just resetting the dex explorer component, since the options affecting indexing will have changed.
I also added a safeguard to prevent accidentally clobbering over the relevant app view when the options change. Instead, an explicit opt in with `--new-options` is required to indicate that you intended to reset that app view with new options.
In particular, to test, running pindexer SHOULD FAIL without `--new-options`, and then SHOULD SUCCEED with `--new-options`, with the result of re-running the dex_ex app view, this time without arb executions …
=> Skip arb executions for dex explorer price charts

.dockerignore
The picturesque dep must be present in the container build context in order to resolve dependencies when building for the workspace, because picturesque is included in the workspace.
Follow-up to https://github.com/penumbra-zone/penumbra/pull/5228.
This change will unbreak the failing container builds like https://github.com/penumbra-zone/penumbra/actions/runs/16057260753 since merge of #5228.
=> fix(build): permit picturesque in containers

crates/bin/elcuity/src/lp/mod.rs, crates/bin/pcli/src/command/tx.rs, crates/bin/pcli/src/command/view/lps.rs, crates/view/src/client.rs, crates/view/src/service.rs, crates/view/src/storage.rs, crates/view/src/storage/schema.sql, crates/view/src/worker.rs
Previously, we were ignoring the account index.
This modifies syncing to detect the account by looking at the note you get when you receive an LP NFT.
This is useful, because it allows segregating funds by account, instead of having to make a new wallet.
Smoke testing should be sufficient here.
> client only
=> feat: make view service respect account ownership in positions

crates/bin/pindexer/src/dex_ex/mod.rs
This skips indexing candles with a price of NaN, at the source where we ingest point candles, representing a single trace input and output value. For some reason, the dex sometimes produces candles with 0 input and 0 output volume, resulting in a NaN, which then pollutes and corrupts other data. This fix addresses the source of the pollution in indexing.
We should investigate why these traces are being emitted.
To test, run pindexer again, observe that NaNs are out of the candles.
> Indexing only.
=> fix: pindexer: don't index candles with NaN

crates/bin/pcli/src/command/tx/auction/dutch.rs
When interacting with dutch auctions via the CLI, the previous pcli interface only accepted a single auction id for end/withdraw actions. This change permits a list of auction ids, so that auctions can be closed in batches.
Also adds a `--batch` flag, default 20, to close that many auctions. If the batch size is much higher, we'll hit the limit on tx size. The `--batch` option works automatically when using `--all`, chaining together end or withdraw actions, to stay under the tx size limit.
refactor: more informative logging on batches
refactor: strongly typed auction ids in pcli
n/a
Visual review should be fine. If you want to test interactively, I recommend:
1. use testnet prax
2. create 48h dutch auctions, across two pairs (so that >20 auctions are created)
3. run the code in this …
=> feat(pcli): handle batches of auctions

crates/core/component/dex/src/component/router/path_cache.rs
There is a bug in path search that causes spurious path activation, as a result, path search is far slower than it should. The bug is a divergence from the intended design.
Penumbra uses a variant of Bellman-Ford (SPFA) in order to "lock in" a path for execution. There are a few differences with ordinary SPFA. First, iterations are bounded to `k` hops, rather than potentially finding paths of length `|V|`. Second, is that paths are not directly comparable to one another until they are complete, or if they share the same start/end.
**Bug**
At the moment, path search will mark `PathEntry`s as "active" if their best path OR if their spill path improves. When an entry is marked as active, it will be considered in future rounds and its tip will be tentatively relaxed against candidates.
That …
=> dex: fix degraded relaxation phase

docs/protocol/src/dex.md
broken: https://faculty.chicagobooth.edu/eric.budish/research/HFT-FrequentBatchAuctions.pdf
correct: https://ericbudish.org/wp-content/uploads/2022/03/high_frequency_trading_arms_race.pdf
=> fix(docs): update broken Budish research link in DEX docs

crates/bin/pd/src/cli.rs, crates/bin/pd/src/main.rs, crates/bin/pd/src/migrate.rs, crates/bin/pd/src/migrate/migrate2/mod.rs, crates/bin/pd/src/migrate/migrate2/noop.rs
This PR adds `pd migrate no-op [--target-app-version=<APP>]` which is tooling that can be used to produce a hard-fork upgrades. It uses the new migration framework and can serve as an example for prospective protocol engineers.
> consensus breaking when exercised
=> pd: make it easy to do an upgrade hard-fork
