notes/SUMMARY.md
notes/updates.md

Add implementation kickoff update

---

spec/protocol/addresses_keys/addresses.md

spec: addresses

---

crypto/Cargo.toml
crypto/src/keys.rs

feat: keys implementation

---

Cargo.toml
penumbra/Cargo.toml

deps: pin tracing* to commit 6cc6c47354ceeb47da7c95faa41c6d29b71b5f37

---

crypto/src/keys/diversifier.rs
crypto/src/note.rs
spec/protocol/notes/note_plaintexts.md

and fixes to spec/code comments re: size of fields

note serialization/deserialization

---

crypto/src/asset.rs
crypto/src/note.rs
crypto/src/proofs/transparent.rs
crypto/src/transaction.rs
crypto/src/transaction/builder.rs
penumbra/Cargo.toml
penumbra/src/app.rs
penumbra/src/genesis.rs
penumbra/src/lib.rs

This allows us to create an initial set of genesis notes.

Add JSON'able `GenesisNotes` container.

---

penumbra/Cargo.toml
penumbra/README.md
penumbra/src/bin/pd.rs
penumbra/src/genesis.rs

Closes #31 
```sh
$ cargo run --bin pd -- create-genesis penumbra \
"(100, pen, penumbra_tn001_1kpgdhlzws6kyk2cf580wtt76t9nn2vf7em3pn05y3h8ym5a6aevdxshjgsnxecv94rzsxdhng6cjp8kgchqxud06p9xka0yxv99rty3njetqqnx2hrzz4tc03956e0)" \
"(1, tungsten_cube, penumbra_tn001_1kpgdhlzws6kyk2cf580wtt76t9nn2vf7em3pn05y3h8ym5a6aevdxshjgsnxecv94rzsxdhng6cjp8kgchqxud06p9xka0yxv99rty3njetqqnx2hrzz4tc03956e0)"
{
"notes": [
{
"diversifier": "b050dbfc4e86ac4b2b09a1",
"amount": 100,
"note_blinding": "fb5b430096940592704c911b0fdef6ae324f054ddc6ea8cb13555373af81a00b",
"asset_id": "3213674d74c0f0a10b786838225460288830940147ed6f66bbae7af1ed759101",
"transmission_key": "dee5afda596735313ecee219be848dce4dd3baee58d342f244266ce185a8c503"
},
{
"diversifier": "b050dbfc4e86ac4b2b09a1",
"amount": 1,
"note_blinding": …
```

pd: add deterministic `create-genesis` command

---

docker-compose.override.yml
docker-compose.yml

cf https://github.com/penumbra-zone/penumbra/pull/122#discussion_r744288524

Set Docker version to 3.7

---

spec/concepts/addresses_keys.md
spec/protocol.md
theme/css/general.css

Fix broken links and improve fonts.

Small spec tweaks

---

penumbra/src/bin/pcli.rs

Rename the `pcli --addr` to `pcli --node`

---

crypto/src/action.rs
crypto/src/action/output.rs
crypto/src/action/spend.rs
crypto/src/address.rs
crypto/src/memo.rs
crypto/src/note.rs
crypto/src/nullifier.rs
crypto/src/proofs/transparent.rs
crypto/src/transaction.rs
crypto/src/transaction/builder.rs
crypto/src/value.rs
decaf377-fmd/src/clue_key.rs
decaf377-fmd/src/detection.rs
decaf377-ka/src/lib.rs
decaf377-ka/tests/proptests.rs
penumbra/src/app.rs
penumbra/src/bin/pcli.rs
penumbra/src/bin/pd.rs
proto/build.rs

This PR is a series of fixes to lints detected by clippy; all lints are now resolved. Clippy uncovered one performance optimization: a location where bounds checks could be elided in a loop by using an iterator.

Clippy fixes

---

penumbra/Cargo.toml
penumbra/src/bin/pcli.rs

Fixes #125.
For reviewers: should any of the paths out of this command have a non-zero exit code?

Delete wallet command

---

pd/src/state.rs
pd/src/wallet.rs
proto/proto/wallet.proto

Closes #147 
Build is failing here due to #149

wallet service: add transaction by note commitment 

---

pcli/Cargo.toml
pd/Cargo.toml
pd/src/app.rs
pd/src/db/schema.rs
pd/src/state.rs

update ABCI branch

---

pd/src/app.rs
pd/src/db/schema.rs
pd/src/state.rs

fix: switch height to i64 to match SQL type INT8

---

crypto/src/transaction.rs
crypto/src/transaction/builder.rs
wallet/src/state.rs

This includes the fee in the transaction builder's value balance computation
Closes #170

fix: Include fee in PEN in transaction value balance

---

pcli/src/main.rs

Closes #168 
This only affects generation of new wallets, as a result existing wallets won't be archived (shouldn't be an issue, but worth pointing out).
Additionally I saw some logic in the wallet code for re-saving client state (e.g. `state.commit()`) however I don't think it's desirable to do that step for backups since we only really care about the seed data AFAIK -- please correct me if that's a bad assumption.

168: Store backups of wallets in archive directory for debugging

---

crypto/src/address.rs

Proposed format for v0 Penumbra addresses

feat: decouple address version from testnet ID

---

README.md
crypto/src/asset.rs
crypto/src/note.rs
crypto/src/proofs/transparent.rs
crypto/src/transaction.rs
crypto/src/transaction/builder.rs
crypto/src/value.rs
pd/src/app.rs
pd/src/genesis.rs
wallet/src/state.rs

This is a little less generic than "PEN".

Change asset name to 'penumbra'

---

README.md
pd/Cargo.toml
pd/src/app.rs
pd/src/main.rs

Closes #12 
You can try this out for yourself by running and observing the counters on http://127.0.0.1:9000/ which is the endpoint for Prometheus to scrape

feat: integrate metrics

---

crypto/src/transaction.rs
pd/src/verify.rs

test: de-duplicate transaction verification logic 

---

pd/src/app.rs

this TODO isn't needed after #206

remove unnecessary todo

---

pd/src/app.rs

we use `check_tx` and `app.mempool_nullifiers` to protect the mempool from duplicate nullifiers, however when running `deliver_tx` we didn't verify that the transaction that was put into the block didn't spend the same nullifier as a different transaction in the same block.
this PR adds a branch which ignores txns that spend nullifiers that were already spent in the pending block.

verify that nullifiers are not double spent in the same block

---

pd/sqlx-data.json
pd/src/app.rs
pd/src/genesis.rs
pd/src/state.rs
scripts/setup_validator.py

Add support for epoch duration to genesis, EndBlock

---

pcli/Cargo.toml
pd/Cargo.toml

Closes #11 now that https://github.com/informalsystems/tendermint-rs/pull/862 is merged.

Switch to upstream tendermint-rs

---

pd/sqlx-data.json
pd/src/db.rs
pd/src/db/indexes/notes_height_idx.sql
pd/src/db/indexes/notes_position_idx.sql
pd/src/db/indexes/nullifiers_height_idx.sql
pd/src/db/notes.sql
pd/src/pending_block.rs
pd/src/state.rs
pd/src/verify.rs

245 data enhancements

---

crypto/src/action.rs
crypto/src/action/output.rs
crypto/src/memo.rs
crypto/src/note.rs
crypto/src/proofs/transparent.rs
crypto/src/transaction.rs
pd/src/genesis.rs

Produced along the way to debugging #259.

minor `Debug` improvements

---

pd/sqlx-data.json
pd/src/db/validators.sql
pd/src/pending_block.rs
pd/src/state.rs

three small issues:
* couldn't get position in the NCT
* hit a not null constraint due to unused unclaimed_reward column (removed)
* validators insert was not committed to database (just was in a pending database transaction)

fixes to initchain 

---

README.md
crypto/src/address.rs
pcli/src/opt.rs

Switches the chain ID and DNS name, and updates the readme.

Euporie updates

---

crypto/src/address.rs
pd/sqlx-data.json
pd/src/db.rs
pd/src/db/validator_fundingstreams.sql
pd/src/db/validators.sql
pd/src/main.rs
pd/src/staking.rs
pd/src/state.rs
spec/stake/validator-rewards.md

add validator FundingStreams to allow multiple commission payout destinations

---

stake/src/epoch.rs

Add Epoch type

---

pcli/Cargo.toml
pcli/src/state.rs

Commit wallet state atomically using a temporary file

---

pcli/Cargo.toml
pcli/src/state.rs

Use a lockfile to prevent concurrent execution of `pcli`

---

crypto/src/asset/registry.rs
stake/Cargo.toml
stake/src/lib.rs
stake/src/token.rs
stake/src/validator.rs

This rebases and supercedes #242 to match the denomination refactoring from #283.

stake: add a DelegationToken

---

README.md
scripts/docker_compose_freshstart.sh
scripts/setup_validator.py

No longer automatically start testnet with freshstart.sh, ensure DB is present and configured prior to build

Docker Fixes

---

crypto/src/asset.rs
crypto/src/asset/denom.rs
crypto/src/asset/registry.rs

Closes #292, now working on adding property test

feat: add `DisplayDenom` formatting and parsing, fix display parsing bug

---

crypto/src/asset.rs
crypto/src/asset/denom.rs
crypto/src/asset/registry.rs
crypto/src/value.rs

feat: impl `FromStr` for `Value`

---

crypto/src/asset.rs
crypto/src/asset/cache.rs
crypto/src/asset/denom.rs
crypto/src/value.rs
pcli/src/fetch.rs
pcli/src/main.rs
pcli/src/opt.rs
wallet/src/state.rs

Use display denominations in `pcli`

---

testnets/003-eupheme/genesis.json

Copies the Euporie genesis.json over from Eupheme and edits to change `penumbra` to `upenumbra`.

testnet: add genesis.json for eupheme

---

pcli/src/main.rs

This requires that the `wallet` field of the top-level object be parseable as a `Wallet`, but does not require any other structure. As a result, this will still not allow migrations between wallet state formats where the serialization of a `Wallet` changes, but this logic could be added later.
This also adds a check to make sure that if the wallet cannot be parsed after being written to disk, it will not be overwritten.

Allow the wallet to be reset even if it is only partially parseable

---

README.md

Thanks to discussion with @bazouk#5545 on Discord, a few vague spots in the README were identified. This clarifies them.

Add clarifications based on discord discussion

---

Dockerfile.dev
chain/Cargo.toml
chain/src/lib.rs
chain/src/params.rs
pcli/Cargo.toml
pd/Cargo.toml
proto/build.rs
proto/proto/params.proto
proto/src/lib.rs

326: Add ChainParams proto definition and penumbra-chain crate

---

pcli/src/command/balance.rs
wallet/src/state.rs

Rename pending to submitted

---

chain/src/params.rs
crypto/src/address.rs
crypto/src/asset/id.rs
crypto/src/keys/diversifier.rs
crypto/src/note.rs
crypto/src/value.rs
proto/build.rs
proto/proto/chain.proto
proto/proto/crypto.proto
proto/src/lib.rs
proto/src/serializers/bech32str.rs
transaction/src/transaction.rs
wallet/src/state.rs

Serde cleanup

---

chain/Cargo.toml
chain/src/params.rs
crypto/src/asset/denom.rs
pd/Cargo.toml
pd/migrations/20211216025603_init.sql
pd/sqlx-data.json
pd/src/app.rs
pd/src/pending_block.rs
pd/src/state.rs
pd/src/wallet.rs
proto/build.rs
proto/proto/chain.proto
proto/proto/crypto.proto
proto/proto/thin_wallet.proto

this PR implements the changes described in #335

track the total token supply, and update RPCs to use supply tracking

---

chain/src/params.rs
proto/build.rs

Properly (de)serialize params::ChainParams as pb::ChainParams

---

pcli/src/command/wallet.rs
wallet/src/state.rs

Remove chain_params from ClientState constructor

---

pd/sqlx-data.json
pd/src/app.rs
pd/src/state.rs

process changes to delegation and staking token supplies at epoch boundary

---

pd/src/genesis.rs
proto/build.rs
proto/proto/genesis.proto
proto/src/lib.rs

Implement Genesis data as protobufs

---

pcli/src/command/wallet.rs
pd/src/app.rs
pd/src/genesis.rs
pd/src/main.rs
pd/src/wallet.rs
proto/proto/genesis.proto
wallet/src/state.rs

Use ChainParams in Genesis

---

pd/src/pending_block.rs

(wip, see discussion in discord)

pd: fix up definition of funding stream notes

---

.vscode/settings.json
crypto/Cargo.toml
crypto/src/merkle.rs
pd/Cargo.toml
pd/migrations/20211216025603_init.sql
pd/sqlx-data.json
pd/src/genesis.rs
pd/src/state.rs
pd/src/state/jellyfish.rs
pd/src/wallet.rs
proto/build.rs
proto/proto/crypto.proto

Imports the JMT code to PD and writes NCT root data to backing store on block commit.

Import and implement jmt

---

pcli/src/command/stake.rs
pd/migrations/20211216025603_init.sql
pd/sqlx-data.json
pd/src/app.rs
pd/src/main.rs
pd/src/pending_block.rs
pd/src/state.rs
pd/src/verify.rs
proto/build.rs
proto/proto/stake.proto
stake/src/lib.rs
stake/src/rate.rs
stake/src/status.rs
stake/src/validator.rs

Remaining work around validator state transitions is to be completed in #375 but this helps unblock @plaidfinch

Add validator_state/unbonding_epoch to the validators table and domain types

---

pcli/src/command/balance.rs

Does what it says on the tin. This additional option makes `pcli balance` display the values of individual notes, which can aid in debugging issues related to wallet fragmentation.

Add `--by-note` option to `pcli balance`

---

README.md
pcli/src/network.rs

fix: send transaction in POST request body

---

pcli/src/command/stake.rs
pcli/src/command/tx.rs
pcli/src/fetch.rs
pcli/src/sync.rs
pd/src/wallet.rs
proto/proto/light_wallet.proto
proto/proto/thin_wallet.proto
wallet/src/state.rs

Fixes #394 (not yet finished, need to actually check on `pd` side).

WIP: Chain id checking

---

pd/Cargo.toml
pd/sqlx-data.json
pd/src/consensus/worker.rs
pd/src/main.rs
pd/src/state/reader.rs

Implements one of the bullets in #211

feat(metrics): track counter of spent nullifiers

---

chain/src/params.rs
crypto/src/nullifier.rs
crypto/src/value.rs
pcli/src/command/addr.rs
pd/migrations/20211216025603_init.sql
pd/sqlx-data.json
pd/src/consensus/worker.rs
pd/src/genesis.rs
pd/src/main.rs
pd/src/pending_block.rs
pd/src/state.rs
pd/src/state/reader.rs
pd/src/state/writer.rs
pd/src/verify.rs
pd/src/verify/stateful.rs
pd/src/verify/stateless.rs
pd/src/verify/tests.rs
pd/src/wallet.rs
proto/proto/chain.proto

Implements unbonding period and reversion of quarantined outputs in the event of slashing (pending slashing being implemented separately to this PR).

Unbonding (new architecture)

---

spec/zswap/auction.md

I think this is the intended link

Add link to Barry Whitehat's post on why a private Uniswap with ZKPs doesn't work

---

spec/crypto/flow-encryption/threshold-encryption.md

this PR fixes some rendering bugs in the rendered LaTex, changes the notation a bit to be more consistent, and adds a note on the encryption SNARK note to the threshold spec

spec: threshold: fix some rendering bugs and make notation more consistent

---

pd/sqlx-data.json
pd/src/state/writer.rs

fix: resolve error when base rate is updated at epoch boundary

---

Dockerfile.dev

Fixes an issue that was preventing dev Docker instances from running

Copy the testnets directory into dev Docker instances

---

.github/workflows/integration.yml

ci: add gh action w/ postgres container for integration tests

---

docker-compose.prod.yml

docker: add log rotation for pd container in prod configuration

---

theme/css/general.css

This makes monospaced renderings show up properly.

swap Iosevka for Iosevka Term

---

spec/crypto/decaf377/group_hash.md
spec/crypto/decaf377/invsqrt.md

These are the protocol spec updates for https://github.com/penumbra-zone/decaf377/pull/21 (to be reviewed together)

spec: Sarkar 2020 based table lookup method for decaf377 sqrts and optimized Elligator

---

pd/src/state/jellyfish.rs
pd/src/state/writer.rs

use jmt::WriteOverlay in pd

---

tct/src/lib.rs

This can be edited later, I just thought it'd be nice to include it in the
renderings.

Add monodraw diagram for tct

---

Cargo.toml
ibc/Cargo.toml
ibc/src/ibcaction.rs
ibc/src/lib.rs
pd/Cargo.toml
pd/src/components.rs
pd/src/components/app.rs
pd/src/components/ibc.rs
proto/build.rs
proto/proto/sighash.proto
proto/proto/transaction.proto
proto/src/lib.rs
transaction/Cargo.toml
transaction/src/action.rs

this PR adds a skeleton IBC component, using the new Component architecture, along with a new transaction Action, `IBCAction`

ibc: add skeleton IBC component, IBC Action

---

chain/src/lib.rs
chain/src/note_source.rs

chain: add NoteSource enum

---

crypto/src/proofs/transparent.rs
pd/src/verify/stateless.rs
proto/proto/transaction.proto
proto/proto/transparent_proofs.proto
transaction/src/action/output.rs
transaction/src/action/spend.rs
transaction/src/transaction.rs
transaction/src/transaction/builder.rs

One of the checkboxes towards #450

feat: lifting proofs to transaction level

---

crypto/src/address.rs
docker-compose.override.yml
pd/src/components/ibc.rs
pd/src/components/shielded_pool.rs
pd/src/state.rs

#517 added the new `App` as a sidecar; this PR includes tweaks that get it running correctly.

Post-component integration tweaks

---

proto/proto/ibc.proto

this is a quick PR, preliminary for #506

add IBC client messages to IBCAction

---

pd/src/components.rs
pd/src/components/app.rs
pd/src/components/staking.rs
pd/src/components/validator_set.rs
stake/src/epoch.rs

Optimistically merging prior to writing the rest of the implementation

Staking component scaffolding

---

pd/src/consensus/worker.rs

The existing sidecar code wasn't really a sidecar, because it would abort
`DeliverTx` on error, so the new Component code was actually in the consensus
path.

pd: correctly separate new Component code from consensus

---

pd/src/components/shielded_pool.rs
pd/src/pending_block.rs
pd/src/state/writer.rs

Currently, all new transactions fail verification in the `ShieldedPool`
component, because the `ShieldedPool` NCT and the legacy NCT de-sync and have
different commitment roots.  There are two reasons for this:
- the legacy code used a different (worse) mechanism for deterministically deriving the blinding factors for minted notes;
- the new code does not mint reward notes on epoch transitions.
To fix the first point, this commit backports the hash-the-NCT-root method to
the legacy code.
The second point is unfixed, so following this commit, the tree state will
continue to de-sync following the first epoch transition.  To fix it, we need
to mint reward notes in the `ShieldedPool` component.

pd: unify note minting between ShieldedPool and legacy code

---

pd/src/storage.rs

Requires [jmt #37](https://github.com/penumbra-zone/jmt/pull/37) for `NodeKey` `version()` access
Closes #502 
Closes #526

Implement get_rightmost_leaf for restore and version tracking

---

Dockerfile
docker-compose.override.yml
docker-compose.prod.yml
docker-compose.yml

changes so far for testnet deployment

Orthosie hotfixes

---

pd/Cargo.toml
pd/src/components/staking.rs
proto/proto/stake.proto
stake/src/changes.rs
stake/src/lib.rs

It was unclear how to handle reward notes right now so those aren't working. The implementation also had to change a fair bit from the original, so a close review would be appreciated.

Update next rates on epoch transition in Staking component

---

ibc/Cargo.toml
ibc/src/client.rs
ibc/src/lib.rs
pd/Cargo.toml
pd/src/components.rs
pd/src/components/ibc.rs
proto/Cargo.toml
proto/proto/ibc.proto

this PR adds support to the IBC component for handling incoming CreateClient IBC messages.

ibc client: implement handling of CreateClient IBC message

---

pcli/src/command/stake.rs
pcli/src/fetch.rs
pcli/src/main.rs
pcli/src/network.rs
pcli/src/sync.rs
pd/src/info.rs
pd/src/info/light_client.rs
pd/src/info/thin_client.rs
pd/src/main.rs
pd/src/wallet/server/light.rs
pd/src/wallet/server/thin.rs
proto/build.rs
proto/proto/light_client.proto
proto/proto/thin_client.proto
proto/src/lib.rs

Rename light/thin wallet -> light/thin protocol

---

pd/src/main.rs

Add preserve-chain-id flag

---

chain/Cargo.toml
chain/src/note_source.rs

hex encode transaction id for `NoteSource`

---

.vscode/settings.json
README.md
wallet-next/Cargo.toml
wallet-next/migrations/20220415094212_init.sql
wallet-next/sqlx-data.json
wallet-next/src/bin/pwalletd.rs
wallet-next/src/lib.rs

rebased sqlx+sqlite scaffolding from #600

---

pd/src/components/shielded_pool.rs

The existing implementation had application logic related to ending the block
(e.g., minting reward notes) in `ShieldedPool::write_block`, which is used by
both `end_block` and `init_chain`.  This worked because the reward notes would
be empty during `init_chain`, but in general isn't great to mix application
logic between the two cases.
Instead, this commit pulls out that logic into `end_block`, and renames
`write_block` to `write_compactblock_and_nct`, so that it's clearer from the
name of the method that it's just about writing specific data, not doing
general processing.

pd: refactor `ShieldedPool::write_block`

---

pd/src/components/shielded_pool.rs

The existing implementation of `mint_note` is very slow, because the
`incrementalmerkletree` implementation isn't particularly fast at computing the
tree root, and we compute it for every genesis allocation.
As noted in the comment there, the point is just to achieve uniqueness:
> These notes are public, so we don't need a blinding factor for privacy,
> but since the note commitments are determined by the note contents, we
> need to have unique (deterministic) blinding factors for each note, so they
> cannot collide.
>
> Hashing the current NCT root is sufficient, since it will change every time
> we insert a new note.
Instead of hashing the root, we could also hash the position, which will also
change every time we insert a new note.  This isn't as good, since we're only
binding to the …

pd: use NCT position rather than root for blinding factor uniqueness

---

wallet-next/src/bin/pwalletd.rs
wallet-next/src/lib.rs
wallet-next/src/storage.rs

Create Storage struct to encapsulate wallet sql interactions

---

pd/src/components/app.rs
pd/src/components/component.rs
pd/src/components/ibc.rs
pd/src/components/ibc/client.rs
pd/src/components/shielded_pool.rs
pd/src/components/staking.rs
pd/src/consensus/worker.rs
pd/src/mempool/worker.rs

pd: reflect infallibility in Component methods

---

pd/src/components/shielded_pool.rs

pd: fix reversed assert

---

docker-compose.multinode.override.yml
docker-compose.override.yml
docker-compose.yml
docs/guide/src/pd/create-testnet.md
scripts/docker_compose_freshstart.sh

docker: edit paths to match generate-testnet defaults

---

docker-compose.multinode.override.yml
docker-compose.override.yml
pd/src/storage/overlay_ext.rs

These combine to get significantly more meaningful output:
```
2022-04-24T22:01:43.442654Z DEBUG pd::storage: creating overlay for version 1227
2022-04-24T22:01:48.155237Z DEBUG abci:BeginBlock{height=block::Height(1228) hash="a1a84dfc447a623e62106c2a831bf78cf77c765095d43e732ec4f3fce780168f"}:begin_block:staking:validator_power{identity_key=penumbravalid1y3cj55z8j0rtk9qfryulhu3yntxwqsseck6dedwsdya3vkwah5rqn8pyzq}: pd::components::staking: getting validator power
2022-04-24T22:01:48.155737Z DEBUG abci:BeginBlock{height=block::Height(1228) hash="a1a84dfc447a623e62106c2a831bf78cf77c765095d43e732ec4f3fce780168f"}:begin_block:staking: pd::components::staking: v=penumbravalid1y3cj55z8j0rtk9qfryulhu3yntxwqsseck6dedwsdya3vkwah5rqn8pyzq voted=true num_missed_blocks=1 missed_blocks_maximum=500 …
```

Demote storage tracing

---

Cargo.toml
chain/Cargo.toml
crypto/Cargo.toml
decaf377-fmd/Cargo.toml
decaf377-ka/Cargo.toml
pcli/Cargo.toml
pd/Cargo.toml
tct/Cargo.toml
transaction/Cargo.toml

To merge with: https://github.com/penumbra-zone/decaf377/pull/23
Closes #713

deps: remove pinned arkworks dependencies, use 0.3.x from crates.io

---

chain/src/params.rs

This value was inverted from what we want.

Fix missed_blocks_maximum

---

Cargo.lock
wallet-next/Cargo.toml
wallet-next/migrations/20220415094212_init.sql
wallet-next/sqlx-data.json
wallet-next/src/note_record.rs
wallet-next/src/storage.rs
wallet-next/src/sync.rs

Add commit logic to wallet-next storage

---

stake/src/component.rs

Prior to this commit, setting validators with enabled: false did not trigger state updates.

stake: correct handling of validator updates

---

wallet-next/sqlx-data.json
wallet-next/src/storage.rs

@zbuc - looks like we had a naming collision on branches for the same issue, which I realized only after I'd pushed my changes to remote, whoops. Doesn't look like there are any merge conflicts as it stands, but this should close #750. Let me know if you're still working on this branch, we can separate our changes or not as preferred.

Add intialize/load methods to wallet-next storage.rs

---

wallet-next/sqlx-data.json
wallet-next/src/service.rs
wallet-next/src/storage.rs
wallet-next/src/sync.rs
wallet-next/src/worker.rs

Add sync_to_latest worker to wallet-next

---

storage/src/storage.rs

When we updated storage to use rocks column families, we didn't update the JMT reader and writers to use the JMT column family. This changes the JMT column family to 'jmt' and updates the readers/writers to use it

storage bugfix: use `jmt` column family in rocksdb

---

wallet-next/src/service.rs

We don't currently have a way of getting the current chain height until we integrate a tendermint client into the wallet service, so the implementation is not yet correct.
Closes #753

First pass at wallet sync status implementation

---

crypto/src/keys.rs
crypto/src/keys/fvk.rs
wallet-next/src/service.rs

Implement check_fvk

---

pd/src/main.rs

pd: add recursion limit override for binary

---

docs/guide/src/pd/join-testnet/validator.md
pcli/src/command/validator.rs

Document validator enabled flag; default to false in templates

---

tct/src/epoch.rs
tct/src/tree.rs

When an epoch was finalized, subsequent insertions into the tree would fail, because they incorrectly attempted to insert into the finalized epoch, rather than creating a new, unfinalized epoch into which to insert. This fixes that bug and shows no errors when testing with `pd` across several epochs from genesis.

Fix bug where inserting a into finalized blocks/epochs failed incorrectly

---

Cargo.lock
wallet/Cargo.toml
wallet/src/state.rs

The root hashes don't seem to agree yet after an epoch boundary.

Integrate TCT tracking into pcli

---

Cargo.lock
wallet-next/Cargo.toml
wallet-next/sqlx-data.json
wallet-next/src/service.rs
wallet-next/src/storage.rs
wallet-next/src/sync.rs

Add storage::notes function

---

Dockerfile.dev

updates the dev dockerfile for the changes described in #847

docker: update wallet-next -> view

---

pd/src/info/specific.rs
proto/proto/client/specific.proto

add key_value generic state query to specific api

---

tct-property-test/tests/witness.rs
tct/src/internal/frontier/node.rs
tct/src/tree.rs

Additional TCT testing to try to reproduce #858 in tests

adding to tests for TCT

---

pd/src/main.rs

There's a remaining issue with `RUST_LOG` no longer being respected, but at least this should hopefully not crash.

Correct TracingContextLayer code for enriching metrics with labels from tracing data

---

pd/src/main.rs

Now `RUST_LOG` should be correctly filtering tracing events.

Add `EnvFilter` to respect `RUST_LOG`

---

proto/proto/view.proto
view/src/service.rs

view: replace AuthPathsResponse with WitnessData

---

view/src/service.rs

Implement witness call in ViewService

---

proto/proto/view.proto
view/migrations/20220415094212_init.sql
view/sqlx-data.json
view/src/note_record.rs
view/src/storage.rs
view/src/sync.rs

change `NoteRecord` to store note positions

---

crypto/src/asset/id.rs
proto/proto/view.proto
view/migrations/20220415094212_init.sql
view/sqlx-data.json
view/src/service.rs
view/src/storage.rs
view/src/worker.rs

Implement assets in pviewd/pcli-next

---

wallet-next/src/plan.rs

implement undelegate in wallet next plan

---

wallet-next/src/plan.rs

I noticed that this module isn't being imported anywhere so we've probably got some compile-time errors in it still, but we can fix those later.
Closes #884

Implement `plan::validator_definition` in `wallet-next`

---

view/src/client.rs
wallet-next/src/plan.rs

This also has a dependency on #881 and can't be fully implemented before that.
Closes #883

Implement send in wallet-next

---

proto/proto/view.proto
view/src/service.rs

add chain params to view protocol

---

Cargo.lock
pcli-next/src/main.rs
proto/proto/view.proto
view/Cargo.toml
view/sqlx-data.json
view/src/bin/pviewd.rs
view/src/service.rs

Add status() to pviewd.rs

---

docs/guide/src/pcli.md
docs/guide/src/pcli/pviewd.md
pcli-next/src/command/balance.rs
pcli-next/src/command/chain.rs
pcli-next/src/command/stake.rs
pcli-next/src/command/tx.rs
pcli-next/src/command/validator.rs
pcli-next/src/main.rs
view/src/bin/pviewd.rs
view/src/client.rs
wallet-next/src/build.rs
wallet-next/src/plan.rs

Also adds a description to the docs.

Add support for `pviewd` use in `pcli-next`

---

docs/guide/src/pd/join-testnet/fullnode.md

- Recommends everyone wipe RocksDB.
- Fixes Latex rendering issue with `$HOME`.

Update pd testnet guide

---

Cargo.lock
chain/Cargo.toml
chain/src/sync.rs
proto/proto/chain.proto
shielded-pool/src/component.rs
tct/src/block.rs
tct/src/epoch.rs
tct/src/lib.rs
tct/src/proof.rs
tct/src/tree.rs
view/src/sync.rs

Track block and epoch roots

---

ibc/src/component.rs

prior to this change, we only set an `enabled` boolean on init-chain, meaning that whether IBC was enabled would depend on if the node had restarted. this PR instead directly pulls the chain parameters when validating IBC transactions.

fix ibc enabled: use chain params from state

---

view/src/bin/pviewd.rs

Improve error message for invalid FVK in pviewd init

---

.github/workflows/notes.yml
Cargo.lock
crypto/Cargo.toml

This PR should render docs of the parameter generation crate for Poseidon (over in the poseidon377 repository)

doc: render poseidon-paramgen crate documentation

---

ibc/src/component/channel.rs
ibc/src/component/channel/execution.rs
ibc/src/component/client.rs
ibc/src/component/connection.rs
ibc/src/component/connection/execution.rs
ibc/src/event.rs
ibc/src/lib.rs

this PR adds ABCI events for the core IBC protocol.

ibc: add events

---

.github/workflows/notes.yml
Dockerfile.dev

Patch up crate renaming changes

---

chain/src/sync.rs

Compact block serialization incorrectly filtered all block roots: fixed

---

pd/src/main.rs

pd: remove -h short name for --host to resolve conflict with --help/-h

---

pcli/src/box_grpc_svc.rs

Signed-off-by: Eliza Weisman <eliza@buoyant.io>

pcli: make `BoxGrpcService` `Clone + Sync`

---

crypto/src/eddy.rs
crypto/src/keys/ivk.rs
pcli/src/network.rs
transaction/src/plan/action/output.rs
view/src/client.rs
view/src/service.rs
view/src/storage.rs
view/src/worker.rs

pcli: Add await change functionality to transaction submission

---

view/src/bin/pviewd.rs

fix: remove short name for --host to resolve pviewd runtime panic

---

.github/workflows/smoke.yml
pcli/tests/network_integration.rs

checking this actually kicks off a build on PRs, woops

ci: fix yaml syntax

---

chain/src/view.rs
pd/src/info/oblivious.rs
pd/src/info/specific.rs
view/src/service.rs

Include original error messages and add more descriptive messages

---

pcli/src/command/stake.rs
wallet/src/plan.rs

Resolves #1010.
One remaining question is how to communicate the meaning of `--fee` to the user. In this implementation, we actually charge them 2x the fee, by using the same fee amount for each of the two-part transaction. What should we do here?

Use exact change for undelegations

---

component/src/shielded_pool/component.rs
component/src/shielded_pool/mod.rs
proto/proto/chain.proto
view/sqlx-data.json
view/src/storage.rs

A couple of quick fixes to get quarantine working.

Use `DelibleNoteSource` to mark deletion, correctly handle quarantined nullifiers in view

---

.github/workflows/deploy-preview.yml
.github/workflows/deploy-testnet.yml
docker-compose.multinode.override.yml
docker-compose.override.yml
docker-compose.prod.yml
docker-compose.yml
docs/guide/src/dev/create-testnet.md
docs/guide/src/dev/devnet-quickstart.md
docs/guide/src/pd/join-testnet/fullnode.md
pd/src/main.rs
scripts/docker_compose_freshstart.sh

pd cli updates: change --rocks-path to --home, add new testnet subcommand

---

storage/src/storage.rs

pd: don't create spans in hot functions

---

crypto/src/memo.rs
crypto/src/note.rs

feat(crypto): impl outgoing decryption

---

tct/src/tree.rs

Thank you to @hawkw for suggesting to ensure `#[instrument]` levels are set to `"trace"` when they should be!

Set the level for every #[instrument] in the TCT to "trace"

---

component/src/shielded_pool/component.rs
component/src/shielded_pool/state_key.rs
pcli/src/command/query.rs
pd/src/info/specific.rs

Add epoch and block anchors to JMT

---

pd/src/main.rs

Resolves #1122 by adding an opt-in flag to enable tokio-console subscriber support to `pd`

Make tokio-console support an opt-in flag for `pd`

---

crypto/src/keys/diversifier.rs
view/src/storage.rs

feat: segment the address space to distinguish ephemeral addresses

---

docker-compose.multinode.override.yml
docker-compose.yml
docs/guide/src/pd/build.md

the latest release contains more p2p fixes.

update tendermint to 0.35.8

---

crypto/src/keys/ivk.rs
pcli/src/command/addr.rs

feat: Add methods to handle ephemeral addresses 

---

component/src/ibc/component/connection/stateful.rs

similar to #1198, we were using the wrong connection ID to verify proofs, which would not allow us to verify counterparty proofs correctly.

ibc ConnectionOpenAck: use counterparty connection ID instead of self connection ID

---

proto/proto/dex.proto
proto/proto/transaction.proto

This PR stubs out some initial protos that define liquidity positions and LP-related actions.

dex: stub LP data structures

---

docs/protocol/src/SUMMARY.md
docs/protocol/src/protocol/notes.md
docs/protocol/src/protocol/notes/note_commitments.md

spec: add note commitment section

---

pcli/src/command/stake.rs
pcli/src/network.rs
proto/proto/view.proto
view/sqlx-data.json
view/src/client.rs
view/src/service.rs
view/src/storage.rs
view/src/worker.rs

Await nullifiers in view service, making transaction confirmation robust when there is no change

---

crypto/Cargo.toml
crypto/src/keys/fvk.rs
crypto/src/note_payload.rs
view/sqlx-data.json
view/src/storage.rs
view/src/sync.rs

Add verification checks to note payload trial decryption

---

chain/src/genesis/app_state.rs
chain/src/params.rs
chain/src/view.rs
measure/src/main.rs
pd/src/info/oblivious.rs
pd/src/main.rs
proto/build.rs
proto/go-proto/chain.pb.go
proto/go-proto/view.pb.go
proto/proto/chain.proto
proto/proto/client/oblivious.proto
proto/proto/view.proto
view/src/bin/pviewd.rs
view/src/client.rs
view/src/service.rs
view/src/storage.rs

I also simplified `if nullifiers.len() == 0` to `if nullifiers.is_empty()`
fixes: #1227

renamed ChainParams to ChainParameters

---

chain/src/params.rs
chain/src/state_key.rs
chain/src/sync.rs
chain/src/view.rs
component/src/app/mod.rs
component/src/shielded_pool/component.rs
proto/build.rs
proto/proto/chain.proto
proto/proto/view.proto
view/migrations/20220415094212_init.sql
view/sqlx-data.json
view/src/client.rs
view/src/service.rs
view/src/storage.rs
view/src/sync.rs

This doesn't yet include logic for actually updating the parameters, just the initial support, and it adds them to the `CompactBlock`
Closes #1226

feat: create initial `FmdParameters` support

---

crypto/src/dex/swap/ciphertext.rs
crypto/src/dex/swap/plaintext.rs
crypto/src/dex/trading_pair.rs
crypto/src/note.rs
crypto/src/symmetric.rs
crypto/src/transaction.rs

Closes #1265
Closes #1267
Towards #1264

crypto: add `OutgoingCipherKey`

---

Cargo.lock
component/src/ibc/component.rs
component/src/ibc/transfer.rs
crypto/src/address.rs
proto/build.rs
proto/proto/ibc.proto
proto/proto/transaction.proto
transaction/Cargo.toml
transaction/src/action.rs
transaction/src/action/ibc.rs
transaction/src/auth_hash.rs

Ics20 withdraw action

---

pcli/src/command/tx.rs

This PR adds the basic skeleton of the `pcli swap` subcommand.

Skeleton for Swap/SwapClaim `pcli` commands

---

deployments/networks/testnet/README.md
deployments/terraform/modules/README.md

Proposal for structuring deployments.
- Terraform modules in `deployments/terraform/modules/`
- Testnet deployment state in `deployments/networks/`

Initial Directory Structure for testnet deployments.

---

component/src/ibc/transfer.rs
crypto/src/dex/swap.rs
crypto/src/eddy.rs
crypto/src/note.rs
crypto/src/proofs/transparent.rs
crypto/src/value.rs
decaf377-fmd/src/clue_key.rs
decaf377-fmd/src/detection.rs
decaf377-ka/src/lib.rs
eddy/src/ciphertext.rs
eddy/src/decryption_table.rs
eddy/src/transcript.rs
transaction/src/action/swap.rs
transaction/src/plan/action/swap.rs
transaction/src/plan/action/swap_claim.rs
transaction/src/transaction.rs

fix all warnings to prevent user confusion

---

chain/src/genesis/allocation.rs
component/src/shielded_pool/component.rs
crypto/src/address.rs
crypto/src/keys/fvk.rs
crypto/src/note.rs
decaf377-fmd/src/clue_key.rs
decaf377-fmd/src/error.rs
docs/protocol/src/protocol/notes/note_plaintexts.md
proto/proto/crypto.proto
transaction/src/plan/action/output.rs
transaction/src/plan/action/spend.rs
transaction/src/plan/action/swap.rs
transaction/src/plan/action/swap_claim.rs
view/migrations/20220415094212_init.sql
view/sqlx-data.json
view/src/note_record.rs
view/src/quarantined_note_record.rs
view/src/storage.rs
view/src/sync.rs

Closes #1084
~Marked wip as this still needs the changes propagating to the view service to either add a column storing the clue key (probably I'll do this first option) or to store the full address somewhere~ (done, by having a single address column)

feat: add full `Address` to `Note`

---

decaf377-fmd/src/clue_key.rs
proto/build.rs
proto/proto/transaction.proto
transaction/src/auth_hash.rs
transaction/src/plan.rs
transaction/src/plan/clue.rs

add deterministic `Clue` generation and `CluePlan` [FMD part 1]

---

proto/build.rs
proto/go-proto/view.pb.go
proto/go-proto/wallet.pb.go
proto/proto/view.proto
view/migrations/20220415094212_init.sql
view/sqlx-data.json
view/src/client.rs
view/src/lib.rs
view/src/note_record.rs
view/src/service.rs
view/src/storage.rs
view/src/sync.rs
wallet/src/plan.rs

Rename NoteRecord to SpendableNoteRecord

---

deployments/terraform/modules/gcp/README.md
deployments/terraform/modules/gcp/gcs/README.md
deployments/terraform/modules/gcp/gcs/main.tf
deployments/terraform/modules/gcp/gcs/outputs.tf
deployments/terraform/modules/gcp/gcs/providers.tf
deployments/terraform/modules/gcp/gcs/variables.tf
deployments/terraform/modules/gcp/project/services/README.md
deployments/terraform/modules/gcp/project/services/main.tf
deployments/terraform/modules/gcp/project/services/providers.tf
deployments/terraform/modules/gcp/project/services/variables.tf
deployments/terraform/modules/gcp/terraform_state/README.md
deployments/terraform/modules/gcp/terraform_state/chain/README.md
deployments/terraform/modules/gcp/terraform_state/chain/locals.tf
deployments/terraform/modules/gcp/terraform_state/chain/main.tf
deployments/terraform/modules/gcp/terraform_state/chain/outputs.tf
deployments/terraform/modules/gcp/terraform_state/chain/providers.tf
deployments/terraform/modules/gcp/terraform_state/chain/variables.tf
deployments/terraform/modules/gcp/terraform_state/main.tf
deployments/terraform/modules/gcp/terraform_state/outputs.tf
deployments/terraform/modules/gcp/terraform_state/providers.tf
deployments/terraform/modules/gcp/terraform_state/variables.tf

**Description:** Introduce terraform modules for GCS, project, and terraform state.
Closes #1285

use GCS for terraform remote state

---

chain/src/params.rs
component/src/shielded_pool/component.rs
component/src/shielded_pool/consensus_rules.rs
component/src/shielded_pool/consensus_rules/stateful.rs
component/src/shielded_pool/consensus_rules/stateless.rs
component/src/shielded_pool/mod.rs
decaf377-fmd/src/clue.rs
proto/proto/chain.proto

add consensus rules to check `Clue`s [FMD part 3]

---

crypto/src/memo.rs
transaction/src/action/undelegate.rs
wallet/src/plan.rs
wallet/src/plan/balance.rs
wallet/src/plan/balance/imbalance.rs
wallet/src/plan/balance/iter.rs
wallet/src/plan/builder.rs
wallet/src/plan/planner.rs

This implements a `Builder` API for transaction plans, factoring out all the shared functionality between different kinds of plans, and giving a much more flexible interface for bespoke actions.
In order for an action to be supported by this new architecture, its contribution to the value balance of the transaction plan must be accurately tracked by the builder. This is done in `Builder::action`, using the `provide` and `require` methods on the `balance` field of `Builder`. If an action contributes some `Value` to the balance of the transaction, it should `provide` that value in this method; likewise, if it subtracts some `Value` from the balance of the transaction, it should `require` that value in the same place. Some actions do both (for example, delegation and undelegation), and some …

Transaction plan builder

---

Cargo.lock
crypto/src/note.rs
crypto/src/proofs/transparent.rs
proto/proto/transparent_proofs.proto
transaction/src/plan/action/output.rs
transaction/src/plan/action/spend.rs

Closes #1317 (leaves #1315 as a pure refactor which I might do next)

crypto: add clue key into note commitments

---

component/src/ibc/transfer.rs
proto/proto/ibc.proto

Co-Authored-By: aubrey@penumbra.zone
Closes #978

add ics20 transfer packet processing

---

Cargo.lock
pd/Cargo.toml

Temporary pinning to previous tokio version to fix #1355

deps: pin tokio to known good version

---

pcli/src/command.rs
pcli/src/command/query/proposal.rs
pcli/src/command/view.rs
pcli/src/command/view/transactions.rs
proto/proto/view.proto
view/migrations/20220415094212_init.sql
view/migrations/20220715220553_tx_info.sql
view/sqlx-data.json
view/src/client.rs
view/src/service.rs
view/src/storage.rs

Add pcli view query for transaction hashes by block

---

chain/src/params.rs
pd/src/main.rs

Increase epoch duration and proposal voting block duration in future testnets

---

docs/guide/src/pcli/transaction.md

Document swaps in the guide

---

LICENSE
LICENSE.Apache-2.0
LICENSE.MIT
README.md

Add repository-wide dual license

---

docs/guide/src/pcli/transaction.md
pcli/src/command/query.rs
pcli/src/command/query/governance.rs

rename `pcli query proposals` to qpcli query governance`, add proposal status and title

---

crypto/src/address.rs
crypto/src/proofs/transparent.rs
decaf377-fmd/src/hkd.rs
tct/Cargo.toml
tct/src/proof.rs
transaction/src/auth_hash.rs
transaction/src/plan/action/output.rs
transaction/src/plan/action/spend.rs
transaction/src/plan/build.rs
transaction/src/witness_data.rs
view/src/service.rs
wallet/src/build.rs
wallet/src/plan.rs

support dummy `Spend`s and `Output`s

---

transaction/src/auth_hash.rs

regression test for #1386 (this will fail until that #1386 is resolved)

test: regression for auth hash mismatch

---

wallet/src/plan.rs

wallet: add memo in `plan::sweep` to dodge a panic

---

component/src/shielded_pool/component.rs
component/src/shielded_pool/consensus_rules/stateless.rs
transaction/src/transaction.rs

Closes #1376
Followup from 378a86114a457fd1a4fb3110f2145e4609f3a0f8 in #1391

consensus rules: add rule for memos, re-enable clue checks

---

crypto/src/dex/trading_pair.rs
pcli/src/command/query.rs
pcli/src/command/query/dex.rs
pd/src/info/specific.rs
proto/proto/client/specific.proto

This adds the `pcli q dex cpmm-reserves` and `pcli q dex batch-outputs` subcommands.
Closes #1399

Implement `pcli q dex` commands

---

component/src/shielded_pool/component.rs
crypto/src/asset/registry.rs
crypto/src/value.rs

add `gm` and `gn` to asset registry, parse genesis allocations with `parse_unit`

---

component/src/shielded_pool/consensus_rules/stateless.rs

Disabling this for today's testnet release due to #1416

temporarily disable memo consensus rule

---

.github/workflows/smoke.yml
pcli/tests/network_integration.rs

add swaps to integration tests

test(integration): add swap test

---

pcli/src/network.rs

I noticed that this error was formatted differently from some of the other errors so I added some handling around that as well.
Closes #1316

Better handle request body too large errors in pcli, better handle errors in general

---

docs/guide/src/pcli/transaction.md

Update swap documentation in guide to describe CPMM

---

crypto/src/note_payload.rs

Closes #1086
Is this an accurate description for future devs?

view: add explanation for future devs about not panicing in view

---

pcli/src/command/query/dex.rs

Display denomination for batch swap outputs instead of Asset ID

---

Cargo.lock
pcli/src/command.rs
pcli/src/command/view.rs
pcli/src/command/view/transaction_hashes.rs
proto/proto/view.proto
view/sqlx-data.json
view/src/client.rs
view/src/service.rs
view/src/storage.rs

This is to help with work in #1437

view: Rename transaction hash storage method & add full transaction retrieval method

---

crypto/src/dex/swap/plaintext.rs

Rework asset ID hashing to add every element individually instead of packing

---

component/src/dex/component.rs
crypto/src/proofs/transparent.rs
proto/proto/dex.proto
proto/proto/transparent_proofs.proto
transaction/src/action/swap.rs
transaction/src/plan/action/swap.rs

Make fee_blinding private for Swaps

---

crypto/src/value.rs

Support parsing values with asset IDs as well as denoms

---

component/src/dex/stub_cpmm.rs

Fix AMM calculation to incorporate return flow, add test

---

pd/src/main.rs

Implement --moniker flag for testnet join command

---

wallet/src/plan.rs
wallet/src/plan/planner.rs

Use the planner for constructing Swap/SwapClaim transactions

---

view/src/storage.rs

Improve note detection error messages in storage

---

crypto/src/address.rs
docs/protocol/src/protocol/addresses_keys/addresses.md

crypto: `Address` short form

---

crypto/src/proofs.rs
crypto/src/proofs/transparent.rs
crypto/src/proofs/transparent_gadgets.rs

crypto: refactor transparent proof statements into gadgets

---

Cargo.lock
testnets/tm_config_template.toml

update default config template with 0.34

---

Cargo.lock
storage2/src/lib.rs
storage2/src/metrics.rs
storage2/src/state.rs
storage2/src/state/transaction.rs
storage2/src/storage.rs

Add stub impls for Storage2 crate

---

crypto/src/proofs/transparent.rs
proto/proto/penumbra/core/transparent_proofs/v1alpha1/transparent_proofs.proto
proto/src/gen/penumbra.core.transparent_proofs.v1alpha1.rs
transaction/src/plan/action/swap_claim.rs

Use pro-rata output in constructing SwapClaimProof

---

storage2/src/lib.rs
storage2/src/metrics.rs
storage2/src/state.rs
storage2/src/state/read.rs
storage2/src/state/transaction.rs
storage2/src/state/write.rs
storage2/src/storage.rs

Incorporates @hdevalence feedback on #1495 
Closes #1489

Storage stubs continued

---

proto/proto/penumbra/core/transaction/v1alpha1/transaction.proto
proto/src/gen/penumbra.core.transaction.v1alpha1.rs
transaction/src/action.rs
transaction/src/action/delegate.rs
transaction/src/action/ibc.rs
transaction/src/action/output.rs
transaction/src/action/position.rs
transaction/src/action/propose.rs
transaction/src/action/spend.rs
transaction/src/action/swap.rs
transaction/src/action/swap_claim.rs
transaction/src/action/undelegate.rs
transaction/src/action/vote.rs
transaction/src/transaction.rs
transaction/src/view.rs
transaction/src/view/action_view.rs
transaction/src/view/action_view/output_view.rs
transaction/src/view/action_view/spend_view.rs
transaction/src/view/action_view/swap_claim_view.rs
transaction/src/view/action_view/swap_view.rs

Refactor view_from_perspective to infallibly return an ActionView

---

docs/protocol/src/SUMMARY.md
docs/protocol/src/crypto/fmd.md
docs/protocol/src/crypto/fmd/threat_model.md

spec(fmd): threat model

---

pcli/src/main.rs

This fixes https://github.com/penumbra-zone/penumbra/issues/1516, thanks to @plaidfinch for walking me through my first PR!

Added call to ensure that the opt.data_dir exists before pcli runs

---

pcli/tests/network_integration.rs
scripts/docker_compose_freshstart.sh

Attempt at a regression test for #1507 (downside of doing this through the smoke tests is that it will be slow)

test: note commitment bug regression

---

view/sqlx-data.json
view/src/storage.rs

Duplicate note commitment fix

---

component/src/governance/component.rs
component/src/governance/view.rs

Initialize unfinished_proposals during init_chain to prevent TOFU crash

---

docs/protocol/src/SUMMARY.md
docs/protocol/src/crypto/fmd.md
docs/protocol/src/crypto/fmd/system_mapping.md

spec(fmd): describe how FMD maps to Penumbra

---

storage2/src/snapshot.rs
storage2/src/state.rs
storage2/src/state/read.rs
storage2/src/state/transaction.rs
storage2/src/state/write.rs
storage2/src/storage.rs

This implements some missing default trait implementations, and implements the storage of all JMT key preimages to RocksDB.

#1491: Wrap up initial Storage V3 implementation

---

.github/workflows/notes.yml

temp: specify jmt 0.2.0 to fix docs build

---

pcli/tests/network_integration.rs

test(integration): fix flaky undelegation

---

component/src/app/mod.rs
storage2/src/snapshot.rs
storage2/src/state.rs
storage2/src/state/read.rs
storage2/src/state/transaction.rs
storage2/src/state/write.rs
storage2/src/storage.rs

I'm not sure about the handling of the `RwLock` + `Arc` in `storage::Inner`

Asyncify storage code

---

crypto/src/asset/amount.rs
crypto/src/symmetric.rs
pcli/src/command/view/tx.rs
proto/proto/penumbra/core/crypto/v1alpha1/crypto.proto
proto/proto/penumbra/core/transaction/v1alpha1/transaction.proto
proto/src/gen/penumbra.core.crypto.v1alpha1.rs
proto/src/gen/penumbra.core.transaction.v1alpha1.rs
tools/proto-compiler/src/main.rs
transaction/src/action/output.rs
transaction/src/action/swap_claim.rs
transaction/src/transaction.rs
transaction/src/view.rs
transaction/src/view/action_view.rs
transaction/src/view/action_view/output_view.rs
transaction/src/view/action_view/spend_view.rs
transaction/src/view/action_view/swap_claim_view.rs
transaction/src/view/action_view/swap_view.rs

Most of this work consisted of connecting the proto and domain types.

Add a `--raw` option to `pcli view tx`

---

pcli/src/command/view/balance.rs
pcli/src/opt.rs

This fixes https://github.com/penumbra-zone/penumbra/issues/1393
While implementing this, I attempted to refactor this command's code to reduce duplication. I normalized the row representations into a single type and then moved the table generation to the end of the function. This required  unwrapping the value in the `Addr Index` column if the `--by-address` flag is set as the notes generated for `pcli view balance` don't have any address information. End users should never see the except case on `pcli/src/command/view/balance.rs:171`.
Other than those improvements, the code is still a bit of a mess. The fundamental problem is that `pcli view balance` is manually implementing a  `SELECT SUM(note.amount) GROUP BY asset` query on the note data. `pcli view balance` needs just the list by …

 Rework pcli view balance code to hide and combine ephemeral addresses

---

component/src/ibc/component.rs
component/src/ibc/component/channel.rs
component/src/ibc/component/channel/stateful/mod.rs
component/src/ibc/component/state_key.rs
component/src/ibc/mod.rs
component/src/ibc/packet.rs
component/src/ibc/transfer.rs
crypto/src/asset/amount.rs
crypto/src/asset/denom.rs
proto/proto/penumbra/core/ibc/v1alpha1/ibc.proto
proto/src/gen/penumbra.core.ibc.v1alpha1.rs
transaction/src/action/ibc.rs
transaction/src/auth_hash.rs

this PR implements ICS20 withdrawals, allowing us to commit withdrawal packets to penumbra's state.
Closes #985

ICS20 withdrawal implementation

---

component/src/dex/component.rs
component/src/shielded_pool/component.rs
component/src/stake/component.rs
storage/src/snapshot.rs
storage/src/state.rs
storage/src/state/read.rs
storage/src/state/transaction.rs
storage/src/state/write.rs
storage/tests/basic.rs
view/src/lib.rs

Rename storage trait methods

---

Cargo.lock
chain/Cargo.toml
chain/src/app_hash.rs
component/Cargo.toml
crypto/Cargo.toml
pcli/Cargo.toml
pd/Cargo.toml
storage/src/lib.rs
storage/src/state.rs
storage/src/storage.rs
view/src/storage/nct.rs

Re-export JMT imports from storage crate and remove JMT dependencies elsewhere

---

pd/src/info.rs

re-enable ABCI query using new apphash API

---

tct/src/proof.rs
view/src/client.rs
wallet/src/build.rs

Closes https://github.com/penumbra-zone/penumbra/issues/1555

client: change ViewTransaction::witness() to take TransactionPlan

---

Cargo.lock
decaf377-fmd/Cargo.toml
decaf377-fmd/src/clue_key.rs
decaf377-fmd/src/detection.rs

This is good to do and might fix some recent issues with dependency resolution.

decaf377: upgrade to bitvec 1.0

---

component/src/shielded_pool/component.rs
crypto/src/dex/lp/nft.rs
crypto/src/dex/lp/position.rs
crypto/src/dex/lp/trading_function.rs
proto/proto/penumbra/core/dex/v1alpha1/dex.proto
proto/src/gen/penumbra.core.dex.v1alpha1.rs
transaction/src/action/swap_claim.rs

Based on discussions with @zbuc and @erwanor this morning (notes to come)

Revise LP data

---

pcli/tests/network_integration.rs

Towards #1210. Adds the first of two tests required by that ticket. Currently passing smoke tests, so considering ready for review. I'll follow up separately with another test, at which point we can consider 1210 complete.

test: uploading duplicate consensus key fails

---

pcli/tests/network_integration.rs

Builds on #1631 and closes #1210. The new test confirms that trying to update a validator with a mismatched consensus key fails. Ideally we'd create a new validator identity from scratch in this test, but instead I'm reusing the validator created in the previous test. This is suitable for how we execute the smoketest suite, but does assume strict ordering of the tests. At some point in the future, we may wish to generate multiple wallets (and therefore multiple validator identities), but for now, this is Progress™.

test: validator malformed definition update fails

---

Cargo.lock
custody/Cargo.toml
custody/src/lib.rs
custody/src/pre_auth.rs
custody/src/request.rs
custody/src/soft_kms.rs
pcli/src/opt.rs
proto/proto/penumbra/custody/v1alpha1/custody.proto
proto/src/gen/penumbra.custody.v1alpha1.rs
wallet/src/build.rs

Add optional pre-authorizations to custody protocol

---

Cargo.lock
chain/src/genesis/app_state.rs
chain/src/lib.rs
component/Cargo.toml
component/src/action_handler/transaction.rs
component/src/dex/mod.rs
component/src/dex/tests.rs
component/src/lib.rs
component/src/mock_client.rs
component/src/shielded_pool/component.rs
crypto/src/dex/swap.rs
crypto/src/dex/swap/plaintext.rs
crypto/src/note.rs
crypto/src/proofs/transparent.rs
crypto/src/proofs/transparent_gadgets.rs
crypto/src/value.rs
pcli/tests/network_integration.rs
proto/proto/penumbra/core/dex/v1alpha1/dex.proto
proto/proto/penumbra/core/transaction/v1alpha1/transaction.proto
proto/proto/penumbra/core/transparent_proofs/v1alpha1/transparent_proofs.proto
proto/src/gen/penumbra.core.dex.v1alpha1.rs
proto/src/gen/penumbra.core.transaction.v1alpha1.rs
proto/src/gen/penumbra.core.transparent_proofs.v1alpha1.rs
storage/src/state/read.rs
transaction/src/auth_hash.rs
transaction/src/plan/action/swap.rs
transaction/src/plan/action/swap_claim.rs
transaction/src/transaction.rs
wallet/src/plan/planner.rs

Add blinding factor to Swap plaintext

---

Cargo.lock
proto/proto/penumbra/view/v1alpha1/view.proto
proto/src/gen/penumbra.view.v1alpha1.rs
view/src/client.rs
view/src/service.rs
wallet/src/build.rs

Move the transaction plan into the WitnessRequest & corresponding logic into the View service

---

Cargo.lock
chain/Cargo.toml

Hopefully resolves https://github.com/penumbra-zone/penumbra/actions/runs/3623725129/jobs/6109914575

deps: deduplicate jmt git dependencies

---

docs/guide/src/pcli/install.md
docs/guide/src/pcli/update.md

Part of https://github.com/penumbra-zone/penumbra/issues/1699

docs: update testnet tag to 037-megaclite

---

component/src/stake/component.rs

The implementation was changed here:
https://github.com/penumbra-zone/penumbra/commit/03de128b249e7b3f2e5913c870f5cc5bdcb42755#diff-6e0042a0b016aaac378df25ae205439acf4f2e438704798a9870337b3ba35f25L1023-R1029
This implementation only calls `next()` on the _stream_ once, and then iterates over "maybe the first value of the stream", and maps that iterator into the desired shape, so while it typechecks, it only ever returns the first validator in the list. Instead, we want to use the `TryStreamExt` methods to map on the _stream_, and then `try_collect` the whole thing.
Testing this locally shows that it fixes the bug causing the chain halt on `037-megaclite`.
This bug isn't particularly interesting, which is in a way reassuring -- it's not a subtle logic error, instead it's the kind of thing …

stake: fix bug in `validator_list()`

---

crypto/src/dex.rs
crypto/src/dex/swap.rs
crypto/src/dex/swap/plaintext.rs
crypto/src/proofs/transparent.rs
crypto/src/value.rs
proto/proto/penumbra/client/v1alpha1/client.proto
proto/proto/penumbra/core/crypto/v1alpha1/crypto.proto
proto/proto/penumbra/core/transaction/v1alpha1/transaction.proto
proto/proto/penumbra/view/v1alpha1/view.proto
proto/src/gen/penumbra.client.v1alpha1.rs
proto/src/gen/penumbra.core.crypto.v1alpha1.rs
proto/src/gen/penumbra.core.transaction.v1alpha1.rs
proto/src/gen/penumbra.view.v1alpha1.rs
tct/src/commitment.rs
tools/proto-compiler/src/main.rs
transaction/src/plan/action/swap.rs

Closes #1715 (required for #1712)

refactor: add `swap_commitment` method and use inner value as asset ID

---

Cargo.lock
pcli/src/network.rs
pd/src/main.rs
pd/src/tendermint_proxy.rs
proto/proto/penumbra/client/v1alpha1/client.proto
proto/src/gen/penumbra.client.v1alpha1.rs
proto/src/gen/tendermint.crypto.rs
view/src/worker.rs

Combine proxy gRPC services

---

component/src/ibc/component/connection/execution.rs
component/src/ibc/component/connection/stateful.rs

component(ibc): remove deprecated `prev_connection` logic

---

docs/guide/src/pcli/install.md
docs/guide/src/pcli/update.md

Towards https://github.com/penumbra-zone/penumbra/issues/1743

docs: update guide to 038-kalyke

---

crypto/src/proofs/groth16.rs

test: convert groth16 proof unit tests to proptests

---

proto/proto/penumbra/core/dex/v1alpha1/dex.proto
proto/proto/penumbra/core/transaction/v1alpha1/transaction.proto
proto/src/gen/penumbra.core.dex.v1alpha1.rs
proto/src/gen/penumbra.core.transaction.v1alpha1.rs
transaction/src/view/action_view.rs
transaction/src/view/action_view/output_view.rs
transaction/src/view/action_view/spend_view.rs
transaction/src/view/action_view/swap_claim_view.rs
transaction/src/view/action_view/swap_view.rs

Align ActionView proto types with ActionView domain types

---

proto/proto/penumbra/view/v1alpha1/view.proto
proto/src/gen/penumbra.view.v1alpha1.rs

Add PlannerRequest message proto

---

Cargo.lock
proto/proto/penumbra/core/crypto/v1alpha1/crypto.proto
proto/proto/penumbra/core/governance/v1alpha1/governance.proto
proto/proto/penumbra/core/transaction/v1alpha1/transaction.proto
proto/src/gen/penumbra.core.crypto.v1alpha1.rs
proto/src/gen/penumbra.core.governance.v1alpha1.rs
proto/src/gen/penumbra.core.transaction.v1alpha1.rs
tools/proto-compiler/src/main.rs
transaction/Cargo.toml
transaction/src/action/propose.rs
transaction/src/effect_hash.rs

Governance proto refactor: use `Any` for indirection

---

Cargo.lock
crypto/Cargo.toml
tct/Cargo.toml
transaction/Cargo.toml

deps: pin poseidon377 to a specific rev

---

proto/proto/penumbra/view/v1alpha1/view.proto
proto/src/gen/penumbra.view.v1alpha1.rs
view/sqlx-data.json
view/src/client.rs
view/src/service.rs
view/src/storage.rs

Add function to view storage to return account balance by address

---

crypto/src/proofs/groth16.rs

I just noticed while testing https://github.com/penumbra-zone/decaf377/pull/42 against latest penumbra that one test (`spend_proof_verification_diversified_address_integrity_failure`) had inconsistent behavior in debug and release mode: in release mode the test passed (hence CI was green), but in debug mode the test panicked, due to a [debug assertion in ark-groth16](https://github.com/arkworks-rs/groth16/blob/master/src/prover.rs#L253) that checks the constraint system is satisfied. This PR modifies the test to check the constraint system is unsatisfied, as it cannot be if the diversified address is incorrect at proving time (the case for the test in question).

test: ensure consistent behavior in debug and release mode

---

crypto/src/dex.rs
crypto/src/dex/fixed_encoding.rs
crypto/src/dex/lp/trading_function.rs

Preliminary work for the keys to be used in #1778

Implement big-endian fixed point encoding

---

component/src/dex/mod.rs
component/src/dex/position_manager.rs
component/src/dex/state_key.rs
component/src/shielded_pool/state_key.rs
crypto/src/dex/lp/trading_function.rs
crypto/src/dex/trading_pair.rs

First pass at dex LP state keys

---

crypto/src/keys/fvk.rs
crypto/src/keys/ivk.rs
proto/proto/penumbra/view/v1alpha1/view.proto
proto/src/gen/penumbra.view.v1alpha1.rs
view/src/service.rs

view: add rpcs to retrieve ephemeral address, address by index, and index by address

---

proto/proto/penumbra/view/v1alpha1/view.proto
proto/src/gen/penumbra.view.v1alpha1.rs
view/src/service.rs

view: add transaction_planner function to view service

---

crypto/src/dex/swap.rs
crypto/src/dex/swap/ciphertext.rs
crypto/src/dex/swap/payload.rs
crypto/src/dex/swap/plaintext.rs
crypto/src/symmetric.rs
docs/protocol/src/protocol/transaction_crypto.md
proto/proto/penumbra/core/dex/v1alpha1/dex.proto
proto/src/gen/penumbra.core.dex.v1alpha1.rs
proto/src/gen/penumbra.core.dex.v1alpha1.serde.rs
transaction/src/action/swap.rs
transaction/src/effect_hash.rs
transaction/src/plan/action/swap.rs
transaction/src/transaction.rs

crypto: encrypt swaps using a symmetric key derived from the `OutgoingViewingKey`

---

component/src/stake/component.rs

This uses the changes to StateRead introduced in #1940 to concurrently fetch all data required for performing validator uptime tracking.  Note that we're not actually processing the _updates_ concurrently, because that would require mediating access to our shared mutable data.  Instead, we just concurrently fetch all of the data we'll need to process those updates, and then do the updates sequentially.

staking: optimize validator uptime tracking

---

Cargo.lock
pcli/Cargo.toml
pd/Cargo.toml
view/Cargo.toml

build: fix pd build by pinning tokio-util

---

Cargo.lock
transaction/Cargo.toml
transaction/src/effect_hash.rs
transaction/src/plan/build.rs
wallet/src/build.rs

Needed for #1923, will close #717

perf: concurrent proving

---

transaction/Cargo.toml
transaction/src/plan/build.rs
wallet/Cargo.toml

Followup to #1970 
See [this Discord discussion](https://discord.com/channels/824484045370818580/979785365437165658/1075021011809992784)

make `tokio` an optional dependency of `penumbra-transaction`

---

component/src/action_handler/transaction/stateless.rs
transaction/src/plan/build.rs

crypto: compute binding signature over the entire tx body

---

component/src/dex/position_manager.rs
crypto/src/dex/lp/position.rs
crypto/src/dex/lp/reserves.rs
transaction/src/action.rs
transaction/src/action/position.rs

dex: bound LP positions to at most 112 bits

---

chain/src/sync/state_payload.rs
component/src/shielded_pool/note_manager.rs
crypto/src/lib.rs
crypto/src/note.rs
crypto/src/note_payload.rs
proto/proto/penumbra/core/chain/v1alpha1/chain.proto
proto/proto/penumbra/core/crypto/v1alpha1/crypto.proto
proto/proto/penumbra/core/transaction/v1alpha1/transaction.proto
proto/src/gen/penumbra.core.chain.v1alpha1.rs
proto/src/gen/penumbra.core.crypto.v1alpha1.rs
proto/src/gen/penumbra.core.crypto.v1alpha1.serde.rs
proto/src/gen/penumbra.core.transaction.v1alpha1.rs
tools/proto-compiler/src/main.rs
transaction/src/action/output.rs
transaction/src/effect_hash.rs
transaction/src/plan/action/output.rs
view/src/sync.rs

refactor: clean up `penumbra-crypto` note API

---

crypto/src/address.rs
crypto/src/dex/swap/plaintext.rs
crypto/src/keys/diversifier.rs
crypto/src/keys/fvk.rs
crypto/src/keys/ivk.rs
crypto/src/memo.rs
crypto/src/note.rs
crypto/src/proofs/groth16.rs
crypto/src/proofs/groth16/spend.rs
crypto/src/proofs/transparent.rs
pcli/src/command/tx.rs
pcli/src/command/tx/proposal.rs
pcli/src/command/validator.rs
pcli/src/command/view/address.rs
pcli/src/command/view/tx.rs
pd/src/testnet/generate.rs
proof-params/src/lib.rs
proto/proto/buf.lock
proto/proto/penumbra/core/transaction/v1alpha1/transaction.proto
proto/proto/penumbra/view/v1alpha1/view.proto
proto/src/gen/penumbra.core.transaction.v1alpha1.rs
proto/src/gen/penumbra.core.transaction.v1alpha1.serde.rs
proto/src/gen/penumbra.view.v1alpha1.rs
proto/src/gen/penumbra.view.v1alpha1.serde.rs
transaction/src/effect_hash.rs
transaction/src/view/action_view/address_view.rs
view/src/service.rs
wallet/src/plan.rs
wallet/src/plan/planner.rs

Refactor to support account groups

---

Cargo.lock
crypto/Cargo.toml
crypto/src/asset/amount.rs
crypto/src/fixpoint.rs
crypto/src/fixpoint/div.rs
crypto/src/fixpoint/from.rs
crypto/src/fixpoint/ops.rs
crypto/src/fixpoint/tests.rs
crypto/src/lib.rs

Add 128x128-bit fixed-point arithmetic.

---

view/src/bin/pclientd.rs

Add --home argument to specify home directory for pclientd

---

chain/src/sync.rs
chain/src/sync/state_payload.rs
component/src/app/mod.rs
component/src/shielded_pool/note_manager.rs
crypto/src/proofs/groth16/output.rs
crypto/src/proofs/groth16/spend.rs
pd/src/mempool/service.rs

Improves debug output for `pd` in various small ways

pd(debug): improve debug output

---

pcli/src/command/tx.rs
pcli/src/command/tx/proposal.rs
pcli/src/command/validator.rs
pcli/src/command/view/balance.rs
view/src/storage.rs

Two changes of note:
- we didn't update the `view balance` output to reflect accounts
- we were not correctly filtering notes by account

Fix account handling bugs in `pcli`

---

pcli/src/command/tx.rs
pcli/src/command/tx/proposal.rs
pcli/src/command/validator.rs
pcli/src/command/view/balance.rs
pcli/tests/network_integration.rs
view/src/storage.rs

Workflow outage yesterday induced some doubt - let's get this passing for sure

pcli account fix - CI confirmation

---

crypto/src/address.rs
crypto/src/memo.rs
pcli/src/command/tx.rs
pcli/src/command/view/tx.rs
proto/proto/penumbra/core/transaction/v1alpha1/transaction.proto
proto/src/gen/penumbra.core.transaction.v1alpha1.rs
proto/src/gen/penumbra.core.transaction.v1alpha1.serde.rs
transaction/src/effect_hash.rs
transaction/src/plan/memo.rs
transaction/src/transaction.rs
transaction/src/view.rs
wallet/src/plan.rs
wallet/src/plan/planner.rs

use MemoPlaintext structured data instead of String for memos

---

pcli/src/command/view/tx.rs

Fix hash parsing in `pcli tx view`

---

crypto/src/keys/fvk.rs
pcli/src/command/query/chain.rs
pcli/src/command/tx.rs
pcli/src/command/validator.rs
pcli/src/command/view/balance.rs
pcli/src/command/view/staked.rs
pcli/src/main.rs
view/src/client.rs
view/src/service.rs
wallet/src/build.rs
wallet/src/plan.rs
wallet/src/plan/planner.rs

swap FVK in planner for AccountID

---

component/src/action_handler/actions/spend.rs

Earlier while debugging another issue, I had a concern that there was an issue with multiple spends, so this PR adds a second spend to one of the spend state machine tests.

test: state machine test coverage for a tx with multiple spends

---

view/src/storage.rs

client: add awaiting detection of swaps to view server

---

pcli/src/command/view/address.rs
proto/proto/buf.lock

pcli: extend functionality of `pcli view address` to include account refactor

---

crypto/src/symmetric.rs
proto/proto/penumbra/core/transaction/v1alpha1/transaction.proto
proto/src/gen/penumbra.core.transaction.v1alpha1.rs
proto/src/gen/penumbra.core.transaction.v1alpha1.serde.rs
transaction/src/view/action_view/output_view.rs
transaction/src/view/transaction_perspective.rs

Add PayloadKey proto type

---

component/src/action_handler/actions/proposal/submit.rs
crypto/src/symmetric.rs
transaction/src/effect_hash.rs
transaction/src/plan/build.rs
transaction/src/transaction.rs
view/src/service.rs

add authorize function to transaction build to allow concurrent proving and authorization

---

proto/proto/buf.lock
proto/proto/penumbra/narsil/ledger/v1alpha1/ledger.proto
proto/src/gen/penumbra.narsil.ledger.v1alpha1.rs
tools/proto-compiler/src/main.rs

The only part of the basic data flow we didn't specify already is the DKG data; which this PR (will) add.

Add DKG data to Narsil protos

---

component/src/dex/position_manager.rs
component/src/dex/state_key.rs

component(dex): use composite key to index prices

---

component/src/stubdex/component.rs
component/src/stubdex/stub_cpmm.rs
crypto/src/asset/amount.rs
crypto/src/dex/swap.rs
crypto/src/flow.rs
crypto/src/proofs/transparent.rs
pcli/src/command/query/dex.rs
pcli/src/command/tx.rs
proto/proto/penumbra/core/dex/v1alpha1/dex.proto
proto/proto/penumbra/core/transparent_proofs/v1alpha1/transparent_proofs.proto
proto/src/gen/penumbra.core.dex.v1alpha1.rs
proto/src/gen/penumbra.core.dex.v1alpha1.serde.rs
proto/src/gen/penumbra.core.transparent_proofs.v1alpha1.rs

#2157: Change semantics of BatchSwapOutputData

---

component/src/dex/position_manager.rs

component(dex): implement `PositionRead::positions_by_price stream`

---

crypto/src/memo.rs
pcli/src/command/view/tx.rs
proto/proto/penumbra/core/transaction/v1alpha1/transaction.proto
proto/src/gen/penumbra.core.transaction.v1alpha1.rs
proto/src/gen/penumbra.core.transaction.v1alpha1.serde.rs
transaction/src/lib.rs
transaction/src/plan/memo.rs
transaction/src/transaction.rs
transaction/src/view.rs
transaction/src/view/action_view.rs
transaction/src/view/action_view/delegator_vote_view.rs
transaction/src/view/action_view/output_view.rs
transaction/src/view/action_view/spend_view.rs
transaction/src/view/action_view/swap_claim_view.rs
transaction/src/view/action_view/swap_view.rs

Add TransactionView::transaction() to retrieve the original Transaction from the TransactionView

---

view/src/storage.rs

Add check to avoid inserting zero-valued notes in give_advice

---

crypto/src/lib.rs
crypto/src/note.rs
crypto/src/value.rs
pcli/src/command/view/tx.rs
proto/proto/penumbra/core/crypto/v1alpha1/crypto.proto
proto/proto/penumbra/core/dex/v1alpha1/dex.proto
proto/proto/penumbra/core/transaction/v1alpha1/transaction.proto
proto/src/gen/penumbra.core.crypto.v1alpha1.rs
proto/src/gen/penumbra.core.crypto.v1alpha1.serde.rs
proto/src/gen/penumbra.core.dex.v1alpha1.rs
proto/src/gen/penumbra.core.transaction.v1alpha1.rs
proto/src/gen/penumbra.core.transaction.v1alpha1.serde.rs
transaction/src/action/delegator_vote.rs
transaction/src/action/output.rs
transaction/src/action/spend.rs
transaction/src/action/swap_claim.rs
transaction/src/transaction.rs
transaction/src/view.rs
transaction/src/view/action_view/delegator_vote_view.rs
transaction/src/view/action_view/output_view.rs
transaction/src/view/action_view/spend_view.rs
transaction/src/view/action_view/swap_claim_view.rs
transaction/src/view/transaction_perspective.rs
view/src/service.rs

The goal is to be able to display structured information about note contents (in particular, to be able to show information about denoms and addresses).  This new information isn't used by `pcli`, which already had access to it (by having direct view server and FVK access), but is visible in JSON output, as here:
<details>
<summary>TxV JSON</summary>
```json
{
"bodyView": {
"actionViews": [
{
"spend": {
"visible": {
"spend": {
"body": {
"balanceCommitment": {
"inner": "bOPxkNX7m41kqV+n3uYO3V02wRB9TrWpAwjeSq2HtQo="
},
"nullifier": "t1bIxH7JAvwFLGrcLS2sXoVH289yjaK3hqhhnc0BOAY=",
"rk": "fCpGU9Rjgnw4XgJTOKKOG+hyIesN8C2gQVYY7jHpJwY="
},
"authSig": {
"inner": "ktByagYzITt+/5Vxj3rsLISn/L2mIQpz/3OIji8iSQheZBdC4I+UThi3+2RWmnqX3eqLzoqtfH0Bt15PKGsIAQ=="
},
"proof": {
"inner": …
```

Add `NoteView`, `ValueView`

---

chain/src/sync/state_payload.rs
component/src/app/mod.rs
component/src/mock_client.rs
proto/proto/penumbra/core/chain/v1alpha1/chain.proto
proto/src/gen/penumbra.core.chain.v1alpha1.rs
proto/src/gen/penumbra.core.chain.v1alpha1.serde.rs
view/src/sync.rs
wasm/src/mock_client.rs

Remove StatePayload::Position

---

component/src/action_handler/actions/spend.rs
transaction/src/plan/build.rs
wallet/src/build.rs

Update build_concurrent() to return an UnauthTransaction

---

pcli/src/command/view/address.rs

Change pcli view address to not include additional information in address output, for composability

---

component/src/action_handler/actions/position/open.rs
crypto/src/dex/lp/position.rs
crypto/src/dex/lp/reserves.rs
crypto/src/dex/lp/trading_function.rs

Close #2203 and refactored some of the dex component stateless checks

dex: limit `fee` to 5000 bps and refactor

---

component/src/dex/position_manager.rs
component/src/dex/tests.rs

component(dex): implement execution against multiple positions

---

Cargo.lock
component/src/action_handler/actions/ibc_action/msg/acknowledgement.rs
component/src/action_handler/actions/ibc_action/msg/channel_close_confirm.rs
component/src/action_handler/actions/ibc_action/msg/channel_close_init.rs
component/src/action_handler/actions/ibc_action/msg/channel_open_ack.rs
component/src/action_handler/actions/ibc_action/msg/channel_open_confirm.rs
component/src/action_handler/actions/ibc_action/msg/channel_open_init.rs
component/src/action_handler/actions/ibc_action/msg/channel_open_try.rs
component/src/action_handler/actions/ibc_action/msg/connection_open_ack.rs
component/src/action_handler/actions/ibc_action/msg/connection_open_confirm.rs
component/src/action_handler/actions/ibc_action/msg/connection_open_init.rs
component/src/action_handler/actions/ibc_action/msg/connection_open_try.rs
component/src/action_handler/actions/ibc_action/msg/create_client.rs
component/src/action_handler/actions/ibc_action/msg/recv_packet.rs
component/src/action_handler/actions/ibc_action/msg/timeout.rs
component/src/action_handler/actions/ibc_action/msg/update_client.rs
component/src/ibc/component/connection/stateful.rs
pcli/Cargo.toml
pcli/src/command.rs
pcli/src/command/query.rs
pcli/src/command/query/ibc_query.rs

With these changes, the IBC implementation gets stuck on `ConnectionOpenAck`: https://gist.github.com/hdevalence/b9c7a8621ec9e5fbd07cf6f444c0f464

Additional IBC tracing + debugging

---

Cargo.lock
pd/Cargo.toml
pd/src/consensus/service.rs
pd/src/lib.rs
pd/src/main.rs
pd/src/mempool/service.rs
pd/src/trace/mod.rs
pd/src/trace/request_span.rs
pd/src/trace/service_span.rs

This crate is really useful, but it's unpublished, and we'd like to avoid a git dependency. So let's vendor it for now, and then potentially work with upstream (cc @hawkw) to see if we could help get a version of the crate published.

pd: vendor unpublished `tracing-tower`

---

view/sqlx-data.json
view/src/storage.rs

Mark claimed swaps in view storage

---

pd/src/lib.rs
pd/src/main.rs

fix: raise pd recursion limit 256 -> 512

---

crypto/src/proofs/groth16.rs
crypto/src/proofs/groth16/spend.rs
tct/src/r1cs.rs

refactor: impl `AllocVar` for all TCT R1CS variables

---

pd/src/info.rs
proto/proto/buf.lock

This may be the cause of IBC issues.

pd: respond to queries with specified height

---

pcli/src/command/query/dex.rs
pcli/src/command/tx.rs
pcli/src/command/tx/liquidity_position.rs
pd/src/info/specific.rs
view/src/planner.rs

Support for `pcli tx position close`

---

deployments/scripts/smoke-test.sh

The recently refactored smoke test (#2094) was leaving a dangling `pd` process after exiting. Adjusted the process cleanup so that both tm and pd are killed, regardless of whether the tests pass or fail.

ci: smoke test process cleanup

---

view/src/service.rs

Add advice to TxP

---

narsil/src/bin/narsild.rs
pclientd/src/lib.rs
pd/src/main.rs

For testing on testnet-preview; see https://github.com/penumbra-zone/penumbra/issues/1887 for context.

deploy: experimentally disable http/1

---

.github/workflows/bluesky.yml

ci: post to bluesky on merge

---

.vscode/settings.json
app/Cargo.toml
proto/proto/buf.lock
transaction/Cargo.toml

Enable parallel flag for penumbra-transaction in VSCode

---

app/src/action_handler/actions/swap.rs

Add check in Swap::check_stateless to reject a swap from a denom into itself

---

Cargo.lock
app/Cargo.toml
app/src/action_handler/actions/position/open.rs
app/src/action_handler/actions/position/withdraw.rs
app/src/dex/mod.rs
app/src/dex/position_manager.rs
app/src/dex/router/mod.rs
app/src/dex/router/path.rs
app/src/dex/router/tests.rs
app/src/dex/state_key.rs
app/src/dex/tests.rs
crypto/src/dex/lp/nft.rs
crypto/src/dex/lp/position.rs
crypto/src/dex/lp/trading_function.rs
pcli/src/command/query/dex.rs
pcli/src/command/tx.rs
proto/proto/penumbra/client/v1alpha1/client.proto
proto/proto/penumbra/core/dex/v1alpha1/dex.proto
proto/src/gen/penumbra.client.v1alpha1.rs
proto/src/gen/penumbra.core.dex.v1alpha1.rs
proto/src/gen/penumbra.core.dex.v1alpha1.serde.rs
proto/src/gen/proto_descriptor.bin
transaction/src/action/position.rs
transaction/src/effect_hash.rs
view/src/planner.rs

Refactor: Remove `PositionMetadata`, initial path extension implementation

---

Cargo.lock
app/Cargo.toml
app/src/dex/router/mod.rs
app/src/dex/router/path_cache.rs

dex: implement a shared PathCache for Bellman-Ford

---

app/src/dex/router/mod.rs
app/src/dex/router/path.rs
app/src/dex/router/path_cache.rs
app/src/dex/router/path_search.rs
app/src/dex/router/tests.rs

Implement a `PathSearch` trait

---

Cargo.lock
narsil/Cargo.toml
narsil/src/bin/narsild.rs
pclientd/Cargo.toml
pclientd/src/main.rs
pd/Cargo.toml
pd/src/main.rs

Closes #2314
(I haven't tested that this does the desired behavior)

pd,pclientd,narsild: auto-color log output

---

deployments/containerfiles/Dockerfile

build: fix dns in container image

---

app/src/dex/position_manager.rs
app/src/dex/router/path_search.rs
app/src/dex/state_key.rs
app/src/dex/tests.rs
crypto/src/dex/lp/position.rs
narsil/src/ledger/app.rs
pcli/src/command/tx.rs
transaction/src/action/position.rs

Implement candidate_set to find routing candidates based on available position liquidity

---

docs/protocol/src/SUMMARY.md
docs/protocol/src/protocol/action_descriptions/delegator_vote.md
docs/protocol/src/protocol/action_descriptions/spend.md

Adding more docs towards #1825

spec: add description of delegator vote zk-SNARK statements

---

view/src/service.rs

Stop calling scan_advice in transaction_perspective() in favor of querying for notes directly

---

proto/proto/buf.lock
view/src/storage.rs

Add record_note_inner function to view storage

---

view/src/storage.rs

add comment to scan_advice explaining query intent

---

app/src/app/mod.rs
app/src/dex/component.rs
app/src/governance/component.rs
app/src/ibc/component.rs
app/src/ibc/transfer.rs
app/src/lib.rs
app/src/shielded_pool/component.rs
app/src/stake/component.rs
app/src/stubdex/component.rs
app/src/stubdex/tests.rs
storage/src/cache.rs
storage/src/delta.rs
storage/src/lib.rs

the thing we are contemplating is: can you rewrite a rwlock mechanic with `Option` and `Arc` without losing sanity?

state of contemplation

---

Cargo.lock
crypto/Cargo.toml
tct/Cargo.toml
transaction/Cargo.toml

Another item towards https://github.com/penumbra-zone/penumbra/issues/2004

chore: use poseidon377 0.3.0 release from crates.io

---

Cargo.lock
crypto/Cargo.toml
proto/Cargo.toml
transaction/Cargo.toml

Towards https://github.com/penumbra-zone/penumbra/issues/2004

use published versions of `decaf377-rdsa` and `frost377`

---

view/src/worker.rs

Implement pre-caching of LPNFT assets in the view client as well as filtering of already known assets

---

app/src/app/mod.rs
app/src/dex/component.rs
app/src/governance/component.rs
app/src/ibc/component.rs
app/src/lib.rs
app/src/shielded_pool/component.rs
app/src/stake/component.rs
app/src/stubdex/component.rs

part of #2288
later, it'd be cool to have each component define its own isolated state and have the penumbra-chain crate stitch them together

app: make genesis state an associated type of Component

---

.github/workflows/buf-pull-request.yml

ci: enable buf breaking change detection

---

docs/protocol/src/SUMMARY.md
docs/protocol/src/protocol/action_descriptions/swap.md

Another page of protocol docs towards #1825

spec: add description of swap zk-SNARK statements

---

.gitignore
wasm/src/view_server.rs

Add transaction_info function for generating txv and txp to wasm crate

---

crypto/src/stake/penalty.rs
docs/protocol/src/SUMMARY.md
docs/protocol/src/protocol/action_descriptions/undelegate_claim.md

Another page of protocol docs towards #1825

spec: add description of undelegate claim zk-SNARK statements

---

docs/guide/src/dev/protobuf.md

Jotted down some notes based on current best understanding for how we maintain the protos in our repo.

docs: update protobuf maintenance workflows

---

pcli/src/command/view/tx.rs

Display basic position information in pcli v tx

---

Cargo.lock
crates/ibc/src/component.rs
deployments/relayer/configs/penumbra-preview.json
deployments/scripts/relayer-local-devnet
pd/Cargo.toml
pd/src/info.rs

ibc: implement required grpc proxied relayer queries

---

Cargo.lock
crates/ibc/src/component.rs
deployments/relayer/configs/penumbra-preview.json
pd/src/info.rs

should be the last step towards #2330

ibc: add ClientStates query

---

view/src/storage.rs

view: increase buffer size for detection

---

docs/guide/src/pcli/transaction.md

Document dex LP management in guide

---

pcli/src/command/tx/liquidity_position.rs

Block creation of cyclic orders in client

---

docs/guide/src/pcli/transaction.md
pcli/tests/network_integration.rs

Implement smoketest for liquidity position lifecycle

---

app/src/dex/router/fill_route.rs

router(dex): burn dust during routing execution

---

crypto/src/dex/lp/reserves.rs
crypto/src/dex/trading_pair.rs
crypto/src/fixpoint.rs
crypto/src/fixpoint/from.rs
pcli/src/command/query/dex.rs
pd/src/info/specific.rs
proto/proto/penumbra/client/v1alpha1/client.proto
proto/src/gen/penumbra.client.v1alpha1.rs
proto/src/gen/penumbra.client.v1alpha1.serde.rs
proto/src/gen/proto_descriptor.bin

This allows querying what positions are available on the chain by price and pair.

dex: fill in position-by-price RPCs

---

app/src/dex/router/tests.rs

The tests are intentionally lax for now, because I'm locally testing with aggressive panics.

dex(router): tests three levels of dust fills

---

proto/proto/penumbra/core/transaction/v1alpha1/transaction.proto
proto/src/gen/penumbra.core.transaction.v1alpha1.rs
proto/src/gen/penumbra.core.transaction.v1alpha1.serde.rs
proto/src/gen/proto_descriptor.bin
transaction/src/id.rs
transaction/src/view/transaction_perspective.rs

Add transaction ID to transaction perspectives

---

view/src/storage.rs

Co-authored-by: plaidfinch <finch@penumbralabs.xyz>
Co-authored-by: conorsch <conor@penumbralabs.xyz>

Fix bug with in-memory database pooling by limiting number of connections to 1

---

app/src/dex/router/tests.rs
app/src/dex/tests.rs
crypto/src/dex.rs
crypto/src/dex/trading_pair.rs
crypto/src/fixpoint.rs
crypto/src/fixpoint/from.rs
pcli/src/command/tx.rs
pcli/src/command/tx/approximate.rs
pcli/src/command/tx/liquidity_position.rs
pcli/src/command/view.rs
pcli/src/dex_utils/approximate.rs

dex_utils: map individual payoffs to `Position`s

---

crypto/src/address.rs
crypto/src/proofs/groth16/delegator_vote.rs
crypto/src/proofs/groth16/output.rs
crypto/src/proofs/groth16/spend.rs
crypto/src/proofs/groth16/swap.rs
crypto/src/proofs/groth16/undelegate.rs
proof-params/Cargo.toml
proof-params/benches/delegator_vote.rs
proof-params/benches/nullifier_derivation.rs
proof-params/benches/output.rs
proof-params/benches/spend.rs
proof-params/benches/swap.rs
proof-params/benches/undelegate_claim.rs
proto/proto/buf.lock

crypto: add benchmarks for all ZKPs

---

crypto/src/dex/lp.rs
crypto/src/dex/lp/order.rs
pcli/src/command/tx.rs
pcli/src/command/tx/liquidity_position.rs
pcli/tests/network_integration.rs

This results in sell orders with the expected `p`/`q`

Swap p/q for pcli order sell

---

crypto/src/asset/denom.rs
pcli/src/command/tx.rs
pcli/src/command/utils.rs
pcli/src/command/view/balance.rs
pcli/tests/network_integration.rs

Hide withdrawn LPNFTs from pcli view balance output

---

crates/ibc/src/component/transfer.rs

ics20: implement timeouts

---

pcli/src/command/tx/approximate.rs
pcli/src/command/utils.rs
pcli/src/dex_utils/approximate/xyk.rs
pcli/src/warning.rs
proto/proto/buf.lock

rmm: display a normal warning message to the user

---

.github/workflows/bluesky.yml

I think this version automatically includes facets (like links)

ci: update bluesky post action

---

app/src/dex/position_manager.rs
app/src/dex/tests.rs

Part of #2589, this PR removes `fill_against` and `fill`, and trim vestigial parts of the DEX engine that aren't used anymore.

app(dex): remove `fill_against` and `fill`

---

app/src/dex/router/fill_route.rs
app/src/dex/router/path.rs
crypto/src/dex/lp/order.rs
crypto/src/fixpoint.rs
crypto/src/fixpoint/from.rs
crypto/src/fixpoint/ops.rs
crypto/src/fixpoint/tests.rs
docs/protocol/src/zswap/replicating_market_makers.md
pcli/src/dex_utils/replicate/xyk.rs

fixpoint: change api to use `Result`s

---

crypto/src/proofs/groth16/delegator_vote.rs
crypto/src/proofs/groth16/nullifier_derivation.rs
crypto/src/proofs/groth16/output.rs
crypto/src/proofs/groth16/spend.rs
crypto/src/proofs/groth16/swap.rs
crypto/src/proofs/groth16/undelegate.rs

crypto: zk proof domain types now just store bytes

---

crypto/src/fixpoint.rs
crypto/src/fixpoint/div.rs
crypto/src/fixpoint/from.rs

Needed for #2151 for the pro rata output calculation

crypto: R1CS U128x128 implementation

---

app/src/dex/state_key.rs
pd/src/info/specific.rs
proto/proto/penumbra/client/v1alpha1/client.proto
proto/src/gen/penumbra.client.v1alpha1.rs
proto/src/gen/penumbra.client.v1alpha1.serde.rs
proto/src/gen/proto_descriptor.bin

These don't have an implementation yet; the first commit just defines a spec for some methods that seem useful.

dex: add additional RPC methods

---

crypto/src/asset/denom_metadata.rs
crypto/src/asset/id.rs
crypto/src/asset/registry.rs

This does further alignment with the CosmosSDK denom types.

Better parsing for `DenomMetadata`

---

crates/bin/pd/src/testnet.rs

pd: disable pprof_laddr in tendermint config

---

crates/bin/pcli/src/command/query/dex.rs

docs: clarify dex pair format in pcli

---

crates/bin/pcli/src/command/query/dex.rs
crates/bin/pd/src/info/specific.rs
crates/core/component/dex/src/component/arb.rs
crates/core/component/dex/src/component/dex.rs
crates/core/component/dex/src/component/router/fill_route.rs
crates/core/component/dex/src/component/router/route_and_fill.rs
crates/core/component/dex/src/component/router/tests.rs
crates/core/component/dex/src/component/tests.rs
crates/core/component/dex/src/state_key.rs
crates/core/component/dex/src/swap_execution.rs
crates/proto/proto/penumbra/client/v1alpha1/client.proto
crates/proto/proto/penumbra/core/dex/v1alpha1/dex.proto
crates/proto/src/gen/penumbra.client.v1alpha1.rs
crates/proto/src/gen/penumbra.core.dex.v1alpha1.rs
crates/proto/src/gen/penumbra.core.dex.v1alpha1.serde.rs
crates/proto/src/gen/proto_descriptor.bin

Clean up SwapExecution handling

---

.github/workflows/deploy-preview.yml
docs/guide/src/dev/rpc.md

docs: add grpcui to dev docs

---

docs/guide/src/SUMMARY.md
docs/guide/src/dev/protobuf.md
docs/guide/src/extension.md

* Move web wallet to the top of the list
* Improve faucet instructions
* Remove stale protobuf comment

docs: improve guide

---

crates/view/src/storage.rs
crates/view/src/worker.rs

Fix view service erroring on new unknown assets.

---

crates/bin/pcli/tests/proof.rs
crates/core/component/dex/src/batch_swap_output_data.rs
crates/core/component/dex/src/lp/nft.rs
crates/core/component/dex/src/swap/plaintext.rs
crates/core/component/dex/src/swap/proof.rs
crates/core/component/dex/src/swap_claim/proof.rs
crates/core/crypto/src/asset.rs
crates/core/crypto/src/asset/cache.rs
crates/core/crypto/src/asset/denom_metadata.rs
crates/core/crypto/src/balance.rs
crates/core/crypto/src/lib.rs
crates/core/crypto/src/memo.rs
crates/core/crypto/src/note.rs
crates/core/crypto/src/proofs/groth16.rs
crates/core/crypto/src/value.rs
crates/core/transaction/src/effect_hash.rs

Add functionality to replace the asset registry with the asset cache

---

crates/core/crypto/src/fixpoint.rs

We have tests for all the other operations but this was uncovered. This adds a test Groth16 circuit that just does division of two U128x128 and checks the R1CS division is consistent with the out of circuit computation.

test(zk): add test for R1CS U128x128Var division

---

crates/bin/pcli/tests/network_integration.rs

Adds exercising of `pcli view tx` logic to the smoke test suite. Reuses the existing `pcli send tx` test, ensuring that the initial send can be viewed as raw JSON, and that JSON can be used to construct a TransactionView. Also adds a memo string so we can sanity-check that the TV is in fact legible.
Closes #2759.

test: add pcli view tx to smoke test

---

crates/bin/pcli/src/command/tx.rs
crates/core/crypto/src/lib.rs
crates/core/transaction/src/effect_hash.rs
crates/core/transaction/src/lib.rs
crates/core/transaction/src/memo.rs
crates/core/transaction/src/plan/build.rs
crates/core/transaction/src/plan/memo.rs
crates/core/transaction/src/transaction.rs
crates/core/transaction/src/view.rs
crates/view/src/planner.rs
crates/wallet/src/plan.rs
crates/wasm/src/planner.rs

Another item for https://github.com/penumbra-zone/penumbra/issues/2765

refactor: move memo to `transaction` crate

---

Cargo.lock
crates/wasm/Cargo.toml
crates/wasm/src/view_server.rs

Fixed penumbra-zone/penumbra#2785 stateless tx p/tx v generation for wasm code

---

crates/core/component/dex/src/batch_swap_output_data.rs
docs/protocol/src/zswap/swap.md

Document current implementation of pro-rata batch swap outputs

---

crates/bin/pcli/src/command/tx/liquidity_position.rs

This PR adds an optional `limit-order` flag for `pcli tx lp order [buy | sell]` commands.

pcli: support `--limit-order` flag for tx orders

---

crates/core/component/chain/src/component/view.rs
crates/core/component/chain/src/state_key.rs
crates/core/component/compact-block/src/component/view.rs
crates/core/component/dex/src/component/position_manager.rs
crates/core/component/sct/src/component/view.rs
crates/storage/src/cache.rs
crates/storage/src/delta.rs
crates/storage/src/future.rs
crates/storage/src/metrics.rs
crates/storage/src/read.rs
crates/storage/src/snapshot.rs
crates/storage/src/storage.rs
crates/storage/src/write.rs
crates/storage/tests/basic.rs
crates/storage/tests/delta.rs
deployments/config/grafana/dashboards/Penumbra.json

misc: rename `nonconsensus` storage to `nonverifiable`

---

docs/guide/src/extension.md

Detailed steps on how to force a manual update of the web extension. Taken from Zpoken in Discord discussions, worked well enough on my end. Refs #2748.

docs: how to update web extension

---

docs/guide/src/pcli/install.md

docs: add `git lfs install`

---

crates/misc/measure/src/main.rs

This is a new `measure` harness that opens a large number of `CompactBlock` streams and polls the server asynchronously. It reproduces generating orphaned tonic streams on the server-side. The main difference with `OpenConnections` is that the rate of polling should be much higher, this is an educated guess. This is useful harness as we implement performance improvements to the full node.

measure: add `OpenConnectionsActive`

---

Cargo.lock
Cargo.toml
crates/crypto/proof-setup/Cargo.toml
crates/crypto/proof-setup/src/dlog.rs
crates/crypto/proof-setup/src/group.rs
crates/crypto/proof-setup/src/lib.rs
crates/crypto/proof-setup/src/phase1.rs
crates/crypto/proof-setup/src/phase2.rs
deployments/scripts/rust-docs
docs/protocol/src/setup/contributions.md

Fixes #2869.
This implements the contributions for phase 1 and phase 2.
One important related thing still missing is the logic for verifying an entire log of contributions, but that will be relying primarily on this code.

Setup Ceremony Contributions

---

crates/core/component/ibc/src/component/channel.rs
crates/core/component/ibc/src/component/client.rs
crates/core/component/ibc/src/component/state_key.rs

ibc: use ibc-types for ibc component state paths

---

crates/bin/pcli/src/command/query/chain.rs

Adding current epoch info to the `pcli q chain info` output. When interacting with validators, epochs are important, but answering the question "what is the current epoch right now?" via pcli was difficult. No more.

feat(pcli): add epoch to chain info query

---

deployments/config/grafana/dashboards/sync.json

Prepared by @erwan while working on #2867.
Exported from the preview grafana instance, and storing in version control, so it's part of deployments going forward.

metrics: add new sync dashboard

---

crates/bin/pd/src/info/oblivious.rs
crates/bin/pd/src/main.rs

pd: remove req-resp timeouts

---

crates/bin/pd/src/testnet/generate.rs

Follow-up to #2882. We want the external addresses to win out when writing peering info for genesis validators, and that wasn't happening. Fixed. This logic isn't currently used in CI, but will be in the near future.

fix(pd): support external address in generate

---

crates/bin/pd/src/info.rs
crates/core/app/src/governance/view.rs
crates/core/component/chain/src/component/app_hash.rs
crates/core/component/dex/src/component/arb.rs
crates/core/component/dex/src/component/router/path.rs
crates/core/component/dex/src/component/router/route_and_fill.rs
crates/core/component/dex/src/component/router/tests.rs
crates/core/component/dex/src/swap_execution.rs
crates/core/component/stake/src/validator/state.rs
crates/storage/src/future.rs
crates/storage/src/snapshot.rs
crates/view/src/planner.rs
crates/view/src/service.rs

CI was failing on PRs, so I ran `rustup update` and `cargo fmt`, then committed the results. Open PRs should rebase on this post-merge for green CI.

chore: cargo fmt

---

crates/core/component/chain/src/component/view.rs
crates/core/component/chain/src/genesis/app_state.rs
crates/core/component/chain/src/lib.rs

Remove usage of "unwrap" in the chain component

---

crates/core/component/component/src/lib.rs

Remove usage of "unwrap" in the component component

---

crates/core/component/dao/src/lib.rs

Remove usage of "unwrap" in the dao component

---

crates/core/component/fee/src/fee.rs
crates/core/component/fee/src/lib.rs

Remove usage of "unwrap" in the fee component

---

clippy.toml

Allow unwrap in tests

---

crates/core/component/ibc/src/component/client.rs
crates/core/component/ibc/src/component/grpc_query.rs
crates/core/component/ibc/src/component/msg_handler/channel_open_init.rs
crates/core/component/ibc/src/component/msg_handler/channel_open_try.rs
crates/core/component/ibc/src/component/msg_handler/connection_open_ack.rs
crates/core/component/ibc/src/component/msg_handler/connection_open_confirm.rs
crates/core/component/ibc/src/component/msg_handler/connection_open_init.rs
crates/core/component/ibc/src/component/msg_handler/connection_open_try.rs
crates/core/component/ibc/src/component/msg_handler/create_client.rs
crates/core/component/ibc/src/component/msg_handler/update_client.rs
crates/core/component/ibc/src/component/packet.rs
crates/core/component/ibc/src/component/transfer.rs
crates/core/component/ibc/src/lib.rs

Remove usage of "unwrap" in the ibc component

---

crates/core/component/shielded-pool/src/component/shielded_pool.rs
crates/core/component/shielded-pool/src/lib.rs
crates/core/component/shielded-pool/src/nullifier_derivation.rs
crates/core/component/shielded-pool/src/output/proof.rs
crates/core/component/shielded-pool/src/spend/proof.rs

Remove usage of "unwrap" in the shielded-pool component

---

crates/core/app/src/app/mod.rs
crates/core/app/src/lib.rs

Remove usage of "unwrap" in the app crate

---

crates/core/asset/src/asset/denom_metadata.rs
crates/core/asset/src/asset/registry.rs
crates/core/asset/src/lib.rs
crates/core/asset/src/value.rs

Remove usage of "unwrap" in the asset crate

---

crates/core/num/src/fixpoint.rs
crates/core/num/src/lib.rs

Remove usage of "unwrap" in the num crate

---

crates/core/transaction/src/action.rs
crates/core/transaction/src/auth_hash.rs
crates/core/transaction/src/effect_hash.rs
crates/core/transaction/src/lib.rs
crates/core/transaction/src/plan/action.rs
crates/core/transaction/src/plan/build.rs
crates/core/transaction/src/view/transaction_perspective.rs

Remove usage of "unwrap" in the transaction crate

---

crates/core/keys/src/keys/fvk.rs
crates/core/keys/src/keys/fvk/r1cs.rs
crates/core/keys/src/lib.rs

Remove usage of "unwrap" in the keys crate

---

deployments/relayer/README.md
deployments/relayer/build-path
deployments/relayer/configs/penumbra-preview.json
docs/guide/src/pcli/transaction.md

These docs changes are based on feedback from a pairing session with @aubrika today.

docs: relayer setup and usage

---

crates/bin/pcli/src/command/debug.rs
crates/bin/pcli/src/command/query/dex.rs
crates/bin/pcli/src/command/query/governance.rs
crates/bin/pcli/src/command/tx.rs
crates/bin/pcli/src/command/tx/replicate.rs
crates/bin/pcli/src/command/utils.rs
crates/bin/pcli/src/command/validator.rs
crates/bin/pcli/src/command/view/staked.rs
crates/bin/pcli/src/dex_utils/replicate/debug.rs
crates/bin/pcli/src/dex_utils/replicate/xyk.rs
crates/bin/pcli/src/main.rs
crates/bin/pcli/src/network.rs
crates/bin/pcli/src/opt.rs

Remove usage of "unwrap" in the pcli crate

---

crates/bin/pd/src/events.rs
crates/bin/pd/src/info.rs
crates/bin/pd/src/info/specific.rs
crates/bin/pd/src/lib.rs
crates/bin/pd/src/main.rs
crates/bin/pd/src/testnet/config.rs
crates/bin/pd/src/testnet/generate.rs
crates/bin/pd/src/testnet/join.rs
crates/bin/pd/src/upgrade.rs

Remove usage of "unwrap" in the pd crate

---

crates/bin/pclientd/src/lib.rs
crates/bin/pclientd/src/main.rs

Remove usage of "unwrap" in the pclientd crate

---

crates/bin/pclientd/src/lib.rs

Closes #3060 (also automatically creates the default pclientd home directory in `pclientd init`, should none be provided and the default does not exist)

Add `pclientd reset` to reset local view storage

---

crates/core/component/ibc/src/component/action_handler/ibc_action.rs
crates/core/component/ibc/src/component/client_counter.rs
crates/core/component/ibc/src/component/msg_handler.rs
crates/core/component/ibc/src/component/msg_handler/misbehavior.rs
crates/core/component/ibc/src/component/msg_handler/update_client.rs
crates/core/component/ibc/src/ibc_action.rs

ibc: add SubmitMisbehavior ibc message handling

---

crates/bin/pd/src/main.rs

pd(upgrade): use  `upgrade_path` flag

---

crates/core/transaction/src/transaction.rs

Followup from #3088 (h/t to @zbuc for pointing this out)

refactor: fix clippy never loop

---

.github/workflows/deploy-preview.yml
deployments/helmfile.d/penumbra-preview.yaml
deployments/helmfile.d/penumbra-testnet.yaml
deployments/helmfile.d/vars/penumbra-preview-nodes-ips.yml
deployments/helmfile.d/vars/penumbra-testnet-nodes-ips.yml

ci: add new 2 more fullnodes to deployment

---

deployments/README.md
deployments/charts/penumbra-network/templates/deployment.yaml
deployments/charts/penumbra-node/templates/NOTES.txt
deployments/scripts/relayer-local-devnet
deployments/scripts/smoke-test.sh
deployments/systemd/README.md
deployments/systemd/penumbra.service

docs: update systemd guide for cometbft

---

.github/workflows/containers.yml

ci: check out repo for remote containers

---

.dockerignore
deployments/containerfiles/Dockerfile

ci: add summonerd to container image

---

crates/core/component/ibc/src/component/action_handler/ibc_action.rs
crates/core/component/ibc/src/component/msg_handler.rs
crates/core/component/ibc/src/component/msg_handler/upgrade_client.rs
crates/core/component/ibc/src/component/proof_verification.rs
crates/core/component/ibc/src/ibc_action.rs

ibc client upgrades

---

.github/workflows/deploy-testnet.yml

Follow-up to #3135. There was an unescaped newline which broken the task. Should work next time.

ci: fix bot image update task

---

tools/summonerd/src/coordinator.rs

Closes #3200.
This is dependent on #3201 being merged in though, can be reviewed after that.

Tweak Summonerd coordinator to avoid amplification

---

crates/bin/pcli/src/command/tx.rs
docs/guide/src/pcli/transaction.md

WIP: started this PR after release of 62, but wasn't able to figure out the right steps. In particular, the `--timeout-height` default arg will not work.

docs: add ibc channel info for testnet 62 iapetus

---

crates/bin/pcli/src/command/ceremony.rs
crates/crypto/proof-setup/src/all.rs
tools/summonerd/src/main.rs

I also tested that things work E2E, now to make them faster!

Bug: Summonerd: Fix serialization of elements

---

docs/protocol/src/crypto/transaction_signing.md

spec: add motivation for tx signing section

---

crates/crypto/proof-params/build.rs

proof-params: improve error message

---

crates/bin/pcli/tests/proof.rs
crates/wasm/src/tx.rs
crates/wasm/src/utils.rs
crates/wasm/src/view_server.rs

chore: rename note commitment tree to state commitment tree

---

deployments/scripts/smoke-summoner.sh

Closes #3241
Note: CI will be green here on the PR but this should not be merged until a run of the summonerd smoke test job (can be triggered via the Actions tab) is green

test: update syntax for pcli init command in summonerd smoke test

---

crates/bin/pcli/src/command/ceremony.rs
crates/crypto/proof-setup/src/all.rs

This can make it unto the upcoming release, and allows us to include these hashes into the database later.

Pcli ceremony: add contribution hash / receipt

---

tools/summonerd/src/storage.rs
tools/summonerd/src/storage/schema.sql

Summonerd: add transcript hashes and timestamps

---

deployments/containerfiles/Dockerfile

Follow-up to https://github.com/penumbra-zone/penumbra/pull/3253

build: msrv for containerfile, too

---

deployments/containerfiles/Dockerfile-grafana

build: pin grafana at 10.1.5

---

.github/workflows/containers.yml

ci: set dependencies for bot containers

---

deployments/scripts/smoke-summoner.sh

Fix summoner smoke test port usage

---

Cargo.lock
crates/bin/pcli/src/command.rs
crates/bin/pcli/src/command/ceremony.rs
crates/bin/pcli/src/config.rs
crates/bin/pd/src/testnet/generate.rs
crates/bin/pd/src/testnet/join.rs
crates/core/app/src/genesis/app_state.rs
crates/core/asset/src/asset/denom_metadata.rs
crates/core/component/ibc/src/component/msg_handler/update_client.rs
crates/core/component/stake/src/component.rs
crates/crypto/proof-setup/src/all.rs
crates/crypto/proof-setup/src/single/phase1.rs
crates/storage/src/snapshot.rs
tools/summonerd/src/coordinator.rs
tools/summonerd/src/main.rs
tools/summonerd/src/server.rs
tools/summonerd/src/storage.rs

cargo fmt, cargo update, clean up lints

Chore: cleanup lints

---

tools/summonerd/src/main.rs
tools/summonerd/src/web.rs
tools/summonerd/templates/main.html

This modifies the instructions to dynamically show the right address and min bid

Summonerd: dynamically show address and min bid

---

.github/workflows/deploy-testnet.yml
deployments/charts/penumbra-network/templates/deployment.yaml
deployments/charts/penumbra-node/templates/deployment.yaml
deployments/scripts/gha-repository-dispatch

A handful of small fixes, refs #3279.

ci: deploy tweaks to smooth out container builds

---

deployments/charts/penumbra-node/values.yaml

ci: more permissive cors for pd grpc

---

docs/guide/src/pcli/install.md

docs: tweak rust version in guide

---

crates/core/transaction/src/memo.rs
crates/view/src/planner.rs
crates/wallet/src/plan.rs
crates/wasm/src/planner.rs

Closes #2756 
Related to #3286

remove default impl of `MemoPlaintext`

---

crates/bin/pcli/src/command/debug.rs

Since we moved to new pcli config file in #3239, we don't use the archives anymore. If a machine doesn't have archive dirs, then pcli will throw an error, which is bad. Stop looking for archive dirs.
Similar, we shouldn't look for a custody.json file, we should look for the new config.toml file.
Closes #3321.

fix(pcli): remove archives from debug output

---

crates/bin/pcli/src/command/view/transaction_hashes.rs

In the future, once the MemoView has an AddressView, we can change this to show the AddressView and show the address structure. #2780

pcli: show sender and memo in list-tx-hashes

---

crates/bin/pd/src/main.rs
deployments/systemd/cometbft.service
deployments/systemd/penumbra.service
docs/guide/src/dev/devnet-quickstart.md
docs/guide/src/pd/join-testnet.md

feat(pd): add default homedir for start

---

crates/core/component/shielded-pool/src/component/transfer.rs

previously, the `is_source` check returned true if the prefix matches, but the `is_source` check in `onTimeoutPacket` [here] (https://github.com/cosmos/ibc/blob/main/spec/app/ics-020-fungible-token-transfer/README.md#packet-relay) is the reverse:: `source = data.denom.slice(0, len(prefix)) !== prefix`. this PR fixes the `is_source` logic to take an `is_refund` bool to return the correct value.

fix: update `is_source` to have `is_refund` bool, fixes ICS20 transfer logic

---

crates/wasm/src/planner.rs
crates/wasm/src/tx.rs
crates/wasm/src/wasm_planner.rs

Remove expects from wasm crate

---

crates/bin/pcli/src/command/init.rs

Some minor UX improvements (create paths if not exist, rename to home, add docs).

pcli: tweaks to pcli init threshold deal

---

crates/core/transaction/src/plan/clue.rs
crates/crypto/decaf377-fmd/src/clue_key.rs

fix: panic when sending funds to invalid address

---

crates/bin/pcli/src/command/tx.rs

pcli: don't randomize sender address

---

docs/protocol/src/crypto/transaction_signing.md
docs/protocol/src/dex/routing.md
docs/protocol/src/protocol/notes/note_plaintexts.md
docs/protocol/src/protocol/transaction_crypto.md
docs/protocol/src/zswap/swap.md

Hi, I found few typos while reading the docs. I hope I fixed them correctly. Have a nice evening.

Fixed few errors in the documentation.

---

crates/core/component/ibc/src/component/client.rs
crates/core/component/ibc/src/component/msg_handler/connection_open_ack.rs
crates/core/component/ibc/src/component/msg_handler/connection_open_confirm.rs
crates/core/component/ibc/src/component/msg_handler/connection_open_try.rs
crates/core/component/ibc/src/component/msg_handler/misbehavior.rs
crates/core/component/ibc/src/component/msg_handler/update_client.rs
crates/core/component/ibc/src/component/proof_verification.rs
crates/core/component/ibc/src/component/rpc/client_query.rs

as title says :) needed these for the astria hermes fork, as we're not using ABCI queries, just gRPC queries.

feat(ibc): implement consensus_state, consensus_states, consensus_state_heights gRPC queries

---

crates/bench/benches/delegator_vote.rs
crates/bench/benches/nullifier_derivation.rs
crates/bench/benches/spend.rs
crates/bin/pcli/tests/proof.rs
crates/core/component/governance/src/action_handler/delegator_vote.rs
crates/core/component/governance/src/delegator_vote.rs
crates/core/component/governance/src/delegator_vote/plan.rs
crates/core/component/governance/src/delegator_vote/proof.rs
crates/core/component/governance/src/lib.rs
crates/core/component/shielded-pool/src/component/action_handler/spend.rs
crates/core/component/shielded-pool/src/lib.rs
crates/core/component/shielded-pool/src/nullifier_derivation.rs
crates/core/component/shielded-pool/src/spend.rs
crates/core/component/shielded-pool/src/spend/plan.rs
crates/core/component/shielded-pool/src/spend/proof.rs

refactor: define public, private structs for spend, nullifier derivation and delegator vote circuits

---

crates/core/component/governance/src/delegator_vote/proof.rs
crates/core/component/shielded-pool/src/nullifier_derivation.rs
crates/core/component/shielded-pool/src/spend/proof.rs

test: add proptests of first three circuits vs an in rust impl

---

crates/core/component/dex/src/component/metrics.rs
crates/core/component/dex/src/component/position_manager.rs
crates/core/component/dex/src/component/tests.rs
crates/core/component/ibc/src/component/msg_handler/connection_open_try.rs
crates/core/component/ibc/src/component/packet.rs
crates/core/component/ibc/src/component/proof_verification.rs
crates/core/component/ibc/src/ibc_token.rs

One is an error message displayed to the user, rest are comments.
Have a nice week.

chore( crates/core/component): typo fix

---

crates/core/component/stake/src/component.rs

Closes #2919. This is a simple fix, at the same time I am reading up on the ecology of misbehavior that CometBFT can report and whether the CSDK evidence module has been helpful for other chains.
As part of #3588, we should remember to add a test for equivocation from unknown validators and reexamine if we make similar assumptions elsewhere.

stake: ignore byzantine misbehavior from unknown validators

---

Cargo.lock
crates/core/component/distributions/Cargo.toml

Fixes interactions between #3639 & #3640.

fix: distributions must depend on asset

---

crates/core/component/stake/src/component.rs
crates/core/component/stake/src/rate.rs

staking(rate): measure voting power in units of staking tokens

---

tools/summonerd/src/storage.rs
tools/summonerd/templates/phase1.html
tools/summonerd/templates/phase2.html

Closes #3626.
(there's still some debate in that issue, but that's orthogonal to writing code to do what that feature request asks)

Display full address in summoner interface

---

crates/core/app/src/app/mod.rs
crates/core/component/community-pool/src/component.rs
crates/core/component/distributions/src/component.rs
crates/core/component/fee/src/component.rs
crates/core/component/funding/src/component.rs
crates/core/component/governance/src/component.rs
crates/core/component/ibc/src/component.rs
crates/core/component/ibc/src/component/ibc_component.rs
crates/core/component/shielded-pool/src/component/shielded_pool.rs
crates/core/component/stake/src/component.rs

app: fold genesis param init into their respective component

---

Cargo.lock
crates/bin/pd/src/main.rs
crates/core/app/Cargo.toml
crates/core/app/src/rpc.rs

This reverts commit 7b0458c920650d8644161b824e88eb602436777e. Refs #3697.

Revert "pd: 📬 create tonic router in penumbra-app"

---

crates/core/component/shielded-pool/src/component/transfer.rs

Strip ICS20 prefix from beginning of packet data denoms only

---

crates/core/component/shielded-pool/src/component/transfer.rs

Use checked math for ICS20 withdrawal addition

---

crates/core/component/governance/src/proposal.rs
crates/core/component/governance/src/vote.rs

Simplify string matching in governance code

---

crates/core/component/stake/src/delegation_token.rs

Fix delegation token regex to check boundaries

---

Cargo.lock
Cargo.toml
crates/core/transaction/src/plan/build.rs

3388 decaf377 rdsa upgrade

---

.dockerignore

This should fix preview, unless something else is wrong ~~if providence favors us today~~.

ci: exclude `assets/` from docker ignore

---

crates/core/component/shielded-pool/src/component/transfer.rs

Once the mock test framework is further along, it would be good to add some tests around this logic.
Closes #3773

Check value balance during IBC packet timeout

---

crates/core/component/stake/src/component/validator_handler/validator_store.rs

staking: 🧹 tidy `validator_store` imports

---

crates/view/src/client.rs
crates/view/src/lib.rs
crates/view/src/note_record.rs
crates/view/src/planner.rs
crates/view/src/service.rs

i hadn't looked at `penumbra-view` much before today. in preparation for a design conversation tomorrow, i read through some of the important facilities provided by this library.
this is a small collection of assorted bits of tidying / documenting / clean-up i handled as i read through it.

chore: 🌱 document and tidy `penumbra-view`

---

crates/core/component/ibc/src/component/packet.rs

Previously, we only checked if the client was frozen

ibc: error on attempts to send packets with expired client

---

crates/bin/pd/src/main.rs

we log when there is nothing to remove, but let's also log what happens when this is run.

pd: 👄 log testnet directory reset

---

crates/core/component/dex/src/component/router/fill_route.rs

Closes #4007
The bug results from a hazardous API I created. The `apply` method does _not_ apply the events to the underlying state, it extracts them and returns them to the caller, who can silently discard them.
A better fix is outlined in the comment:
```
// We have to manually extract events and push them down to the state to avoid losing them.
// TODO: in a commit not intended to be cherry-picked, we should fix this hazardous API:
// - rename `StateDelta::apply` to `StateDelta::apply_extracting_events`
// - add `StateDelta::apply_with_events` that pushes the events down.
// - go through all uses of `apply_extracting_events` and determine what behavior is correct
```
However, I didn't do this in this commit, because my hope is that we can have something easily cherry-pickable into a …

dex: hotfix to avoid discarding EventPositionExecution

---

crates/bin/pd/Cargo.toml

see #4042. sorts and tidies up the `pd` crate manifest.

chore(pd): 🤏 sort and tidy `Cargo.toml`

---

docs/guide/src/dev/sql.md

Hat tip to @aubrika for the db schema pointers. Capturing this example in the dev guide to make it a bit easier to explore.

docs: dev guide notes on asset ids in sqlite3

---

Cargo.lock
Cargo.toml
crates/bench/Cargo.toml
crates/bench/benches/arkworks.rs
crates/bench/benches/decaf377.rs

refactor(bench): field and curve benchmarks

---

docs/guide/src/pd/chain-upgrade.md

docs: fix typo

---

docs/guide/src/pd/chain-upgrade.md

Refs #4087, #4131.
> docs only

docs: fixes another typo in upgrade docs

---

tools/summonerd/src/config.rs

this finishes an incomplete documentation comment.
> documentation change

docs(summonerd): 🪄 finish incomplete comment

---

crates/core/component/stake/src/component/action_handler/validator_definition.rs

This PR adds a **new consensus rule** which forces validators with `sequence_number = u32::MAX` to be in the state `enabled = false`. This reduces the incentive to steal validator identity signing keys, because it means that it's impossible to "lock" a validator in the `enabled` state; the operator can always permanently disable their validator, cutting off profits for the attacker.
This is an implementation of issue #4170; see its description for more details about the risk this mitigates.
> **This is a consensus-breaking change**: it rejects validator definitions which would previously have been accepted by the chain.

Add consensus check preventing end-of-life enabled validators

---

crates/core/asset/src/asset/id.rs
crates/core/asset/src/balance.rs
crates/core/asset/src/value.rs
crates/core/component/dex/src/lp/nft.rs
crates/core/component/governance/src/delegator_vote/proof.rs
crates/core/component/shielded-pool/src/output/action.rs
crates/core/component/shielded-pool/src/output/proof.rs
crates/core/component/shielded-pool/src/spend/action.rs
crates/core/component/shielded-pool/src/spend/proof.rs
crates/core/keys/src/symmetric.rs
docs/protocol/src/addresses_keys/transaction_crypto.md
docs/protocol/src/assets.md
docs/protocol/src/crypto/flow-encryption/threshold-encryption.md
docs/protocol/src/dex/action/swap.md
docs/protocol/src/transactions.md
docs/protocol/src/transactions/actions.md

This PR fills in some TODOs in the table of balance contributions by action. I have gone through the other entries of the table and verified they are correct. 
Closes #3991 
Closes #1553

spec: fill in balance by action table

---

docs/guide/src/node/pd/validator.md
docs/guide/src/pcli/wallet.md

Additional documentation in the guide about validator-specific custody options in `pcli`.
N/A
> This is a docs-only PR.

Add documentation about custody considerations for validators

---

crates/bin/pcli/src/terminal.rs
crates/custody/src/terminal.rs
crates/custody/src/threshold.rs

Improves UX for the DKG ceremony based on user feedback, so we can actually tell people to use it.
This is a PR on top of #4343 to make it as easy as possible to merge.
#4335
> client-side key generation logic only

Better threshold UX

---

crates/core/app/tests/swap_and_swap_claim.rs
crates/core/component/dex/src/swap_claim/proof.rs
crates/view/src/planner.rs
crates/wallet/src/plan.rs
docs/protocol/src/addresses_keys.md
docs/protocol/src/assets.md
docs/protocol/src/concepts/notes_nullifiers_trees.md
docs/protocol/src/crypto/decaf377-rdsa.md
docs/protocol/src/dex/action/swap_claim.md
docs/protocol/src/dex/swap.md
docs/protocol/src/governance/action/delegator_vote.md
docs/protocol/src/sct.md
docs/protocol/src/sct/nullifiers.md
docs/protocol/src/shielded_pool/action/output.md
docs/protocol/src/shielded_pool/action/spend.md
docs/protocol/src/shielded_pool/note_commitments.md
docs/protocol/src/stake/action/undelegate_claim.md
docs/protocol/src/transactions/invariants.md

This PR contains protocol spec changes from internal feedback
Related to #4280 
Closes #4342
> spec only

spec: updates per internal feedback

---

crates/bin/pcli/src/command/init.rs
crates/bin/pcli/src/command/query/auction.rs
crates/bin/pcli/src/command/query/ibc_query.rs
crates/bin/pcli/src/command/tx/auction/dutch/gda.rs
crates/bin/pcli/src/terminal.rs
crates/bin/pd/src/lib.rs
crates/bin/pd/src/migrate.rs
crates/bin/pd/src/migrate/testnet72.rs
crates/bin/pd/src/migrate/testnet74.rs
crates/bin/pd/src/zipserve.rs
crates/cnidarium/src/storage.rs
crates/cnidarium/src/store/multistore.rs
crates/cnidarium/src/store/substore.rs
crates/cnidarium/src/write_batch.rs
crates/core/component/dex/src/component/rpc.rs
crates/core/component/dex/src/params.rs
crates/crypto/proof-params/src/lib.rs
crates/custody/src/threshold/sign.rs
crates/test/mock-consensus/src/block.rs
crates/test/mock-consensus/src/block/signature.rs
crates/view/src/storage.rs

This PR cleans up various lint warnings across the codebase.

Chore: Cargo clippy cleanups

---

docs/protocol/src/sct/tct.md

Adds a description of the TCT to the spec from this [nice blog post](https://penumbra.zone/blog/tiered-commitment-tree) and the Rust docs
Closes #2889
> protocol spec only

spec: add description of the TCT

---

.github/ISSUE_TEMPLATE/upgrade_testnet.md

We've long had an issue template for releasing a testnet, which presupposes resetting the chain. There's a substantially different procedure for performing an upgrade. Let's codify that information so it's easy to use in planning going forward.
Finishes and therefore closes #4374.
> docs-only, no code changes

docs: add upgrade planning checklist

---

crates/view/src/service.rs

`check_worker()` is called by almost every public interface in the view server, as a preliminary check that the worker task running in the background has not recorded an error of some kind.
this commit makes a change to `check_worker()`, so that it does not need to frivolously acquire, release, and subsequently reacquire the mutex in the event of an error being stored in the slot.
tracing events and documentation are also added to this function.
x-ref: #3913
> this is only making changes to the view server, consensus should not be affected.

view: 📫 do not thrash `error_slot` mutex

---

crates/view/src/storage.rs

This PR addresses issue #3530, improving the error message displayed to the user by providing how to solve the problem.
Closes #3530

chore: improve error message for view database schema mismatch

---

crates/core/component/dex/src/component/metrics.rs

change buckets to 16 log spaced values between 5 and 250
#4464 
> metrics changes only

dex: update bucket values

---

crates/core/component/auction/src/component/action_handler/dutch/schedule.rs

This PR adds a historical check which disallow scheduling new dutch auctions if the DEX component is disabled
> This is a change to validation rules, and therefore it is consensus breaking

auction: disallow new auctions if the dex is disabled

---

docs/guide/src/node/pd/join-testnet.md

docs: update join url for testnet 77

---

crates/bin/pcli/src/command/view/staked.rs
crates/view/src/planner.rs

This PR backports #4536 to `v0.77.x`
> Client change

pcli: backport `staked` fix to `v0.77.x`

---

crates/bin/pcli/src/command/query/chain.rs

Show the full chain parameters, not just handpicked ones.
> Formatting changes to pcli

pcli: show full params

---

tools/summonerd/templates/main.html

chore: update summonerd docs to 0.77.2

---

docs/protocol/src/stake/action/undelegate_claim.md

References spec findings from ECC audit on `UndelegateClaim`
> Spec only

spec: clarify UndelegateClaim in spec

---

crates/bin/pcli/src/command/view/address.rs

tweak terminology in pcli
none
> pcli help text

pcli: clarify terminology to ibc deposit address

---

crates/bin/pd/src/migrate/testnet78.rs

Don't deserialize proto types to avoid applying new domain validations to old types in migration 78
https://github.com/penumbra-zone/penumbra/pull/4596#discussion_r1637191934

Migration 78: Avoid deserializing proto types to domain types in migration

---

crates/bin/pd/src/testnet/join.rs

Follow-up to #4607. This fix is required to preserve the original downloading from URL behavior. Both file:// and https:// URLs must remain supported. Must have accidentally rebased this diff out while collborating on 4607.
> cli-flags only

fix: pd testnet join file archive support

---

crates/core/app/tests/app_can_sweep_a_collection_of_small_notes.rs
crates/core/app/tests/view_server_can_be_served_on_localhost.rs

This disable two app tests that have flake occasionally.
Possibly related to #4517

app(tests): disable flakey app tests for now

---

Cargo.toml

remove duplicate dependency in the Cargo.toml

chore: remove duplicate crate

---

crates/core/app/src/app/mod.rs
testnets/cometbft_config_template.toml

During team sync today we decided that this new value is superior.
Follow-up to related work in #4614, #4627, and #4632.
> This change does affect consensus and so should be treated carefully.

app: change max tx bytes constant to `96KB`

---

crates/core/component/stake/src/uptime.rs

fix comment in `Uptime::missed_blocks`

---

docs/guide/src/dev/devnet-quickstart.md
docs/guide/src/node/pd/join-network.md
docs/guide/src/tutorials/running-frontend.md
docs/guide/src/tutorials/running-node.md

docs: fix pd commands

---

crates/util/cometindex/README.md

cometindex: clarify some environment context in the readme

---

crates/bin/pd/build.rs

Updates the build.rs file for pd to error out if the frontend asset bundles are incomplete, by checking for a small filesize. That isn't a super durable method, but it's a cheap check and easy to update in the future.
Closes #4703.
> changes to build logic, does not affect app consensus logic
CI currently checks the happy-path, meaning it ensures that LFS is used for building Penumbra artifacts. If you're reviewing a Penumbra PR, your local dev env likely has git-lfs properly configured, too. To test the unhappy-path, try saving this Dockerfile locally:
```dockerfile
FROM docker.io/rust:1-slim-bookworm
RUN apt-get update && apt-get install -y git curl clang libssl-dev pkg-config
WORKDIR /app
RUN rustc --version
RUN git clone https://github.com/penumbra-zone/penumbra && \
cd /app/penumbra …
```

build(pd): fail if asset zipfiles aren't complete

---

crates/custody/src/policy.rs
docs/protocol/src/shielded_pool/action/output.md
docs/protocol/src/transactions/actions.md

chore: fix some comments

---

.github/workflows/buf-pull-request.yml
Cargo.lock
Cargo.toml
crates/bin/pcli/Cargo.toml
crates/bin/pd/Cargo.toml
crates/bin/pindexer/Cargo.toml
crates/bin/pmonitor/Cargo.toml
crates/test/tracing-subscriber/Cargo.toml
crates/util/auto-https/Cargo.toml
crates/util/cometindex/Cargo.toml
crates/view/Cargo.toml
crates/wallet/Cargo.toml
tools/parameter-setup/Cargo.toml
tools/proto-compiler/Cargo.toml
tools/summonerd/Cargo.toml

This is the ultimate step before hands-on spelunking to figure out if publishing on crates.io can be done as-is. Or, whether it will need more tweaks (plausible).
> Cargo plumbing

penumbra: `v0.82.0-alpha.0`

---

crates/core/keys/src/address.rs

The link is invalid, I changed it to use the latest address.

chore: fix 404 status URL

---

crates/core/component/dex/src/component/position_manager.rs
crates/core/component/dex/src/component/position_manager/volume_tracker.rs

Close #5028.
> Consensus and state breaking

dex: track outflows in position manager

---

crates/bin/pcli/src/command/validator.rs
crates/bin/pcli/src/command/view/lps.rs
crates/util/cometindex/src/indexer/indexing_state.rs
crates/view/src/sync.rs
docs/protocol/src/SUMMARY.md
docs/protocol/src/dex/swap.md

chore: fix some typos

---

crates/bin/pcli/src/command/tx/lqt_vote.rs

This exploits the change address to simplify the note consolidation logic inside of `pcli tx lqt-vote`, instead relying on the already existing code inside of the planner which mints outputs as necessary to balance the transaction.
I tested this on a devnet, and it behaves exactly the same as before, just with simpler code.
> Same behavior as before, and only changes client code

pcli: simplify tx lqt-vote

---

crates/util/cometindex/src/indexer.rs

We created a transaction too early in the previous version of the code, which meant that in the common case of skipping a batch of transactions, we would create the transaction before checking if we need to do anything.
Smoke tests should be sufficient to test.

cometindex: avoid unnecessary rollbacks

---

crates/core/component/auction/src/component/dutch_auction.rs
crates/core/transaction/src/view.rs
crates/crypto/proof-setup/src/single/mod.rs

chore: fix some typos in comments

---

crates/core/app/src/rpc.rs

exposes the funding service
> LQT branch

pd: add funding service

---

crates/core/component/auction/src/component/auction.rs
crates/core/component/dex/src/component/position_manager.rs
crates/core/component/dex/src/component/router/tests.rs
crates/core/component/shielded-pool/src/fmd.rs
crates/core/component/shielded-pool/src/ics20_withdrawal.rs

chore: fix some typos in comment

---

Cargo.lock
Cargo.toml

This bumps `tendermint-rs@0.40.3` and `ibc-types@0.15.1`
#5150 
> consensus breaking.

penumbra: bump tendermint-rs and ibc-types

---

crates/bin/pd/src/migrate/mainnet4.rs

For some reasons some imports were missing post rebase, this adds those in to get CI happy again.
CI should be sufficient to test.
> makes the migration compile again, so should be fine?

Fix mainnet4 migration

---

crates/core/app-tests/tests/app_can_define_and_delegate_to_a_validator.rs
crates/core/app-tests/tests/app_can_undelegate_from_a_validator.rs

chore: Fix typos in comment

---

crates/bin/pcli/src/command/init.rs

Updates the `pcli init view-only` CLI behavior
to read the FVK from interactive input, or else stdin, but not accept a CLI arg that will be stored in shell history.
Refs #5171. Inspired by https://github.com/penumbra-zone/penumbra/pull/5173, so best review in tandem with that PR.
It's worth considering whether we want to change the CLI behavior at all: it could break downstream client scripting. I argue that it's worthwhile, given the baseline security improvements, and also because it only affects creation of new wallets via pcli, and existing wallets will work just fine.
> CLI args only, no changes to app code

pcli: read fvk interactively

---

crates/core/app/src/app/mod.rs
crates/core/app/src/event.rs

Backport AppParameter event fix from 1.5.1 to 0.79.x

---

crates/core/app/src/app/mod.rs
crates/core/app/src/event.rs

Backport AppParameter event fix from 1.5. to v1.3.x

---

crates/bin/pindexer/src/lqt/schema.sql

We accidentally omitted which we need for the LQT lp leaderboard.

pindexer: lqt: add missing `um_fees` column

---

crates/bin/pindexer/src/insights/mod.rs
crates/bin/pindexer/src/insights/schema.sql

Before we were incrementing the supply of a validator, treating this event the same as delegation!
This should fix https://github.com/penumbra-zone/penumbers/issues/26.

fix: insights, implement undelegation correctly

---

COMPATIBILITY.md

Trying to be maximally clear about which software versions map to which protocol versions.
Docs only.

docs: update compatibility versions

---

crates/bin/elcuity/src/clients.rs
crates/bin/pclientd/src/lib.rs

docs: fix some typos in comment

---

crates/core/asset/src/asset/denom_metadata.rs

This is useful (for the trading SDK), and doesn't seem harmful to expose.
No testing should be needed.
> no protocol behavior changes.

feat: asset: expose symbol method

---

crates/bin/pindexer/src/ibc/ibc.sql
crates/bin/pindexer/src/ibc/mod.rs
crates/bin/pindexer/src/ibc/reset.sql

this PR adds indexing of tx_hash in ibc events to pindexer, to support https://github.com/penumbra-zone/web/issues/2605

feat: index tx_hash in ibc transfers

---

crates/bin/pclientd/src/lib.rs
crates/bin/pd/src/network/generate.rs
crates/bin/pmonitor/tests/network_integration.rs

fix some minor issues in comments

chore: fix some minor issues in comments

---

crates/bin/elcuity/README.md
docs/protocol/src/crypto/flow-encryption/dkg.md

docs: Fix typos
