penumbra-zone/penumbra

.github/workflows/notes.yml, .github/workflows/rust.yml, .gitmodules, Cargo.toml, penumbrad/Cargo.toml
This is a bit of a hack; tower-abci was developed in a separate repo.
Why include it in the workspace at all? The main reason is to have it
included in the auto-rendered docs.  However, git submodules aren't
super easy to work with, so in the long run this might not be a great
solution. Two possible alternatives:
- merge `tower-abci` into this repo, replaying git history;
- change the doc building process to have both.
=> Add tower-abci to the workspace.

.dockerignore, Dockerfile, docker-compose.yml
This branch adds an initial setup for running a Penumbra node using
`docker-compose`, and a `Dockerfile` for building a `pd` docker image.
There's some room for additional work here. In particular:
- the `docker-compose` file could also include Prometheus and
Grafana containers (and Prometheus can be configured to scrape metrics
from both Tendermint *and* pd)
- the correct way to volume mount the Tendermint dir so that it can be
effected by running tendermint CLI commands locally on the host (for
dev purposes) remains to be figured out
- `docker-compose` configuration should probably make a private network
for tendermint -> pd RPCs so that nothing else on the host is allowed
to talk to the pd process' ABCI RPCs
- Tendermint has a nifty [docker-compose config][1] for running a local …
=> add Dockerfile & docker-compose for pd

.github/workflows/notes.yml, .github/workflows/rust.yml, .gitmodules, Cargo.toml, penumbra/Cargo.toml
Currently, a Git submodule is used to include the `tower-abci` crate in
the workspace, rather than a Cargo git dependency. This is in order to
build `tower-abci`'s documentation via `cargo doc`. However, git
submodules are terrible<sup>\[citation needed\]</sup>, and introduce a
lot of friction to basic development workflows.
It's possible to build the RustDoc documentation for the `penumbra` and
`tower-abci` crates without building external dependencies, *without*
the use of a submodule. This can be done by changing the docs build to
run two commands, `cargo doc --no-deps` (to build `penumbra`'s RustDoc)
and `cargo doc --no-deps -p tower-abci` (to build the `tower-abci`
RustDoc). This doesn't require using git submodules, which should make
everyone's life easier.
Therefore, this branch …
=> destroy horrible submodule

.github/workflows/notes.yml
This is useful until
https://github.com/informalsystems/tendermint-rs/pull/862 is merged
upstream.
=> docs: render tendermint docs

Cargo.toml, penumbra/Cargo.toml, proto/Cargo.toml, proto/build.rs, proto/proto/transaction.proto, proto/src/lib.rs, proto/src/protobuf.rs
This adds a skeleton of a crate that holds Protobuf definitions of Penumbra
datatypes, and a `transaction.proto` file with some scratch work on transaction
structure definitions.
=> proto: add skeleton of penumbra-proto crate

.github/workflows/notes.yml
This should be removed at some point in the future when we publish a crate.
=> docs: add decaf377 to rustdoc

.github/workflows/notes.yml, Cargo.toml, crypto/Cargo.toml, crypto/src/asset.rs, crypto/src/lib.rs, crypto/src/poseidon_hash.rs, crypto/src/value.rs, penumbra/Cargo.toml
Adds asset identifiers and value commitment generator computation.
Also changes the workspace to use a Penumbra fork of some of the
arkworks crates.  The current change is in the Display impl for Fp* instances.
The fork's `ours` branch is based off of `v0.3.0`, in order to not pick up any
unreleased breaking changes.
=> crypto: create new crate, scratch work

spec/SUMMARY.md, spec/concepts/addresses_keys.md, spec/crypto/fmd.md, spec/crypto/fmd/construction.md, spec/crypto/fmd/sender-receiver.md
- adds a addresses/keys diagram in the Concepts chapter that just has the user-visible keys, not the internal key components;
- updates the terminology in the FMD section to match the implementation (clues / clue keys).
=> Update spec with user-facing addresses/keys diagram and consistent FMD terminology

crypto/Cargo.toml, crypto/src/action.rs, crypto/src/action/constants.rs, crypto/src/action/output.rs, crypto/src/keys/diversifier.rs, crypto/src/keys/ivk.rs, crypto/src/keys/ovk.rs, crypto/src/memo.rs, crypto/src/note.rs, crypto/src/proofs/transparent.rs, crypto/src/transaction/builder.rs, decaf377-ka/src/lib.rs
Closes #99 
This is using `AEAD_CHACHA20_POLY1305` as in Sapling/Orchard note encryption (ref: p.64-65 spec). One difference for Penumbra is since our memos are separated from the note, the memo is encrypted separately, but using the same method (i.e. same key, symmetric cipher). I'm using a unique nonce from the Note encryption (notes use `[0u8; 12]`, memos are using `[1u8; 12]`) but let me know if this is not the best choice. Another option could be to make further modifications to the Memo encryption/decryption.
=> feat: Note, memo, ovk encryption/decryption

.gitignore, Dockerfile, docker-compose.override.yml, docker-compose.yml, penumbra/Cargo.toml, penumbra/src/bin/pd.rs, penumbra/src/db.rs, penumbra/src/dbschema.rs, penumbra/src/dbutils.rs, penumbra/src/lib.rs
This is the proof of concept for adding a database, bootstrapping it with one table, and doing dummy transactions.
This work is not ideal but is a quick PR to add the feature.
Also, there are no tests. 
To check this out - 
1. Checkout this branch
2. Kill all previous docker containers and delete docker volumes and images
3. Re-run `docker-compose up -d`
4. In another terminal see `docker-compose logs -f`
5. You will see log of the `println`
Alternatively, 
1. Checkout this branch
2. Kill all previous docker containers and delete docker volumes and images
3. Re-run `docker-compose up -d`
4. `exec` into docker container `db` - `docker exec -it db bash`
5. Run psql to see database and single row  
- `psql -U postgres`
- `\c penumbra`
- `select * from note_commitment_tree_anchors;`
Closes …
=> Stub Postgres Scaffolding 

crypto/src/memo.rs, crypto/src/note.rs
Memo encryption shares key derivation logic with note encryption, so we can reuse the note key derivation standalone function (followup from #107)
=> refactor: use `note::derive_symmetric_key` for memo encryption

crypto/Cargo.toml, crypto/src/address.rs, spec/protocol/addresses_keys/addresses.md
Addresses now encode like: `penumbra_tn001_1kpgdhlzws6kyk2cf580wtt76t9nn2vf7em3pn05y3h8ym5a6aevdxshjgsnxecv94rzsxdhng6cjp8kgchqxud06p9xka0yxv99rty3njetqqnx2hrzz4tc03956e0`
Closes #63
=> feat: Bech32m encoding/decoding, set first testnet ID

docker-compose.override.yml, docker-compose.yml
The docker command will just loop fail, since the proper command is `pd start --host <ip>`. I also had to add a version entry to the override yaml in order to start it.
I personally had to change it to version 3.7, since that's the latest my Docker package supports (Ubuntu), but I wasn't sure if you cared about supporting that or were using 3.9 for a specific reason, so I didn't include that in this.
=> fix pd start command

.gitignore, README.md, crypto/Cargo.toml, crypto/src/keys/diversifier.rs, crypto/src/keys/spend.rs, penumbra/Cargo.toml, penumbra/src/bin/pcli.rs, wallet/Cargo.toml, wallet/src/lib.rs, wallet/src/state.rs, wallet/src/storage.rs
This PR:
* Adds a `generate` command for generating keys
* Stores key material once generated in `penumbra_wallet.dat` (or alternatively a custom location)
* Loads and saves key material using a minimal (minimal bc this is what we serialize) `Wallet` struct that has a spend key seed and the last diversifier index in use
* Integrates https://docs.rs/directories/4.0.1/directories/
=> feat(pcli): add `generate` command, save/load wallet data in/from `penumbra_wallet.dat`

penumbra/src/bin/pcli.rs
We need `create(true)` to allow `save_wallet` to create the wallet
=> fix: create wallet if it doesn't exist

README.md, crypto/src/action/output.rs, crypto/src/merkle.rs, crypto/src/note.rs, crypto/src/transaction.rs, crypto/src/transaction/builder.rs, crypto/src/transaction/error.rs, crypto/src/transaction/genesis.rs, penumbra/Cargo.toml, penumbra/src/app.rs, penumbra/src/bin/pcli.rs, penumbra/src/bin/pd.rs, penumbra/src/dbschema.rs, penumbra/src/dbutils.rs, penumbra/src/genesis.rs, penumbra/src/lib.rs, penumbra/src/state.rs, testnets/genesis_tn001.json
This PR closes #33 (and implements the necessary pre-reqs). 
This PR handles `InitChain` for genesis and describes how to setup genesis JSON files for development or testnets. If you follow the documentation you should see for block 0:
```
Nov 11 13:14:09.290  INFO abci{addr=127.0.0.1:49932}:consensus: penumbra::app: performing genesis for chain_id: penumbra_tn001
Nov 11 13:14:09.517  INFO abci{addr=127.0.0.1:49932}:consensus: penumbra::app: successfully loaded all genesis notes
Nov 11 13:14:09.517  INFO abci{addr=127.0.0.1:49932}:consensus: penumbra::app: committing pending changes to database
Nov 11 13:14:12.497  INFO abci{addr=127.0.0.1:49932}:consensus: sqlx::query: /* SQLx ping */; rows: 0, elapsed: 268.625µs
Nov 11 13:14:12.498  INFO abci{addr=127.0.0.1:49932}:consensus: …
```
=> feat: genesis, wallet service, tx serving

pd/Cargo.toml
Should close #149 (might need to kick off CI again due to having just merged the associated fix in tower-abci: https://github.com/penumbra-zone/tower-abci/pull/9)
h/t to @hdevalence for keeping this branch around
=> deps: pin tendermint libraries to stable branch

README.md, crypto/src/address.rs, crypto/src/lib.rs, crypto/src/transaction.rs, pcli/src/main.rs, pd/src/app.rs, wallet/src/state.rs
This connects the transaction sending functionality of `pcli` with its receipt on the `pd` side (using hex-encoded protobuf serialization). The transaction is just a dummy transaction pending the functionality described in #138 (which in turn requires client sync in #35). When the dummy transaction is sent by the client via `pcli tx send`, one will see a `DeliverTx` request be handled by `pd`, and if deserialized correctly, a zero code in the `DeliverTx` response:
```
Nov 16 15:46:45.592  INFO abci{addr=127.0.0.1:52232}:consensus: pd::app: req=DeliverTx(DeliverTx { tx: b"0a3412208b406b738e5b126329c74ef246db66d4b8292032002e20eaa49c2f5c9b4f9a07220e70656e756d6272615f746e3030312a00124072f32a44611108830a035d4818cf1d4b5a920a70b376f064f601728a1ebb2f0e2ec3d0eadfecf0e023c4b39c1edb403bce22b170533705 …
```
=> feat: send dummy tx using pcli to pd, log for now

pcli/src/main.rs
Adds a big scary message with colors and emoji when running `pcli` so nobody is surprised if all their money in the testnet goes away.
Closes #32
=> Add scary warning to pcli

Dockerfile, Dockerfile.dev, docker-compose.override.yml
This PR partially closes #166 by creating a new `Dockerfile.dev` used by `docker-compose.override.yaml` which has cacheing of Rust build artifacts and no longer performs a release build.
=> Improve Docker Compose For Development

README.md, crypto/src/asset.rs, pcli/src/main.rs, pcli/src/opt.rs, pcli/src/sync.rs, wallet/src/state.rs
Closes #137, adding a command that lists balance by asset. In that ticket another idea is proposed, adding balance by address (could be part of the address command perhaps?), I propose we do in a followup such that the `notes_by_asset_denomination` method and asset registry syncing can be used for #138 
Output looks like:
```
Asset denomination  Balance
pen                 100
```
=> feat: add pcli balance command 

crypto/src/action/spend.rs, crypto/src/keys/diversifier.rs, crypto/src/proofs/transparent.rs, crypto/src/transaction.rs, crypto/src/transaction/builder.rs, pcli/src/main.rs, pd/src/app.rs, pd/src/verify.rs, wallet/Cargo.toml, wallet/src/state.rs, wallet/src/wallet.rs
Closes #138
This draft PR implements the basic functionality for constructing a transaction in `pcli`. Other thoughts (also listed as comments inline) are:
* We could specify the memo in an optional arg on the command line for `tx send`
* It would be cleaner when we have no memo to let `Builder::add_output` take an `Option<MemoPlaintext>`
* It may be nice to let the user specify the change address - currently it's just the Default index 0 address
Not ready for merge as currently the spend auth sig is failing to verify in CheckTx: you will see this if you try to submit a transaction with debug level logging. I've added a regression test to display the problem in https://github.com/penumbra-zone/penumbra/pull/180/commits/5956d77ec5733956f77f92d79e1a70bd21827d3e (the test currently will fail …
=> Implement `pcli tx send`

.vscode/settings.json, crypto/src/action/spend.rs, crypto/src/note.rs, crypto/src/nullifier.rs, crypto/src/transaction.rs, pd/Cargo.toml, pd/build.rs, pd/sqlx-data.json, pd/src/db.rs, pd/src/db/assets.sql, pd/src/db/blobs.sql, pd/src/db/blocks.sql, pd/src/db/notes.sql, pd/src/db/nullifiers.sql, pd/src/db/schema.rs, pd/src/main.rs, pd/src/state.rs, proto/proto/wallet.proto, wallet/src/state.rs
Fixes #175 by extending the wallet protocol to send nullifier sets in `CompactBlock`s and using them to detect spends on the set of known unspent notes kept by the client.
Included in this PR are some improvements to the way we handle the database, which fix #155.
Additionally, if using VS Code, one can get `sqlx` query macros properly verified by rust-analyzer by opening the project directory as a folder; this will pick up the `.vscode/settings.json` file added here which sets the `DATABASE_URL` for the project appropriately.
=> Spend detection

pcli/src/main.rs
Ensures the client syncs the wallet state before reporting the balance.
=> Sync before balance

pcli/src/main.rs
This commit adds an (intentionally) undocumented environment variable that
suppresses the scary testnet warning text.  If someone can dig through the
source and/or git history to find it and then set it, they're good to go.
=> pcli: suppress warning message with undocumented env var

crypto/Cargo.toml, crypto/src/keys/diversifier.rs, crypto/src/lib.rs, crypto/src/nullifier.rs, pcli/src/main.rs, wallet/src/state.rs
This also pulls in a `derivative` dependency to make other hex-encoded things easier to derive `Debug` impls for; we should use this pattern going forwards.
This also implements a quick fix to omit the nullifiers list from the `scan_block` instrumentation span.
=> Print nullifiers in `hex::encode`d format

crypto/src/action/spend.rs, crypto/src/transaction.rs, crypto/src/transaction/builder.rs, pd/src/verify.rs, proto/build.rs, proto/proto/sighash.proto, proto/src/lib.rs
This implements basic sighash functionality in the following way:
- Adds a new `SigHashTransaction` proto type that mirrors the `Transaction`
proto but skips all of the signatures;
- Defines a `TransactionBody` -> `SigHashTransaction` conversion and a
`TransactionBody::sighash()` function that hashes the serialization of the
`SigHashTransaction`;
- Changes the transaction builder to defer creation of spend auth signatures
until finalization is complete and the sighash is available;
- Changes transaction verification to verify signatures against the sighash
value.
The effect of these changes is to ensure that spend authorizations are bound to
the entire transaction, not just the single spend description, so that spend
descriptions cannot be replayed into different transactions than the one …
=> crypto: implement basic sighash

crypto/src/asset.rs, crypto/src/note.rs, crypto/src/proofs/transparent.rs, crypto/src/transaction.rs, crypto/src/transaction/builder.rs, crypto/src/value.rs, pd/src/app.rs, pd/src/genesis.rs, wallet/src/state.rs
This PR adds the asset::Denom type, which wraps a `String` and adds a `From<Denom>` implementation for `asset::Id`.
Closes #179
=> add asset denom type

pd/src/main.rs
We should error out if either service errors, rather than continuing to run.
=> pd: propagate errors from worker tasks

pcli/src/main.rs
This is mostly cosmetic, just means directories like `zone.penumbra.testnet-archive/penumbra-tn001/81b6f2200a5aef30/` instead of `zone.penumbra.testnet-archive/penumbra-tn001/12C0ADDC7808DDE714548B8366E09D06261CCED0BF00DC694A9084B964A6F6F1/`
=> pcli: truncate archive directory hash

pd/sqlx-data.json, pd/src/app.rs, pd/src/state.rs
This PR introduces a getter to `pd/src/state.rs` that retrieves the `last` most recent NCT anchors, and changes `app.rs` to use the getter to populate the initial App state.
Closes #192
=> load latest note commitment tree anchors from database on startup

crypto/src/memo.rs, pcli/src/main.rs, pcli/src/opt.rs, wallet/src/state.rs
This PR adds support for users to set their transaction's `memo` field using pcli.
Closes #214
=> add tx memo support to pcli

crypto/src/memo.rs
`copy_from_slice` requires the source and dest to be the same size, or else it will panic at runtime as discovered during testnet testing.
=> fix panic on setting tx memo field from pcli

pd/src/main.rs
Previously we were parsing the genesis CSV file accidentally treating the first row as a header,
which meant that the first genesis allocation would always be dropped. Now, we don't do this.
=> Don't treat first row of genesis CSV as a header

pd/src/app.rs
This refactors the check_tx and deliver_tx methods to return a `Result<(),
Error>` rather than an ABCI response, and then wraps those methods in an
invocation that transforms the result into an ABCI response, so that:
* we can return any errors that occur in the ABCI `log` field;
* we have one place where we send the completion signal, so we don't forget it;
* the implementation of the functions is simpler;
* we can instrument the processing with a span with the transaction hash.
=> pd: refactor check_tx, deliver_tx to have better instrumentation

pcli/src/main.rs
Using https://docs.tendermint.com/master/rpc/#/Tx/broadcast_tx_sync instead waits for the `CheckTx` response. Thanks to @avahowell for pointing this out.
=> pcli: wait for checktx response

pcli/src/main.rs, pcli/src/opt.rs, pcli/src/sync.rs
This PR does a few pieces of cleanup to `pcli` and implements one bug fix:
- sychronization is called in one place in the main function, eliminating multiple duplicate code blocks
- the determination of whether a command requires pre-synchronization is done in a separate function
- if starting from height zero, the INFO messages will use round 1000s rather than X999s
- refactor the `addr` subcommands to eliminate code duplication
- *bug fix*: wallets were not archived when imported, only when generated locally; this is now resolved
=> Pcli cleanup

pd/sqlx-data.json, pd/src/app.rs, pd/src/db.rs, pd/src/db/validators.sql, pd/src/lib.rs, pd/src/staking.rs, pd/src/state.rs
This PR adds the `validators` field to `App`, which is a `BTreeMap<tendermint::PublicKey, Validator>` that will track the validator set. Note that this just pulls the initial validator state from the tendermint genesis state, we will need to add additional logic to the ABCI app once undelegations, slashing/evidence handling, etc, are implemented.
Closes #36
=> add `App.validators`, staking module, Validator type and track initial validator set

pd/Cargo.toml, pd/src/main.rs, pd/src/wallet.rs
This cleans up the changes in #236 but required inlining some helper functionality from tonic.
=> pd: move remote_addr to server-level span

wallet/src/state.rs
Now, the transaction builder does not produce an output if that particular output would be equal to zero.
This prevents silliness like requiring you to have at least one penumbra-denominated note in hand in order to send a zero-fee transaction, because that note needs to be split into shares of (0% fee, 100% change) in order to create the (zero!) fee output.
=> Remove zero outputs

pcli/src/main.rs, pcli/src/opt.rs
Now we can check what the balance is in the currently cached wallet.
=> Fixes #250 by adding --offline option to `pcli balance`

crypto/Cargo.toml, crypto/src/asset.rs, crypto/src/value.rs, pd/Cargo.toml, pd/sqlx-data.json, pd/src/app.rs, pd/src/db/validators.sql, pd/src/genesis.rs, pd/src/staking.rs, pd/src/state.rs
This PR adds support for loading initial validator state from initial application state, and extends our `Validator` struct to include the commission address, commission rate, and unclaimed reward.
Closes #40
=> track validator commission rate, commission address, and unclaimed reward

crypto/src/note.rs, crypto/src/proofs/transparent.rs, crypto/src/transaction/builder.rs, pcli/src/main.rs, pcli/src/state.rs, pcli/src/sync.rs, pd/src/genesis.rs, pd/src/verify.rs, wallet/src/lib.rs, wallet/src/state.rs
This PR implements pending-spend and pending-change tracking in `pcli`, along the way cleaning up a couple APIs in the crypto crate. High level changes:
- `Note::new` is now `Note::from_parts`
- `Note::generate` is a new function to create a freshly random note given a destination address and a typed value (this should be preferred over `Note::from_parts` where possible, because it is infallible since addresses are always well-formed)
- A new method on the transaction builder allows adding an output while getting the internally-generated note back as a clone. This is useful for implementing change-tracking, because when we add change outputs, we need to keep track of those notes.
- Sets of pending spends and pending change have been added to the wallet state, with backwards-compatible …
=> Track pending spends and change in `pcli`

crypto/src/address.rs, crypto/src/asset.rs, crypto/src/transaction.rs, crypto/src/transaction/genesis.rs, pd/Cargo.toml, pd/src/app.rs, pd/src/genesis.rs, pd/src/lib.rs, pd/src/main.rs, pd/src/staking.rs, pd/src/state.rs
Our create-genesis subcommand was serving two roles:
1. using command line parameters to generate JSON output that could be put into
the `app_state` field of the Tendermint `genesis.json` file;
2. constructing genesis notes given an input of genesis allocations.
The second role was only necessary because we made the `app_state` record
notes, rather than recording allocations directly, even though they have the
same information.  Instead, we can record the allocations as part of the
genesis state, and compute the notes as needed.  (Digging into this revealed
that the genesis transaction was being created non-deterministically, which
would cause an instant consensus divergence on a multi-node system; that's
fixed along the way).
The first role is not tenable as the scope of the Penumbra …
=> pd: rework and rename `create-genesis` to `create-genesis-template`

pd/src/state.rs
Fixes a crash while restarting the node because of bincode/serde-features incompatibility.
=> pd: save genesis data in json

crypto/src/asset.rs
=> change asset ID encoding to use bech32 with prefix `passet`

pcli/src/main.rs, wallet/src/state.rs
This fixes several bugs with displaying pending spends and change in `pcli`:
- State is committed after a transaction is created, thus saving pending spends/change which were
previously implicitly dropped
- Better tracing messages make it easier to understand the management of the pending sets
- Logic error corrected where pending set was not cleared if a transaction was confirmed on-chain,
leading to confusing display for 60 seconds
- Logic error corrected where notes were simultaneously present in the unspent and pending set after a spend
- Use `BTreeMap`s to store the array of assets to print, which results in alphabetically sorted assets
It also improves the balance display, so that pending transactions are easier to understand:
```
Asset          Total    Available  Pending …
```
=> Fix pending spend display in `pcli`

pcli/src/fetch.rs
After merge of #283, `penumbra` is no longer a valid base denomination (in favor of `upenumbra`). This causes an error when syncing (discovered by @plaidfinch):
```
Error: invalid asset denomination: penumbra
```
This PR just adds debug output for the future to display which asset denom is invalid
=> pcli: add asset denom to error output when syncing asset registry

README.md, docker-compose.yml, pd/src/main.rs, scripts/docker_compose_freshstart.sh, scripts/setup_validator.py
The fresh start script now integrates the `create-genesis-template` command, uses a persistent directory mount for tendermint configs, and uses the tendermint testnet setup command.
Closes: #267
=> Integrate create-genesis-template into validator setup script, groundwork for multi-node

crypto/src/asset/registry.rs, stake/src/token.rs
This prevents the denomination from being awkwardly line-wrapped by software that interprets a - as an opportunity for wrapping.
=> crypto,stake: change delegation token denoms to use underscores

spec/SUMMARY.md, spec/stake.md, spec/stake/arithmetic.md, spec/stake/tokens.md
this PR specifies fixed-point arithmetic for computing:
* base exchange rate
* commission rate
* validator reward rate
* validator exchange rate
* validator voting power adjustment
by adding an extra section to the Staking and Delegation part of the spec called "arithmetic".
Closes #271
=> specify fixed-point arithmetic for rate calculations

crypto/src/asset.rs, crypto/src/asset/cache.rs, crypto/src/asset/denom.rs, crypto/src/asset/registry.rs, crypto/src/note.rs, crypto/src/proofs/transparent.rs, crypto/src/transaction.rs, crypto/src/transaction/builder.rs, crypto/src/value.rs, pcli/src/fetch.rs, pcli/src/main.rs, pd/src/app.rs, pd/src/genesis.rs, pd/src/verify.rs, stake/src/epoch.rs, stake/src/token.rs, wallet/src/state.rs
This terminology is clearer, per discussions with @redshiftzero @zbuc @plaidfinch.
=> Rename `BaseDenom`->`Denom`, `DisplayDenom`->`Unit`.

pd/src/app.rs, pd/src/lib.rs, pd/src/sequential.rs
This change attempts to fix an issue observed on the testnet where the node
stalled.  Investigating revealed that the response future from a `DeliverTx`
message, which is supposed to be processed sequentially, was not being polled.
(perhaps because the thing that would be polling it was waiting on sending
another request first?).
This caused the `App` to not process any *other* requests, as it (correctly)
signaled unreadiness. The root of this problem is that, while the `App`
requires that the request should be processed sequentially, it doesn't actually
take responsibility for doing so (by spawning a new task that would drive the
processing to completion).
This change avoids this failure mode, by changing the `CompletionTracker` that
tracks someone else's execution of a future (and …
=> pd: avoid deadlock by refactoring `CompletionTracker` -> `Sequencer`

pd/src/main.rs
The `tower-abci` `Server` state machine's event loop selects over readiness of
either the stream of incoming requests, or the stream of responses to those
requests.  Once it receives a request, it checks which service should process
the request, and *then* waits for that service to become ready.  While it
waits, it doesn't drive the response futures to completion.
Increasing the buffer size adds more slack to the system and seems to make the
problem go away for now.
=> pd: temporarily increase buffer size to work around probable tower-abci bug

crypto/src/asset/denom.rs, pcli/src/main.rs, wallet/src/state.rs
This implements two changes to make the output of `pcli balance` nicer:
- Assets are now printed in a stable order (determined by comparing their base denominations as strings)
- The pending change and pending spend columns are now aligned as columns for easier reading
=> Align pending balance display and stabilize asset printing order

crypto/src/address.rs
Instead of referring to an address version as a "network ID", refer to it as an "address format"
=> Change address version mismatch error to be more correct

pcli/src/command/balance.rs
In #319 I split up the `pcli` command implementations, but reversed the meaning
of the `balance` needs-sync check.
=> pcli: fix bug introduced in refactoring

pcli/src/command/addr.rs, pcli/src/main.rs
Some of the offline commands still need a state file, so it's easier to have
common code if we ensure the state is always available, rather than forcing
subcommands to load it on their own.
=> pcli: streamline state handling

pd/sqlx-data.json, pd/src/app.rs, pd/src/state.rs, stake/src/rate.rs
This PR:
- factors out the rate calculations from App.end_block and puts them in the stake crate
- adds the computation of the validator reward rate based on the commission rate calculated from the sum of their funding streams
=> refactor rate calculations into stake crate

pcli/Cargo.toml, pcli/src/command.rs, pcli/src/command/stake.rs, pcli/src/command/tx.rs, pcli/src/command/validator.rs, pcli/src/main.rs, pd/src/wallet.rs, proto/proto/stake.proto, proto/proto/thin_wallet.proto, stake/Cargo.toml, stake/src/delegate.rs, stake/src/lib.rs, stake/src/rate.rs, stake/src/undelegate.rs
WIP code following #321 that tries to map out required internal functionality for staking by sketching an external interface via `pcli`.
=> Stub staking support for pcli

pd/src/app.rs, stake/src/rate.rs
Since we want to eventually have variable reward rates, it seems better to
avoid having a reward rate constant, so that the rest of the API is built
around the idea that the base reward rate for the next epoch is an external
input.
=> stake: avoid BASE_REWARD_RATE constant

crypto/src/lib.rs, crypto/src/proofs/transparent.rs, crypto/src/value.rs, stake/src/delegate.rs, stake/src/undelegate.rs, transaction/src/action.rs, transaction/src/action/output.rs, transaction/src/genesis.rs, transaction/src/transaction.rs, transaction/src/transaction/builder.rs
Previously, we treated the value commitment in an output description as a
commitment to the (positive) value accruing to the output notes, rather than as
a commitment to the (negative) value contributed (i.e., withdrawn) from the
transaction's value balance.  This meant that when summing the value
commitments for each action, we needed to handle spends and outputs
differently, because they had inconsistent signs.
Instead, this commit changes the value commitment of the output description to
commit to the action's contribution to the transaction's value balance (a
negative number).  This means that the semantics of the action (whether it is
contributing or withdrawing) are encapsulated in the action logic, rather than
leaking out to the code that handles the actions.
=> Consistent sign handling for value commitments, and (un)delegate commitments

crypto/Cargo.toml, crypto/src/note.rs, proto/build.rs, proto/src/serializers/hexstr.rs
This fixes the error on latest `main` where `pcli wallet reset && pcli balance` would result in:
```
Error: Could not parse wallet data
Caused by:
tag for enum is not valid, found 64
```
=> Add tests for roundtrip parsing of note commitments, and fix parse error

pd/src/app.rs, pd/src/pending_block.rs, pd/src/state.rs
The changes in #346 #335 change the meaning of the field, so renaming it helps clarify its new meaning.
=> pd: rename PendingBlock::new_assets to PendingBlock::supply_updates

pd/sqlx-data.json, pd/src/app.rs, pd/src/state.rs, stake/src/epoch.rs
Staking actions are supposed to make use of the rates in the epoch in which
they take effect (the next epoch), so we need to compute them in advance. This
commit changes the end-epoch processing to more cleanly model the epoch
transition (it happens after the end of the last block in the epoch) and
precompute the next epoch's rates.
=> pd: make next epoch's rates available

spec/stake/arithmetic.md
this PR updates the arithmetic part of the staking spec to compute the voting power instead of just the voting power adjustment function.
=> update staking arithmetic spec for voting power calculation

crypto/Cargo.toml, pd/migrations/20211216025603_init.sql, pd/sqlx-data.json, pd/src/app.rs, pd/src/pending_block.rs, pd/src/state.rs, pd/src/verify.rs, stake/src/identity_key.rs, stake/src/rate.rs
Work with @plaidfinch on tracking (un)delegations during an epoch.
There are two parts to the database changes:
- a `delegation_changes` table used for tracking the changes to delegation token supplies;
- some `undelegation_*` tables which are not currently used, but will be used for doing unbonding.
In this PR, only the delegation changes are used. We validate the (un)delegate descriptions statefully against the rate data for the next epoch.
=> Track delegations per epoch.

pd/src/verify.rs, stake/src/rate.rs
For undelegations, we enforce correct computation (with rounding)
of the *unbonded amount based on the delegation amount*, because
users (should be) starting with the amount of delegation tokens they
wish to undelegate, and computing the amount of unbonded stake
they receive.
The direction of the computation matters because the computation
involves rounding, so while both
(unbonded amount, rates) -> delegation amount
(delegation amount, rates) -> unbonded amount
should give approximately the same results, they may not give
exactly the same results.
=> stake,pd: use correct rounding for undelegation checks

chain/Cargo.toml, chain/src/params.rs, pcli/src/command/wallet.rs, pcli/src/main.rs, pcli/src/sync.rs, pd/src/wallet.rs, proto/proto/light_wallet.proto, wallet/Cargo.toml, wallet/src/state.rs
This will automatically sync the ChainParams to `pcli` when initially instantiated. There's currently no support for updating chain parameters afterwards. This shouldn't be an issue for now as they're currently static for the lifetime of the chain, but that may not always be the case.
Fixes #329
=> Add tracking of ChainParams to pcli wallet

chain/src/params.rs, crypto/src/asset/denom.rs, crypto/src/merkle.rs, crypto/src/proofs/transparent.rs, pcli/Cargo.toml, pcli/src/command/stake.rs, pcli/src/command/tx.rs, pcli/src/fetch.rs, pcli/src/main.rs, pcli/src/network.rs, pcli/src/state.rs, pcli/src/sync.rs, pd/src/app.rs, pd/src/main.rs, pd/src/testnet.rs, pd/src/verify.rs, pd/src/wallet.rs, stake/src/token.rs, transaction/src/action/spend.rs, transaction/src/transaction.rs, transaction/src/transaction/builder.rs, wallet/Cargo.toml, wallet/src/state.rs, wallet/src/wallet.rs
Closes #45 #48, and does cleanup to `pcli` and the transaction builder code along the way; more details on the steps are in the commit messages.
=> Implement delegations and undelegations

pd/src/app.rs, pd/src/state.rs, pd/src/wallet.rs
This fixes a bug where different parts of the code were writing asset IDs to
bytes in different ways (either as a 32 byte array, or as that array wrapped in
a proto encoding), causing lookups to fail.
=> pd: change asset_lookup to take asset::Id instead of bytes

pcli/src/command/stake.rs
This fixes a problem where a failed delegation command would wrongly commit the client state.
=> pcli: remove extra .commit() call

pd/src/app.rs, pd/src/pending_block.rs, stake/src/funding_stream.rs, stake/src/rate.rs
closes #42 
this PR adds commission rewards processing to the EndBlock phase of consensus, by inserting notes for each validator's funding stream. the reward is calculated using the formula from the spec, that is 
`yv*cv,e*re*ψ(e−1)`
where yv is the total number of delegation tokens, cv,e is the rate for the funding stream, re is the base reward rate for the epoch, and psi(e-1) is the base exchange rate for the previous epoch. 
these notes are constructed using a zero ephemeral key and are assigned a 0 transaction ID in their `NoteData`.
=> implement validator commission rewards

pcli/Cargo.toml, pcli/src/command/wallet.rs, pcli/src/state.rs
This avoids the problem where on some systems, the /tmp directory is mounted on a different
filesystem than the /home directory, which leads to a failure to persist the wallet data when
committing the state.
=> Use temp files in the `pcli` data directory

config/Caddyfile, crypto/src/address.rs, crypto/src/lib.rs, pcli/src/command/wallet.rs, pcli/src/main.rs, pd/src/genesis.rs
This means we don't have to do DNS/config changes every time we redeploy a testnet.
=> Move to testnet.penumbra.zone, eliminate hardcoded CURRENT_CHAIN_ID

pcli/src/network.rs
For some reason, the Thelxinoe testnet node doesn't wrap the result of tx submission in a `result` object, as happens on local testnets (??).  This fixes the problem for now.
=> pcli: avoid problem with response codes on thelxinoe testnet

crypto/src/value.rs
2+-digit numbers without denomination names should not be parsed as `Value`s; they should be
rejected before they are even checked in the asset registry. This one-line change to the regex fixes
this problem, at the cost of preventing all assets beginning with a digit. This is fine, because we
couldn't handle those cases anyhow! (see
https://github.com/penumbra-zone/penumbra/issues/349 for more discussion of this issue).
=> Fix regex bug that parsed "10" as a `Value`

pd/src/pending_block.rs, wallet/src/state.rs
The ephemeral public key needs to be derived using the diversified generator
for the note, in order for the recipient to be able to scan it correctly.
We can apply this in-place on Thelxinoe; the existing notes will be undetected, but future notes will be constructed correctly.
=> Fix funding stream note detection bug

pd/Cargo.toml, pd/sqlx-data.json, pd/src/state.rs, pd/src/state/jellyfish.rs
Adding enum to be able to use `jellyfish::Key::T.hash()` for generating unique `HashValue`s for relevant types, utilizing the `Hasher` generated by `jmt`'s 'define_hasher!` macro.
Depends on changes to `jmt`: https://github.com/penumbra-zone/jmt/pull/9
=> Add jmt key enum

wallet/src/state.rs
Since they're spent, we don't need to ever produce an auth path for them, so we
can prune them to reduce the size of the NCT.
=> wallet: remove authentication paths for spent notes

pcli/Cargo.toml, pcli/src/command/wallet.rs, wallet/src/state.rs
This makes `pcli wallet reset` _much_ faster. Two changes:
1. The `File` used as a `Read` for `serde_json::from_reader` when parsing the `penumbra_wallet.json` is now wrapped in a `BufReader`, which _dramatically_ accelerates parsing.
2. The `wallet` field of `ClientState` is now listed _first_ in the struct, which means that it will be written out first in the JSON encoding. This should mean that when clients perform a single wallet reset using this new code, their wallet will be rearranged in all of the future such that extracting the spend seed is very fast, since it comes first, and therefore all future resets will be even quicker, even if the data contained is very large.
=> Faster `pcli wallet reset`

crypto/Cargo.toml, pd/Cargo.toml
This unbreaks the jmt dependency following the migration to a new main jmt branch by pointing pd at the legacy repo for now.
=> Point jmt dependency at renamed jmt branch

spec/concepts/transactions.md, spec/penumbra.md, spec/protocol/addresses_keys.md
Walking through the spec, I found a few deadlinks and corrected them. From what I could tell, they were all relative links that became outdated, so my fixes will fall victim to the same problem later if there is another shuffle of the protocol's documentation outline.
=> corrected deadlinks in spec

pd/sqlx-data.json, pd/src/consensus/worker.rs, pd/src/state/reader.rs
Fixes the issue described in #402 where inactive validators without rate data for the given epoch don't return their last rate data.
=> Update rate data query to select most recent rate data

pd/src/state/reader.rs, pd/src/wallet.rs, proto/proto/light_wallet.proto, wallet/src/state.rs
=> Use `u64` to represent block heights in light wallet `CompactBlock`

pd/src/main.rs
> [If your testnet blockchains do not have unique chain IDs, you will have a bad time. ](https://docs.tendermint.com/master/tendermint-core/using-tendermint.html)
=> pd: randomize testnet IDs

spec/crypto/flow-encryption/threshold-encryption.md
Earlier there were only two properties that we needed, now there are three (+Robustness), and a previous version of the spec had group elements in the sigma protocols as r,s, and now they are \alpha, \gamma. This PR fixes those typos. Thanks @samczsun for the catch
=> fix typos in threshold spec

crypto/Cargo.toml
Hit a build error on `main` (https://github.com/penumbra-zone/penumbra/runs/5308110178?check_suite_focus=true) upon merge of #430 due to an upstream change in `f4jumble`
This PR pins `f4jumble` to a specific commit hash for stability
=> deps: pin f4jumble

pd/Cargo.toml, pd/src/consensus/service.rs
In v0.7 of `tokio-util`, the `PollSender` API was changed to have the
semantics that most users expect (see tokio-rs/tokio#4214). The
`poll_send_done` method was replaced with a `poll_reserve` method, and
the implementation rewritten to drive a `Sender::reserve_owned` future
that's consumed in `send_item`. Now, `PollSender` essentially implements
exactly the same code that was written by hand in the consensus service.
We can simplify the consensus service significantly by upgrading the
`tokio-util` dependency to 0.7 and replacing the hand-written version
with `PollSender`.
There should be no functional change as a result of this refactor.
=> pd: use `tokio_util::sync::PollSender` in consensus svc

pd/Cargo.toml, pd/build.rs, pd/src/main.rs, pd/src/testnet.rs
This uses the build script to compute the chronologically most recent testnet and embed the allocations and validators of it in the binary, which means several things:
1. Running `pd generate-testnet` is no longer dependent on being run from the root of the `penumbra` repository, as it previously implicitly was.
2. Running `pd generate-testnet` now appropriately uses the latest available testnet as a default for the chain id, allocations, and validator set, although each can be individually overridden by a command line flag as before.
3. We do not need to maintain these defaults every time we do a new testnet (and indeed, we had forgotten to maintain them before; I found this issue because they were still pointed at Thelxinoe).
This also incorporates a smattering of improvements to error …
=> Automatically detect latest testnet when generating testnet

chain/src/params.rs, pd/src/main.rs, proto/proto/chain.proto
this PR adds `ibc_enabled`, `inbound_ics20_transfers_enabled`, and `outbound_ics20_transfers_enabled` chain parameters in preparation for our IBC implementation. Addresses #466
=> add IBC chain parameters

pd/src/main.rs
This will automatically insert a 1 upenumbra allocation to each validator's `0` payment address during `generate-testnet`.
=> Add a 1 upenumbra allocation to each genesis validator

.github/workflows/smoke.yml, README.md, docker-compose.yml, scripts/docker_compose_freshstart.sh
Closes #475 (https://github.com/penumbra-zone/penumbra/issues/475#issuecomment-1063425837 I'll put in a new ticket since that's a good next step)
This adds a gh action that builds and runs a testnet for a configurable amount of time. It will fail the job (non-zero exit code from pd) if a crash is encountered in that time. See [here](https://github.com/redshiftzero/penumbra/runs/5487945502?check_suite_focus=true) for a successful build and [here](https://github.com/redshiftzero/penumbra/runs/5487953621?check_suite_focus=true) for a failed build where a panic occurred during `InitChain`. 
Currently this is configured to run only on the `main` branch since the job is slow. I think it's better to put slow jobs on `main` and act on build failures, but if we are finding that we're having a lot …
=> ci: add gh action with pd smoke test

proto/Cargo.toml, proto/build.rs, proto/src/lib.rs
This is a small PR that exposes the `ibc` proto types as part of the `proto` crate.
=> expose IBC module in `proto`

decaf377-fmd/src/clue_key.rs, decaf377-fmd/src/detection.rs, decaf377-fmd/src/error.rs, decaf377-fmd/tests/fmd.rs
This PR implements #82, it's still a draft but the main parts are here. Beside evaluating whether adding nice-to-haves (e.g. `Zeroize` on `ClueKey`), fmt and tests, I need to improve error propagation if `ensure_at_least` fails.
=> feat(decaf377_fmd): improve subkey generation logic

crypto/Cargo.toml, crypto/src/merkle.rs, pd/Cargo.toml, pd/src/state/jellyfish.rs, pd/src/state/writer.rs
Retarget `jmt main` from `penumbra` following asyncification. Closes #486.
=> Implement needed changes following refactor and asyncification of the JMT crate

scripts/docker_compose_freshstart.sh
The docker-compose files only work when it's set to $HOME/scratch/testnet_build, so we might as well hardcode that path.
=> Hardcode build path in freshstart script

.github/workflows/smoke.yml
While it's nice to get pre-merge checks, this change avoids two problems:
- it avoids spawning many ephemeral CI runs;
- it means we don't get into the habit of skipping checks.
=> Only run smoke test on successful pushes to `main`

pd/src/components.rs, pd/src/components/app.rs, pd/src/components/component.rs, pd/src/components/shielded_pool.rs, pd/src/lib.rs, pd/src/storage.rs, pd/src/storage/write_overlay_ext.rs
Notes from Discord are below -- though the actual design ended up being
slightly different, handling init_chain as a special case, and splitting out
separate check_tx_stateless and check_tx_stateful methods.
Another addition to the design in the notes is the WriteOverlayExt trait; if
we're encoding data into the tree, it's much easier if we encode it using our
existing, proto-based encoding framework.
> some thoughts on a new design for our state handling:
> as a prerequisite, we'd shift all of our persistent state to be recorded in a rocksdb-backed jellyfish tree, eliminating postgres entirely
> this has a bunch of advantages, but one really important one is that it means that our apphashes are actually hashes of the entire application state, which improves replicability. another is that …
=> Sketch an application/component interface.

pd/src/components/app.rs, pd/src/components/component.rs, pd/src/components/ibc.rs, pd/src/components/shielded_pool.rs
This commit makes three changes to the `Component` trait:
- it adds `Result`s even to methods that are "logically" infallible, like execution, so that internal errors can be more easily propagated upwards via ? to the original caller, who can decide whether to panic;
- it changes `new` to be an `async` method, so that constructors can read data from the state and cache it internally (e.g., a note commitment tree);
- it changes `&self` to `&mut self` so that components can edit their internal data while doing things.
=> Make the `Component` trait more usable

pd/src/storage/write_overlay_ext.rs
The `put` methods shouldn't return anything, because they're infallible -- we can always write a key to the overlay.
=> Correct WriteOverlayExt trait signatures

chain/src/note_source.rs, chain/src/sync.rs, crypto/src/merkle.rs, crypto/src/note.rs, crypto/src/nullifier.rs, pd/src/components/app.rs, pd/src/components/shielded_pool.rs, transaction/Cargo.toml, transaction/src/transaction.rs
Work towards #505.  This is a good worked example of our new `Component` structure, and has most of the shielded pool functionality, but it does *not* implement:
- quarantining -- per discussion on #463, we may need to rework that approach, but that code got backburnered in favor of fixing the application architecture;
- stateless validation -- that code will change with #489, so it's better not to reimplement it before that lands;
- supply and denom tracking -- because we may want to change how that's exposed in the wallet RPC.
=> First-pass implementation of the shielded pool as a `Component`

pd/src/components/app.rs, pd/src/lib.rs, pd/src/storage.rs, pd/src/storage/penumbra_store.rs
This trait is motivated by the need to have multiple application components
that access common data.  So far we've had the idea that there are going to be
sub-trees of the JMT for the different application areas, like shielded_pool/,
ibc/, staking/, etc, and that each component is responsible for managing the
state in there, and that we handle "transactions affecting multiple areas" by
"each area does its part separately".
However, there's going to be some cases where we'd want to have different
components accessing common data -- like the epoch_duration.  In individual
components, most of the actual "business logic" of the component is separated
from accesses to the state store, by means of accessor methods that just handle
interfacing with the tree.
This is obviously a good approach, …
=> Add a `PenumbraStore` extension trait for accessing common data.

Cargo.toml
xref https://github.com/penumbra-zone/tower-abci/pull/14
=> Remove git-pin on tracing now that tower-abci no longer needs it.

crypto/src/proofs/transparent.rs, pd/src/verify/stateless.rs, proto/proto/transaction.proto, proto/proto/transparent_proofs.proto, transaction/src/action/output.rs, transaction/src/action/spend.rs, transaction/src/transaction.rs, transaction/src/transaction/builder.rs
Related to #450 
In benchmarking PLONK libraries, it turns out circuit preprocessing can take a significant amount of time (for jellyfish, ~seconds), so having custom circuits based on the actions in each transaction may introduce significant performance implications (or complexity trying to reduce the performance hit, e.g. by caching circuits for common sets of actions in a transaction). For now we'll back out the proof lifting changes.
=> Revert proof lifting

pd/src/components/app.rs, pd/src/consensus/worker.rs, pd/src/storage.rs
The initial sidecar use of the `App` code didn't call `commit` following `init_chain`, so the genesis state was never actually committed.
However, trying to commit that state causes new problems, which are probably related to the JMT's handling of the empty tree:
```
Mar 31 14:55:03.809 DEBUG abci:InitChain{chain_id="penumbra-orthosie-23a3e8b8"}:commit: pd::storage: node_key=NodeKey { version: 0, nibble_path:  } value=None
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /Users/hdevalence/.cargo/git/checkouts/jellyfish-merkle-6b18a07b8fd5fec6/445c51a/src/tree_cache.rs:188:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
=> Commit App state following init_chain

pd/src/pending_block.rs
We didn't finish implementing the client-side logic before realizing we needed
a better internal architecture, so the quarantining isn't usable at the moment,
and delegation/undelegation functionality therefore doesn't work.  In order to
avoid having to fix this simultaneously with the port to the new architecture,
temporarily disable quarantining, processing all notes immediately.  Once we
finish the port, we can reintroduce the quarantine logic simultaneously with
the required changes to the client protocol and to the (new) architecture.
=> Disable output quarantining.

pd/src/components/app.rs, pd/src/storage/penumbra_store.rs
This PR adds some methods to `PenumbraStore` and to App::begin_block that stores the block height and block timestamp in the application state, so that components (such as the IBC component) can access them
=> store the current block height and block timestamp in app state

pd/src/consensus/worker.rs, pd/src/state/writer.rs
This commit fixes a problem where the `chain_params` key of the JMT was
mysteriously unavailable, even though it had been written, causing a crash.
The problem was that although we started using the JMT in the new component
code, we didn't remove its use from the legacy Postgres state.  This caused the
legacy postgres code to clobber the tree roots, so although the tree roots were
actually written to the backing store, they were inaccessible, because the
roots had been overwritten with ones that didn't point to those leaves.
In the short term, the fix for this is to remove the JMT from the legacy state
code, so that there is only one writer.
In the long term, we should probably try to have the `Storage` impl return an
error if it is about to clobber existing data; since the JMT is an …
=> Unlink the JMT from the legacy Postgres state

README.md
Some things aren't ready yet, specifically:
1. Specifying the persistent peers requires the node ID, which is determined by the public key of the node. This will need to be grabbed and filled in when we deploy the next testnet (and we should probably use the same key between testnet deployments to avoid needing to update the value in the documentation)
2. The `genesis.json` file is not available for the newest testnet deployment. We'll want to have these available at a constant well-known URL.
=> First pass at documentation for running fullnodes

pcli/src/command/stake.rs, pd/src/wallet/server/thin.rs, proto/proto/thin_wallet.proto
To do staking transactions, we only need the *next* epoch's rate data, not any
historical rate data.  Restricting the RPC to only what we actually need will
make porting the staking component much easier.
=> pd: change RPC to only provide the next epoch's RateData

.github/workflows/integration.yml, .github/workflows/rust.yml
This will hopefully avoid duplicate CI jobs.  We don't generally have ongoing
work in branches that doesn't have a (draft) PR.
=> Only do CI runs on pull_request, not push

proto/src/protobuf.rs
This works exactly like `.into()`, but does not require type inference to
ensure that it produces the protobuf type.
=> proto: add Protobuf::to_proto()

pd/src/components.rs, pd/src/components/shielded_pool.rs
This allows other components to read relevant data stored by the ShieldedPool component, initially just the token supply.
This is needed for #507, which needs to be able to read the delegation token supplies.
=> pd: add ShieldedPoolStore extension trait

pd/src/consensus/worker.rs, pd/src/info.rs, pd/src/state/writer.rs
We now report the AppHash from the RocksDB-backed JMT code, since we don't have
a JMT implementation in the legacy implementation any more.  This means that
the node will fail to restart, because (until this commit) it would query the
Postgres instance for the app hash, returning a dummy value.
Also this revealed that the height cache / notification channel thing never
even worked.  We need to trash all of this code ASAP
=> "Correctly" report AppHash in Info messages

pd/src/consensus/worker.rs
This is a temporary workaround for #558 for Orthosie deployment
=> temp: do not process validator definitions

docker-compose.multinode.override.yml
This way by default `docker-compose` without arguments will use a single-node testnet but we can easily change to multinode for testing.
=> Separate multinode configuration into a new override file

pd/src/consensus/service.rs, pd/src/consensus/worker.rs, pd/src/lib.rs, pd/src/main.rs, pd/src/mempool.rs, pd/src/mempool/message.rs, pd/src/mempool/service.rs, pd/src/mempool/worker.rs
Closes https://github.com/penumbra-zone/penumbra/issues/521
Currently, the new mempool is threaded through the old mempool, and its
processing is executed on a newly spawned task, with the results printed to a
tracing event and then forgotten.  This lets us compare validation results
against the old code (they're currently different, because of missing reward
notes causing NCT root divergence), and then drop the old mempool when we
migrate.
=> pd: add a new, Component-based mempool.

pd/src/components/shielded_pool.rs, pd/src/components/staking.rs, pd/src/verify/stateless.rs
Closes #565
This contains the migration of the (relevant) stateless checks into the `ShieldedPool` component. Everything in the stateful checks has already been migrated to either the `ShieldedPool` or the `Staking` component.
=> refactor: migrate verification checks to relevant `Component` 

crypto/src/merkle.rs, crypto/src/note.rs, pd/src/components/shielded_pool.rs
The initial implementation of the `ShieldedPool` didn't make much use of the `View` trait. This commit moves all of the tree access (with the exception of the raw NCT data, which isn't protoized and will be replaced by the TCT) into the `View` trait so it can be used by other things (e.g., RPC)
=> pd: move functionality into ShieldedPool's View trait

crypto/src/merkle.rs, pd/src/components/app.rs, pd/src/components/ibc.rs, pd/src/components/shielded_pool.rs, pd/src/components/staking.rs
This PR changes the methods in the `App` impl of `Component` to create top-level spans for each of the component methods, and changes the methods in all of the other components' `Component` impls to have spans with only the name of the component.
This lets us watch what the `App` is doing, whether it's in the mempool:
```
Apr 08 00:28:55.884 DEBUG abci:CheckTx{kind=New txid="f83ecfc5ae93ba6422670ab26a7c794cbd25b11eb3ccf2e0aee633a6e66db6cb"}:check_tx_stateful:shielded_pool: jmt: key_hash=KeyHash("39a6276c184e99911c0fc0664ec54ebf49d4e185c59a54fb3b429083ac6aa6e0") key=b"shielded_pool/valid_anchors/04fc076435b20be65816ced9435de189c5b06a71bcfad7d4b6439b238280aa07"
Apr 08 00:28:55.884 DEBUG abci:CheckTx{kind=New txid="f83ecfc5ae93ba6422670ab26a7c794cbd25b11eb3ccf2e0aee633a6e66db6cb"}:check_tx_st …
```
=> Better `Span` handling in `App` and `Components`

pd/src/components.rs, pd/src/components/app.rs, pd/src/components/component.rs, pd/src/components/ibc.rs, pd/src/components/shielded_pool.rs, pd/src/components/staking.rs, pd/src/consensus/service.rs, pd/src/consensus/worker.rs, pd/src/info.rs, pd/src/info/light_wallet.rs, pd/src/info/thin_wallet.rs, pd/src/lib.rs, pd/src/main.rs, pd/src/mempool/worker.rs, pd/src/storage.rs, pd/src/storage/overlay_ext.rs
Following #571, this switches over to use only the `Storage` backend and the new code.  It doesn't delete all of the old code; that's for a later PR.
=> Switch to new JMT, `Component` state machine from Postgres

pd/src/main.rs
This might be helpful for cases where #601 is caused by a user error rather than a bug on our end.
=> pd: add context to `Storage::load` errors

.github/workflows/notes.yml
This requires using nightly rust for docs, since the `--enable-index-page` option is unstable.
=> docs: add index page to rustdoc

pcli/src/command/stake.rs, pcli/src/fetch.rs, pcli/src/main.rs, pcli/src/network.rs, pcli/src/sync.rs, pd/src/info.rs, pd/src/info/oblivious.rs, pd/src/info/specific.rs, pd/src/main.rs, proto/build.rs, proto/proto/client/oblivious.proto, proto/proto/client/specific.proto, proto/src/lib.rs
This should close #611; we might as well clean up the naming for the request types while we're doing it, since the current names don't make much sense.
TODO: update the rest of the code to fix import paths.
=> proto: better naming for client (sub)protocols

testnets/007-herse/genesis.json
There was a json RPC element in the Genesis file, because of which Tendermint would not start with it, and gave an error. I've installed the corrected Genesis that works in Tendermint.
=> Corrected Genesis

pcli/Cargo.toml, pcli/src/command/validator.rs, pd/src/components/staking.rs
Closes #648
Along the way to this, I noticed that we have a lot of overlapping "validator"
structures, and maybe we should try to streamline those later?
=> pcli: add validator template-definition and fetch-definition commands

.github/workflows/deploy.yml
In the future we'd properly utilize Docker and Kubernetes or something for deployment, but this will work for the moment.
=> Deploy to testnet-next automatically on pushes to main branch

pd/src/consensus/worker.rs
This sends validator power back to Tendermint, as it's been verified working
=> Send tm validator updates

crypto/src/keys/diversifier.rs, crypto/src/keys/fvk.rs, proto/build.rs, proto/proto/crypto.proto, proto/src/serializers/bech32str.rs
This will be useful for things like `pwalletd` where we want to give only viewing capability.
=> crypto: make FullViewingKey serializable

docs/protocol/src/SUMMARY.md, docs/protocol/src/concepts/validators.md
There was nothing in the spec about how validators work and the original ticket seemed like a good starting place: https://github.com/penumbra-zone/penumbra/issues/375
=> Add validator spec doc based on original ticket

.github/workflows/notes.yml
There are two versions of the tendermint crate floating around our dep tree:
- a version from our own fork, which we started using because it took a long
time to get the ABCI domain types changes merged upstream;
- another version, pulled in by some ibc-rs code.
We can only document one of them, so we had to specify; I picked the one with
the higher version number, but the version with the ABCI domain types actually
has a *lower* version number for some reason, so we were rendering the wrong
version.  This is a bit of a mess, and we should figure out if we can get off
of it.  However, any movement to a published version of the Tendermint crate
will likely be short-lived anyways, since we should move to ABCI++, and we'll
need a feature branch to do those changes.
=> docs: render the version of the tendermint crate with ABCI

.cargo/config, pcli/Cargo.toml, pd/Cargo.toml, pd/src/consensus/service.rs, pd/src/main.rs, pd/src/mempool/service.rs, pd/src/storage.rs, wallet/Cargo.toml
This commit adds initial support for the [Tokio Console], using the
basic [`console_subscriber::init`] API.  This should not interfere with
the existing logging configuration using `tracing`, as
`console_subscriber::init` is essentially a superset of
`tracing_subscriber::fmt::init`. Note that the console filter
configuration does not interfere with the filter configuration for
logging.
The console endpoint is served on the default address,
http://127.0.0.1:6669/. 
Future commits will improve the console instrumentation by configuring
the console endpoint using `pd`'s command line arguments, adding the
filter reloading described in
https://github.com/penumbra-zone/penumbra/issues/13#issuecomment-1100969950,
and integrate Tokio Console with the existing Grafana setup, but this is
a working …
=> pd: initial tokio-console integration

ibc/src/lib.rs, pd/src/components/ibc.rs
Many of the IBC message types are enums, where the number of variants differs depending on the build configuration, meaning that the fallthrough case gets marked as unreachable only when not building in test configuration.
Should these be marked `#[non_exhaustive]` upstream?
=> ibc: suppress warnings of unreachable patterns

transaction/src/action/output.rs
The default impl printed each byte value individually, which is really
unhelpful, but since the data is encrypted there's not much point in showing it
anyways.
Related to #532
=> transaction: hide encrypted_note from output::Body Debug

pd/src/consensus/service.rs, pd/src/mempool/service.rs
Currently, if the consensus worker task panics (or terminates
unexpectedly), the rest of the `pd` process will simply continue
running. This is because the consensus `Service` calls `.expect(...)` on
the oneshot reciever from the worker task, and the `tower_acbi` server
may spawn the response future in a background task whose panicking may
not be propagated. Additionally, it is possible that the `Service` may
be driven to readiness successfully before the worker panicked or
terminated. If this occurs, the message will be sent successfully, but
the worker task may never respond.
This branch should fix these issues by changing the consensus service
to:
1. proactively check if the worker is still there in `call`, and return
a failed response future if the worker has died;
2. return a …
=> pd: fail service if consensus worker task panics

.github/workflows/deploy.yml
Maybe even better would be to nuke the local repo and clone it again?  Or maybe that's a pointer that we should have a less duct-tape-and-bailing-wire approach ahaha...
=> ci: add cargo update step to deploy

.github/workflows/deploy.yml
The previous workflow broke with #691; I used `rg testnet_build` to try to find
all references to the old paths, but the deployment workflow is in the
`.github/` directory, which ripgrep ignores by default.
=> ci: update deploy workflow

pd/src/components/staking.rs
The first attempt at implementing this functionality in #678 ignored the
`signed_last_block` field that records whether or not a validator actually
voted.  This commit uses it, and testing locally shows that it records missed
blocks (upload a validator definition with a random consensus key, delegate to
it, watch its missed block counter increase...).
=> pd: fix vote tracking in staking component

docs/guide/src/pcli/install.md, docs/guide/src/pd/build.md, docs/guide/src/pd/join-testnet/validator.md
This PR fixes a few minor issues in the validator guide.
- Makes dependency on `clang` explicit, as recommended in #659.
- ~~Drops `-n testnet-preview.penumbra.zone` from "Updating your validator" (most people will not want to use the preview deployment.~~ Someone beat me to this!
- Makes explicit that validators must restart Tendermint after setting `mode = validator` in the Tendermint config.
=> Guide fixes

pd/src/request_ext.rs
It's not really useful to include the hash in the BeginBlock span, because the
other spans don't include it, so we don't have a way to filter all of the
processing of a block by its hash, and because Tendermint has finality, so it's
just as easy to identify a block by height as by hash.
Also, use a plain integer value in the span for consistency with the other messages.
=> pd: make the BeginBlock span smaller

ibc/src/client.rs, ibc/src/connection.rs, ibc/src/lib.rs, pd/src/components/ibc.rs, pd/src/components/ibc/client.rs, pd/src/components/ibc/connection.rs, proto/proto/ibc.proto
this PR scaffolds out an ibc connection handling component, and adds support for handling `ConnectionOpenInit`. Closes #640.
=> scaffold IBC connections component, add ConnectionOpenInit handling

component/src/lib.rs, pd/src/components/app.rs, pd/src/components/ibc.rs, pd/src/components/ibc/client.rs, pd/src/components/ibc/connection.rs, pd/src/components/shielded_pool.rs, pd/src/components/staking.rs, pd/src/consensus/worker.rs, pd/src/info.rs, pd/src/info/oblivious.rs, pd/src/info/specific.rs, pd/src/mempool/worker.rs, storage/src/lib.rs, storage/src/overlay_ext.rs, storage/src/storage.rs
This is a better word, because instead of giving an implementation detail
("it's an overlay over the persistent storage"), it gives the semantics: "it's
an instance of the application state".
(There should be additional documentation, but this commit just does the name change).
This was on the way to #709, but I split it out since there's a potential complication on that effort in re: transaction structuring, and it's better to not risk a delay in merging broad-touching refactoring.
=> storage: rename Overlay to State

docker-compose.multinode.override.yml, docker-compose.yml, pcli/src/main.rs, pcli/src/network.rs, pd/src/main.rs
We currently have two different client RPC endpoints in `pd` for no real
reason, other than that I don't think I realized that it was possible to have
multiple gRPC services on one endpoint when I wrote the original skeleton code,
and then we just copied that structure forward.
This commit unifies them onto a single service on port 8080.
=> pd: unify gRPC services

.github/workflows/notes.yml, component/Cargo.toml, ibc/Cargo.toml, pcli/Cargo.toml, pd/Cargo.toml, pd/src/components/ibc/connection.rs, proto/Cargo.toml, stake/Cargo.toml
this PR unifies the version of tendermint-rs that we are using to `0.24.0-pre.1`, across ibc-rs and the main penumbra crates.
=> update to upstream tendermint 0.24.0-pre.1

pd/src/components/app.rs, pd/src/components/shielded_pool.rs, storage/src/lib.rs, storage/src/overlay_ext.rs, storage/src/storage.rs
This commit changes the `State` typedef to use an `RwLock` instead of a
`Mutex`.  This allows concurrent read access to a shared `State`, which means
(because of the split between validation and execution in the `Component`
trait) that we can execute the `check_tx_stateful` methods of every `Component`
concurrently, even in the serial `consensus::Worker`.
=> storage: replace State Mutex with RwLock

pd/src/components/ibc/connection.rs
this implements the connectionOpenAck and connectionOpenConfirm phase of the IBC connection handshake. This should complete the connection handshake work, though it is still untested
closes #641
=> ibc: implement connection open ack and connectionOpenConfirm handling

docs/guide/src/dev/sqlx.md
The lack of indenting destroyed the markdown list.
=> docs: correct formatting in SQLX instructions

Dockerfile.dev, pd/src/consensus/worker.rs, stake/src/component.rs
This refactors the tendermint validator power handling to be managed in-memory during the course of the block, making it easier to report only updates to tendermint, as well as not report 0 power for new, inactive validators.
=> Fix tendermint validator power handling

proto/proto/wallet.proto, wallet-next/Cargo.toml, wallet-next/src/lib.rs, wallet-next/src/service.rs, wallet-next/src/storage.rs, wallet-next/src/worker.rs
This commit scaffolds the basic wallet server state machine, which uses a
pub-sub architecture mediated by SQLite:
- a single `Worker` task runs indefinitely, scanning the chain, and writing the
results to SQLite;
- any number of `WalletService` readers can serve gRPC requests.
Along the way, tidy the proto files slightly for consistency.
Closes #613
=> wallet-next: scaffold the wallet server state machine

pd/src/main.rs
This should fix an issue with Sponde, where we didn't delegate additional
tokens beyond the bare minumum to the testnet validator, causing the chain to
halt when someone else declared a validator with a different genesis file,
which then had far more consensus weight.
=> pd: increase genesis validator delegation in generate-testnet

ibc/src/component.rs, ibc/src/component/client.rs, ibc/src/component/client/stateful.rs, ibc/src/component/client/stateless.rs
This splits up the stateful and stateless validation checks for the IBC client component into many little functions that each do one check.
Co-Authored-By: Ava <ava@penumbra.zone>
Co-Authored-By: redshiftzero <jen@penumbra.zone>
=> ibc: refactor client validation

docker-compose.prod.yml
The docker-compose wasn't persisting the main grafana data directory, causing data loss on container restart.
=> Fix grafana mount path

pcli/src/command/stake.rs
This makes a few changes to list-validators:
- it shows the voting power (unfortunately, this can only be showed in units of "dPEN", rather than penumbra tokens, because we don't expose the base exchange rates in the RPC at the moment);
- it makes the validator identity, the cryptographic root of identity, come first, rather than the freeform text name;
- it adds some color codes.
=> pcli: show voting power in list-validators

shielded-pool/src/component.rs
This produces nice output like
```
2022-05-07T04:04:04.563526Z DEBUG abci:DeliverTx{txid="dd1f840a773cf1fd8925742d65b3cb231539f90d34c1873eca34c04ee274bacf"}:check_tx_stateful:shielded_pool: penumbra_shielded_pool::component: anchor is valid anchor=merkle::Root("878945de86c5006abab1817b130b783783a4c934382902324882709cd6fbfa02") anchor_height=0
2022-05-07T04:04:04.565083Z DEBUG abci:DeliverTx{txid="dd1f840a773cf1fd8925742d65b3cb231539f90d34c1873eca34c04ee274bacf"}:execute_tx:shielded_pool:add_note{note_commitment=note::Commitment(bebb9f09d17cdbf08a54a758882fbc56e7d53922e7536bf6597133f6c8fc9709)}: penumbra_shielded_pool::component: adding note
2022-05-07T04:04:04.565534Z DEBUG abci:DeliverTx{txid="dd1f840a773cf1fd8925742d65b3cb231539f90d34c1873eca34c04ee274bacf"}:execute_tx:shielded_pool:spen …
```
=> shielded_pool: improved tracing for component

ibc/src/component/client.rs, ibc/src/component/connection.rs, ibc/src/connection.rs, proto/proto/ibc.proto
This PR updates the connection component to use the canonical state paths as specified in ICS3, and the canonical protobuf encoding for `ConnectionEnd`.
=> use correct ICS3 state paths, connectionEnd encoding

chain/src/params.rs
Temporarily change the default downtime slashing threshold to try to exercise
those paths of the state machine.
Leaving this open as a PR for now, so we can continue exercising `testnet-preview` on the current state of `main` (it will be wiped on the next push to `main).
=> stake: use aggressive downtime slashing to test state machine

docs/guide/src/pd/join-testnet/fullnode.md, testnets/tm_config_template.toml
`persistent-peers` is designed for persistent connections like validator <> sentry node and ignores backoffs. `bootstrap-peers` is the correct configuration to use for normal validators.
=> Use bootstrap-peers rather than persistent-peers

Cargo.lock, ibc/Cargo.toml, ibc/src/client.rs, ibc/src/component/client.rs, ibc/src/component/client/stateful.rs, ibc/src/component/connection.rs, ibc/src/component/connection/stateful.rs, ibc/src/connection.rs, ibc/src/lib.rs, proto/Cargo.toml, proto/src/lib.rs
This PR removes our wrapper types for the IBC domain types, and instead does `impl Protobuf` directly in the proto crate on the IBC types. Also, the state paths for client related data have been brought into spec with ICS2.
=> remove wrapper types for IBC domain types

storage/src/storage.rs
when we changed how we use the RocksDB API, from `open_default` to `open_cf`, we removed the create_if_missing and create_missing_column_families flag, which exist by default in `open_default`. this was causing our smoke test and the IBC test to fail.
=> storage: create database and column families if they are missing

chain/src/sync.rs, crypto/src/lib.rs, crypto/src/note_payload.rs, proto/build.rs, proto/proto/chain.proto, proto/proto/crypto.proto, proto/proto/transaction.proto, shielded-pool/src/component.rs, transaction/src/action/output.rs, transaction/src/transaction.rs, wallet-next/src/sync.rs, wallet/src/state.rs
We use this structure in multiple places in the codebase, and it's
self-contained (being the minimal data payload needed to identify and scan a
new note).  So moving it into the `crypto` crate makes sense.
More importantly, it frees up the name `OutputBody` for other use.  In order to
have a useful signing/custody protocol, we need to classify transaction data
into *authorizing data* (which describes the actions that signatures authorize)
and *effecting data* (which effects those actions, but is not necessary to
authorize, e.g., proof data).  Then we'll want to have a protocol that allows
us to bundle up only the authorizing data and send it to a signer, who signs an
authorization hash (a renamed sighash) of the authorization data.  However,
this means that we want to pull apart the proto …
=> crypto: rename `transaction::output::Body` to `crypto::NotePayload`

pd/src/components/app.rs, pd/src/consensus/worker.rs, pd/src/mempool/worker.rs, shielded-pool/src/component.rs
This commit fixes a bug introduced in #796, which removed the `new` method from
the `Component` trait, in order to be able to "sideload" a copy of the note
commitment tree kept in a sidecar part of the underlying storage, rather than
in the (merklized) application state.
In that change, the `ShieldedPool` component was changed to take a raw
`Storage`, rather than a `State`, so that it would be able to read the NCT out
on its own.  But it's important that all of the components use the *same*
shared state, rather than each creating their own fork off of the version
currently in persistent storage.
Co-Authored-By: Ava Howell <ava@penumbra.zone>
=> pd: ensure components have shared state

docs/guide/src/dev/sqlx.md, wallet-next/src/service.rs, wallet-next/src/worker.rs
Closes #758, this will cause any errors occurring in the wallet workers to be bubbled up to the wallet service, as well as adds an `mpsc` channel between the worker and the wallet services, so that the worker can shut down when the services halt.
=> Bubble up errors in wallet service/worker, shut down worker when service shuts down

shielded-pool/src/component.rs
This fixes a bug that slipped in during the review process for #807: changing
the code to not `.expect` on errors from the TCT left behind a duplicate API
call with an `expect`, which then panicked, causing a chain halt on the very
first epoch transition.
=> pd: fix crash from TCT misuse

shielded-pool/src/component.rs, wallet/src/state.rs
Previously there were a couple subtle order-of-execution bugs in the shielded pool because we sourced height from the under-construction `CompactBlock`. This PR uniformly uses `get_block_height` throughout the shielded pool to get the height, and it sets it in the compact block immediately upon begin-block. Log messages indicate that the height now correctly reflects the increasing sequence of blocks.
=> Use `get_block_height` as canonical source of block height

wallet-next/src/sync.rs, wallet-next/src/worker.rs
Closes #843 by calling chain_params() from the wallet worker to retrieve the stored epoch_duration
=> Pass epoch duration to sync_to_latest in sync.rs

.github/workflows/deploy-preview.yml, config/Caddyfile
This should fix the inaccessibility of testnet-preview's grafana instance.
=> Use env var for Caddyfile domains

pcli/src/command.rs, pcli/src/command/chain.rs, pcli/src/main.rs
This implements new `pcli chain params` and `pcli chain info` commands.
`pcli chain params` prints the current chain parameters.
`pcli chain info` prints some summary information about the chain. Maybe this would be better off implemented in the general state query interface later on.
Closes #759
=> Add `chain params` and `chain_info` `pcli` commands

.github/workflows/smoke.yml
this adds a wallet to the smoke test config (gonna add allocations in #848 for the corresponding address)
tested this in CI build: https://github.com/penumbra-zone/penumbra/runs/6530949266?check_suite_focus=true
=> ci: setup local wallet for smoke test

docs/guide/src/pd/join-testnet/validator.md
This PR fixes an incorrect flag for validator nodes listed in the docs.
=> Correct flag in testnet instructions

stake/src/component.rs, stake/src/metrics.rs, storage/src/metrics.rs, storage/src/storage.rs
This introduces some simple metrics on validator state and TCT size.
One thing that wasn't clear was how we should handle the missed blocks metric. Missed blocks are only relevant for Active validators, so the metric is only updated for Active validators -- but if a validator transitions out of Active state, the metric won't be updated. Maybe it should be zeroed out if the validator transitions out of Active?
However that would mismatch the state machine code, which never resets the missed blocks counter, even if the validator goes disabled and then active again. I'm thinking we can try the metric as implemented and tweak if needed.
=> Add additional PD metrics for staking and TCT

stake/src/component.rs
This is a small edit with no semantic change intended, meant to prevent future changes to the ordering of clauses in the validator state transition function from causing unintended consequences. It uses `|`-patterns to enumerate all the illegal states that are caught for each error message returned.
=> Enumerate all error states explicitly, making match statement non-order-dependent

Cargo.lock, pd/Cargo.toml
Fixes the memory leak seen when running `pd` for a long time.
=> Use latest console-subscriber; cargo update

pd/src/consensus/service.rs, pd/src/mempool/service.rs
This should allow us to differentiate sources of metrics events.
=> Create MempoolService/ConsensusService spans

view/src/bin/pviewd.rs, view/src/service.rs, view/src/worker.rs
First part of #755. This wraps the NCT with `Arc<RwLock<>>` so it's shared between the `ViewService` and view `Worker`.
=> Use shared NCT between ViewService and Worker

docs/guide/src/pd/join-testnet/fullnode.md
People may need to reset RocksDB when upgrading between testnets. This PR makes a suggestion to that effect.
=> Suggest removing RocksDB on Tendermint error

docker-compose.multinode.override.yml, docker-compose.yml, docs/guide/src/dev/create-testnet.md
0.35.5 contains a p2p-related fix and may improve stability on our testnets
=> update tendermint deployment to 0.35.5

Cargo.lock, proto/proto/view.proto, view/Cargo.toml, view/sqlx-data.json, view/src/bin/pviewd.rs, view/src/service.rs, view/src/worker.rs
This commit does two things:
1. It provides the Worker with a way to notify subscribers when it's learned of a new block;
2. It adds a new RPC method, StatusStream, that streams those height updates to clients, closing the connection when the sync has finished.
This gives view clients a way to wait for the sync process to complete, while receiving progress information along the way.
=> view: add a streaming sync status RPC method.

crypto/src/address.rs, crypto/src/keys.rs, crypto/src/keys/spend.rs, crypto/src/memo.rs, crypto/src/note.rs, crypto/src/proofs/transparent.rs, pcli-next/src/main.rs, pcli/src/command/wallet.rs, pd/src/main.rs, proto/build.rs, proto/proto/crypto.proto, proto/src/serializers/bech32str.rs, transaction/src/auth_hash.rs, wallet/src/wallet.rs
The `SpendSeed` doesn't add anything to the API except complexity, because it's
exactly the same data as the `SpendKey` (in the sense that all of the
`SpendKey` data can be derived from it, and the `SpendKey` contains a copy of
the `SpendSeed`). It's really better thought of as a serialization detail.
This commit renames it to `SpendKeyBytes`, and eliminates most of its uses.  We
can't make it entirely hidden, because we need it to parse existing wallets.
But going forward, we should use the protoized format (introduced in this
commit) with Bech32 encoding.
=> crypto: eliminate SpendSeed

pcli-next/src/network.rs
Now that we don't use `tracing` for progress output, we should be printing output to the user and only using `tracing` for debugging.
=> pcli-next: print tx submissions

pcli/src/sync.rs, pd/src/info.rs, pd/src/info/oblivious.rs, pd/src/main.rs, proto/proto/client/oblivious.proto, view/src/worker.rs
This allows clients to leave connections open to pd, and to be notified
immediately whenever new blocks arrive, rather than having to periodically
poll.  This significantly improves the latency of checking sync readiness,
since if the full node is a block ahead, we don't need to wait a few seconds
for the worker to find out.
=> pd: add keep-alive to compact block streams

ibc/src/component/channel.rs, ibc/src/component/connection.rs, ibc/src/component/connection/execution.rs
this PR refactors the way execution is structured for IBC connections, moving it to its own `execution` module, similar to what we do for channels
=> move connection execution to `execution.rs`

pd/src/info/oblivious.rs, pd/src/metrics.rs
This lets us track sync rates and the number of clients holding open connections to `pd`.
=> pd: add metrics for compact block responses

Cargo.lock, chain/src/sync.rs, view/Cargo.toml, view/src/storage.rs, view/src/worker.rs
The initial version of the view service's sync logic suffered from poor sync
performance as the size of the NCT grows, because it commits the full NCT to
the database on every block.  This causes a massive amount of disk traffic.
In the future, we'll avoid this by using incremental serialization of the NCT,
so that the data to serialize drops from being on the order of megabytes to on
the order of kilobytes.
In the meantime, this is an easy optimization for empty blocks: only commit
changes to the database when the block is nonempty.  Otherwise, if the block
was empty, there was no data to update, except the NCT, which is already
in-memory.
To actually implement this, we have to be a bit more careful, and also add an
in-memory cache for the `last_sync_height` field, update it when we …
=> view: only commit to database on nonempty blocks

view/src/worker.rs
=> view: fix missing notification in empty block sync

tct-property-test/tests/witness.proptest-regressions, tct/src/internal/complete/item.rs, tct/src/internal/complete/node.rs, tct/src/internal/complete/node/children.rs, tct/src/internal/complete/tier.rs, tct/src/internal/complete/top.rs, tct/src/internal/frontier/item.rs, tct/src/internal/frontier/node.rs, tct/src/internal/frontier/tier.rs, tct/src/lib.rs
The only place where laziness actually improves the efficiency of the TCT is along the frontier, because we may overwrite a node's hash without ever making use of it. However, it is not necessary in the complete portion of the tree, because for each internal node, it will either (a) be evaluated when computing the root, or (b) be explicitly forgotten before that time, which requires computing its hash. This change has several benefits:
1. we save space on each node in the internal complete tree structure, because we don't need a `parking_lot::Mutex` to synchronize, and
2. we have a fixed upper bound on the time it takes to compute a root of a tree, regardless of how long it has been since the root was last computed.
This changeset also adds the `Commitment` to the bottom-most leaves of …
=> Make the complete part of the TCT strict for hashes

pd/src/info.rs, pd/src/info/specific.rs, proto/proto/client/specific.proto
this adds ABCI query handling to `pd`, currently only handling one path: `/jmt/key`, which queries the JMT state for an arbitrary key. The query response is a proto-encoded `KeyValueResponse` that contains the value as well as an ICS23 CommitmentProof of that value's inclusion.
=> implement ABCI query interface for JMT

pcli/src/command/addr.rs
Updated addr.rs to make use of `0` for the default value of puli command, `pcli addr show` fixes #941
=> Patch for setting `pcli addr show` default to 0

.github/workflows/rust.yml
The property tests crate for the TCT takes some time to run, because it does a lot of hashing; this PR speeds it up by running it in release mode. This decreases the total CI time spent in the test suite from 15 minutes to 9 minutes.
=> Test tct-property-test using release build

.github/ISSUE_TEMPLATE/release_testnet.md
Prior to creating the release tag, the release manager should make sure we're running on the latest desired version of Tendermint.
=> Add testnet release step of checking for tendermint updates

pcli/Cargo.toml, pcli/src/main.rs, view/Cargo.toml, view/src/bin/pviewd.rs, view/src/service.rs, view/src/storage.rs, view/src/worker.rs
This PR adds an `nct-divergence-check` Cargo feature to `pcli` that causes
the view service worker to explicitly request each and every anchor from `pd`,
then check it against the computed root at that sync height.
Currently, it detects a divergence at height 1472:
```
2022-06-07T22:09:54.503222Z  INFO penumbra_view::worker: nct roots match height=1470 actual_root=Root(25a39ec6e2b5e165a2de6e3e9eb48f1f29667a58809a609ac21df6e336cc2f04) expected_root=Root(25a39ec6e2b5e165a2de6e3e9eb48f1f29667a58809a609ac21df6e336cc2f04)
2022-06-07T22:09:54.528923Z  INFO penumbra_view::worker: nct roots match height=1471 actual_root=Root(92737fbdf5f7788f7c135fd0291a79fa960cb11e3e30923fa48382763866e20f) expected_root=Root(92737fbdf5f7788f7c135fd0291a79fa960cb11e3e30923fa48382763866e20f) …
```
=> Add an NCT divergence check mode to `pcli`

pcli/Cargo.toml, pcli/src/main.rs, view/Cargo.toml, view/src/bin/pviewd.rs, view/src/service.rs, view/src/storage.rs, view/src/sync.rs, view/src/worker.rs
Implementing block-level acceleration accidentally left the epoch finalization code inside the branch where block acceleration is not engaged. It should happen always.
=> Unconditionally end the epoch if needed regardless of block acceleration

Cargo.lock, pcli/Cargo.toml, pcli/src/box_grpc_svc.rs, pcli/src/main.rs
`pcli` may use either an in-process view/custody service, or be
configured to talk to an out-of-process view or custody daemon. This
means that the types of the `tower::Service` given to the `tonic` client
for these services may differ depending on how `pcli` is configured.
Currently, this is handled by splitting out half of the `main` function
into a separate function and making it generic, which is kind of
unfortunate.
This branch adds a `box_grpc_svc` module in `pcli`, with utilities for
type-erasing a local or remote gRPC service. It changes the view service
constructed in `main` to use these utilities and removes the (now
unnecessary) `main_inner`. The `box_grpc_service` module could also be
used to do the same for a custody service, once a standalone custody
daemon is implemented.
I …
=> pcli: Erase gRPC service types

Cargo.lock, pcli/Cargo.toml, pcli/src/command.rs, pcli/src/command/addr.rs, pcli/src/command/balance.rs, pcli/src/command/chain.rs, pcli/src/command/query.rs, pcli/src/command/stake.rs, pcli/src/command/tx.rs, pcli/src/command/validator.rs, pcli/src/command/wallet.rs, pcli/src/main.rs, pd/Cargo.toml, pd/src/main.rs, view/Cargo.toml, view/src/bin/pviewd.rs
The `structopt` crate is a wrapper around a previous version of `clap`.
Now, this functionality is provided by `clap` v3. This commit updates
`pcli` and `pd` to use `clap` v3 rather than `structopt`.
=> Replace use of `structopt` with `clap`

Cargo.lock, pcli/Cargo.toml, pcli/src/command/wallet.rs, pcli/src/legacy.rs, pcli/src/main.rs
Currently, the default data directory is not specified in a `clap`
attribute, but instead determined in `main` after the CLI arguments are
parsed. This is rather unfortunate, because it means that `clap` will
not display the actual data path in the help text, and we have to do
extra path construction after parsing the arguments.
This commit changes `pcli` to specify the default data dir path in
`#[clap(..., default_value_t = ...)]`. This way, the actual default
value is displayed in the help text rather than just saying "[default:
platform appdata directory]".
This required changing the path to be a `camino::Utf8PathBuf`, rather
than a `std::path::PathBuf`. Camino provides a variant of
`Path`/`PathBuf` which is guaranteed to always contain valid UTF-8
(which paths *should* be on any …
=> pcli: path handling improvements

view/src/service.rs, view/src/worker.rs
Closes #932
I've turned down the error level in `view/src/worker.rs:216` to warn because when the `break` is hit here it was causing a spurious error reported to the user (i.e. when running without RUST_LOG)
This was tested against testnet-preview
=> fix: break once the sync to latest_known_block_height is complete

Cargo.lock, pcli/Cargo.toml, pcli/src/main.rs
Currently, users can configure `pcli` with the hostname of a Penumbra
node, the `pd` and Tendermint ports on that node, and the (optional)
address of a `pviewd` instance. However, these configurations must
currently be passed as CLI arguments to *every* `pcli` invocation. This
is a bit annoying: if I'm running `pviewd` on my machine, I'd probably
want to be able to configure `pcli` to always use my `pviewd` instance,
without having to pass the argument every time.
This commit adds support for reading the node and pviewd addresses from
environment variables. This way, if a user always wants to use a
particular `pviewd` instance (for example), they can add
```bash
export PENUMBRA_VIEW_ADDRESS="localhost:42069"
```
or something to their `.bashrc` or other shell configuration files.
In the …
=> pcli: Read node and pviewd addresses from env vars 

Cargo.lock, pcli/Cargo.toml, pcli/src/command/chain.rs, pcli/src/command/query.rs, pcli/src/command/stake.rs, pcli/src/command/tx.rs, pcli/src/command/validator.rs, pcli/src/main.rs, pcli/src/network.rs, pcli/src/opt.rs, view/Cargo.toml, view/src/bin/pviewd.rs, view/src/service.rs, view/src/storage.rs
The `Opt` type in `pcli` represents the parsed command line arguments.
Currently, it's passed into most subcommands' `exec` methods, along with
a bunch of other stuff that's constructed in `main`. This is kind of
unfortunate, since there are a number of singletons we want to construct
a _single_ time based on the values in `Opt` (such as the `view` service
client).
This branch refactors `pcli` to add an `App` type that contains the
actual values necessary to run the application, which are constructed
based on the CLI arguments in the `Opt` type. Most of the fields on
`Opt` are made private, and `Opt` is moved into its own submodule of
`main`. This way, the *only* thing that an `Opt` value can be used for
is constructing an `App` value, and checking which subcommand should be
run.
=> pcli: refactor away from passing `Opt` into everything

component/src/shielded_pool/component.rs
This would allow quarantined notes to be spent immediately; the point of the
quarantine system is to record notes provisionally, before adding them to the
NCT.
=> shielded-pool: don't add quarantined notes to the NCT

.github/workflows/deploy-testnet.yml
This should make the deployment GitHub Action use the correct tag rather than `main`.
=> Use git tag for deployment

pcli/src/command/balance.rs, proto/build.rs, proto/proto/view.proto, view/migrations/20220415094212_init.sql, view/sqlx-data.json, view/src/client.rs, view/src/lib.rs, view/src/quarantined_note_record.rs, view/src/service.rs, view/src/storage.rs, view/src/sync.rs
=> View quarantine v2

Cargo.lock, pd/Cargo.toml, pd/src/consensus/service.rs, pd/src/main.rs, pd/src/mempool/service.rs
Also renames the `worker` label as `role` and places it in an `app` span as per #965 
Closes #965
=> Use AllowList for metrics labels extracted from spans

pcli/src/command/stake.rs, pcli/src/network.rs
We won't detect change, because it's quarantined, but we also don't need to,
because it's not spendable.
=> pcli: don't wait for full confirmation of undelegations

Cargo.lock, pd/Cargo.toml, pd/src/main.rs, pd/src/testnet.rs
This aims to make it so that joining a running testnet is as easy as:
1. `cargo run --release --bin pd -- join-testnet HOSTNAME`;
2. `cargo run --release --bin pd -- start -r ~/.penumbra/testnet_data/node0/rocksdb`;
3. `tendermint --home ~/.penumbra/testnet_data/node0/tendermint start`.
=> pd: add a `join-testnet` command

tct/src/tree.rs
Previously, end_block and end_epoch did not return the empty block root in some cases when they
should have. This meant that the returned root was not reliably the root of the block which had just
been closed.
=> Return the correct block root from end_block and end_epoch

component/src/ibc/component.rs, component/src/ibc/component/channel.rs, component/src/ibc/ibc_handler.rs, component/src/ibc/mod.rs, component/src/ibc/transfer.rs
This PR adds a scaffold that should allow us to cleanly implement ICS20 transfers, and any other future IBC applications (such as interchain accounts).
Originally, we had considered the ICS20 implementation to be through another component. However, this isn't correct, because IBC applications want to consume (validated) IBC channel events, not raw transactions.
Along the lines of https://github.com/cosmos/ibc/tree/master/spec/core/ics-026-routing-module and https://github.com/cosmos/ibc/tree/master/spec/core/ics-025-handler-interface, this PR adds an "App Handler" interface, which defines the interface that IBC applications use to consume events from the IBC core protocol, and adds an "App Router" that allows instantiations of IBC applications to bind to IBC Ports and receive events for …
=> add IBC "app handlers", router for IBC events, ICS20 Transfer scaffold

Cargo.lock, crypto/Cargo.toml, tct/Cargo.toml, transaction/Cargo.toml
This is such that we can perform the audit and make fixes from the
audit against the new parameters to be merged to the `main` branch of `poseidon377`. Here in the
penumbra repository we want to continue to use the old parameters,
which will be kept in the `oldparams` branch of the `poseidon377`
repository. This way, we can merge the new parameters to `main`, as
well as audit fixes, without disturbing development in the main
repository.
Once all address-breaking changes are ready - including the new `poseidon377`
parameters - this commit can be reverted, thus switching over to the
new parameter set.
=> deps: pin `poseidon377` to a branch with the existing parameters

crypto/src/proofs/transparent.rs, proto/proto/crypto.proto, proto/proto/transparent_proofs.proto, tct/src/block.rs, tct/src/block/proof.rs, tct/src/internal/proof.rs, tct/src/proof.rs
We should probably have proptests that the proofs work as intended, but this should be fine as-is for now.
=> Implement block inclusion proof support in TCT

pd/src/info.rs
This behavior mirrors the ABCI query behavior in SDK chains, where the `data` field is decoded as hex-encoded bytes. In our case, if decoding the data field fails, we try interpreting the data as a raw key. This functionality is important for MVP relayer support
=> decode ABCI key data as hex by default

component/src/ibc/component/connection/stateless.rs, component/src/ibc/event.rs
msg.version = nil is allowed in ConnectionOpenInit. This also fixes an issue where we could unwrap nil values in IBC events (some events necessarily have nil fields, depending on the protocol sequence).
=> ibc: allow nil version in ConnectionOpenInit, fix unwrap in ibc events

Cargo.lock, pd/src/info/oblivious.rs
We need to send block responses in order, but fetching the compact block
involves disk I/O, so we want to look ahead and start fetching compact blocks,
rather than waiting for each state query to complete sequentially.
To do this, we spawn a task that runs ahead and queues block fetches from the
state.  Each block fetch is also spawned as a new task, so they execute
independently, and those tasks' JoinHandles are sent back to this task using a
bounded channel.  The channel bound prevents the queueing task from running too
far ahead.
=> pd: accelerate block streaming with concurrent state access

chain/src/lib.rs, chain/src/note_source.rs, chain/src/quarantined.rs, chain/src/sync.rs, component/src/shielded_pool/component.rs, proto/build.rs, proto/proto/chain.proto, proto/proto/view.proto, view/migrations/20220415094212_init.sql, view/sqlx-data.json, view/src/note_record.rs, view/src/quarantined_note_record.rs, view/src/storage.rs, view/src/sync.rs
This will allow a client to determine the provenance of a note they detect,
which might or might not have been created by a particular transaction. Without
this data, it's difficult for a client to determine the source of the notes
they detect, even if they download a full block, because some notes are created
as a result of chain-wide logic, rather than any particular transaction in the
block.
This commit does not yet add this information into the `NoteRecord`s in the
view service, but that's the next step.
=> chain: record `NoteSource`s in `CompactBlock`s

.github/workflows/notes.yml, Cargo.lock
This updates the GitHub Action to automatically generate and upload protobuf documentation to Firebase, available at https://protobuf.penumbra.zone
Relies on [protoc-gen-doc](https://github.com/pseudomuto/protoc-gen-doc) and the `protoc` command.
Closes #1068
=> Implement GitHub Action for building/publishing protobuf docs

component/src/ibc/component/client.rs
in building the relayer, discovered that our state storage key for consensusStates was out of spec
=> bring IBC consensusStates into IBC key spec

component/src/ibc/component/channel.rs, component/src/ibc/component/client.rs, component/src/ibc/component/connection.rs, component/src/ibc/component/connection/stateful.rs, component/src/ibc/component/state_key.rs, component/src/ibc/mod.rs
after implementing the JMT prefix as required in #1189, this PR brings all the IBC commitment paths into spec + uses the new commitment prefix.
=> ibc: bring commitment paths fully into spec and use `state_key` pattern

component/src/stake/component.rs, component/src/stake/state_key.rs
This PR fixes #997 (as a prereq to #1022 ). I've followed the naming convention set out in [shielded_pool::state_key](https://github.com/penumbra-zone/penumbra/blob/main/component/src/shielded_pool/state_key.rs#L16).
Happy to incorporate feedback if naming doesn't look right...
=> refactor(component/stake): factor out explicit key formatting

component/src/ibc/component/connection/stateful.rs
our ConnectionOpenAck implementation couldn't verify counterparty's proofs due to us using our own prefix for their chain.
=> ibc: use counterparty prefix instead of self prefix in ConnectionOpenAck verification

docs/guide/src/pd/join-testnet.md
This PR instructs users to reset the tesetnet state before running the `pd testnet join` command.
The reasoning for this change is this:
- Most testnet participants participate in multiple testnets; most followers of this guide will need to reset state.
- As the file was originally structured, a careless reader blindly running commands might reset the testnet state after running the join command, creating a confusing error condition.
=> Instruct users to reset state before testnet join

view/src/storage.rs, view/src/worker.rs
Resolves #1201 by removing buggy retry loop in view service and fixing database locking error that was triggering retries. Also resolves #1191 by the same token.
The retry loop shouldn't be necessary, and I think it's a good idea to keep it brittle for the moment so that if errors occur, we can properly diagnose them rather than letting them slide by if they are ephemeral.
Co-Authored-By: @aubrika
=> Enable sqlite shared cache and remove retry loop

chain/src/params.rs
Restore the less-aggressive slashing parameters copied from the Cosmos Hub,
we're pretty sure that slashing works now, and this prevents needless jailing.
=> params: less aggressive slashing

component/src/stake/component.rs, component/src/stake/state_key.rs
Closes #1062 (albeit with a different mechanism).
This prevents a chain halt that can occur if two validator definitions are
uploaded with the same consensus key -- resulting in pd sending a validator
update to Tendermint with duplicate entries, causing a halt.
This change obviates the suggestion in #1062 to add a signature by the
consensus key -- now, it's impossible to create a validator definition with an
existing key, so no signature is needed.
This commit should fix the chain halt that killed the Eurydome testnet.
=> stake: ban duplicate consensus keys

crypto/src/dex.rs, crypto/src/dex/swap.rs, crypto/src/dex/swap/ciphertext.rs, crypto/src/dex/swap/plaintext.rs, crypto/src/dex/trading_pair.rs, crypto/src/lib.rs, transaction/src/action/swap.rs
This reorganization divides the existing swap.rs into submodules, and puts it
under a new `dex` module, so that we can have a place for structures that are
common to both the swap side and the lp side, and have room for sibling `swap`
and `lp` modules.
=> crypto: split up WIP swap code into modules

docs/guide/src/pd/join-testnet.md
small fix to the giude docs that changing the `priv_validator_key.json` path
=> Update priv_validator_key.json path

chain/src/state_key.rs, chain/src/view.rs, component/src/app/mod.rs, component/src/app/state_key.rs, component/src/ibc/component/channel.rs, component/src/ibc/component/client.rs, component/src/ibc/component/connection.rs, component/src/ibc/component/state_key.rs, component/src/shielded_pool/component.rs, component/src/shielded_pool/state_key.rs, component/src/stake/component.rs, component/src/stake/state_key.rs, pcli/src/command/query.rs, pcli/src/command/query/shielded_pool.rs, pd/src/info/specific.rs, proto/proto/client/specific.proto
This PR fixes #1022, here's a breakdown of what it does:
1. [x] make all `state_key` methods return their respective raw path instead of `KeyHash`
2. [x] make downstream consumers of `state_key` modules meet the new API
3. [x] protobuf: remove the `key_hash` field from the `KeyValueRequest` message definition
4. [x] pd: modify how "specific" `Info` requests for `key_value` are executed (always use `get_with_proof`)
5. [x] pcli: stop using `KeyHash` in query commands for `ShieldedPool` (WIP - I have questions about this)
7. [x] cargo fmt
8. [x] testing
There are two chunks of code that require increased scrutiny from reviewers:
=> refactor(state_key): only use raw keys to build  `KeyValueRequest`s 

component/src/ibc/component/connection/stateless.rs, component/src/stake/component.rs, crypto/src/asset/denom.rs, crypto/src/keys/seed_phrase.rs, eddy/src/value.rs, storage/src/app_hash.rs, transaction/src/action/swap.rs
some smol clippy auto fixes.
had to roll back some clippy false positives manually, as clippy tries to fix
```diff
-        let nonce = Nonce::from_slice(&*MEMO_ENCRYPTION_NONCE);
+        let nonce = Nonce::from_slice(MEMO_ENCRYPTION_NONCE);
```
for lazy arrays
```
static MEMO_ENCRYPTION_NONCE: Lazy<[u8; 12]>;
```
which does not compile.
`&*MEMO_ENCRYPTION_NONCE` is also `&MEMO_ENCRYPTION_NONCE[..]`
or since the arrays can be made const, the lazy could be omitted entirely:
```diff
-pub static NOTE_ENCRYPTION_NONCE: Lazy<[u8; 12]> = Lazy::new(|| [0u8; 12]);
+pub static NOTE_ENCRYPTION_NONCE: [u8;12] = [0u8; 12];
```
=> chore(clippy): clippy --fix -Z unstable-options

crypto/src/dex/swap.rs, crypto/src/dex/swap/ciphertext.rs, crypto/src/dex/swap/plaintext.rs, crypto/src/lib.rs, crypto/src/memo.rs, crypto/src/note.rs, crypto/src/symmetric.rs
This has two of the items towards #1264. It adds a `symmetric` module that contains a new `PayloadKey` to represent the symmetric key used to encrypt/decrypt notes, memos and swaps
Closes #1268
=> crypto: add `PayloadKey` and use for notes, memos, and swaps

crypto/src/lib.rs, crypto/src/memo.rs, crypto/src/note.rs, crypto/src/symmetric.rs, decaf377-ka/src/lib.rs, transaction/src/action/output.rs, transaction/src/auth_hash.rs
Three more symmetric crypto items towards #1264:
- makes `PayloadKey` pub and enables one to decrypt a note ciphertext given only a `PayloadKey` - this is for a scenario where a user wishes to share fine grained viewing capability to a third party (but not provide viewing keys for all time)
- adds an `OvkWrappedKey` struct to represent the encrypted key material to reconstruct the `PayloadKey` at a later date
- stores the `SharedSecret` in `OvkWrappedKey` instead of the transmission key and ephemeral secret (saves 32 bytes)
=> crypto: add `OvkWrappedKey` and `PayloadKey`-only decrypt method

pcli/src/command/tx.rs, transaction/src/plan.rs, transaction/src/plan/action.rs, transaction/src/plan/action/swap_claim.rs, wallet/src/plan.rs
This adds initial support for generating `SwapPlan`s/`SwapClaimPlan`s in the wallet.
Only `SwapPlan` is fully implemented, as `SwapClaimPlan` requires the ability to retrieve clearing prices from the dex.
=> Support generating plans for Swap/SwapClaim in wallet

docs/protocol/src/SUMMARY.md, docs/protocol/src/protocol.md, docs/protocol/src/protocol/transaction_crypto.md
Closes #1264
I've added a page in the protocol docs to describe how the symmetric crypto currently works, using the recently introduced nomenclature after the changes described in #1264. I've put it in the chapter associated with the cryptographic protocol since it relies on the keys and addresses section.
=> spec: transaction-level symmetric crypto

crypto/src/address.rs
I had a moment earlier where I thought that clue keys were not properly diversified. Tracing through, I see that the diversified detection key is derived from the incoming viewing key _and_ the diversifier, and the diversified clue key is derived from this diversified detection key. 
Adding a wee test to verify this.
=> test: verifies that addresses are diversified

crypto/src/address.rs, crypto/src/dex/swap.rs, crypto/src/dex/swap/plaintext.rs, crypto/src/memo.rs, crypto/src/proofs/transparent.rs, proto/build.rs, proto/proto/dex.proto, proto/proto/transaction.proto, proto/proto/transparent_proofs.proto, transaction/src/action/swap_claim.rs, transaction/src/auth_hash.rs, transaction/src/plan.rs, transaction/src/plan/action/swap.rs, transaction/src/plan/action/swap_claim.rs, transaction/src/plan/build.rs, wallet/src/plan.rs
This simplifies a lot of the Swap/SwapClaim code and continues implementation stubbing in the client.
=> Rebase swaps/swapclaims on current main branch changes, use address from notes, move NFT asset ID generation to SwapPlaintext

crypto/src/address.rs, decaf377-fmd/src/clue_key.rs, proto/proto/transaction.proto, transaction/src/auth_hash.rs, transaction/src/plan.rs, transaction/src/plan/build.rs, transaction/src/plan/clue.rs, wallet/src/build.rs, wallet/src/plan.rs
Towards #1039, adding FMD clues into transactions.
This is the next step after https://github.com/penumbra-zone/penumbra/pull/1296 which adds support deterministic clues and the `CluePlan` field in the transaction body.
=> build `Clue`s from `CluePlan`s [FMD part 2]

pcli/src/command/tx.rs, pcli/src/network.rs, wallet/src/plan.rs
#1329 should be merged first, this PR was branched off of that since it relies on the "waiting on commitments to sync to view" behavior introduced in #1329
=> Automatically submit SwapClaim after Swap completes

docs/protocol/src/protocol/addresses_keys/viewing_keys.md
We use the first 16 bytes of the hash output for the DK:
https://github.com/penumbra-zone/penumbra/blob/main/crypto/src/keys/fvk.rs#L47-L60
h/t to @hdevalence for pointing this out
=> spec: fix inaccurate diversfier key derivation

crypto/src/keys/fvk.rs, docs/protocol/src/concepts/addresses_keys.md, docs/protocol/src/protocol/addresses_keys.md, docs/protocol/src/protocol/addresses_keys/viewing_keys.md
Closes #1080
For each seed phrase, we can have multiple accounts (equivalent to spending authority). For each account we can have multiple diversified addresses. Sharing a viewing key means giving access to an entire _account_.
=> spec: introduce account and account ID terminology

Cargo.lock, pd/Cargo.toml, pd/src/main.rs
Using gRPC from a web context is difficult because of its reliance on HTTP/2 features not exposed by browser APIs.  Instead, grpc-web allows a proxy to translate an HTTP/1 based protocol into normal gRPC.  Normally, this is done with Envoy or some other proxy service, but Rust and Tonic make this much more convenient, by making it easy to bundle the proxy into the application itself.
I haven't tested this code from a web context, because that requires compiling our protos to JS and loading them into a page, but I have checked that this works just fine with normal gRPC (i.e., it does not degrade any functionality), so we could merge it experimentally and see if it unblocks proof of concept work towards #1373.
=> pd: experimentally enable grpc-web

component/src/dex/component.rs, component/src/dex/mod.rs, component/src/dex/state_key.rs, component/src/dex/stub_cpmm.rs, crypto/src/asset/denom.rs, crypto/src/dex/swap.rs
his module and struct are marked "Stub" to indicate that they're intended to
be thrown away.  This won't be the real AMM we use.  But, having *a* toy AMM
lets us exercise the shielded swaps in a more real way than just failing all of
them.
Two things we might want to do before releasing this code:
1. Add `gm` and `gn` to the asset registry as display denoms of a base denom
with a reasonable precision (e.g., 1e6, so gm is really 1e6 ugm).  This is
because the stub CPMM implementation pays no real attention to rounding
behavior other than "round down", which could cause unexpected behavior we'd
then have to help people through. #1398 
2. Add a `pcli q dex cpmm-reserves gm:gn` subcommand that can display the state
of the reserves for a specified trading pair (in this case `gm:gn`, choosing …
=> Add a stub CPMM (UniV2) AMM to back the DEX for testing purposes.

crypto/src/transaction.rs, crypto/src/value.rs, pcli/src/command/view/balance.rs, pcli/src/command/view/staked.rs
This prevents a crash in the case where a Swap NFT (which has no associated denom) is attempted to format via `pcli view balance`.
=> Make asset ID formatting infallible in the case that a denom doesn't exist

crypto/src/symmetric.rs, transaction/src/auth_hash.rs, transaction/src/plan/action/output.rs, transaction/src/plan/build.rs
~Making this a little clearer for the future by getting the memo key with `expect`. Related to #1395~
Closes #1394
Flagging that any outputs without memos will be invalid transactions as of #1403
=> provide dummy memo key such that `Transaction::auth_hash` does not panic

Cargo.lock, component/Cargo.toml, custody/Cargo.toml, eddy/Cargo.toml, measure/Cargo.toml, pcli/Cargo.toml, pd/Cargo.toml, pd/src/consensus/service.rs, pd/src/main.rs, pd/src/mempool/service.rs, storage/Cargo.toml, storage/src/storage.rs, tct-property-test/Cargo.toml, view/Cargo.toml, wallet/Cargo.toml
This should fix #1363 , see the diff for more details but I went ahead and bumped a couple crates from `tokio@1` to `1.21.1`.
The main API change was in `penumbra-storage`: [`tokio::task::Builder::spawn_blocking`](https://docs.rs/tokio/latest/tokio/task/struct.Builder.html#method.spawn_blocking) is fallible. It returns an `io::Error` if the runtime fails to spawn a task. We're not handling those errors, but let me know if you think we should!
=> chore: use `tokio@1.21.1` and `console-subscriber@0.1.8`

measure/src/main.rs, view/src/service.rs
=> Ignore `max_peer_block_height` for determining `latest_known_block_height`

transaction/src/action.rs, transaction/src/action/delegate.rs, transaction/src/action/ibc.rs, transaction/src/action/output.rs, transaction/src/action/position.rs, transaction/src/action/propose.rs, transaction/src/action/spend.rs, transaction/src/action/swap.rs, transaction/src/action/swap_claim.rs, transaction/src/action/undelegate.rs, transaction/src/action/vote.rs, transaction/src/lib.rs, transaction/src/transaction.rs
This moves the existing balance commitment code into a trait common to all actions, which we can use as a place to add more common functionality for actions.
=> transaction: add IsAction trait

.vscode/settings.json
This broke my VS Code configs, which just used `cargo fmt`, and now the editor hangs every time I save.  I think we should only use the settings file for things like the database path, and not for opinions about how to configure the editor.
=> tooling: don't override people's vs code configuration

.github/workflows/notes.yml
These steps broke with the proto reorganization. We could update them, but we'd potentially have to update the steps every time we added new protos or changed the layout.  Now that we publish to buf.build, it seems like we might want to use that instead?
=> ci: disable protobuf docs

docs/guide/src/pcli/install.md
`prost` used to "just work", by including a bundled `protoc`.  Later, that was removed, ostensibly in order to improve security posture, so now we need to have our users figure out how to install it from some random location.
=> docs: tell users to install protoc

.github/workflows/rust.yml, .github/workflows/smoke.yml, Cargo.lock, Dockerfile, Dockerfile.dev, docs/guide/src/pcli/install.md, docs/guide/src/pd/build.md, proto/Cargo.toml, proto/build.rs
Since PROST has removed its vendored `protoc` compiler, we need a new way to source `protoc` during our build. This PR adds the [protobuf-src](https://docs.rs/protobuf-src/1.1.0+21.5/protobuf_src/) crate for that. This should hopefully fix our containerized deployments
=> use protobuf-src to source protoc in build

testnets/tm_config_template.toml
After making this change, the `pd testnet join` command works with `testnet-preview.penumbra.zone` and Tendermint 0.34.
=> pd: use seeds (0.34) instead of bootstrap-peers (0.35)

pcli/tests/network_integration.rs
I thought I'd already added listing the proposals to the integration tests (wrt #1484), but I was mistaken.
=> test(integration): list created proposals

component/src/governance/proposal/chain_params.rs, pcli/src/command.rs, pcli/src/command/query/governance.rs, pd/src/info/oblivious.rs, proto/proto/penumbra/client/v1alpha1/client.proto, proto/proto/penumbra/core/governance/v1alpha1/governance.proto, proto/src/gen/penumbra.client.v1alpha1.rs, proto/src/gen/penumbra.core.governance.v1alpha1.rs, tools/proto-compiler/src/main.rs
Adds `pcli query governance parameters` command to view governance-controllable parameters along with human-readable descriptions.
Closes #1374
=> Allow pcli querying of governance-controllable chain parameters

component/src/dex/stub_cpmm.rs
This was due to a typo in the definition of the reverse direction trading function. This commit fixes that problem, so that the CPMM works correctly.
=> Swapping in one direction caused most of the input to be burned

clippy.toml, component/src/ibc/ibc_handler.rs, component/src/stake/component.rs, storage2/src/state.rs, tct/src/validate.rs
The use of `std::collections::HashMap` has a high risk of introducing unexpected nondeterminism in consensus, because its key ordering is not stable. Additionally, as a more minor concern, user interfaces which present keys as iterated from a `HashMap` present them in varying orders, which can be more confusing than if they were sorted. This PR adds a workspace-global clippy lint to warn on use of `HashMap`, and removes all current uses of it from the codebase.
If in the future there really is a well-justified use of this type, we can use `#[allow(clippy::disallowed_types)]` to silence the warning at the precise place where it is required.
=> Stop using `HashMap` across codebase, add clippy lint for it

Cargo.lock, decaf377-ka/Cargo.toml
Builds started failing on main today due to decaf377-ka failing to build. @plaidfinch noticed that this was due to a yanked version of zeroize-derive (1.2.2), which we depend on in decaf377-ka. This PR just updates the version to one that has not been yanked.
=> chore: fix decaf377-ka build failure due to yanked zeroize-derive

README.md
protobuf docs have changed. https://protobuf.penumbra.zone is dead. Replace with updated https://buf.build/penumbra-zone/penumbra
=> readme protobuf update

Cargo.lock, storage2/Cargo.toml, storage2/src/snapshot.rs, storage2/src/state.rs, storage2/src/state/read.rs, storage2/src/state/transaction.rs
Simplify storage code by moving cache interleaving complexity to a new merge_cache fn
Co-authored-by: Kenny Foner <kwf@very.science>
=> Simplify storage code

.github/workflows/buf-pull-request.yml, docs/guide/src/README.md, docs/guide/src/SUMMARY.md, docs/guide/src/dev/devnet-quickstart.md, docs/guide/src/dev/docs.md, docs/guide/src/dev/protobuf.md, docs/guide/src/pd/join-testnet.md, docs/guide/src/resources.md
Updated the dev guide to include instructions on rebuilding the protobuf spec files. While I was in the guide, made some small touch-ups to URLs throughout. Also tacked on a new CI check, so that forgetting to rebuild and commit the protobuf specs will now result in failing builds, so we can catch that mistake prior to merging into main. You can see a failing CI check based on a temporary (now removed) commit [here](https://github.com/penumbra-zone/penumbra/actions/runs/3341262009/jobs/5532290154).
Closes #1530.
=> Document protobuf build process

crypto/src/value.rs, docs/protocol/src/crypto/decaf377-rdsa.md
This is an example to describe how the binding signature / value balance trick works. Is this helpful? Are there issues with this explanation?
=> spec: add example on binding signature

crypto/proptest-regressions/memo.txt, crypto/src/memo.rs, transaction/src/auth_hash.rs, transaction/src/plan/build.rs, transaction/src/plan/memo.rs, transaction/src/transaction.rs, wallet/src/plan.rs, wallet/src/plan/planner.rs
We need a fixed length of 512 bytes for passing the memo plaintext to cryptographic functions. Everywhere else, though, a String is most convenient. Here we add some conversion traits to make working with MemoPlaintext a bit more ergonomic. Ideally we'd perform validation such that a too-long String cannot be used to construct a MemoPlaintext.
Opening early for feedback on approach and style. The `strip_padding` function should be smarter, will address its TODO before declaring final. I'm tempted to create a constructor for MemoPlaintext so that we could validate string length just once and be done with it.
=> Convert MemoPlaintext to String type

storage2/src/snapshot.rs, storage2/src/snapshot/rocks_wrapper.rs, storage2/src/state.rs, storage2/src/storage.rs
This change works around a limitation of the `rocksdb` API: the `rocksdb::Snapshot` can only take a borrowed database handle, not an `Arc`'d one, so the lifetime of the `rocksdb::Snapshot` is bound to the lifetime of the borrowed handle.  This isn't what we want, because we're using all of these snapshots in an async context, where objects need to be able to live arbitrarily long (so that they can be included in futures that are spawned as tasks, and executed whenever).
To fix this, we add a wrapper type that bundles an `Arc`'d handle together with the `rocksdb::Snapshot`, so that the database is guaranteed to live at least as long as any snapshot of it.
This requires unsafe code, which is encapsulated in the single-purpose `RocksDbSnapshot` wrapper type, so that it's self-contained and …
=> storage2: add a RocksDbSnapshot wrapper with internal Arc

Cargo.lock, storage2/Cargo.toml, storage2/src/lib.rs, storage2/src/snapshot.rs, storage2/src/state.rs, storage2/src/state/read.rs, storage2/src/state/transaction.rs, storage2/src/state/write.rs, storage2/src/storage.rs, storage2/tests/basic.rs
Before starting the replacement of `storage` with `storage2`, it seems like a good idea to have an end-to-end integration test to check that the external API is usable on its own and that it appears to work correctly.
This PR does a docs/API pass on the external API, then adds the skeleton of a simple end-to-end test. The test is verbose but very explicit. (It does not currently pass).
=> [WIP] storage2: add an end-to-end test of storage/state flow and do a docs/API pass

crypto/src/proofs/transparent.rs, crypto/src/proofs/transparent_gadgets.rs, crypto/src/transaction.rs, docs/protocol/src/protocol/notes/note_commitments.md, transaction/src/action/delegate.rs, transaction/src/action/swap.rs, transaction/src/action/undelegate.rs, transaction/src/plan/action/output.rs, transaction/src/plan/action/spend.rs, transaction/src/plan/build.rs, transaction/src/transaction.rs
Fixes #1483 
[`Balance`](https://rustdoc.penumbra.zone/main/penumbra_crypto/balance/struct.Balance.html) keeps track of different `Value`s as well as their signs, and incorporates it to create [commitments](https://github.com/penumbra-zone/penumbra/blob/facc120686043aa0e03b7a00ea62b22ee7814144/crypto/src/balance.rs#L80).
A commitment to a negative value used to be the negation of the value commitment i.e. for a value $v_o$, a commitment to $-v_o$ with randomness $rcv_o$ was defined as: $cv_o = [-v_o] G_v + [-rcv_o] G_{rcv}$.
With the introduction of `Balance::commitment`, we now define the same commitment to a negative value as: $cv_o = [-v_o] G_v + [rcv_o] G_{rcv}$.
This PR eliminate the use of negated value commitments, and replace them with the `Balance::commit` implementation outlined …
=> crypto: remove ad-hoc use of signs in balance commitments

storage2/src/snapshot.rs, storage2/src/state.rs, storage2/src/state/read.rs, storage2/src/state/transaction.rs, storage2/src/state/write.rs, storage2/tests/basic.rs
As discussed on Discord, we discovered a problematic interaction between the new execution model (where execution can be fallible, even after `check_tx_stateful`) and the existing Component design: now that any part of the execution can fail, it's not safe for the Components to modify any state except for through the StateTransaction, because any other component could error out, leaving data in an inconsistent state -- while the StateTransaction would roll back, any state in the Components wouldn't.
To fix this, we need to have the Components only make writes to the StateTransaction passed into them.  We don't want to be writing temporary data into the consensus state, but writing it into the nonconsensus state is also difficult, because the system would have to be careful to clean it all …
=> storage2: add a transactional object store

crypto/src/dex/swap.rs, crypto/src/dex/swap/plaintext.rs
I noticed this just now when looking at #1571, I think `SwapPlaintext::encrypt_key` (and the corresponding constant) should've been removed as part of #1264
=> crypto: remove Swap-specific wrapped OVK code (no longer used)

.github/workflows/docker-publish.yaml, Dockerfile, Dockerfile.dev
Resolves #1292 
Updates `Dockerfile` and `Dockerfile.dev` to use scratch image for final image with minimal necessary bins, libs, CA root trust, and `penumbra` `1000:1000` user
Final distributed images have a minimal shell and minimal utilities, sourced from https://github.com/strangelove-ventures/infra-toolkit
Modifies `Dockerfile` for use with buildkit/buildx to support `linux/amd64` and `linux/arm64` platforms, cross-compiling for non-native architecture. This results in a quick builds due to no QEMU emulation necessary and multi-arch docker image manifests for the image tags in the container repository
Example: tag for this PR:
https://github.com/penumbra-zone/penumbra/pkgs/container/penumbra/48612389?tag=strangelove-docker_image_publish
See new workflow below, an image will be built …
=> Docker - cross-compile, scratch image, gh actions workflow

tct/src/storage.rs, tct/src/storage/in_memory.rs, view/sqlx-data.json, view/src/storage/nct.rs
Having these available to a storage backend means that the backend can pull out selected portions of the tree in its own `hashes` and `commitments` implementations, effectively choosing to selectively deserialize only the frontier of the tree.
=> Add methods to random-access hashes and commitments in NCT storage

pd/src/info/specific.rs, proto/proto/penumbra/client/v1alpha1/client.proto, proto/src/gen/penumbra.client.v1alpha1.rs
This will be more scalable going forward than the current approach of having one giant list of fixed assets, which should in any case be removed as part of #1593.
=> rpc: add an RPC method for asset lookups.

component/src/shielded_pool/component.rs
Previously, we used a cached version of the CompactBlock, meaning we'd skip any changes made during end_block -- and in particular, we'd skip any notes coming out of quarantine.
Hopefully fixes #1606
=> bug: avoid using cached CompactBlock in ShieldedPool::end_block

Dockerfile
This reverts commit e1c94972292fac08764c35d3b0976b15ce4ff2bb.
Fixes buildkit builds such as the docker build and publish github actions workflow
=> Revert "Try specifying default BUILDPLATFORM"

storage/src/snapshot.rs, storage/src/state.rs, storage/src/state/read.rs, storage/src/state/transaction.rs, storage/tests/basic.rs
Unlocks forward progress on the DEX, since now we'll be able to index liquidity positions.
=> storage: fill in nonconsensus_prefix support

pcli/src/command/query.rs, pd/src/info/specific.rs, proto/proto/penumbra/client/v1alpha1/client.proto, proto/src/gen/penumbra.client.v1alpha1.rs, proto/src/lib.rs, view/src/worker.rs
closes #1595, updates our kv query api to produce proofs back to the apphash, using the same method as ABCI queries.
=> clean-up KV rpc api

Cargo.lock, crypto/Cargo.toml, crypto/src/note.rs, crypto/src/proofs.rs, crypto/src/proofs/groth16_gadgets.rs
Closes #1091. There's a Groth16 proof added in the tests here (`TestNoteCommitmentCircuit`) that uses the note commitment integrity gadget only, its circuit cost is 3201 constraints.
=> zk: add r1cs note commitment integrity gadget

.github/workflows/buf-pull-request.yml, Dockerfile, Dockerfile.dev, docker-compose.multinode.override.yml, docker-compose.yml, docs/guide/src/pcli/install.md, docs/guide/src/pcli/update.md
Testnet deployment failed because we use a stale docker rust image. This is a change to use `rust:1.65.0-bullseye`.
=> deployment: use `rust:1.65.0-bullseye`

.github/workflows/docker-publish.yaml, .github/workflows/smoke.yml
We hit API ratelimits for non-authenticated pulls from docker hub [0] while running a lot of CI jobs concurrently. The long-term solution to this problem is to add auth, which we've done, but in the process we decided that we were a bit overzealous with the frequency of container image builds.
[0] https://docs.docker.com/docker-hub/download-rate-limit/
Closes #1648.
Changes made out of band and not reflected in the diff:
* registered a docker hub account
* stored credentials in the usual place
* generated api token for hub account
* added api token to GitHub Actions "secrets", so it can be referenced in workflows
=> ci: use authenticated pulls from docker hub

deployments/networks/testnet/ci.sh, deployments/networks/testnet/helm/templates/fn-deployments.yaml, deployments/networks/testnet/helm/templates/fn-p2p-svcs.yaml, deployments/networks/testnet/helm/templates/fn-tm-config.yaml, deployments/networks/testnet/helm/templates/val-tm-configs.yaml
- Multi-stage deploy to inject tendermint p2p kube service IPs as the tendermint external p2p addr in each node's config.
- Removes private peers from config since external_address on each node is now be publicly routable
=> k8s testnet - public peering

docs/guide/src/pcli/install.md, docs/guide/src/pcli/update.md
Running `cargo update` as currently recommended in the docs will cause local dependencies to get out of sync with tagged testnet version. We commit the `Cargo.lock` file in order to version lock dependencies; `cargo update` breaks that strict version locking. Worse, `cargo update` will result in a dirty git working tree, requiring manual cleanup (or `git stash`) on subsequent testnet upgrades. We don't document that manual cleanup, nor should we: we should expect that all nodes run exactly the versions of dependencies that we specify in Cargo.lock.
=> docs: no 'cargo update' during testnet upgrades

.github/ISSUE_TEMPLATE/release_testnet.md
This restores the previous deployment flow, where testnet-preview.penumbra.zone acts as a preview of the next testnet.  It's important that the genesis data for the new testnet is defined in advance, rather than on the release day, because releasing the testnet should not involve any configuration changes that can introduce surprise breakage.
=> docs: fix deployment checklist

Cargo.lock, component/src/app/mod.rs, component/src/lib.rs, pcli/Cargo.toml, pcli/src/network.rs, pd/src/consensus/worker.rs, pd/src/mempool/worker.rs
This does some minor tidying on the code we use to pass messages into the `App`, and breaks the dependency of `pcli` on `pd` (which we don't really need, we only want to be able to do stateless checks pre-submission).
=> pd: clean up App message handling wrappers

component/src/app/mod.rs, component/src/ibc/component/client.rs, component/src/lib.rs, component/src/temp_storage_ext.rs, storage/src/lib.rs, storage/src/state.rs, storage/src/storage.rs, storage/src/storage/temp.rs, transaction/src/transaction.rs
Work towards #1664
Closes #853
This commit cleans up the IBC client test as an example case of the new API.
Along the way, we also clean up some other ergonomic pain points, notably adding an `Arc<State>::try_begin_transaction()` method.
Co-Authored-By: Conor Schaefer <conor@penumbra.zone>
=> component: better test infrastructure

chain/src/params.rs, pd/src/main.rs
This commit changes the Clap arguments for `pd testnet generate` to not include a second set of default values for chain parameters beyond those already specified in `ChainParameters::default()`, so we only have one place to look.
Also increase the default validator limit to 80.
Co-Authored-By: Conor Schaefer <conor@penumbra.zone>
=> pd: avoid two levels of defaults in ChainParameters

Cargo.lock
This is to pull in [this change](https://github.com/penumbra-zone/poseidon377/commit/425d97e6fe794f90e283a1c0870e0cd199545020) such that the full poseidon parameters can be easily viewed in the documentation
=> cargo update (for docs build)

docs/guide/src/resources.md
Simple change, trying to collect a few useful talks for folks who want to understand the platform better. There's an argument that this content should go on https://penumbra.zone, rather than https://guide.penumbra.zone, but we can always cross link later.
Things to check as part of review:
1. Are these talks reasonable ones to call attention to?
2. Are the links and titles accurate?
3. Is the guide a good enough place to link to these talks for now?
=> docs: add talks & presentations to resources page

.github/workflows/buf-push.yml
We want to ensure that API users can track protobuf definitions from a specific tag. Updates the GH Actions workflow accordingly.
Closes #1667.
=> ci: run buf build on tags, too

docs/guide/src/pcli/install.md, docs/guide/src/pcli/update.md
We had a chain halt on 037-megaclite, so this release contains a hotfix from https://github.com/penumbra-zone/penumbra/pull/1704.
Refs #1699
=> docs: update testnet tag to 037-megaclite.1

proto/proto/penumbra/view/v1alpha1/view.proto, proto/src/gen/penumbra.view.v1alpha1.rs, view/src/client.rs, wallet/src/plan/planner.rs
We plan to implement bearer-token authentication. This change adds an optional field "token" to the view service protocol. We preserve the use of account_id, since it's used for filtering events in e.g. the custody service. The field numbers for both "account_id" and "token" have been changed to 14 and 15 respectively, in an attempt to stabilize the proto, so subsequent implementing token auth updates don't need to make proto-breaking changes to field numbers.
Closes #1682. Towards #1556.
=>   proto(view): add bearer token field

.github/workflows/deploy-preview-new.yml, deployments/ci.sh, deployments/networks/testnet-preview/README.md, deployments/networks/testnet-preview/helm-values-for-penumbra-testnet-preview.yml, deployments/networks/testnet/README.md, deployments/networks/testnet/cluster.tf, deployments/networks/testnet/main.tf
Depends on #1707, so would prefer to land that first. Then this diff becomes pretty small.
Duplicates the "testnet" logic for "testnet-preview", targeting k8s cluster. Does not spin up a discrete cluster; we reuse a single cluster, with carefully labelled resources, and manage the configs via helm.
=> ci: adds testnet-preview k8s deploy workflow

view/migrations/20220908223928_notes.sql, view/sqlx-data.json, view/src/storage.rs
This change allows the notes table to act as an advice mechanism for
out-of-band note commitments during scanning: we can add notes to the notes
table in anticipation of their appearance, and then crossreference out-of-band
notes against known notes in the table.
Note: needs to be rebased on `main` after #1710 lands.
=> view: refactor notes table to just do note commitment lookups

crypto/src/keys/fvk.rs, crypto/src/keys/nullifier.rs
Closes #1712
A nullifier should be derivable for any element of state added to the state commitment tree (i.e. any positioned state commitment). Nullifiers will be unique as they are derived from the position in the TCT.
=> crypto: generic `Nullifier` derivation

Cargo.lock, pd/Cargo.toml
=> chore(pd): use `tower-abci@0.2.0` from crates.io

proto/Cargo.toml, proto/src/gen/cosmos.base.tendermint.v1beta1.rs, proto/src/gen/penumbra.client.v1alpha1.rs, proto/src/gen/penumbra.custody.v1alpha1.rs, proto/src/gen/penumbra.view.v1alpha1.rs, proto/src/lib.rs, tools/proto-compiler/src/main.rs, transaction/Cargo.toml, view/Cargo.toml
Fixes #1717  - uses [`tonic_build::client_mod_attribute`](https://docs.rs/tonic-build/latest/tonic_build/struct.Builder.html#method.client_mod_attribute), [`tonic_build::server_mod_attribute`](https://docs.rs/tonic-build/latest/tonic_build/struct.Builder.html#method.client_mod_attribute), to encapsulate tonic generated client/servers behind an `rpc` feature flag.
=> penumbra: make `tonic` an optional dependency

deployments/ci.sh, deployments/helm/templates/_helpers.tpl, deployments/helm/templates/fn-deployments.yaml, deployments/test.sh
During the release of 038-kaylke, we declined to cut over to the cluster deployment pipelines, due to an obscure misconfiguration. The bug was subtle: the local container used for building the config files prior to deployment was properly referred to by its "main" tag, but without a `--pull=always` flag, stale containers were being used from the local cache. This caused old config-generation code to be used to create the genesis, which lacked updates for new slashing penalty logic.
The above is enough to unbreak `pd/tm` node functionality, but there's an additional tweak required to honor requests from client-side `pcli` over 8080/TCP: the `pd` service now binds to `0.0.0.0`, rather than localhost, ensuring that traffic to the NodePort for "fullnode" reaches pd as intended.
Makes a few …
=> ci: fix cluster-based preview deployment

crypto/src/dex/lp.rs, crypto/src/dex/lp/nft.rs, crypto/src/dex/lp/position.rs, crypto/src/dex/lp/trading_function.rs, proto/proto/penumbra/core/dex/v1alpha1/dex.proto, proto/src/gen/penumbra.core.dex.v1alpha1.rs, tools/proto-compiler/src/main.rs, transaction/src/action/position.rs
Fixes #1762 .
Nomenclature: A `TradingFunction` (φ) is associated to a trading pair (`TradingPair`) and an internal component (`BareTradingFunction`) that specifies its parameters (`p`, `q`, `fee`).
=> dex: create `BareTradingFunction`

custody/src/pre_auth.rs, custody/src/request.rs, proto/proto/penumbra/custody/v1alpha1/custody.proto, proto/src/gen/penumbra.core.transaction.v1alpha1.rs, proto/src/gen/penumbra.custody.v1alpha1.rs, tools/proto-compiler/src/main.rs, wallet/src/build.rs
This commit changes the `PreAuthorization` modeling in the custody protocol to allow custodians to require pre-authorization from multiple parties prior to submission, by making the `PreAuthorization` field `repeated`.
It also changes the `PreAuthorization` from just being an Ed25519 signature to being a `oneof` with one message (the existing Ed25519 preauthorization message), so that in the future, more kinds of preauthorization data can be added (e.g., webauthn).
=> custody: allow multi-party pre-authorizations

component/src/action_handler/actions/proposal/withdraw.rs, component/src/action_handler/actions/spend.rs, component/src/action_handler/transaction/stateless.rs, component/src/governance/check.rs, crypto/src/dex/swap.rs, crypto/src/dex/trading_pair.rs, crypto/src/encrypted_note.rs, crypto/src/transaction.rs, proto/proto/penumbra/core/transaction/v1alpha1/transaction.proto, proto/src/gen/penumbra.core.transaction.v1alpha1.rs, tools/proto-compiler/src/main.rs, transaction/src/action/propose.rs, transaction/src/auth_data.rs, transaction/src/effect_hash.rs, transaction/src/lib.rs, transaction/src/plan/auth.rs, transaction/src/plan/build.rs
Closes #1758
We use the same words as in ZIP-244, namely "effecting" and "authorizing" data, but accidentally use them with opposite meanings, because I misunderstood which was which when originally reading the ZIP.  This is a huge source of conceptual confusion, which will surely lead to bugs.
The correct definitions are here: https://github.com/zcash/zips/issues/651
> * "Effecting data" is any data within a transaction that contributes to the effects of applying the transaction to the global state (results in previously-spendable coins or notes becoming spent, creates newly-spendable coins or notes, causes the root of a commitment tree to change, etc.). Any change to this data by definition results in a different transaction.
> * "Authorizing data" is the rest of the data within a …
=> Fix usage of "effecting" vs "authorizing" data

.github/workflows/buf-pull-request.yml, .github/workflows/rust.yml, .github/workflows/smoke.yml, chain/src/lib.rs, crypto/proptest-regressions/proofs/groth16.txt, crypto/src/proofs/groth16.rs
Motivations:
- Property tests mean we spend a lot of time running code as well as compiling it, so optimizing it makes tests shorter overall.
- Cargo check isn't doing a lot of lifting here, since all the work it does is duplicated as part of a build, and it will error early if there's a problem.  Because of caching, it shouldn't be spending much time rebuilding dependencies anyways.
- Using nextest https://nexte.st/index.html should make test runs faster via parallelism.
=> ci: try using nextest in release mode

component/src/action_handler/actions/ibc_action/msg/create_client.rs, component/src/action_handler/actions/ibc_action/msg/update_client.rs, component/src/ibc/client.rs, component/src/ibc/component/client.rs, component/src/ibc/component/client/stateful.rs, component/src/ibc/component/client/stateless.rs
Fixes #1697 (partially).
Context: the newer versions of ibc-rs defer deserialization of lightclient state (consensus, header, client etc.). As a result, execution ibc actions is faillible. This PR refactors some of the validation code (`ics02_validation`) to avoid windy and repetitive match statements, and propagates errors when lightclient state fails to deserialize.
=> component(ibc): make message execution faillible

deployments/README.md, deployments/ci.sh, deployments/helm/templates/fn-tm-config.yaml, deployments/helm/templates/manged-certs.yaml, deployments/helm/templates/val-tm-configs.yaml, deployments/networks/devnet/helm-values-for-penumbra-devnet.yml
Refs #1815. There are two changes here:
* adds a `devnet` deploy target, basically a sandbox environment that is not expected to be publicly consumed, for the purpose of debugging 
* updates the config-munging logic so that _all_ k8s services use external IPs to talk to peers.
The goal of the latter changes is to achieve consistency with the goals in #1815. Also hoping to improve legibility via comments for the benefit of future maintainers. The changes aren't just superficial: now fullnodes and validators alike will peer with each other. At a later date we may wish to rearchitect the peering to implement [sentry nodes](https://docs.tendermint.com/main/tendermint-core/validators.html). 
These changes are not sufficient for resolution of 1815, but upon merge, we'll see them land on …
=> Ensures all peers in k8s config are via external IPs

pd/src/main.rs, pd/src/testnet.rs
`pd testnet join` connects to a node of a running network and pulls information from it to generate configs for a node that runs as part of that network.  It needs to do this, because Tendermint's P2P layer is authenticated, so at some point a node needs to obtain the fingerprint of at least one other peer. However, if we only add the node we're scraping as a peer, then we might not be able to join the network if that peer has too many connections open.
To prevent this, we added logic to `pd testnet join` that scrapes the node's `net_info` RPC endpoint to obtain a list of bootstrap peers.  However, in the first version of that code, we used the `remote_ip`, which might not be the externally routable address.  This commit changes the `testnet join` logic to scrape the self-reported …
=> pd: change testnet join to use peers' listen addresses

Cargo.lock, crypto/Cargo.toml, crypto/src/proofs/groth16.rs, crypto/src/proofs/groth16/gadgets.rs
In 4afb56bb02e9377fbe571a85736f5125cd2b9fa1 a test of the diversified address integrity gadget was ignored due to a proptest failure. The gadget checks the transmission key is equal to `[ivk] g_d` where `ivk` is the incoming viewing key and `g_d` is the diversified basepoint. The ivk should be derived from the output of a rate 2 poseidon hash - i.e. an Fq - and then reduced modulo r. However, in the gadget we were not reducing mod r (there was an unimplemented inline todo about this).
=> crypto: re-enable diversified address integrity gadget test

deployments/helm/templates/fn-tm-config.yaml, deployments/helm/templates/val-tm-configs.yaml
Updates the k8s tendermint config to match
what we've long been shipping via the tm config
generated by `pd`. We're doing this in advance of shifting the public testnet to use the k8s deployment, so we want the closest match possible for consistency's sake. Closes #1816.
=> k8s: reconcile tendermint configs

deployments/ci.sh, deployments/helm/templates/fn-p2p-svcs.yaml, deployments/helm/templates/val-p2p-svcs.yaml
During load-testing, we observed that the k8s setup stopped peering once its peer count surpassed the number of external IPs assigned to the deployment. Log diving showed that peers were identified by the closest hop, i.e. NAT'd, addresses. To resolve, here we update the Service spec externalTrafficPolicy from "Cluster" (the default) to "Local". See docs at [0]. After deploying this change on a devnet, each remote peer successfully peered with all nodes in the deployment. The remote peers do not peer with each other, but further config changes will be required to support that functionality, based on our generated tm configs.
[0] https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
=> k8s: set externalTrafficPolicy=Local

component/src/stake/component.rs
There's an issue hinted at by an existing comment: the `LastCommitInfo` refers to the commit for the _last_ block, not the block in progress, i.e. during block 1 you're receiving commit info for the genesis block -- which has no commit info.
So, the fix introduced here is to consider all validators present to have voted during the genesis block to prevent the uptime tracking from reporting a single missed block in blocks 1+.
Closes #1050
=> Mark genesis block as voted

component/src/shielded_pool/note_manager.rs, crypto/src/asset/amount.rs, crypto/src/balance.rs, crypto/src/balance/imbalance.rs, crypto/src/balance/iter.rs, crypto/src/dex/swap.rs, crypto/src/dex/swap/plaintext.rs, crypto/src/note.rs, pcli/src/command/view/tx.rs
Partial implementation of https://github.com/penumbra-zone/penumbra/issues/1378, this PR:
- make Amount use a u128 internally
- provide a getter Amount::value returning a u64
- adds the necessary conversion traits
- implements encoding a u128 into two u64s, and vice-versa
Previous #1571 - reopened with a clean remote
=> feat(crypto): switch `Amount` to 128 bits internally

.github/workflows/smoke.yml, scripts/smoke-test.sh
The goal here is to get faster feedback from the smoke test suite. We now run the integration tests almost immediately after creating the network, allowing for a tighter feedback loop if errors are encountered, then continue running the network for a while longer, in an attempt to catch more subtle problems.
The wall-time here is mostly unchanged; the smoke test suite still takes >20m to complete. It will now exit much faster if errors are found, though, which is a win.
Closes #1780.
=> ci: make smoke tests fail fast

deployments/helm/templates/fn-tm-config.yaml
The first fullnode in the deployment will now have `p2p.seed_mode=true` set in its Terndermint config. The first fullnode already has its external IPs targeted by DNS A records like "testnet.penumbra.zone", so folks joining the testnet will still talk to the same service on the backend. The seed_mode=true change is intended to allow clients to connect and find peers, but then they'll be automatically disconnected immediately, ensuring that the max connections of 50 isn't exhausted by the first 50 peers joining.
Refs #1847.
=> feat: use seed node in k8s deployment

docs/guide/src/pd/join-testnet.md, pd/src/main.rs, pd/src/testnet.rs
Our auto-generated client config inherits "0.0.0.0" for `external_address` from the `laddr` setting. That works well enough to connect to the testnet, but doesn't support inter-peer gossip. Let's provide a flag to opt-in to p2p gossip. This setting isn't appropriate for all environments; the node admin must ensure that the relevant firewall configs are correct. Still, for those who run externally accessible nodes, this will permit them to declare themselves as viable peers for others.
Closes #1848.
=> feat: support external addr for testnet join

Cargo.lock, view/Cargo.toml, view/src/bin/pviewd.rs
This allows using Buf Studio against a local `pviewd` instance (!)
=> view: enable tonic-web for pviewd

Cargo.lock, crypto/src/keys/spend.rs, custody/Cargo.toml, custody/src/client.rs, custody/src/lib.rs, custody/src/policy.rs, custody/src/soft_kms.rs, custody/src/soft_kms/config.rs, pcli/src/opt.rs
This PR reworks the `custody` crate to support authorization policy, so that we can use it for online signers from other languages (e.g., the go relayer).
The behavior is defined by the `soft_kms::Config` struct, designed to be serialized using TOML:
```toml
spend_key = 'penumbraspendkey1h8z74kgcgm6azte70yehzv8tlkqwwlr4zpkt9qtr60zgkz5axesqnej2vj'
[[auth_policy]]
type = 'OnlyIbcRelay'
[[auth_policy]]
type = 'DestinationAllowList'
allowed_destination_addresses = ['penumbrav2t1zxzas63u5sy8s3ph5kh6tdd0dad6zxxgw3tr8vhhzvygwwzxvt87xfkldez8q2trm36xhnuagle9knt7lnyphcg2ap6yr0nlnsmcwzg95gn90wwhxjkc0acpd6thj2cu3qrn6n']
[[auth_policy]]
type = 'PreAuthorization'
method = 'Ed25519'
required_signatures = 1
allowed_signers = ['Ss08p+SPEk0sWRhDKDTFIkh07e6qLopQ2AFUq5toMds=']
```
In this example, three …
=> custody: rework crate to support policy

Dockerfile.old
The `pd` container in the docker-compose workflow had a mismatched command path of `/usr/bin/pd` in the Dockerfile, but `/bin/pd` in the docker-compose file referencing it. Let's use `/bin/pd` everywhere instead.
=> build: fix docker-compose entrypoint for pd

chain/src/note_source.rs, component/src/ibc/component/channel/stateful/proof_verification.rs, component/src/ibc/component/client.rs, component/src/ibc/component/client/stateful.rs, crypto/src/address.rs, crypto/src/encrypted_note.rs, pd/src/consensus/service.rs, pd/src/consensus/worker.rs, pd/src/main.rs, pd/src/mempool/service.rs, proto/src/protobuf.rs, transaction/src/action/output.rs, transaction/src/action/spend.rs, transaction/src/action/swap.rs, transaction/src/action/swap_claim.rs, transaction/src/plan/action/swap.rs, transaction/src/transaction.rs
Currently, we handle errors very poorly, leading to a lot of useless and unhelpful error messages, like `transaction malformed`. This PR works towards fixing that, by replacing a lot of `.map_err(|_| ...)` with `.context(...)`, and by passing full chains of error causes in `CheckTx`/`DeliverTx` messages.
=> Discard fewer errors

crypto/src/dex/lp/trading_function.rs, proto/proto/buf.lock, proto/proto/penumbra/core/dex/v1alpha1/dex.proto, proto/src/gen/penumbra.core.dex.v1alpha1.rs
Adds a new `SwapExecution` proto that contains the execution path of a particular swap, represented as `Trade`s consisting of a `Path` and amounts.
Closes #1834
This is branched from https://github.com/penumbra-zone/penumbra/tree/1836_amm_composition_cherry and shouldn't be merged before https://github.com/penumbra-zone/penumbra/pull/1854
=> Add `SwapExecution` proto

pcli/src/main.rs, pcli/src/opt.rs, pcli/tests/network_integration.rs
Ensures that diagnostic info emitted during `pcli` commands goes to stderr, so that only substantive content is written to stdout. This enables use of unix pipes, such as `| jq` to parse JSON data.
Also modified the tracing_subscriber config to ensure logged events for pcli do not pollute stdout. Tracing settings for other crates are unaffected.
Updates the pcli integration tests to read stdout in a few places, preserving the `--file` arg in others, so that both forms of invocation are exercised.
Closes #1624.
=> feat: pcli commands are composable with pipes

docs/protocol/src/crypto/decaf377-rdsa.md, docs/protocol/src/crypto/fmd/construction.md
[infinite loop just got fixed in `mdbook-katex` v0.3.4](https://github.com/lzanini/mdbook-katex/pull/62) so it should be able to render dollar signs in LaTeX now (`cargo install` in the GitHub Action should pick it up already)
fixes a number of artifacts like these:
=> docs: fix LaTeX delimiters`s/\\\\\$/\\$/g`

pd/src/main.rs, pd/src/testnet.rs, pd/src/testnet/generate.rs, pd/src/testnet/join.rs
Shoves things around a bit and fleshes out the docstrings. The `testnet generate` logic has been largely superseded by the config-munging in the k8s deploy scripts, but timeboxed the refactor to focus on organization.
=> refactor(pd): testnet logic moved to module

Cargo.lock, chain/Cargo.toml, chain/src/view.rs, pd/src/info.rs, pd/src/info/oblivious.rs, pd/src/info/specific.rs
Removes the `tonic` dependency from the `chain` crate, in order to support compiling it to wasm. The only use of `tonic` in `chain` was for a few error return types. Here we swap those specific errors for more general anyhow versions, and re-map them back to tonic::Status::unknown in the calling crate, `pd`. The use of `map_err` is suboptimal, but in the interest of unblocking external partners, seems a reasonable choice.
Closes #1857.
=> build(chain): drop tonic dep to support wasm

Cargo.lock, component/Cargo.toml, component/src/lib.rs, component/src/stake/validator.rs, custody/Cargo.toml, custody/src/lib.rs, custody/src/soft_kms/config.rs, pcli/Cargo.toml, pcli/src/command/validator.rs, pcli/src/legacy.rs, pcli/tests/network_integration.rs, wallet/src/key_store.rs
Resolves #1898.
This is missing updated documentation to reflect that validator definitions are toml instead of json now.
=> Uncouple serde minimal

component/src/dex/component.rs, component/src/dex/state_key.rs, docs/guide/src/pcli/transaction.md, docs/guide/src/pcli/update.md, docs/guide/src/pcli/wallet.md, docs/guide/src/pd/build.md, docs/guide/src/pd/join-testnet.md, pcli/tests/network_integration.rs
Went through sections 1 & 2 in the guide and updated according to the latest version of the code. There's now a two-stop process for undelegating:
* `undelegate <delegation>`
* `undelegate-claim`
Therefore closes #1755. Also includes JSON -> TOML changes resulting from #1911; there's a bit more follow-up required there, so the "Updating your validator" section still mentions JSON. That'll change soon.
=> docs: update undelegation and validator toml defs

component/src/app/mod.rs, pd/src/consensus/worker.rs, pd/src/mempool/worker.rs
This commit changes the tracing output to demote the mempool maintenance tasks and instead promote information about the blocks being processed and committed. Its output now looks like:
```
2023-02-03T05:31:26.027364Z  INFO abci:BeginBlock{height=10072}:app{role="consensus"}: beginning block time=Time(2023-01-31 15:18:27.927578868)
2023-02-03T05:31:26.079132Z  INFO abci:Commit:app{role="consensus"}: committed block app_hash=AppHash("79be9ea80a3e63992423eea639c2c1c46ebae32b5a11ffaff4c228d57b0cda54")
2023-02-03T05:31:26.143461Z  INFO abci:BeginBlock{height=10073}:app{role="consensus"}: beginning block time=Time(2023-01-31 15:18:33.399157325)
2023-02-03T05:31:26.193797Z  INFO abci:Commit:app{role="consensus"}: committed block app_hash=AppHash("600178a176b6fc1ca51bf74e9a3878ccb314305ecd8019f6a …
```
=> pd: improve tracing output at info level during block sync

Cargo.lock, docs/guide/src/dev/devnet-quickstart.md, pcli/src/opt.rs, pcli/tests/network_integration.rs, pd/src/main.rs, proto/Cargo.toml, scripts/grpcurl-wrapper, scripts/smoke-test.sh, view/Cargo.toml, view/src/bin/pviewd.rs, view/src/service.rs, view/src/storage.rs, view/src/worker.rs
Updated the option handling for pcli so that the `--node` arg is now a URL, rather than a hostname. Defaults to
`https://grpc.testnet.penumbra.zone`, which routes connections to pd's grpc service on the testnet deployment. Because it's a URL, HTTP is still supported, e.g. `http://testnet.penumbra.zone:8080`.
Requires disabling support for HTTP1 in the pd service. Was not able to identify any breakage from this change; external services like Buf Studio were still able to speak protobuf fine to the patched pd instance.
Includes a wrapper script that was helpful to me during debugging, so I'm tossing it in the repo.
=> feat(pcli): use https url by default for pd

docs/guide/src/pcli/install.md
Updates install instructions to avoid tarball-based git-lfs instructions. Also touches up the Fedora commands, ensuring they use `dnf` as `yum` is deprecated. Closes #1928. Supersedes and therefore closes #1919.
=> docs: install git-lfs from package managers

Cargo.lock, pcli/Cargo.toml, pcli/src/command.rs, pcli/src/command/debug.rs, pcli/src/main.rs
Emits a JSON struct tracking common support-related info. Closes #1564.
Running on my machine, I see:
```
❯ pcli debug info
{
"tendermint_version": "v0.34.23",
"pd_version": "pd 042-adraste-27-g959dc1d",
"pcli_version": "042-adraste-27-g959dc1d",
"uname": "Linux Antigonus 6.1.7-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jan 18 17:11:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux",
"pcli_data_directory": "/home/conor/.local/share/pcli",
"pcli_keyfile": "/home/conor/.local/share/pcli/custody.json",
"pcli_keyfiles_archived": [
"/home/conor/.local/share/penumbra-testnet-archive/4004b7529b88362b/custody.json",
"/home/conor/.local/share/penumbra-testnet-archive/b4ab58fadef2a573/custody.json",
"/home/conor/.local/share/penumbra-testnet-archive/accb59f66b2910be/custody.json"
]
}
```
The …
=> feat(pcli): 'debug info' subcommand

component/src/app/mod.rs, pcli/tests/network_integration.rs
This avoids the performance hit until we resolve that issue.
=> governance: temporarily disable BeginBlock/EndBlock until #1938

component/src/stake/component.rs, proto/src/state/read.rs, storage/src/snapshot.rs, storage/src/state.rs, storage/src/state/read.rs, storage/src/state/transaction.rs, storage/tests/basic.rs
Profiling revealed we were spending a lot of time parsing validator definitions and their funding streams during block sync. This PR aims at streamlining that, and in the process discovering some new patterns for working with the chain state.
In particular, it:
- Adds `StateRead::prefix_keys`, which works like `prefix_raw` but doesn't look up values;
- Changes the `StateRead::get*` trait methods to return `'static` futures, so that state queries can be run concurrently by spawning them as independent tasks.
- Changes the `build_tendermint_validator_updates` method that runs at the end of every block to (1) not parse full validator definitions and (2) to run each validator's state queries in parallel.
=> Improve efficiency of validator updates

crypto/src/dex/execution.rs, crypto/src/dex/lp/trading_function.rs, proto/proto/penumbra/core/dex/v1alpha1/dex.proto, proto/src/gen/penumbra.core.dex.v1alpha1.rs
This is a refactor that moves `TradingFunction::compose` into `BareTradingFunction`. A follow-up PR will deal with coefficient rescaling within `BareTradingFunction` as part of #1836
=> dex: move composition into `BareTradingFunction`

pd/src/consensus/service.rs, pd/src/consensus/worker.rs, pd/src/mempool/service.rs
Removes some superfluous spans and records ABCI events.  At some point we might want to demote the ABCI events, but it's a useful summary for now:
```
2023-02-07T22:45:58.056113Z  INFO abci:BeginBlock{height=15531}: beginning block time=Time(2023-02-07 22:45:52.083434842)
2023-02-07T22:45:58.116424Z  INFO abci:Commit: committed block app_hash=AppHash("77ecedaf48871e9f2296f8303d3b5b9a6450f42a14981bfa65c9295cedade1ee")
2023-02-07T22:46:02.653850Z  INFO abci:CheckTx{kind=New txid="79249e76a5f90fb664703198a0624050d7882993c2ab26521b4f27367ed4081c"}: tx accepted
2023-02-07T22:46:03.937495Z  INFO abci:BeginBlock{height=15532}: beginning block time=Time(2023-02-07 22:45:57.754330666)
2023-02-07T22:46:03.966957Z  INFO abci:DeliverTx{txid="79249e76a5f90fb664703198a0624050d7882993c2ab26521b4f27367ed4 …
```
=> pd: improve tracing output at info level

component/src/action_handler/actions/spend.rs, component/src/action_handler/actions/swap_claim.rs, component/src/shielded_pool/component.rs, component/src/shielded_pool/event.rs, component/src/shielded_pool/note_manager.rs, component/src/shielded_pool/state_key.rs, component/src/stake/component.rs, component/src/stake/event.rs, component/src/stake/mod.rs, pcli/src/command/query/shielded_pool.rs, pd/src/consensus/worker.rs
Per discussion on a shared slack channel, Cosmos-SDK apps use a config file to determine which events should be indexed or not; this is totally controlled by the app, and not by Tendermint. At some point we might consider giving users the option to configure indexing.
=> pd: more event improvements

component/src/stubdex/tests.rs, crypto/src/proofs/transparent.rs, transaction/src/plan/action/swap.rs
Closes #1746
The test here setting swap fees to non-zero fails on `main` due to the fee commitment integrity check failing in the corresponding swap proof. The second commit fixes the failure by ensuring the the fee commitment computation in the swap plan also uses `Balance::commit` (instead of `Value::commit` which does not first negate the fee value, resulting in the mismatch).
=> fix: fee commitment sign in swaps

.github/workflows/containers.yml, deployments/compose/docker-compose.multinode.override.yml, deployments/compose/docker-compose.override.yml, deployments/compose/docker-compose.prod.yml, deployments/compose/docker-compose.yml, deployments/config/Caddyfile, deployments/config/grafana/dashboards/ABCI.json, deployments/config/grafana/dashboards/Client Info.json, deployments/config/grafana/dashboards/Consensus.json, deployments/config/grafana/dashboards/P2P.json, deployments/config/grafana/dashboards/Penumbra.json, deployments/config/grafana/dashboards/Transactions.json, deployments/config/grafana/dashboards/Validators.json, deployments/config/grafana/grafana.ini, deployments/containerfiles/Dockerfile-grafana
Refs #1843. 
This PR includes a new container spec, and some tweaks to the compose files to consume the new container. No changes will be visible on the k8s deployments post-merge; first, I need CI to build the containers, then I'll work on wiring up some ingress and DNS for them. This work so far works just peachy on the caddy/compose setup when running a fullnode outside k8s, though.
=> ci: build grafana container with custom dashboards

storage/src/metrics.rs, storage/src/snapshot.rs
This could hopefully give us a little bit of insight into what our storage performance is like, but also lets us exercise the workflow of using newly added metrics.
=> storage: add metrics for state queries

docs/guide/src/dev/devnet-quickstart.md, docs/guide/src/pcli/balance.md, docs/guide/src/pcli/install.md, docs/guide/src/pcli/pviewd.md, docs/guide/src/pcli/transaction.md, docs/guide/src/pcli/update.md, docs/guide/src/pcli/wallet.md, docs/guide/src/pd/build.md, docs/guide/src/pd/join-testnet.md
We're trying to make the guide more accessible. In practice, symlinking the compiled binaries onto a PATH location allows for less typing at the command line, and makes the documentaiton significantly easier to read.
Closes #1976.
=> docs: prefer symlinks to 'cargo run' in guide

deployments/systemd/README.md, deployments/systemd/penumbra.service, deployments/systemd/tendermint.service, docs/guide/src/pd/join-testnet.md
Drops in some example configs for using systemd to orchestrate pd and tm. I use these configs myself in a few contexts to bottle up the start/stop logic in a predictable manner. Includes mention of the option in the setup guide.
Closes #1974.
=> deploy: document systemd service files

docs/guide/src/pd/join-testnet.md, pcli/src/command/validator.rs
Rather than recommending a two-step copy/paste workflow for creating validator identities, we now provide a CLI flag that supports reading in the `priv_validator_key.json` file for Tendermint, and uses its pubkey file when rendering the TOML template. Updated docs accordingly.
Closes #1992.
=> feat(pcli): flag for reading tendermint validator keyfile

crypto/src/keys/diversifier.rs
Toward addressing recent Galileo breakage, as of Testnet 45. Implements FromStr to aid in opt-parsing for galileo; see related PR at: https://github.com/penumbra-zone/galileo/pull/27
Refs https://github.com/penumbra-zone/galileo/issues/26
=> account groups: add from_str impl

Cargo.lock, chain/Cargo.toml, component/Cargo.toml, crypto/Cargo.toml, custody/Cargo.toml, eddy/Cargo.toml, pcli/Cargo.toml, pd/Cargo.toml, proof-params/Cargo.toml, proto/Cargo.toml, storage/Cargo.toml, tct-property-test/Cargo.toml, tct/Cargo.toml, transaction/Cargo.toml, view/Cargo.toml
Ran `cargo +nightly udeps --all-targets` and slimmed down the Cargo.toml files based on that output. Followed the recommendations rather blindly, but still builds fine.
Refs #1990, which tries to eliminate a few specific dependencies. Motivation for scanning for unused deps in #2025.
=> build: remove unused cargo dependencies

.github/workflows/containers.yml
Closes #2042
Tested in docker build https://github.com/penumbra-zone/penumbra/actions/runs/4268186803/jobs/7430482760
=> ci: use git LFS for penumbra docker build

Cargo.lock
Pulls in `tendermint` 0.29.1 with nicer debug output
=> deps: cargo update

pcli/src/network.rs, transaction/src/transaction.rs
we don't have to keep this forever, but it seems nice as we enable zk proofs
=> pcli: add output describing proving latency

component/src/action_handler/transaction/stateless.rs, transaction/src/auth_hash.rs, transaction/src/effect_hash.rs, transaction/src/lib.rs, transaction/src/plan/build.rs
This is immediately motivated by not wanting to have messy debug output for binding signature verification, but also fits with the conceptual division between "authorizing" and "effecting" data, which now both have their own hash type.
One rough edge in nomenclature this reveals (which we should sand down somehow) is the distinction between `AuthorizingData` (the trait) and `AuthorizationData` (the response from the custody protocol).  Unsure of the best thing to do there.
=> transaction: introduce an AuthHash for use in binding signatures

crypto/src/proofs/groth16.rs, crypto/src/proofs/groth16/output.rs, crypto/src/proofs/groth16/spend.rs, crypto/src/proofs/groth16/traits.rs, proof-params/src/lib.rs
Not sure if this clobbers any other changes, I did it just to see if there would be a performance impact and then put it up.
=> proof-params: use prepared verification keys

custody/src/client.rs, transaction/src/plan/build.rs, view/src/client.rs
This makes it possible to use the well-typed client methods inside spawnable futures.
=> view,custody: fix missing Send bounds on domain-type traits

Cargo.lock, component/src/action_handler/transaction.rs, pcli/src/command/tx.rs, pcli/src/network.rs, proto/proto/penumbra/core/transaction/v1alpha1/transaction.proto, proto/proto/penumbra/view/v1alpha1/view.proto, proto/src/gen/penumbra.core.transaction.v1alpha1.rs, proto/src/gen/penumbra.core.transaction.v1alpha1.serde.rs, proto/src/gen/penumbra.view.v1alpha1.rs, proto/src/gen/penumbra.view.v1alpha1.serde.rs, transaction/src/id.rs, transaction/src/lib.rs, transaction/src/transaction.rs, view/Cargo.toml, view/src/client.rs, view/src/service.rs
This pulls code out of `pcli` and puts it in the view service, so that users of
the view service can submit transactions and await detection without having to
write custom code.
=> view: add BroadcastTransaction with confirmation detection to ViewService

Cargo.lock, deployments/scripts/smoke-test.sh, pcli/Cargo.toml, pcli/src/command/tx.rs, pcli/tests/network_integration.rs
`pcli` waits for confirmation anyways, so it shouldn't be necessary to wait extra time.
=> ci: remove unnecessary smoke test delays

.github/workflows/smoke.yml, deployments/scripts/smoke-test.sh, pcli/tests/network_integration.rs, pd/src/main.rs, pd/src/testnet.rs, pd/src/testnet/generate.rs
This PR changes the smoke test to run with sub-second block times.
Also, I noticed that the undelegation test isn't actually exercising the undelegation claim flow.  In a future PR, it'd be good to add functionality that adds it to the test and checks that it worked.
=> ci: try faster block times for smoke test

crypto/src/address/r1cs.rs, crypto/src/asset/amount.rs, crypto/src/asset/r1cs.rs, crypto/src/balance/commitment.rs, crypto/src/keys/fvk/r1cs.rs, crypto/src/keys/nullifier.rs, crypto/src/note/r1cs.rs, crypto/src/nullifier.rs, crypto/src/value.rs, tct/src/r1cs.rs
The [R1CSVar](https://docs.rs/ark-r1cs-std/latest/ark_r1cs_std/trait.R1CSVar.html) trait is very useful for debugging as it lets you call `.value()` to learn what value the variable has in the constraint system. This PR implements it for most of our circuit variables, though I've noted a couple of places where it doesn't make sense, e.g. we can't reconstruct a full `Note` because we don't have the rseed in-circuit, only the derived values. 
Related to #2040
=> crypto(zk): impl `R1CSVar` for our circuit variables

.github/workflows/rust.yml, wasm-compat/.gitignore, wasm-compat/Cargo.toml, wasm-compat/README.md, wasm-compat/justfile, wasm-compat/src/lib.rs, wasm-compat/src/main.rs
Created a placeholder app, separate from the workspace, strictly to test coverage of building for wasm targets. Right now, only `crypto`, `proto`, and `tct` build without modifications.
Refs #1990.
=> ci: dummy-app for wasm support

crypto/src/proofs/groth16/output.rs, crypto/src/proofs/groth16/spend.rs
There have been a couple of folks reporting unexpected proof verification failures when trying to delegate or send on the most recent testnet: unfortunately these are a hard to debug since we don't have a reproducer. For the next testnet we should add additional logging such that we can ask folks to run their command with `RUST_LOG=debug` to get more info about what is going on. Possible causes include using out of date software/proving parameters or a bug that we only hit in a small subset of cases.
=> adding more logging for verification failures

Cargo.lock, chain/Cargo.toml, component/Cargo.toml, crypto/Cargo.toml, decaf377-fmd/Cargo.toml, decaf377-ka/Cargo.toml, eddy/Cargo.toml, pcli/Cargo.toml, pd/Cargo.toml, proof-params/Cargo.toml, tct-visualize/Cargo.toml, tct/Cargo.toml, tools/parameter-setup/Cargo.toml, transaction/Cargo.toml
This PR switches our decaf377 git dependency to the published [version (0.2.0)](https://github.com/penumbra-zone/decaf377/releases/tag/0.2.0) on crates.io. 
Towards https://github.com/penumbra-zone/penumbra/issues/2004
Note only the last two commits are relevant here as this is a PR stacked on #2083. Before this PR is merged:
This PR switches us from `frost377` main branch to one using `decaf377` 0.2: https://github.com/penumbra-zone/frost377/pull/3
Once this is merged, I will merge https://github.com/penumbra-zone/frost377/pull/3 and then switch us back to the `main` branch of frost377. This is done to minimize disruption to folks that are building on `main` of this repo.
=> use decaf377 0.2

proto/proto/buf.lock, proto/proto/buf.yaml
We use the tendermint-related proto files for the tendermint proxy service. However, because the ibc-go protos depended on them, Buf didn't complain about the implicit dependency.
=> proto: make our implicit dependency on the cosmos-sdk protos explicit

Cargo.lock, chain/Cargo.toml, component/Cargo.toml, component/src/action_handler/actions/proposal/submit.rs, crypto/Cargo.toml, custody/Cargo.toml, decaf377-fmd/Cargo.toml, decaf377-ka/Cargo.toml, eddy/Cargo.toml, pcli/Cargo.toml, pclientd/Cargo.toml, pd/Cargo.toml, proof-params/Cargo.toml, tct-visualize/Cargo.toml, tct/Cargo.toml, tools/parameter-setup/Cargo.toml, transaction/Cargo.toml, transaction/src/plan/build.rs, view/Cargo.toml, wallet/Cargo.toml, wallet/src/build.rs
Closes #2124 
This first needs:
This was tested by running `cargo tree -p pcli -e features`:
* With the `pcli` `parallel` feature enabled: confirming rayon was in the output
* With the `pcli` `parallel` feature disabled: confirming rayon was _not_ in the output
=> crypto: by default do not use parallelism

crypto/src/proofs/groth16.rs, crypto/src/proofs/groth16/traits.rs, proof-params/src/gen/output_id.rs, proof-params/src/gen/spend_id.rs, proof-params/src/gen/swap_id.rs, proof-params/src/lib.rs, proof-params/src/proving_keys.rs, tools/parameter-setup/src/main.rs
Not sure if this is the best approach; AFAICT there's not a way to run the parameter generator without overwriting the existing parameters, so I manually set the debug hashes to the values for the existing parameters.
=> proof-params: add hardcoded hashes for proving keys

pclientd/src/lib.rs
It now uses the string format, like so (shown is the test account):
```toml
fvk = 'penumbrafullviewingkey1f33fr3zrquh869s3h8d0pjx4fpa9fyut2utw7x5y7xdcxz6z7c8sgf5hslrkpf3mh8d26vufsq8y666chx0x0su06ay3rkwu74zuwqq9w8aza'
[kms_config]
spend_key = 'penumbraspendkey1e9gf5g8jfraap4jqul7e80vv0zrnwpsm4ke0df38ejrfh430nu4s9gc22d'
```
Closes #2186
=> pclientd: fix config file format for FVK

pcli/src/command.rs, pcli/src/command/query/governance.rs
It's just querying a fullnode, so there's no need to sync local state, and not waiting to sync local state makes it more useful in debugging (e.g., it's possible to query multiple chains simultaneously).
=> pcli: mark `pcli q` as not requiring a chain sync

Cargo.lock, measure/Cargo.toml, measure/src/main.rs
```
Running `target/release/measure stream-blocks`
[2s] ██████████████████████████████████████████████████   57106/57106   23771/s ETA: 0s
Fetched at least 6.2 MB
Fetched 57107 compact blocks, containing:
5900 nullifiers
18667 state payloads, containing:
18646 note payloads
7 swap payloads
14 rolled up payloads
```
=> measure: print stats on downloaded compact blocks

component/src/dex/position_manager.rs, component/src/dex/state_key.rs, pcli/src/command.rs, pcli/src/command/query/dex.rs, pd/src/info/specific.rs, proto/proto/buf.lock, proto/proto/penumbra/client/v1alpha1/client.proto, proto/src/gen/penumbra.client.v1alpha1.rs, proto/src/gen/penumbra.client.v1alpha1.serde.rs
This adds a new `pcli q dex liquidity-positions` command with an optional filter (`--only-open`) that will query a node for known liquidity positions and print them in a basic table view.
=> `pqli q dex liquidity-positions` implementation

Cargo.lock, deployments/helm/templates/fn-deployments.yaml, deployments/helm/templates/val-deployments.yaml, deployments/scripts/smoke-test.sh, docs/guide/src/dev/devnet-quickstart.md, docs/guide/src/pcli/pclientd.md, docs/guide/src/pd/join-testnet.md, measure/src/main.rs, pcli/src/opt.rs, pcli/tests/network_integration.rs, pclientd/Cargo.toml, pclientd/src/lib.rs, pclientd/tests/network_integration.rs, pd/src/main.rs, pd/src/testnet.rs, pd/src/testnet/generate.rs, pd/src/testnet/join.rs, view/Cargo.toml, view/src/service.rs, view/src/storage.rs, view/src/worker.rs
Updates the CLI args for pcli, pd, and pclientd to use `net::SocketAddr` types for local bind addresses, and `url::Url` types for remote endpoint specification. This makes the CLI args more verbose, but also more explicit and more flexible. For instance, it's now possible to bind pd's metrics port to localhost, but the grpc pd service to a different interface.
Also adds env var options for the new CLI args, to standardize config from other wrapper tools and testing environments.
To see the new options at a glance:
```
cargo build --release
./target/release/pcli -h
./target/release/pclientd -h
./target/release/pclientd start -h
./target/release/pd start -h
./target/release/pd testnet join -h
```
Closes #2196. Closes #2240.
=> Use URLs and SocketAddrs for CLI args

deployments/relayer/README.md, deployments/relayer/configure-relayer, deployments/relayer/generate-configs
This adds a `local` option for testing a local devnet against `preview` or `testnet`.
=> add `local` option to relayer-configs

deployments/relayer/README.md, deployments/relayer/configs/penumbra-preview.json, deployments/relayer/configs/penumbra-testnet.json, deployments/relayer/configs/penumbra.tpl, deployments/relayer/configure-relayer, deployments/relayer/generate-configs, deployments/relayer/justfile, deployments/relayer/run-relayer
Towards #465. Records initial config generation logic for using `rly` (built from the WIP PR at https://github.com/cosmos/relayer/pull/1124). 
The plan is to post transactions between testnet & preview, using the relayer, which must be configured with chain info for both networks, as well as wallet identities. No path configuration logic exists yet; will work with @avahowell to get that straightened out soon.
=> wip: relayer config generation

chain/src/known_assets.rs, pcli/src/command.rs, pcli/src/command/query/chain.rs, pcli/src/command/query/dao.rs, pcli/src/command/query/dex.rs, pd/src/info/oblivious.rs, proto/proto/penumbra/client/v1alpha1/client.proto, proto/src/gen/penumbra.client.v1alpha1.rs, proto/src/gen/penumbra.client.v1alpha1.serde.rs
This allows the various `pcli q` commands to run entirely in offline mode.
I realized after writing this that I possibly could have used the existing `TendermintProxyService` rather than adding an `info` call proxy to `ObliviousQueryService`, but this can be cleaned up in a subsequent PR.
Closes #2223
=> #2223: Remove use of view service from `pcli q` commands

proto/proto/buf.lock, transaction/src/effect_hash.rs, transaction/src/plan.rs, transaction/src/plan/build.rs, transaction/src/transaction.rs, view/src/planner.rs
=> Support `PositionClose` within the planner

component/src/ibc/component/client.rs, component/src/ibc/component/connection/stateful.rs
This is looking up the connection state on chain A, which is processing the ConnectionOpenAck message.
=> ibc: correct connection ID in ConnectionOpenAck

crypto/src/dex/swap.rs, crypto/src/fixpoint.rs
I didn't notice this while reviewing, because the 1/2 typo was buried in conversions; this makes them clearer and adds a test. (We should add more test cases).
=> dex: fix inflation bug with clearer formulas

.gitignore, chain/Cargo.toml, chain/src/view.rs, measure/Cargo.toml, pd/Cargo.toml, proof-params/build.rs, proto/Cargo.toml, tct/Cargo.toml
Several of our crates failed to build under certain combinations of feature flags. Stepped through those crates and adjusted the feature logic where required.
Regarding runtime for this CI check, the wall time isn't bad, especially if we parallelize it with the other rust checks:
command: cargo check-all-features --release
warm cache: 1m39s
cold cache: 12m4s
Notably, the disk usage is an order of magnitude higher:
dir size of `target/`
cargo build --release: ~3.4GB
cargo check-all-features --release 25G(!)
In order to support that additional disk usage in CI caching layers, we'll likely have to pony up for more space on our CI runners.  Still, that's well worth the confidence that we have working builds across all feature combinations.
=> build: straighten out feature flags

deployments/scripts/smoke-test.sh, pcli/tests/network_integration.rs
Closes #2099 ~, except this will currently fail due to the undelegate claim not being implemented from within pcli, I think due to #1901 needing implementation~ (wrong, must have been on the wrong branch or something?)
=> test(integration): undelegate claim

pd/build.rs
Closes #2191. If any files within the latest testnet dir, e.g. `testnets/049-pasiphae` change, then `pd` should be rebuilt. Technically we could just as easily watch for changes to `testnets/`, but one must rerun the intermediate script `testnets/new-testnet.sh` for changes to make it into the allocations dir.
=> build: rebuild pd if testsnet dir changes

deployments/relayer/README.md, deployments/relayer/configs/babylon-testnet.json, deployments/relayer/configs/celestia-testnet.json, deployments/relayer/configs/cosmwasm-testnet.json, deployments/relayer/configs/osmosis-testnet.json, deployments/relayer/configs/penumbra-preview.json, deployments/relayer/configure-relayer, deployments/relayer/generate-configs, deployments/relayer/justfile, deployments/relayer/run-relayer
Refs #2284. Does _not_ achieve working packet relay between other Cosmos chains, but does extend our debugging coverage, so I'm submitting this WIP for inclusion so we can pick up where we left off.
=> relayer: testnet configs for other cosmos chains

.gitattributes, .github/workflows/buf-pull-request.yml, .github/workflows/smoke.yml, Cargo.lock, pclientd/Cargo.toml, pclientd/src/lib.rs, pd/Cargo.toml, pd/src/main.rs, proto/src/gen/proto_descriptor.bin, proto/src/lib.rs, tools/proto-compiler/src/main.rs
To do this, we have to save the `proto_descriptor.bin` generated by Prost/Tonic.  It's currently 300KB and changes with every proto edit, so I attempted to configure it to use git lfs.
Then, in the `pclientd` and `pd` binaries, we add a grpc-web enabled version of the reflection service.
Closes #2299.
=> proto: enable grpc reflection

pcli/src/command/keys.rs
This lets you copy paste a base64 encoded string to access the `pclientd` rpcs
=> pcli: add stub export account-group-id for use with grpcui

tendermint-proxy/Cargo.toml
This One Cool Change™ allows `cargo check-all-features --release` to pass without error. The tendermint-proxy crate (#2253) has a hard dependency on the "rpc" feature within the proto crate, so let's declare that explicitly.
=> build: fix tm proxy feature for proto dep

Cargo.lock, pcli/Cargo.toml, pcli/src/network.rs
I haven't got this working against https://grpc.testnet.penumbra.zone, which fails with
```
Error: status: Internal, message: "grpc-status header missing, mapped from HTTP status code 400", details: [], metadata: MetadataMap { headers: {"content-length": "0", "date": "Sat, 08 Apr 2023 21:51:34 GMT", "via": "1.1 google", "alt-svc": "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"} }
```
but I think this isn't a problem with the `pcli` support, so this could be good to merge anyways (but not yet advertise).  Once we can get HTTPS working with grpc.testnet.penumbra.zone, we can switch the default endpoint over.
=> pcli: try to support HTTPS URLs

view/src/storage.rs
This avoids failures in propagating detections when transactions have many spends or outputs.
=> view: increase detection buffer sizes

docs/protocol/src/SUMMARY.md, docs/protocol/src/protocol/action_descriptions/spend.md, docs/protocol/src/protocol/notes/nullifiers.md
Adding additional documentation towards #1825
More to come, e.g. the details of Merkle path verification is not described anywhere yet in the protocol docs
=> spec: add description of spend zk-SNARK statements

Cargo.lock, pd/Cargo.toml, pd/src/auto_https.rs, pd/src/lib.rs, pd/src/main.rs
Work towards #1406
This works now.  Still TODO:
Later:
=> Add auto-https support to `pd`

proto/Cargo.toml, proto/build.rs
If the build machine lacks git-lfs, then the binary `proto_descriptor.bin` file will just be a plaintext pointer file. Let's check that file's size, and if it's too small, we error out with some helpful recovery steps.
Closes #2354.
If you want to test this locally:
```
git clone https://github.com/penumbra-zone/penumbra penumbra-no-lfs
cd penumbra-no-lfs
cargo build --release
```
You should see an error message. If you don't, the logic in this PR is bad, and should be fixed. If you do, follow the recovery steps in that error message. If they resolve the situation, great! If you're still stuck, that means we should fix up the message.
=> build: fail proto if missing proto descriptor

app/src/dex/position_manager.rs, app/src/dex/router/path.rs, app/src/dex/tests.rs, crypto/src/dex/lp/trading_function.rs, proto/proto/buf.lock
The definition we use elsewhere is that a better price is a lower one; this aligns the `effective_price` method to that definition.
WIP: need to update rounding edge-case tests.
=> dex: correct definition of "effective price"

app/src/dex/router/path.rs, app/src/dex/router/tests.rs, crypto/src/asset/denom.rs, crypto/src/dex/lp/trading_function.rs
This PR cherry-picks from and replaces #2362.
This PR:
```
cheap: 0.6668667066733344
expensive: 1.0003000600100016
```
#2362:
```
cheap: 0.666466686666
expensive: 0.999700029999
```
The `expensive` path is going `gm=>gn=>pusd=>penumbra`; per the comment, the relative prices are 1:2, 2:1, 1:1, so this should be unit price plus the cost of fees, and that means that the price has to be _greater_ than 1, because the fees increase the cost.
Side note: the exchange rates seem wrong, we should have gm:gn be the unit price pair (as if they were two different path representations) and have the gm/gn:pusd and penumbra:pusd pairs be the free-floating ones.
=> Fix `Path::extend` orientation

.gitignore, deployments/relayer/README.md, deployments/relayer/generate-configs
Adds some docs on maintenance tasks and common testing procedures. Links out to information elsewhere, just making it discoverable via the relayer README.
Refs #465, #2252.
=> docs: how to run relayer via local devnet

app/src/dex/router/fill_route.rs, app/src/dex/tests.rs
The main idea behind our current approach to solving executing builds off the assumption that there exists a route between `source` and `target` that has:
- at least infinitesimal capacity
- an execution price similar, or better, than the spill price
The current implementation assumes that the latest constraining hop is also the most constraining one. But this is not necessarily the case, and execution along such routes does fail. This PR changes the implementation of the execution algorithm to pick the smallest "maximum `delta_1`" so that every iteration of the fill-phase lifts the most constraining hop.
=> dex(router): implement fill phase with stacked constraints

.github/workflows/deploy-testnet.yml
Using the new `v1.2.3` semver tag format, managed by cargo-release, to trigger testnet deployments. Refs #1961, #2360.
=> ci: update tag format for deploy workflow

custody/src/request.rs, pclientd/tests/network_integration.rs, proto/proto/penumbra/view/v1alpha1/view.proto, proto/src/gen/penumbra.view.v1alpha1.rs, proto/src/gen/penumbra.view.v1alpha1.serde.rs, proto/src/gen/proto_descriptor.bin, view/src/service.rs, wallet/src/build.rs
It's marked as an optional field in the protos, but it wasn't treated as optional by the rust view server.  This is annoying, since it makes it very hard to use the view RPCs without already having the account group ID in hand. We should let it be optional, since in every current implementation of the view RPC, the account group ID is already implied by the endpoint (all current implementations only support one account group).
=> view,custody: make account_group_id be actually optional

.github/workflows/deploy-preview.yml, .github/workflows/deploy-testnet.yml
The CI changes in #2387 were incomplete: they should have updated the PENUMBRA_VERSION var with the value of `github.ref_name`, so that the tag name is used to identify the container image. The default value of referencing an input will fail if the workflow is triggered from a tag, causing "main" to be deployed instead.
Although not strictly necessary, we modify the vars for the preview deploy, as well, to maintain parity.
=> ci: fix patch release workflow

proto/proto/buf.lock, wasm/src/lib.rs, wasm/src/tx.rs, wasm/src/view_server.rs
It should be called the `ViewServer`, because it serves the view RPC; it's a client to a fullnode.
=> wasm: rename `ViewClient` to `ViewServer`

.github/ISSUE_TEMPLATE/release_testnet.md
Documents the new release workflow, based on cargo-release, as described in #1961. We used these steps for the first time in testnet 51 #2360.
=> docs: update release steps

app/src/dex/router/fill_route.rs, app/src/dex/router/tests.rs
This PR implements a `test_spill_price_check` that tests that we fill as much of a route up to the specified spill price. In particular, its purpose is to check that we neither over or under-fill. It also correct `effective_price` calculation within `fill_route` to make it work when the route asset ids are not ordered.
=> router(dex): implement `spill_price` check

chain/src/params.rs, pcli/src/command/query/ibc_query.rs
Two changes:
* more readable error msgs for `pcli q ibc`, hopefully unobjectionable
* changes default chain params to enable inbound/outbound transfers
Regarding the latter, it looks like that's effectively a no-op. But I'm clicking it on anyway in case the relayer code is checking those values in ways I don't understand.
Will continue to test relayer against preview/devnet post-merge in #2330.
=> IBC quality of life changes for relayer work

pclientd/src/main.rs
The envfilter setting pulled in via #2327 inadvertently broke the `pclientd` binary, by preventing it from running if the env var RUST_LOG was not set (the default behavior). The other bins like pd and narsild handled this error appropriately, via `or_else` and setting a default of "info". Porting that logic to pclientd resolves.
=> pclientd: fix envfilter setting, unbreaking bin

pcli/src/command/tx.rs, pcli/src/command/view.rs, pcli/src/command/view/approximate.rs, pcli/src/dex_utils.rs, pcli/src/dex_utils/approximate.rs, pcli/src/main.rs
Closes #2319 .
This PR creates a `pcli::dex_utils` module which will be home to client-side dex utilities such as the trading function approximations, the online order execution (e.g. TWAP, VWAP etc.), and more. It also stubs a new pcli command:
`pcli view approximate constant-product <PAIR> <VALUE>`
=> pcli(dex_utils): create harness for RMMs

Cargo.lock, app/Cargo.toml, chain/Cargo.toml, pcli/Cargo.toml, pclientd/Cargo.toml, pd/Cargo.toml, proto/Cargo.toml, transaction/Cargo.toml, view/Cargo.toml
This will avoid breakage when we merge breaking changes into the ibc-types repo.
=> deps: use an explicit branch for ibc-types

app/src/dex/router/fill_route.rs, app/src/dex/router/tests.rs
Previously, `fill_route` was expecting its `route` parameter to contain an end-to-route from some `source` to a desired `target`. In practice however, `path_search` returns the "hops" between a known `source` and a target (i.e. the route minus the source). This PR adjusts tests and `fill_route` to work with that api.
=> router(dex): make `fill_route` take `hops`

app/src/dex/component.rs, app/src/dex/position_manager.rs, app/src/dex/router/mod.rs, app/src/dex/router/path.rs, app/src/dex/router/path_cache.rs, app/src/dex/router/path_search.rs, app/src/dex/router/route_and_fill.rs, app/src/dex/router/tests.rs, app/src/dex/state_key.rs, storage/src/delta.rs, storage/src/storage.rs
=> Implement new dex component (WIP)

storage/src/delta.rs, storage/src/escaped_byte_slice.rs, storage/src/lib.rs, storage/src/storage.rs
This may be helpful for debugging.
=> storage: add an EscapedByteSlice convenience wrapper

pd/build.rs, tct-visualize/build.rs
Fixes build caching for pd. Follow up to #2292. Ensures that the testnet directory referenced by the pd build script is a fullpath, rather than a dirname. The dirname didn't resolve to a valid relpath from the perspective of the build, so cargo was always rebuilding pd, even when no code had changed.
For reference, the command I used to identify the always-marked-dirty dir build dep was:
CARGO_LOG=cargo::core::compiler::fingerprint=info cargo build --release --bin pd
The speedup on hot builds of pd is ~100x, 30s -> 0.3s on my machine. Benchmarks from local runs:
On main:
```
❯ hyperfine --warmup 2 --runs 5 'cargo build --release --bin pd' 
Benchmark 1: cargo build --release --bin pd
Time (mean ± σ):     32.689 s ±  0.244 s    [User: 143.447 s, System: 3.406 s]
Range (min … max):   32.394 …
```
=> build: fix pd rebuild on testnet dir

app/src/action_handler/actions/swap_claim.rs, app/src/stubdex/component.rs, crypto/src/dex/swap.rs, crypto/src/proofs/transparent.rs, proto/proto/penumbra/core/dex/v1alpha1/dex.proto, proto/src/gen/penumbra.core.dex.v1alpha1.rs, proto/src/gen/penumbra.core.dex.v1alpha1.serde.rs, proto/src/gen/proto_descriptor.bin
Closes #2351
Note also that I don't think we need the `epoch_duration` on the `SwapClaim`, but I don't want to make a breaking change to the protos.
=> dex: add epoch height to `BatchSwapOutputData`

app/src/dex/position_manager.rs, pd/src/info/specific.rs, proto/src/state/read.rs
There were some instances where we were attempting to re-stream streams across RPC boundaries in a way that only returned the last item. This replaces all instances of that pattern with a simpler implementation using stream combinators.
=> Fix bad re-streams

.github/workflows/notes.yml, .github/workflows/rust.yml, .github/workflows/smoke.yml
We've gone over the 10GB per-repo limit for workflow caches on GH. GH will automatically evict caches not used for a week or longer, but we've had a bunch of active PRs with plenty of rebases, and went over, ~22GB/10GB. Manually cleaned up old caches in the GitHub UI [1] to unbreak workflow runs. This change brings us up to speed with the latest release for the associated GH action helper, which has some updated caching settings in the changelog. May need to follow up with refinements to ensure that we don't hit the cache limit again.
N.B. GH does not allow us to purchase a cache increase per repo, which is unfortunate.
[0] https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy
[1] …
=> ci: update rust cache action v1 -> v2

.github/workflows/deploy-preview.yml
Sometimes we merge several PRs in succession, and currently that causes preview deploys to trigger in parallel, which leads to a race on container build and cluster deploy. Let's instead always prefer the most recent merge, cancelling prior builds if they're still ongoing.
=> ci: cancel pending preview deploys

app/src/dex/component.rs, app/src/dex/router/route_and_fill.rs, pcli/tests/network_integration.rs
This fixes the swap integration test failure seen [here](https://github.com/penumbra-zone/penumbra/actions/runs/4874596015/jobs/8695739703)
=> fix: put starting block height of epoch into BSOD

crates/ibc/src/component/client.rs
differentiate between client type and client state lookups
=> ibc: improve logging

app/src/dex/component.rs, app/src/dex/position_manager.rs, app/src/dex/router/fill_route.rs, app/src/dex/router/path_search.rs, app/src/dex/router/route_and_fill.rs, app/src/dex/router/tests.rs, app/src/dex/tests.rs, pcli/src/command/tx/liquidity_position.rs
Something's still wrong here, because we're doing pessimal routing:
```
cargo run --release --bin pcli -- -n http://localhost:8080 tx position order sell 200penumbra@1.3gm
cargo run --release --bin pcli -- -n http://localhost:8080 tx position order sell 20penumbra@1.2gm
cargo run --release --bin pcli -- -n http://localhost:8080 tx position order sell 10penumbra@1.1gm
```
```
cargo run --release --bin pcli -- -n http://localhost:8080 q dex liquidity-positions
ID                                                                Trading Pair    State   Reserves  Trading Function
plpid1drwgws98rry6xqcax9dtavfh3s4j7u6sr2mdd43qsm775ultm3pql8rleg  (gm, penumbra)  opened  (0, 10)   fee: 0bps, p/q: 1.100000, q/p: 0.909091
plpid1rzrcq2rm6pgdtv2ffxfry92zaxek0z4vjwl423r3j5vduyz0mveq4k4yjm  (gm, …
```
=> dex: integration debugging

app/src/dex/router/route_and_fill.rs, pcli/tests/network_integration.rs
The existing dex smoketests assumed the genesis liquidity pools would exist and were failing as a result.
They've been updated to exercise liquidity position opening to enable the swap to run.
We should probably add a full LP lifecycle test.
=> test(integration): Fix dex smoketests

crates/ibc/src/component/msg_handler/connection_open_try.rs
we were using the wrong client ID here; this wasn't noticed because our testing coincidentally used chains with the same client count, resulting in the counterparty & base chain client ids always being the same.
=> ibc: connection_open_try: fix client id handling

app/src/dex/component.rs, app/src/dex/router/route_and_fill.rs, app/src/dex/router/tests.rs
This fixes the dex execution so that all available routes will be exercised during filling of batch swaps.
=> Fill across consecutive routes until all input exhausted or no route can be found

app/src/dex/router/fill_route.rs
After running these commands, similar to our test code:
```
cargo run --release --bin pcli -- -n http://localhost:8080 tx position order sell 25gn@1gm
cargo run --release --bin pcli -- -n http://localhost:8080 tx position order buy 1pusd@20gm
cargo run --release --bin pcli -- -n http://localhost:8080 tx position order buy 1pusd@20gm
cargo run --release --bin pcli -- -n http://localhost:8080 tx position order buy 5penumbra@1gm
cargo run --release --bin pcli -- -n http://localhost:8080 tx position order sell 1pusd@5penumbra
cargo run --release --bin pcli -- -n http://localhost:8080 tx swap 10penumbra --into gn
```
I saw this chain halt: https://gist.github.com/hdevalence/2ee2c17d6092dca701b45821b2cc9b0f
This commit changes the code to instead burn any rounding error and warn loudly about …
=> dex: burn rounding error rather than halting the chain

pcli/src/command/query/chain.rs
Wanted to look this up, and the first place I checked didn't have it. Exposing it in the `pcli query chain params` output for visibility.
=> pcli: add proposal cost to query chain params

crypto/src/keys/diversifier.rs
=> Fix AddressByIndex handler for cases of AddressIndexes with empty randomizers

narsil/src/bin/narsild.rs, pclientd/src/lib.rs, pd/src/main.rs
This restores the ability to use web clients, like https://studio.buf.build, or the browser extension, against local instances of these services.  I also tested (by temporarily running this branch on `pd-tls.penumbra.zone` with auto-https enabled) to check that it doesn't interfere with https support, either for browser clients or for `pcli`.
=> grpc: re-enable http/1

docs/guide/src/pcli/transaction.md, pcli/src/command/tx.rs, pcli/src/command/tx/liquidity_position.rs, pcli/tests/network_integration.rs
=> Implement close-all/withdraw-all

app/src/dex/router/tests.rs
When I tried to fix #2499 in #2503 , I actually forgot to implement the "burning" part of the patch. This means that when when the router encounters dust constraints it will fail to make progress as reflected in the `fill_route_stacked_dust_constraints` test.
This PR adds a `#[ignore]` on the `fill_route_*` tests until we fix that part of the DEX engine.
=> router(dex): disable the fill_route tests to avoid hanging ci

pcli/src/command.rs, pcli/src/command/query/dex.rs, pcli/src/command/tx.rs, pcli/src/command/tx/approximate.rs, pcli/src/command/utils.rs, pcli/src/dex_utils/approximate.rs
This leaves out interactivity for now. I'm just rendering positions using the logic we already have for querying dex positions (factored out into a `command::utils` crate). My immediate next step is a round of testing against devnet.
=> pcli(dex_utils): render list of positions

crates/ibc/src/component/channel.rs, crates/ibc/src/component/state_key.rs, deployments/relayer/configs/penumbra-preview.json, pd/src/info.rs
these are required for packet relay compatibility with the cosmos relayer
=> pd: add query handlers for packet queries

app/src/dex/router/fill_route.rs, app/src/dex/router/tests.rs
This PR changes the `FillRoute` implementation to fill each successive frontier transactionally, letting us inspect the exact, actual price and compare it with the spill price.  This avoids the situation in the current code where the spill price is only checked _after_ committing to exceeding it.
The current behavior _is_ retained in one special case, however: if we haven't consumed _any_ positions, by default we don't consider the spill price.  The motivation is that the spill price is an estimate, and we haven't ruled out the possibility that there could be two very similar routes, each with an estimated price below their actual price, which could cause the spill/fill cycle to alternate between them, always avoiding doing any filling because the fill would be more than the …
=> dex: exact spill price handling in `FillRoute`

app/src/action_handler/actions/position/close.rs, app/src/dex/component.rs, app/src/dex/position_manager.rs, app/src/dex/router/fill_route.rs, app/src/dex/router/mod.rs, app/src/dex/router/params.rs, app/src/dex/router/path_search.rs, app/src/dex/router/route_and_fill.rs, app/src/dex/router/tests.rs, app/src/dex/state_key.rs, app/src/dex/tests.rs
This PR has changes along the way to starting an arb implementation, split out since they're all mostly finished.
=> dex: prelude to on-chain arb implementation

app/src/action_handler/actions/delegate.rs, app/src/action_handler/actions/undelegate.rs, app/src/governance/view.rs, app/src/stake/component.rs, app/src/stake/rate.rs, chain/src/params.rs, crypto/src/asset.rs, crypto/src/asset/amount.rs, pcli/src/command/query/chain.rs, pcli/src/command/tx.rs, pcli/src/command/tx/approximate.rs, pcli/src/command/view/staked.rs, proto/proto/penumbra/core/chain/v1alpha1/chain.proto, proto/proto/penumbra/view/v1alpha1/view.proto, proto/src/gen/penumbra.core.chain.v1alpha1.rs, proto/src/gen/penumbra.core.chain.v1alpha1.serde.rs, proto/src/gen/penumbra.view.v1alpha1.rs, proto/src/gen/penumbra.view.v1alpha1.serde.rs, proto/src/gen/proto_descriptor.bin, view/src/planner.rs, view/src/service.rs, view/src/storage.rs, wallet/src/plan.rs
There are still some instances of u64 used for token amounts expressed in terms of penumbra tokens, but @hdevalence and @plaidfinch assure me that won't be an issue.
=> Remove existing usage of u64

pcli/src/network.rs, proto/proto/penumbra/view/v1alpha1/view.proto, proto/src/gen/penumbra.view.v1alpha1.rs, proto/src/gen/penumbra.view.v1alpha1.serde.rs, proto/src/gen/proto_descriptor.bin, view/src/client.rs, view/src/service.rs
This is useful for working with the DEX, where most of the queries are height-based.
Example output:
```
Running `target/release/pcli -n 'http://testnet-preview.penumbra.zone:8080' tx lp order buy '20penumbra@0.9gn' --spread 50`
Scanning blocks from last sync height 522 to latest height 522
[0s] ██████████████████████████████████████████████████       0/0       0/s ETA: 0s
building transaction...
finished proving in 0.874 seconds [4 actions, 3 proofs, 2542 bytes]
broadcasting transaction and awaiting confirmation...
transaction confirmed and detected: 278a6b0a6e7781097551dff250094c0494c32569470bf4f6411c832865d3b68c @ 523
```
=> pcli: print height of detected transactions

crypto/src/fixpoint.rs, crypto/src/fixpoint/tests.rs
This test should fail and overflow loudly, but instead it fails silently producing a nonsensical value.
=> crypto(fixpoint): add overflow failure test

docs/guide/src/SUMMARY.md, docs/guide/src/dev/rpc.md
Documents basic workflow for using Buf Studio to interact with the gRPC endpoints for pd and pclientd.
=> docs: add grpc docs to dev guide

app/src/dex/arb.rs, app/src/dex/component.rs, app/src/dex/mod.rs, app/src/dex/router/route_and_fill.rs, app/src/dex/state_key.rs, app/src/dex/tests.rs, proto/proto/buf.lock
=> Implement arbitrage

app/src/dex/position_manager.rs, app/src/dex/router/params.rs
The existing implementation isn't safe to deploy, because it scans every single position in the entire dex on every iteration of edge relaxation during routing.
=> dex: remove complex candidate set computation

Cargo.lock, wasm/src/view_server.rs
- Added a transaction_info wrapper function that deserializes JsValue into Transaction, and serializes TransactionPerspective and TransactionView into JsValue
- Added insert in notes_by_nullifier in block scan function   
Extras: 
We originally planned to change the initialization of ViewServer and pass in data about known notes during initialization. But we changed the architecture of the wallet extension so that it queries TxP and TxV from wasm during block scans and stores all transaction information in indexedDb, and in this scenario the ViewServer state will always have the notes we need to get TxP and TxV
=> Added wrapper function for wasm, TXV/TXP serialization and deserialization in JsValue, insert in notes_by_nullifier 

docs/guide/src/pcli/install.md, docs/guide/src/pcli/update.md, docs/protocol/src/zswap/concentrated_liquidity.md
This updates the guide to use the latest patch, and fixes a rendering issue with the protocol spec. I'm planning a follow-up pr to document current state of our dex architecture as the protocol spec is pretty outdated at this point.
=> guide: update to v0.52.2

pcli/src/command/query/dex.rs
Output:
```
Running `target/release/pcli q dex position plpid13jq86atertnwcw4zuacjhfuuxz93ptu69wnxsk97xckxhczqug8swd3akt`
Scanning blocks from last sync height 4290 to latest height 4522
[0s] ██████████████████████████████████████████████████     232/232     1575/s ETA: 0s
ID          plpid13jq86atertnwcw4zuacjhfuuxz93ptu69wnxsk97xckxhczqug8swd3akt
State       opened
Reserves 1  0lpnft_opened_plpid1930jpputl38kq4ae5t6j36rq5ydxzep4nem2tx5av87l4j5maass0e4fpf
Reserves 2  1lpnft_opened_plpid1ta9emmcxq9gvdfs299mk8gjc03rlwkxv4jme2f46uamaee294khszramt7
Fee         0bps
p           1
q           1
Nonce       5201f26167dacce0ebadfd8a67babda68f80eeb3e168d92d826a3785b55532a9
```
With `--raw`:
```
{
"phi": {
"component": {
"p": {
"lo": "1"
},
"q": {
"lo": "1"
}
},
"pair": {
"asset1": {
"inner": …
```
=> pcli: add pcli q dex position

proto/src/lib.rs, proto/src/protobuf.rs, proto/src/state/future.rs, proto/src/state/read.rs, proto/src/state/write.rs
As documented in [this Stack Overflow post](https://stackoverflow.com/questions/72626885/using-tryinto-generics-with-anyhowerror), the correct type bound to use is `From` instead of `Into` because `?` desugars to `.from()` instead of `.into()`. This also removes the need for the explicit `Send + Sync + 'static` bounds.
=> Fix `anyhow::Error` type bounds to use `From` instead of `Into`

deployments/scripts/rust-docs, pd/src/testnet.rs, pd/src/testnet/join.rs
When joining a testnet, `pd` will inspect the RPC endpoint for the bootstrap node and copy its known peers into the generated Tendermint config. To date, since #1847, that logic has also interpolated an incorrect address for the bootstrap node (by default currently `testnet.penumbra.zone:26657`): the RPC address shouldn't be used, the P2P address should be. This is particularly important when as we move toward updating our configs to default to HTTPS: we can no longer assume that the host portion of a service URL will be the same between the RPC and P2P endpoints. Instead, let's use the RPC to inspect what the correct ListenAddress is.
First, verify the misbehavior on main branch:
```
git checkout main
cargo run --release --bin pd -- testnet unsafe-reset-all
cargo run --release --bin pd …
```
=> fix(pd): look up listenaddr from tm rpc

crypto/src/dex/lp/order.rs, pcli/src/command/query/dex.rs, pcli/src/command/tx/replicate.rs, pcli/src/command/utils.rs
New output:
```
ID                                                                State     Fee        Sell Price               Reserves
plpid1d264h47q89wyelffkur84qg3wl7xhk33qsdq4n64ecpshwd87cuqj569f3  opened   0bps  906.365mpenumbra      49.804882test_usd
plpid1l98l8r4md6l27mlq3hestl297vmumq70mda7ft976574dc4dxqess0h2rj  opened   0bps      910mpenumbra             10test_usd
plpid1tvdew6z7pzeefystptlf6fppq3atj9wuccngnt876kdzc5d637qsz87hwx  opened  30bps  909.091mpenumbra    8638.937729test_usd
30bps  1.100001test_usd   38819.060718penumbra
plpid1n78syzdvjarkzcx6kna5d9742zmkfvq48eesk3sjt323s625wytqgppzrd  opened   0bps         1penumbra            500test_usd
plpid1w2dn9ddswhzm46ce6tc7cejq6dgf4xyans3r36pq5mx4sl8a4f5qyf8u87  opened   0bps  1.007072penumbra      52.537812test_usd …
```
=> Improved order display in `pcli`.

crates/core/crypto/src/fixpoint.rs, crates/proto/proto/buf.lock
We round down in the batch swap pro rata output calculation, so need to be able to do so in R1CS
=> crypto(zk): add rounding down to `U128x128Var`

crates/core/component/compact-block/src/component/view.rs, crates/core/component/compact-block/src/state_key.rs
We don't ever use the compact block inside the chain state.  Strictly speaking, it's not necessary to store it inside the verifiable part of the chain state, and keeping it outside allows it to be accessed more efficiently when serving clients (it can just be read directly from RocksDB, in a linear order...)
We don't currently verify the CB data with a light client anyways, but even if we wanted to, we probably wouldn't want to verify every single CB's merkle inclusion proof separately. One idea we discussed informally some time ago is to write the hash of the current CB into the state (to allow individual verification) and also to write a hash chain accumulator that hashes in each successive CB, so a client can stream many CBs all at once, hash them together in sequence, and then verify …
=> compactblock: store in non-consensus store

.github/workflows/wasm.yml
We want to see the output from `cargo tree` inspecting the dep graph of `mio` on any failure of the wasm workflow, since that's one of the first actions a dev would take in debugging.
=> ci: debug output during failed wasm checks

docs/guide/src/dev/rpc.md
Updates the documentation to use the HTTPS gRPC URLs implemented in #2341. The testnet URLs won't be live until next release, but that's on Monday, so we might as well update the docs now.
=> docs: use https grpc for buf studio

crates/wasm/src/view_server.rs
Issue: 
The extension handled lpnft as an unknown asset 
Solution: 
Added wasm function which allows to get asset values for lpnft
=> added wasm function to get lpnft asset

.github/workflows/buf-pull-request.yml, .github/workflows/buf-push.yml, docs/guide/src/dev/protobuf.md, proto/penumbra/buf.lock, proto/penumbra/buf.yaml
We'll need to revisit these values periodically and update them as we would any other dependency. That's preferable to tolerating numerous false negatives in CI, forcing devs to commit updates manually to track upstream changes.
Closes #2321.
=> ci: eliminate the chore of buf mod update

docs/guide/src/dev/parameter_setup.md
adds some docs about how to run benchmarks for our proofs and a table with the current performance
=> docs: add benchmark info to dev guide zk proof section

deployments/terraform/modules/node/v1/variables.tf
We've been encountering cpu ceiling given recent box additions, so here we raise the total number of nodes in the nodepool from 2 to 4. N.B. the diff says 1 -> 2, but we use a multizonal architecture, with 2 zones by default, so (1 -> 2) * 2 = 4.
=> deploy: grow cluster 2 -> 4 nodes

crates/core/component/dex/src/component/router/route_and_fill.rs, crates/core/component/dex/src/component/tests.rs
This PR fixes a bug that occurred at block 3424 of Testnet 53.
=> dex: discard previously executed macro routes (fix) 

crates/bin/pcli/src/command/query/dex.rs, crates/bin/pcli/src/command/tx.rs
Example output:
```
Compiling pcli v0.53.0 (/Users/hdevalence/code/penumbra/penumbra/crates/bin/pcli)
Finished release [optimized] target(s) in 23.75s
Running `target/release/pcli -n 'http://localhost:8080' q dex simulate 100000penumbra --into test_usd`
Scanning blocks from last sync height 3423 to latest height 3423
[0s] ██████████████████████████████████████████████████       0/0       0/s ETA: 0s
100000penumbra => 93820.028565test_usd via:
Trace                                          Subprice
58.788mpenumbra =>       58200wtest_usd        1.010104penumbra/1test_usd
52909.29182penumbra =>   52380.198901test_usd  1.010102penumbra/1test_usd
70.221mpenumbra =>       61794wtest_usd        1.136373penumbra/1test_usd
47090.579171penumbra =>  41439.70967test_usd   1.136364penumbra/1test_usd …
```
=> Add `pcli q simulate`

crates/core/transaction/src/transaction.rs
=> fix: update `Transaction::num_proofs` for recently added ZKPs

Cargo.lock, crates/core/component/ibc/Cargo.toml, deployments/scripts/rust-docs
I haven't tested this locally, since the rust docs script pins a nightly release I don't have installed, so yolo-merging instead.
=> Add `ibc-types`, `ibc-types2` to rust docs

crates/core/component/dex/src/component/router/fill_route.rs
This was suggested by @hdevalence, presumably to avoid churning over the same positions within a same frontier. I don't fully understand the ramifications of that change yet. I will adjust the PR description once I have worked out the consequences that this change has on the DEX engine.
=> dex(router): make `Frontier` position an append-only log

crates/bin/pcli/src/opt.rs, crates/bin/pclientd/src/lib.rs, crates/bin/pd/src/main.rs, crates/misc/measure/src/main.rs
As of Testnet 53 Himalia, the HTTPS endpoint for pd's gRPC service is live. We can now update the CLI defaults for all the binaries to use the HTTPS URLs for both pd and tendermint.
Refs #1886.
=> updates cli defaults to use HTTPS URLs

Cargo.lock, crates/core/component/ibc/Cargo.toml, deployments/scripts/rust-docs
Adding it to the repo caused breakage, because the existing `ibc-types` dep pins dependencies, and those pins conflict with `ibc-types2`.  The right fix is to remove the pins, but that is a slightly bigger fix than this temporary one.
=> deps: temporarily remove ibc-types2

deployments/charts/penumbra/templates/fn-deployments.yaml, deployments/charts/penumbra/templates/val-deployments.yaml
Refs #2709. We don't dial up the verbosity to global debug on all tendermint modules, because that would generate nearly 10x as many log lines, based on local smoke test run with logging overrides. We may selectively dial up on modules such as consenesus. Relevant docs:
* https://github.com/tendermint/tendermint/blob/main/docs/tendermint-core/running-in-production.md#logging
* https://github.com/tendermint/tendermint/blob/main/docs/tendermint-core/how-to-read-logs.md#list-of-modules
=> ci: debug logging for tendermint rpc calls

crates/bin/pcli/src/command/tx.rs, crates/core/crypto/src/address.rs, crates/core/crypto/src/keys/ivk.rs, crates/core/transaction/src/plan/memo.rs
Closes #2692
The problem in #2692 was:
1. In `TxCmd::exec` we generate an ephemeral address, but in manipulating the `memo` variable (`Option<MemoPlaintext>`), we set the variable to `None` when there is no other memo text, even when we want to provide the ephemeral address in the memo field. Link [here](https://github.com/penumbra-zone/penumbra/blob/2063191218df1bb93f062be4d2479d64ea388b36/crates/bin/pcli/src/command/tx.rs#L258-L266) to relevant code. By setting `memo` to `None`, the ephemeral address is not used.
2. Then, while planning the transaction, we end up populating the previously empty memo field with a default memo, which fills the sender field with a dummy address that is not legible to the sender.
=> fix: ensure ephemeral address of sender is put in memo field

crates/bin/pcli/src/command/tx.rs, crates/bin/pd/src/info/specific.rs, crates/core/component/stake/src/action_handler/delegate.rs, crates/core/component/stake/src/action_handler/undelegate.rs, crates/core/component/stake/src/rate.rs, crates/core/crypto/src/stake/identity_key.rs, crates/proto/src/gen/penumbra.client.v1alpha1.rs, crates/proto/src/gen/penumbra.client.v1alpha1.serde.rs, crates/proto/src/gen/proto_descriptor.bin, proto/penumbra/penumbra/client/v1alpha1/client.proto
Part 1 of #2630. State machine tests to follow later.
=> Use current rate data instead of next rate data for delegate/undelegate requests (#2360)

Cargo.lock, crates/core/component/dex/Cargo.toml, crates/core/component/dex/src/component/router/path_cache.rs, crates/core/component/dex/src/component/router/tests.rs
During the course of testnet `v0.53.1`, the state of a validator diverged from the rest of the network. After investigating, we found that the source of non-determinism was located in the path search logic of the DEX engine. The search phase is performed by spinning up concurrent tasks that perform relaxation over the different routes available for a given `src: asset::Id`. These tasks share a concurrent cache (`PathCache`) which keep a record of the two best available `Path<S>` seen, where best means lower cost. Every time an entry in the path cache is updated, we check whether we should update the best and spill path. At tag `v0.53.1`, this was the logic for the update branch:
```rust
pub fn update(&mut self, new_path: Path<S>) {
if new_path.price < self.path.price { …
```
=> dex(router): fix path search divergence

crates/core/component/dex/src/component/dex.rs, crates/core/component/dex/src/component/router/route_and_fill.rs, crates/core/component/dex/src/lp/trading_function.rs, crates/core/component/dex/src/swap/plaintext.rs, crates/core/component/dex/src/swap_claim/view.rs, crates/core/component/shielded-pool/src/spend/plan.rs, crates/core/crypto/src/memo.rs
Fixes a couple compiler warnings, usage of `expect` statements, obsolete TODOs.
=> crates: miscellaneous warning fixes, comment cleanup.

Cargo.lock, crates/bin/pcli/Cargo.toml, crates/bin/pcli/src/command/keys.rs, crates/bin/pcli/tests/network_integration.rs, crates/wallet/src/key_store.rs
Changes the behavior for `pcli keys import phrase` to prompt for a masked password input interactively. When run via a pipe, reads from stdin instead, which preserves the ability to import seed phrases from other tools.
Closes #2693.
=> pcli: import seed phrase from stdin

crates/bin/pclientd/src/lib.rs
Context: When testnets roll over, I clear out my state for pclientd and bounce the service. On 55, I unthinkingly removed the entire "home" directory for pclientd, which also removed the `config.toml` file containing the FVK. When running `pclientd start`, a rather unhelpful message about "No such file or directory" was displayed. Let's be a bit clearer about what we expect to exist.
=> feat: friendlier err msg for pclientd start

crates/core/component/dex/src/trading_pair.rs
When we're given a trading pair with non-canonical order, we can rearrange its fields to match the expected internal ordering instead of failing.
=> dex: canonicalize trading pairs when converting from pb

.github/workflows/buf-pull-request.yml, tools/proto-compiler/src/main.rs
Let's dial down the strictness on the protobuf codegen story. Here we retain the docs changes from #2739, but drop the requirement for a specific major version of `protoc`. Similarly, we remove the CI check that fails if diffs are detected in the generated `proto_descriptor.bin` file, because often those diffs are cosmetic, rather than substantive. We preserve the CI check for ensuring there are no diff elsewhere in the codegen outputs.
Closes #2736.
=> build: don't require a specific protoc version

crates/core/component/dex/src/component/action_handler/position/open.rs, crates/core/component/dex/src/component/action_handler/position/withdraw.rs, crates/core/component/dex/src/component/position_manager.rs, crates/core/component/dex/src/component/router/fill_route.rs, crates/core/component/dex/src/component/router/path.rs, crates/core/component/dex/src/component/router/tests.rs, crates/core/component/dex/src/component/tests.rs
This PR makes `put_position` async, allowing it to perform state reads. It also renames `index_position` to `index_position_by_price`. Helpful for #2378 and #2753
=> dex: make `put_position` async

crates/bin/pd/src/testnet/generate.rs
Ensures that at least some allocations were parsed from the csv input file, otherwise errors. Includes tests with hardcoded csv data.
Closes #2746.
=> fix(pd): error on bad csv for allocations

crates/core/component/dex/src/component/router/path.rs, crates/core/component/dex/src/component/router/path_cache.rs, crates/core/component/dex/src/component/router/tests.rs
=> dex(router): define ordering on `Path<S>`

crates/core/component/dex/src/component/action_handler/position/close.rs, crates/core/component/dex/src/component/action_handler/position/open.rs, crates/core/component/dex/src/component/action_handler/position/withdraw.rs, crates/core/component/dex/src/component/action_handler/swap.rs, crates/core/component/dex/src/component/action_handler/swap_claim.rs, crates/core/component/dex/src/event.rs, crates/core/component/shielded-pool/src/component/action_handler/output.rs, crates/core/component/shielded-pool/src/component/action_handler/spend.rs, crates/core/component/shielded-pool/src/component/note_manager.rs, crates/core/component/shielded-pool/src/event.rs, crates/core/component/stake/src/action_handler/delegate.rs, crates/core/component/stake/src/action_handler/undelegate.rs, crates/core/component/stake/src/component.rs, crates/core/component/stake/src/event.rs
This commit updates the event handling logic to rework existing events and fill in new ones:
- events are generated per transaction action, and action-triggered events are prefixed with `action_`
- added events for outputs, swaps, swap claims, and lp actions
I think it would be useful to also have events fired on position state changes, but I didn't want to do that in this PR in case of conflicts with in-flight changes to position handling.
=> events: add or rework events for shielded pool, dex actions

Cargo.lock, crates/bin/pcli/src/command/validator.rs, crates/bin/pd/src/testnet/generate.rs, crates/core/app/Cargo.toml, crates/core/app/src/action_handler/actions/proposal/deposit_claim.rs, crates/core/app/src/action_handler/actions/proposal/submit.rs, crates/core/app/src/action_handler/actions/proposal/withdraw.rs, crates/core/app/src/governance/view.rs, crates/core/component/governance/Cargo.toml, crates/core/component/governance/src/lib.rs, crates/core/component/governance/src/proposal_nft.rs, crates/core/component/governance/src/voting_receipt_token.rs, crates/core/component/stake/src/governance_key.rs, crates/core/component/stake/src/lib.rs, crates/core/component/stake/src/validator.rs, crates/core/crypto/src/governance.rs, crates/core/crypto/src/lib.rs, crates/core/transaction/Cargo.toml, crates/core/transaction/src/action/delegator_vote.rs, crates/core/transaction/src/action/proposal_deposit_claim.rs, crates/core/transaction/src/action/proposal_submit.rs, crates/core/transaction/src/action/proposal_withdraw.rs, crates/core/transaction/src/action/validator_vote.rs, crates/core/transaction/src/plan/action/delegator_vote.rs
This is for #2765 - `penumbra-governance` now has the bits from penumbra-crypto related to governance, except for `GovernanceKey` which is together with the validator definition in `penumbra-stake`.
=> refactor: move governance related items from crypto to governance crate

crates/proto/src/gen/penumbra.client.v1alpha1.rs, crates/proto/src/gen/penumbra.core.crypto.v1alpha1.rs, crates/proto/src/gen/penumbra.view.v1alpha1.rs, crates/proto/src/gen/proto_descriptor.bin, proto/go/gen/penumbra/core/crypto/v1alpha1/crypto.pb.go, proto/penumbra/penumbra/client/v1alpha1/client.proto, proto/penumbra/penumbra/core/crypto/v1alpha1/crypto.proto, proto/penumbra/penumbra/view/v1alpha1/view.proto
Adds a few explanatory comments to the protobuf message types:
1. Attempts to describe the expected shape of Address.
2. Explains the lo/hi denom representation of a uint128.
3. Explicitly mentions return type of `stream` where appropriate.
Refs #2768. Closes #2734.
=> docs: helpful comments on a few proto types

Cargo.lock, crates/core/asset/Cargo.toml, crates/core/component/dex/Cargo.toml, crates/core/crypto/Cargo.toml, crates/core/keys/Cargo.toml, crates/core/num/Cargo.toml, crates/core/transaction/Cargo.toml, crates/crypto/tct/Cargo.toml
Just released the poseidon crates such that our R1CS impl is used
=> chore: update poseidon377 to 0.5 release

.github/workflows/rust.yml
When we refactor rust crates, it's easy to break the rustdoc build by forgetting to update pinned versions in our rustdoc build script: `./deployments/scripts/rust-docs`. Let's run that script as part of the Rust checks in each PR, so we get notified promptly about breakage. We'll still only deploy new docs after PRs have been merged into main.
=> ci: check rustdoc build on PRs

Cargo.lock, crates/core/asset/Cargo.toml, crates/core/component/dex/Cargo.toml, crates/core/component/shielded-pool/Cargo.toml, crates/core/crypto/Cargo.toml, crates/core/keys/Cargo.toml, crates/core/num/Cargo.toml, crates/core/transaction/Cargo.toml, crates/crypto/tct/Cargo.toml
Bumping again after https://github.com/penumbra-zone/poseidon377/pull/52
=> chore: bump poseidon377 to 0.6.0

Cargo.lock, crates/bin/pcli/Cargo.toml, crates/bin/pclientd/Cargo.toml, crates/bin/pd/Cargo.toml, crates/core/component/dex/Cargo.toml, crates/core/component/governance/Cargo.toml, crates/core/component/shielded-pool/Cargo.toml, crates/core/component/stake/Cargo.toml, crates/core/transaction/Cargo.toml
Now that the ZKPs are in the individual component crates, they should have a parallel feature like `penumbra-crypto` to turn on and off parallel proving via rayon
=> add parallel features to component crates

deployments/relayer/README.md, deployments/relayer/build-path, deployments/relayer/configs/babylon-testnet.json, deployments/relayer/configs/penumbra-preview.json, deployments/relayer/configure-relayer
We encountered a long (~20s) timeout on all `rly` commands, and traced it to a context timeout on a bad URL for the bablyon testchain. We're still focusing on preview <-> devnet functionality, so let's exclude the external testnet chains from relayer configuration until we're ready.
Also includes some documentation updates so it's a bit easier to understand how test the relayer interactively. Eventually we'll want all this logic bottled up in integration tests, e.g. `interchaintest`, but still working toward that goal.
Refs #2612.
=> relayer: only configure penumbra chains

docs/guide/src/extension.md
Just ran through the procedure after release of v0.56.0, and jotted down some notes for folks to use.
Closes https://github.com/penumbra-zone/penumbra/issues/2748
=> docs: web extension testnet upgrades

Cargo.lock, crates/bin/pcli/tests/network_integration.rs, crates/core/component/dex/Cargo.toml, crates/core/component/dex/src/component/action_handler/position/open.rs, crates/core/component/dex/src/component/dex.rs, crates/core/component/dex/src/component/position_manager.rs, crates/core/component/dex/src/component/router/fill_route.rs, crates/core/component/dex/src/component/router/route_and_fill.rs, crates/core/component/dex/src/component/tests.rs, crates/core/component/dex/src/lp/trading_function.rs
=> dex: faillible dex execution

crates/core/asset/src/asset/registry.rs, crates/core/component/dex/src/component/action_handler/position/open.rs, crates/core/component/dex/src/component/router/tests.rs, crates/core/component/dex/src/lp/position.rs
=> dex: restore support for eth-like assets

docs/guide/src/dev/devnet-quickstart.md, docs/guide/src/pd/join-testnet.md
We crank up verbosity on our PL nodes and validators, because we want maximum visibility into application state. We don't need to recommend that everyone running a node does the same, given that log volume is clocking in around 20GB/week per pd instance running in a testnet.
=> docs: don't recommend verbose logs for nodes

crates/bin/pd/src/info.rs
queries for packet commitments always fail without this
=> ibc: start commitment_idx in packet commitment query at 1 to match ibc spec

crates/util/tendermint-proxy/src/tendermint_proxy.rs
The gRPCUI service was throwing an error on `TendermintProxyService.GetBlockByHeight`, with log messages pointing to `ns out of range [0, 1000000000]`. The relevant pbjson type [0] is not well documented, but consulting the associated protobuf type [1] makes it clear that we want subsecond nanos here.
Closes #2673.
[0] https://docs.rs/pbjson-types/0.5.1/pbjson_types/struct.Timestamp.html
[1] https://protobuf.dev/reference/java/api-docs/com/google/protobuf/Timestamp
=> fix(pd): use proper nanoseconds in tm proxy

crates/core/transaction/src/plan/build.rs
No more red crosses on our PRs, hopefully.
=> Fix unused mut qualifier causing CI to fail

deployments/ci.sh
grep PCREs isn't supported in OS X. I'm replacing this one by a POSIX friendly one
=> ci: use posix regex

crates/core/component/ibc/src/component/state_key.rs
Our packet commitment paths were wrong, because they were modeled on the IBC spec, which contains state commitment paths different than what is currently deployed in `ibc-go`:
https://github.com/cosmos/ibc/blob/854f2e13ccab539dd99d9889dd9367339875f73e/spec/core/ics-004-channel-and-packet-semantics/README.md?plain=1#L231
vs ibc-go:
https://github.com/cosmos/ibc-go/blob/56a519c188ae841818b9ecd11244240941cc5d90/modules/core/24-host/keys.go#L212
this PR brings the penumbra commitment paths inline with `ibc-go`.
Should address #2834, but let's avoid closing that issue until we confirm with testing.
=> fix packet commitment paths: use `sequences` correctly

testnets/names.txt
We're nearly at the end of the list of Jovian moons. We could tack on some recently discovered and lesser-known moons of Jupiter, but they don't have readable names, for the most part, which would defeat the point. So let's use the moons of Saturn to extend the list a bit, allowing us to refer to testnets by a human-readable name and keeping with the theme.
=> ci: add moons of saturn to testnet names

Cargo.lock, crates/bin/pcli/src/command/tx.rs, crates/bin/pd/src/info.rs, crates/core/component/ibc/src/component/channel.rs, crates/core/component/ibc/src/component/packet.rs, crates/core/component/ibc/src/component/proof_verification.rs, crates/core/component/ibc/src/component/transfer.rs, crates/core/component/ibc/src/ics20_withdrawal.rs, deployments/relayer/configs/penumbra-preview.json
- fix inversion in is_source logic
- fix inversion in Unreceived{Packets,Acks} query logic
- fix RecvPacket proof verification path
- fix encoding of packet commitments in RecvPacket proof verification
- fix timestamp encoding in `pcli tx withdraw`
After these fixes, I was able to execute a test ICS20 withdrawal from testnet-preview to a local devnet.
=> miscellaneous ICS20 fixes

Cargo.lock, crates/core/component/dex/Cargo.toml, crates/core/component/dex/src/component/position_manager.rs, crates/core/component/dex/src/component/router/path_search.rs, crates/core/component/dex/src/lp/trading_function.rs, crates/core/component/dex/src/state_key.rs, crates/core/component/ibc/src/component/transfer.rs, crates/core/num/src/amount.rs
This is missing tests.
Closes #2378
=> Index available liquidity as part of put_position

crates/bin/pclientd/src/main.rs, crates/bin/pd/src/info/oblivious.rs, crates/bin/pd/src/main.rs, crates/core/component/chain/src/component/view.rs, crates/narsil/narsil/src/bin/narsild.rs
Ensures that the binaries emit log messages showing which crate generated a specific message. Makes hunting down bugs a lot more straightforward. Also makes a few pd error messages a bit more precise.
=> feat(logging) include rust modules in log messages

crates/bin/pcli/src/command/tx.rs, deployments/relayer/configs/penumbra-preview.json
The `source` semantics isn't relevant to pcli UX, this seems better
=> ibc: pcli transaction withdraw: change source-channel to channel

docs/protocol/src/protocol/action_descriptions/delegator_vote.md, docs/protocol/src/protocol/action_descriptions/outputs.md, docs/protocol/src/protocol/action_descriptions/spend.md, docs/protocol/src/protocol/action_descriptions/swap.md, docs/protocol/src/protocol/action_descriptions/swap_claim.md
Once we started adding the clue key as part of the note commitment, we forgot to update the documentation. This PR fixes that, as well as adds missing closing parentheses for the state commitments.
=> spec: fix out of date note commitment docs, add closing parentheses

crates/core/component/dex/src/component/router/route_and_fill.rs
=> dex(router): internally split execution

.gitignore, crates/bin/pd/src/info/oblivious.rs, deployments/scripts/pcli-client-sync
Trying to resolve a memory leak in pd. These manual drops are a first pass, and appear to reduce memory consumption, but there's still a leak, according to bytehound. We'll continue to investigate.
Includes a missed `to_proto` that's a nice to have, but likely doesn't constitute a fix for our problem.
Refs https://github.com/penumbra-zone/penumbra/issues/2867.
Used this script to generate loadtests against a local pd instance, for memory profiling efforts. Steps I used to test:
pd testnet unsafe-reset-all
pd testnet join https://rpc.testnet-preview.penumbra.zone
./deployments/scripts/pcli-client-test -n 1000 -p 100
Refs #2867.
=> fix(pd): drop unused snapshots

.github/workflows/notes.yml, .github/workflows/rust.yml, .github/workflows/smoke.yml
Astria recently started using buildjet runners and ran into caching flakiness with the reliance on github cache, as alluded to [here](https://buildjet.com/for-github-actions/blog/launch-buildjet-cache#the-buildjet-cache-action). Created a fork of the rust cache that is built on top of `buildjet/cache` instead of `action/cache`, it's otherwise identical.
Figured I'd give you all the option to adopt, since I was inspired to use buildjet to speed up our builds by you.
=> ci: use buildjet cache for less flakiness

.github/ISSUE_TEMPLATE/release_testnet.md, crates/bin/pd/Cargo.toml
Now that we use `cargo-release` (#2384) we can automate the naive string substitutions for versions in the docs. This will remove precisely one checkbox from the release process checklist.
=> build: update docs version strings during release

crates/bin/pd/src/info/oblivious.rs, crates/bin/pd/src/main.rs
This PR is part of a series of performance improvements that we are making to `pd`. This PR specifically:
- terminate  the `compact_block_range` streams  if the outbound queue is full for more than `1s`.
- adds a servel-level timeout of `7s` to all request handlers
=> pd(oblivious): terminate client sync if it exceeds timeout

crates/bin/pd/src/main.rs, crates/core/component/dex/src/component/action_handler/swap.rs, crates/core/component/dex/src/component/arb.rs, crates/core/component/dex/src/component/dex.rs, crates/core/component/dex/src/component/metrics.rs, crates/core/component/dex/src/component/router/fill_route.rs, crates/core/component/dex/src/component/router/path_search.rs, crates/core/component/dex/src/component/router/route_and_fill.rs
Shipping some new dex-related metrics. Care has been taken to ensure that we are emitting Histogram, rather than Summary, data types. More info:
* https://prometheus.io/docs/practices/histograms/
* https://docs.rs/metrics-exporter-prometheus/0.10.0/metrics_exporter_prometheus/struct.PrometheusBuilder.html#method.set_buckets
The buckets themselves were surely need to be tweaked, but for now, I'm eager to get these new metrics onto preview, and will follow up with some visualization work.
Refs #2788.
=> feat(dex): add initial metrics to dex actions

crates/view/src/storage.rs
=> client: refactor balances query

deployments/compose/justfile, deployments/compose/metrics.yml, deployments/config/grafana/dashboards/Transactions.json, deployments/config/grafana/provisioning/datasources/all.yml, deployments/config/prometheus.yml, docs/guide/src/dev/metrics.md
Adds a visual histogram showing how long DEX path search takes. Also includes some overdue updates to the metrics docs, and some tooling I used locally to put the changes together.
Refs #2788.
=> feat(metrics): add dex path search histogram

crates/proto/src/gen/penumbra.view.v1alpha1.rs, crates/proto/src/gen/proto_descriptor.bin, proto/go/gen/penumbra/view/v1alpha1/view.pb.go, proto/penumbra/penumbra/view/v1alpha1/view.proto
We had a request from Zpoken to clarify whether we should support memos on swap actions. We should not! But that wasn't clear from the interfaces docs, so adding a note for future implementors.
=> docs(protos): clarify memo in tx planner

.dockerignore, .github/workflows/containers.yml, deployments/containerfiles/Dockerfile, deployments/containerfiles/Dockerfile-relayer
Removes several of the multi-stage build targets, and drops ostensible support for arm64, which wasn't working anyway (#2857). We now use a bog-standard Debian slim container for the runtime, with no manual wrangling of shared object files.
Closes #2858.
=> build: simplify container build

crates/core/app/src/action_handler/transaction.rs, crates/core/app/src/action_handler/transaction/stateless.rs, crates/core/app/src/mock_client.rs, crates/core/app/src/tests/mod.rs, crates/core/app/src/tests/spend.rs, crates/core/app/src/tests/swap_and_swap_claim.rs, crates/core/transaction/src/lib.rs
This PR fixes an issue found in one of the audits wherein one can vote for the same proposal ID multiple times using the same note if the delegator votes are in a single transaction (case 2 below). Noting for posterity: this was already reviewed in a private repository.
Some additional tests are added in this PR for the possible double spend cases. 
Cases attempting to double spend/vote in a single transaction:
1. We check for duplicate nullifiers across the same tx in `Transaction::check_stateless` for `Spends` and `SwapClaims` only - *a test is added in this PR for double spends in the same tx* (`spend_duplicate_nullifier_same_transaction`)
2. We were _not_ checking for duplicate nullifiers in the same tx for delegator votes (the bug) -  followup issue #2927 for tests
Cases double …
=> fix: delegator vote nullifier handling

crates/core/component/ibc/src/component/transfer.rs
The channel to be used for value balance should be the source channel on the chain that originally sent the funds, i.e. channel B in recv_packet, not channel A.
=> ibc: fix channel in recv_transfer_packet_inner

crates/bin/pcli/tests/network_integration.rs, crates/bin/pd/src/info/oblivious.rs, crates/bin/pd/src/main.rs
Part of #2918 (cc @conorsch ). We have isolated that the stream terminates because of the timeout on polling compact blocks. This PR reenable the req-resp timeout and increase the polling timeout to `2s`.
=> pd: remove client sync timeouts

crates/bin/pcli/src/command/query/ibc_query.rs, crates/bin/pcli/src/command/tx.rs, deployments/relayer/configs/penumbra-preview.json, docs/guide/src/pcli/transaction.md
Documents the rough-and-ready steps we've been using to exercise the developing IBC implementation. We only support preview/testnet for now, but we hope soon to add support for other, non-Penumbra testnet chains (#2284).
Closes #2907.
=> docs: ibc pcli actions in guide

Cargo.lock, crates/bin/pcli/Cargo.toml, crates/bin/pclientd/Cargo.toml, crates/bin/pd/Cargo.toml, crates/core/app/Cargo.toml, crates/core/component/chain/Cargo.toml, crates/core/component/ibc/Cargo.toml, crates/core/transaction/Cargo.toml, crates/proto/Cargo.toml, crates/view/Cargo.toml
We are switching to published crates later today. But to avoid any breakage, we need to point to this specific revision.
=> ibc-types: stop tracking main and use `rev`

crates/core/component/dao/src/action/dao_deposit.rs, crates/core/component/dao/src/action/dao_output.rs, crates/core/component/dao/src/action/dao_spend.rs, crates/core/component/dex/src/swap/action.rs, crates/core/component/dex/src/swap_claim/action.rs, crates/core/component/ibc/src/ics20_withdrawal.rs, crates/core/component/shielded-pool/src/output/action.rs, crates/core/component/shielded-pool/src/spend/action.rs, crates/core/transaction/src/action/proposal_deposit_claim.rs, crates/core/transaction/src/effect_hash.rs
Towards one of the checkboxes in #2808
Closes #2000
The scope of this PR is to in each `EffectingData` implementation hash a single proto that represents the effecting data of that transaction action.
=> crypto: rework action-level `EffectingData` implementations

crates/core/component/dex/src/lp/order.rs, crates/core/component/dex/src/lp/trading_function.rs, crates/core/num/src/fixpoint.rs
Followup from one of the audits. 
Inside the DEX logic for the infallible methods that call `U128x128::round_up`, what should happen? (cc @erwanor)
=> fix: make `U128x128::round_up` fallible

crates/storage/src/delta.rs, crates/storage/src/future.rs, crates/storage/src/lib.rs, crates/storage/src/read.rs, crates/storage/src/snapshot.rs, crates/storage/src/tests.rs, crates/storage/src/utils.rs
This PR adds support for range queries over the `nonverifiable` storage. It does so by:
- extending the `StateRead` trait with a new method:
```rust
/// Retrieve all values for keys in a range from the non-verifiable key-value store, as raw bytes.
/// This method does not support inclusive ranges, and will return an error if passed one.
///
/// Users should generally prefer to use wrapper methods in an extension trait.
fn nonverifiable_range_raw(
&self,
prefix: Option<&[u8]>,
range: impl RangeBounds<Vec<u8>>,
) -> Result<Self::NonconsensusRangeRawStream>;
```
- use a rocksdb range iterator to create an underlying stream of keys and values
- implements a `StateDelta`-level stream that interleaves caching layers and underlying storage.
Example API:
The first intended use of range queries is …
=> storage: implement `StateRead::nonverifiable_range`

Cargo.lock, crates/crypto/proof-setup/Cargo.toml, crates/crypto/proof-setup/benches/phase1.rs, docs/guide/src/SUMMARY.md, docs/guide/src/dev/parameter_setup.md
=> zk ceremony phase 1 benchmarking

crates/core/app/src/action_handler/transaction.rs, crates/core/transaction/src/effect_hash.rs, crates/core/transaction/src/memo.rs, docs/protocol/src/SUMMARY.md, docs/protocol/src/crypto/transaction_signing.md
Closes #2808
Adds a section of documentation on transaction signing which describe the changes made in this PR
=> rework transaction `EffectHash`

crates/bin/pcli/tests/network_integration.rs, crates/bin/pclientd/tests/network_integration.rs
Closes #2597
The tests currently just ensure that swaps are able to be submitted, the swap can be detected, and then a swap claim can be submitted. Testing of the internal mechanics and economics of swaps should be handled elsewhere.
=> Add network integration tests for swap/swapclaim

Cargo.lock, crates/bin/pd/src/info/oblivious.rs, crates/core/component/compact-block/Cargo.toml, crates/core/component/compact-block/src/component/view.rs, crates/core/component/compact-block/src/state_key.rs
This PR:
- implements a `stream_compact_block` method to `compact_block::StateReadExt` 
- remove the `block_fetcher` tokio tasks in `ObliviousQueryService::compact_block_range`
- use a single range query to catch-up on existing `CompactBlock`s
=> pd: use a range query for client synchronization

crates/crypto/proof-params/Cargo.toml, docs/guide/src/dev/parameter_setup.md
@hdevalence noticed that the pcli proving time is much faster than the reported benchmarks, that was because the `parallel` feature was turned off in the benchmarking code, and the `parallel` feature is turned _on_ in pcli. This PR updates the benchmarks to use the `parallel` feature, which results in proving times below 400ms for each proof.
=> doc: update ZKP benchmarks with parallel feature turned on

crates/core/app/src/app/mod.rs, crates/core/app/src/governance/view.rs, crates/core/component/chain/src/component/view.rs, crates/core/component/chain/src/state_key.rs, crates/core/transaction/src/proposal.rs, crates/view/src/storage.rs
This PR implement chain halts when the upgrade height specified in an `UpgradePlan` has been reached. It does this in three steps:
- when an `UpgradePlan` is enacted, we write the scheduled upgrade height in nonverifiable storage at key `chain/next_upgrade_height`
- when the target height is reached:
- trigger an early epoch change so that the upgraded chain starts at a clean epoch boundary
- after committing, shutdown gracefully
=> chain: implement upgrade halts

docs/protocol/src/protocol/addresses_keys.md, docs/protocol/src/protocol/addresses_keys/spend_key.md
This leaves a TODO we should address as part of #2964
=> docs: fix up key derivation chart

crates/core/component/dex/src/swap_claim/proof.rs, crates/core/component/governance/src/delegator_vote/proof.rs, crates/core/component/shielded-pool/src/nullifier_derivation.rs, crates/core/component/shielded-pool/src/output/proof.rs, crates/core/component/shielded-pool/src/spend/proof.rs, crates/core/keys/src/keys/seed_phrase.rs
This enables one to generate a 12- or 24 word seed phrase, instead of having a hardcoded 24 word seed phrase. 
Also adds test vectors referenced in the BIP39 spec for the 12-word phrases, in  https://github.com/trezor/python-mnemonic/blob/master/vectors.json.
=> crypto: allow 12 or 24 words mnemonic seed phrases

crates/bin/pcli/tests/network_integration.rs, crates/core/app/src/action_handler/actions/delegator_vote.rs, crates/core/component/governance/src/delegator_vote/proof.rs, crates/core/transaction/src/action/delegator_vote.rs, crates/core/transaction/src/plan/action/delegator_vote.rs
The `DelegatorVote` stateless checks verify both the action effect hash signature and the supplied proof against the validated public inputs. This PR changes the balance commitment used in the proof verification to match the one used in proof generation: a commitment to the `unbonded_amount` corresponding to the staked note, which represents the voting power at the time of delegation.
=> delegator_vote: use balance commitment to staked note

Cargo.toml
Our cargo actions were emitting a warning:
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
Updating the workspace's Cargo.toml to force use of resolver v1 for the workspace. Setting v2 broke the "rust-docs" script, so hardcoding the current behavior to eliminate warnings.
See related docs: https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html
=> build: set resolver=1 for workspace

Cargo.lock, crates/bin/pd/Cargo.toml, crates/bin/pd/src/main.rs
This PR adds a `pd export` command that copies the content of a full node data directory to an export target. It also incorporate an optional `--prune` flag that will compact the exported JMT state.
=> pd: export storage state

crates/bin/pclientd/src/main.rs
Same as b6ade69cbed3ecb1cc0c25a6403473ad71143725, but this time for pclientd, as well. Refs #2977.
=> fix(pclientd): disable r1cs logging

crates/core/transaction/src/effect_hash.rs, docs/protocol/src/crypto/transaction_signing.md
Followup from #2931 and [recent discussion in discord](https://discord.com/channels/824484045370818580/864913084028158012/1149384015032365117)
=> crypto: use `DetectionData` proto encoding for effect hash

crates/core/component/compact-block/src/lib.rs
=> Remove usage of "unwrap" in the compact-block component

crates/bin/pd/Cargo.toml, crates/bin/pd/src/lib.rs, crates/bin/pd/src/main.rs, crates/bin/pd/src/testnet/generate.rs, crates/bin/pd/src/upgrade.rs, crates/storage/Cargo.toml, crates/storage/src/storage.rs
This PR adds a `pd migrate` command that takes a snapshotted storage state and execute a migration operation on it. The result is an "upgraded" state and a genesis file that specifies the new initial height that CometBFT will start from as well as the hash of the application state.
=> pd:  implement `pd upgrade`

deployments/systemd/README.md, deployments/systemd/penumbra.service
Based on feedback in Discord for Testnet 59, some folks encountered
thread 'tokio-runtime-worker' panicked at 'must be able to successfully commit to storage:
IO error: While open a file for appending: /home/penumbra/.penumbra/testnet_data/node0/pd/rocksdb/004809.sst:
Too many open files', /home/penumbra/penumbra/crates/core/app/src/app/mod.rs:427:14
The recommended fix was to modify systemd configs, so I'm updating the documented defaults to match.
=> docs(deploy): add nofile limit to systemd configs

crates/core/component/dex/src/batch_swap_output_data.rs, crates/core/component/dex/src/component/dex.rs, crates/core/component/dex/src/component/router/fill_route.rs, crates/core/component/dex/src/component/router/params.rs, crates/core/component/dex/src/component/router/path.rs, crates/core/component/dex/src/lib.rs, crates/core/component/dex/src/lp/trading_function.rs, crates/core/component/dex/src/swap/proof.rs, crates/core/component/dex/src/swap_claim/proof.rs, crates/core/component/dex/src/trading_pair.rs
=> Remove usage of "unwrap" in the dex component

crates/core/component/distributions/src/lib.rs
=> Remove usage of "unwrap" in the distributions component

crates/storage/Cargo.toml, crates/storage/src/lib.rs, crates/storage/src/metrics.rs, crates/storage/src/snapshot.rs
This PR creates a `metrics` feature on `penumbra_storage` that is activated by default. The motivation for this addition is that downstream consumer of the crates may not necessarily want it.
=> storage: gate metrics collection behind a feature flag

crates/core/component/sct/src/component/view.rs, crates/core/component/sct/src/lib.rs
=> Remove usage of "unwrap" in the sct component

crates/core/component/stake/src/action_handler/validator_definition.rs, crates/core/component/stake/src/component.rs, crates/core/component/stake/src/lib.rs, crates/core/component/stake/src/penalty.rs, crates/core/component/stake/src/rate.rs, crates/core/component/stake/src/undelegate_claim/proof.rs
=> Remove usage of "unwrap" in the stake component

.github/workflows/rust.yml
Discussed in chat [0], let's try running "cargo check" for warnings inside the test action.
[0] https://discord.com/channels/824484045370818580/930523634945122314/1151655379785240616
=> ci: run cargo check with cargo test

crates/bin/pd/src/testnet/join.rs
During `testnet join` there are a few places where debug-formatting was applied to URLs, which made the log messages difficult to read. I stare at the these logging messages a lot, so I'm making them more readable from the get go.
=> feat(pd) display urls clearly in log messages

crates/bin/pclientd/src/lib.rs, crates/bin/pd/src/main.rs
Follow-up to #3032. Trying to keep the log messages maximally legible, particularly the service start messages.
=> feat(pd) more url formatting in logs

tools/parameter-setup/src/main.rs
=> Remove usage of "unwrap" in the parameter-setup crate

crates/bin/pcli/Cargo.toml, crates/bin/pd/Cargo.toml, crates/core/app/Cargo.toml, crates/storage/Cargo.toml
This bumps the `jmt` dependency to the latest release version, anticipating changes to the ICS23 API that will be implemented next. This version of the `jmt` crate incorporates the "update proofs" feature developed by Sovereign.
=> cargo: bump `jmt@0.7.0`

crates/bin/pd/src/testnet/join.rs, testnets/tm_config_template.toml
Makes a few changes to `pd`, designed to improve peering behavior on testnets:
* raises the default values for inbound/outbound peers
* limits the number of peers discovered during join to 5, randomized
We originally decided to add node discovery logic to aid in peering. There's a downside, however, to reusing all peers of the bootstrap node: the CI deployment nodes get swamped, and the network remains centralized on the nodes that Penumbra Labs run. Instead, let's just take a handful, at random, and trust the p2p gossip to discover more over time.
Refs #3056.
=> feat(pd): raises default peering limits

Cargo.lock, crates/wasm/Cargo.toml, crates/wasm/src/error.rs, crates/wasm/src/keys.rs, crates/wasm/src/lib.rs, crates/wasm/src/note_record.rs, crates/wasm/src/planner.rs, crates/wasm/src/storage.rs, crates/wasm/src/tx.rs, crates/wasm/src/utils.rs, crates/wasm/src/view_server.rs, crates/wasm/src/wasm_planner.rs
- added wasm planner which allows more flexible creation of TransactionPlan on TS side 
- added logic of storing and reading advice when scanning blocks
- added function for generating ephemeral address 
- planner reads data from indexedDB directly from rust
=> Improvements and fixes to wasm transaction planner and wasm view server

crates/bin/pd/src/consensus.rs, crates/bin/pd/src/info.rs, crates/bin/pd/src/upgrade.rs, crates/core/app/src/app/mod.rs, crates/core/app/src/temp_storage_ext.rs, crates/core/component/distributions/src/component.rs, crates/core/component/shielded-pool/src/component/shielded_pool.rs, crates/core/component/stake/src/component.rs
This PR adds support for handling an `InitChain` request when starting from a checkpointed state.
=> pd: perform a `InitChain` handshake during genesis migrations

crates/bin/pd/src/consensus.rs, crates/core/app/src/app/mod.rs, crates/core/app/src/temp_storage_ext.rs
In order to perform an `InitChain` handshake, we need to reset the application height to zero. After starting from a checkpointed genesis, we need to write the new post-genesis height back to the state.
=> pd: write post genesis height when starting from a checkpoint

crates/bin/pd/src/testnet/generate.rs, crates/bin/pd/src/upgrade.rs
After running the migration, we want to produce a checkpointed genesis that will fast-forward state initialization the next time the software boots up.
=> pd(upgrade): generate a checkpointed genesis post-upgrade

crates/view/src/storage.rs
Two bugs:
1. Spent commitments are being forgotten if they _are_ delegation tokens. Should flip the logic on that conditional.
2. Spent swap commitments are never delegation tokens.
Found while pairing 🍐 with @plaidfinch
=> [Bug fix] Forgetting delegation tokens

crates/core/transaction/src/effect_hash.rs, crates/core/transaction/src/transaction.rs
This PR adds a small helper method for decrypting memos given a `Transaction` cc @aubrika
=> crypto: add helper function for decrypting transaction memo

crates/view/src/storage.rs, crates/view/src/sync.rs
The statement previously was returning the wrong asset denomination, which meant we were forgetting delegation tokens because we thought they were upenumbra. This is now fixed, and some relevant debugging statements have been added.
=> Fix broken SQL statement that forgot the wrong notes

crates/bin/pd/src/consensus.rs, crates/core/app/src/app/mod.rs, crates/core/app/src/temp_storage_ext.rs, crates/core/component/distributions/src/component.rs, crates/core/component/ibc/src/component/ibc_component.rs, crates/core/component/shielded-pool/src/component/shielded_pool.rs, crates/core/component/stake/src/component.rs
This PR closes #3004, and simplifies chain initialization. It splits handling checkpointed genesis states and full genesis configurations. This allows skipping most of the component initialization work when a checkpointed state is provided, while leaving space for upgrade-specific health checks to be performed by each component's `init_chain`.
=> pd: fast chain init when starting from checkpoint

docs/guide/src/pd.md, docs/guide/src/pd/build.md, docs/protocol/src/SUMMARY.md, docs/protocol/src/crypto.md, docs/protocol/src/crypto/transaction_signing.md
Based on feedback in Discord. Also fixes a broken link in the guide.
=> docs: link directly to proper cometbft version

crates/view/src/storage.rs, crates/view/src/storage/schema.sql
=> Add amount_by_sender query to storage to return transaction amounts and denominations grouped by sender address

crates/bin/pd/src/info.rs, crates/core/component/chain/src/component/view.rs, crates/core/component/chain/src/lib.rs, crates/core/component/ibc/src/component/ibc_component.rs, crates/core/component/ibc/src/component/msg_handler/connection_open_ack.rs, crates/core/component/ibc/src/component/msg_handler/connection_open_try.rs, crates/core/component/ibc/src/component/msg_handler/recv_packet.rs, crates/core/component/ibc/src/component/proof_verification.rs, crates/narsil/narsil/src/ledger/info.rs
Previously, we hardcoded `0` when constructing IBCHeights (which consist of a revision number, and revision height) to verify that counterparties committed correct penumbra consensus states. This PR instead computes the revision number from the chain ID.
There is an underlying issue here, which is that [ibc-go enforces a relationship between the chain ID and the revision number](https://github.com/cosmos/ibc-go/blob/56a519c188ae841818b9ecd11244240941cc5d90/modules/light-clients/07-tendermint/client_state.go#L140). The revision number is always parsed from the chain ID, matching with a regex that matches chain ids in the form `.*[^\n-]-{1}[1-9][0-9]`. If the matching fails, the revision number is assumed to be zero. This is why, despite our chain ID not fitting this regex, our handshakes …
=> ibc: compute IBC heights from revision number derived by chain id

docs/guide/book.toml, docs/guide/src/SUMMARY.md, docs/guide/src/dev/ibc.md
Captures the detailed steps from PR [0] and records them in the developer documentation, so that more of the team can tinker with IBC functionality.
[0] https://github.com/penumbra-zone/penumbra/pull/3043
Refs #3062.
=> docs: add hermes relaying steps to dev guide

Cargo.lock, crates/bin/pcli/Cargo.toml, crates/bin/pclientd/Cargo.toml, crates/bin/pd/Cargo.toml, crates/core/app/Cargo.toml, crates/core/component/chain/Cargo.toml, crates/core/component/ibc/Cargo.toml, crates/core/component/ibc/src/component/connection.rs, crates/core/component/ibc/src/component/rpc/connection_query.rs, crates/core/component/ibc/src/component/state_key.rs, crates/core/transaction/Cargo.toml, crates/proto/Cargo.toml, crates/proto/src/protobuf.rs, crates/view/Cargo.toml
IBC on main will be broken until this is merged; we still had some of the ibc standard paths defined in the `penumbra-ibc` crate, which recently got changed. This broke compatibility, but these keys shouldn't even be in this crate. This PR removes the hardcoded `connection` keys and replaces them with the ones exposed by `ibc-types`, and also fixes the `ClientConnections` mapping logic to be consistent with the spec and the ecosystem.
This is blocking on release of a new version of ibc-types which includes a domain type we previously missed, `ClientPaths`
=> ibc: fix connection paths to use ibc-types

crates/bin/pcli/src/command/view/tx.rs, crates/core/component/ibc/src/ics20_withdrawal.rs
Now it looks like
```
Scanning blocks from last sync height 2965 to latest height 2965
[0s] ██████████████████████████████████████████████████       0/0       0/s ETA: 0s
Action Type       Description
Spend             [account 1] spent 3000penumbra
Output            1766penumbra to [account 1]
Ics20 Withdrawal  1234penumbra via channel-0 to osmo1kh0fwkdy05yp579d8vczgharkcexfw582zj488
Transaction Fee                0penumbra
Transaction Memo Sender        penumbrav2t1cus5kaxcdh3x6th437s9eslze9mnvmcdxyhw9px79ewfgpd7utu253m52dhevxgf7yqrx04qks5267ysx9rmn7ckhqf0lkc6c9jzr63y8tuvq8d8yh6vatzf7l49xa2xs5xrls
Transaction Memo Text
Transaction Expiration Height  0
```
=> pcli: display ics20 withdrawals in pcli v tx

deployments/charts/penumbra-node/templates/deployment.yaml, deployments/charts/penumbra-node/values.yaml, testnets/tm_config_template.toml
We've been raising the peering limits on our PL nodes, as the testnet grows, maxing out concurrent connections.
We also update the CometBFT default value for `p2p.allow_duplicate_ip` false -> true. The purpose of this option is raise the cost for attackers to spam a network with node/validator identities run on the same host. That's relevant for mainnet, but during testnet, we want to maximize the ability to peer, so newcomers can join in.
Refs #3056.
=> deploy: make peer limits customizable

docs/guide/src/pd/build.md, docs/guide/src/pd/join-testnet.md
We've migrated to cometbft v0.37.x on preview, and updated the docs at the same time, but it's too early for docs changes: those trying to join the currently active Testnet 61 must still use v0.34.27. When we release 62, we'll update the docs then to match.
Refs #2263.
=> docs: revert to cometbft v034 for testnet docs

.github/workflows/containers.yml, .github/workflows/deploy-testnet.yml, deployments/scripts/gha-repository-dispatch
There are a few container images used for Penumbra, but not managed within this repository:
* https://github.com/penumbra-zone/galileo
* https://github.com/penumbra-zone/osiris
* https://github.com/penumbra-zone/hermes
We leverage the Repository Dispatch feature [0] of GitHub actions, so that within penumbra-zone/penumbra CI actions, we can trigger container builds in those other repos.
[0] https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch
=> ci: build container images in external repos

crates/bin/pcli/Cargo.toml, crates/bin/pd/Cargo.toml, crates/core/app/Cargo.toml, crates/storage/Cargo.toml
Use `jmt@0.8.0` that includes the ics23 fix.
=> cargo: use `jmt@0.8.0`

Cargo.lock, crates/bin/pd/Cargo.toml, crates/bin/pd/src/main.rs, crates/narsil/narsil/Cargo.toml, crates/narsil/narsil/src/bin/narsild.rs
While working on #2263, noticed that we aren't using the most recent version of tower-abci. This change bumps to latest, ahead of upcoming more substantive changes in v0.11.0 [0]. Opted to preserve the TCP-only ABCI support for pd out of simplicity.
Also includes mention of `jmt` in the cargo lockfile as a follow-up to f482b485ad265511e2040fa2d9090c5bc04273c7.
[0] https://github.com/penumbra-zone/tower-abci/issues/34
=> build(pd): upgrade to tower-abci v0.10.0

crates/core/component/ibc/src/component/msg_handler/connection_open_ack.rs, crates/core/component/ibc/src/component/msg_handler/connection_open_try.rs
previously, our validation of heights was too permissive.
https://github.com/cosmos/ibc-go/blob/56a519c188ae841818b9ecd11244240941cc5d90/modules/core/03-connection/keeper/handshake.go#L177
=> ibc: use GTE instead of GT in client height comparison

crates/proto/src/gen/penumbra.core.app.v1alpha1.rs, crates/proto/src/gen/penumbra.core.component.chain.v1alpha1.rs, crates/proto/src/gen/penumbra.core.component.compact_block.v1alpha1.rs, crates/proto/src/gen/penumbra.core.component.dex.v1alpha1.rs, crates/proto/src/gen/penumbra.core.component.governance.v1alpha1.rs, crates/proto/src/gen/penumbra.core.component.sct.v1alpha1.rs, crates/proto/src/gen/penumbra.core.component.shielded_pool.v1alpha1.rs, crates/proto/src/gen/penumbra.core.component.stake.v1alpha1.rs, crates/proto/src/gen/penumbra.custody.v1alpha1.rs, crates/proto/src/gen/penumbra.narsil.ledger.v1alpha1.rs, crates/proto/src/gen/penumbra.tools.summoning.v1alpha1.rs, crates/proto/src/gen/penumbra.util.tendermint_proxy.v1alpha1.rs, crates/proto/src/gen/penumbra.view.v1alpha1.rs, tools/proto-compiler/Cargo.lock, tools/proto-compiler/Cargo.toml
This generates `max_decoding_message_size` methods we need to configure the summoner service.
=> proto: use tonic-build 0.9

crates/bin/pd/src/testnet/config.rs, testnets/cometbft_config_template.toml
As of CometBFT v0.37.x, fastsync has been deprecated in favor of blocksync, but v0.38.x will disregard both options. We can't yet update the value since we're on v0.37.x still, but I'm still pulling in the config file changes to comments and explanations created by diffing a newly generated CometBFT config against our TOML template.
Refs #3144. Refs #2263.
=> chore: update cometbft config template

crates/core/component/stake/src/component.rs
We should only initialize the consensus keys when we are doing a full chain bootstrap. Otherwise, we are zeroing out the tendermint validator update.
=> component(stake): only init the consensus keys in bootstrap

Cargo.lock, crates/crypto/proof-setup/src/all.rs, tools/summonerd/Cargo.toml, tools/summonerd/src/coordinator.rs, tools/summonerd/src/main.rs, tools/summonerd/src/storage.rs, tools/summonerd/src/storage/schema.sql
=> Implement persistent storage in summonerd

crates/bin/pd/src/info.rs, crates/core/component/chain/src/component/app_hash.rs
Previously, we would error in the ABCI query interface if a key was not found. This PR changes that behavior to instead return an empty vec for the requested value, along with a nonexistence proof to the root hash showing the value doesn't exist in the state.
This is required for relayers to build timeout packets. I verified that this change works locally using hermes.
=> abci query: support nonexistence proofs

crates/bin/pcli/src/command/query/ibc_query.rs, crates/core/component/ibc/src/component/rpc/client_query.rs
Previously pcli was only capable of looking up info on IBC clients, connections, and channels if the user provided a unique identifier for the resource in question. To facilitate IBC in practice, we want to enable querying for lists of these values, so the end user (or developer) can inspect the current options in a legible format.
Closes #2937.
=> feat(pcli): support new ibc query logic

crates/bin/pd/src/testnet/join.rs, deployments/charts/penumbra-node/templates/NOTES.txt, deployments/charts/penumbra-node/templates/deployment.yaml, deployments/charts/penumbra-node/templates/ingressroute.yaml, deployments/charts/penumbra-node/values.yaml, deployments/helmfile.d/penumbra-devnet.yaml, deployments/helmfile.d/penumbra-preview.yaml, deployments/helmfile.d/penumbra-testnet.yaml, deployments/helmfile.d/vars/penumbra-devnet-nodes-ips.yml, deployments/helmfile.d/vars/penumbra-preview-nodes-ips.yml, deployments/helmfile.d/vars/penumbra-testnet-nodes-ips.yml, deployments/scripts/get-lb-ips
When joining a network via `pd testnet join`, pd already inspects the peers known to the target bootstrap node, and includes those peers in the generated CometBFT config. Technically it's not correct to assume that these peers are seeds, but limiting to a threshold (#3063) ensures that only a few nodes will be miscategorized this way.
The new behavior introduced here is that `pd testnet join` will inspect monikers of peers learned from the bootstrap node, and if the string "seed" appears in the moniker, guarantee that peer lands in the `seeds` field of the CometBFT config.
To complement this change, we update the deployment logic to create a seed node, and ensure that seed node is excluded from the loadbalanced RPC, to avoid hitting it via the join request (in which case it won't report …
=> feat(pd): special handling of seed nodes in join

deployments/helmfile.d/vars/penumbra-devnet-nodes-ips.yml, deployments/helmfile.d/vars/penumbra-preview-nodes-ips.yml, deployments/helmfile.d/vars/penumbra-testnet-nodes-ips.yml, deployments/scripts/get-lb-ips
Follow up to #3155. We've been using moon names as a mnemonic for human-readable names for services related to Penumbra testnets. Due to a typo, the moon of Neptune "Naiad" was misspelled, and that typo made it into a few config files. This is a purely cosmetic change with zero impact on service behavior or performance.
=> ci: fix moon names in host monikers

crates/bin/pclientd/src/lib.rs, crates/bin/pclientd/src/proxy.rs, docs/guide/src/pclientd/rpc.md
Related to #3120, this does a silly quick fix, should be replaced by the generic method described there.
=> pclientd: silly proxy fix workaround

docs/guide/src/pd/build.md, docs/guide/src/pd/join-testnet.md
Revert "docs: revert to cometbft v034 for testnet docs" This reverts commit be6e8aa952360fd7b766b2cb69f9518410a4ad3f.
Sprinkles in some clarifying language based on discussion in Discord.
=> docs: update cometbft to v0.37.2 for Testnet 62

crates/wasm/src/view_server.rs
The extension is current receiving `number` type for block height. Everywhere else it's treated as a `BigInt`. Changing the serialization on ScanBlock for consistency.
@Valentine1898 fyi
=> Serialize u64 as bigint [wasm]

tools/summonerd/src/coordinator.rs
No issue addressed here, but this is a quick fix to the coordinator loop to be able to send updates to clients whenever the queue changes.
I also took the opportunity to fix a bug I noticed, which was that by sorting addresses by the amount bid, we were then choosing the lowest bid, and not the highest.
The idea with the new queue is to create a merged event stream of new participants, and the completion of contributions, and then react to which of those is happening first in the loop accordingly.
=> Make Summonerd a bit more responsive & Fix ranking bug

crates/bin/pd/src/main.rs
Adding a specific error message for a failure mode of `pd` when using `--grpc-auto-https`: if run as a normal user, the bind to 443 will fail. That's OK, but state clearly what operation failed. Without this change, the error message is simply "Permission denied", with no mention of the attempted bind on 443.
=> feat(pd): specific error msg for auto https

crates/crypto/proof-setup/src/all.rs, crates/crypto/proof-setup/src/single/phase1.rs, tools/summonerd/src/coordinator.rs, tools/summonerd/src/main.rs, tools/summonerd/src/storage.rs, tools/summonerd/src/storage/schema.sql
Closes #3156
Note that I have intentionally not done the transition from the provided phase 1 to phase 2, which will be done in #3158 which I'll pick up after this one.
=> summoner: provide phase 1 root during ceremony initialization

deployments/compose/docker-compose.yml
Dusted off the compose setup and updated it to use an initcontainer, same as with the recent overhaul of deploy logic (#2983). This change also removes the requirement for the host machine to use `pd` to bootstrap the config: now, docker-compose is all that's required. The goal is to make the Penumbra containers easier to work with, for example for the block explorer push.
=> deploy: update docker-compose setup

.github/workflows/buf-pull-request.yml, docs/guide/src/dev/protobuf.md
For some reason, I was able to work around the caching issue locally by upgrading to `protoc@24.4` and `buf@1.27`
=> penumbra: regen proto with `protoc@24.4`

Cargo.lock, crates/wasm/src/error.rs, crates/wasm/src/keys.rs, crates/wasm/src/storage.rs, crates/wasm/src/tx.rs, crates/wasm/src/utils.rs, crates/wasm/src/view_server.rs, crates/wasm/src/wasm_planner.rs
- Moving chain+fmd params to be passed in versus grabbing global indexdb tables
- adding error console hook to all wasm-bindgen functions. Without this, we cannot debug from javascript.
=> Tx planner updates [wasm]

Cargo.lock, crates/bin/pcli/src/command/ceremony.rs, crates/crypto/proof-setup/Cargo.toml, crates/crypto/proof-setup/benches/all.rs, crates/crypto/proof-setup/src/all.rs, crates/crypto/proof-setup/src/lib.rs, crates/crypto/proof-setup/src/parallel_utils.rs, crates/crypto/proof-setup/src/single/phase1.rs, tools/summonerd/Cargo.toml, tools/summonerd/src/coordinator.rs, tools/summonerd/src/participant.rs, tools/summonerd/src/phase.rs, tools/summonerd/src/storage.rs
Closes #3202, although I'm not quite sure we're exploiting everything we can.
In particular, the way you enable parallelism in arkworks through spooky action at a distance always makes me unsure if I've done things correctly. Would appreciate a review of that specifically.
(Also, I refactored some of the code so this PR ends up being a net decrease in loc 8^))
=> Improve summonerd performance through parallelism

tools/summonerd/src/storage.rs
Cuts another chunk of time off of contributions
=> Summonerd: remove unnecessary checked parsing when fetching root

.github/workflows/summoner_smoke.yml, crates/bin/pcli/src/command/ceremony.rs, deployments/scripts/smoke-summoner.sh
Closes #3189
Thanks to #3208 the runtime of this went from ~60m down to ~18m! One can see a successful run of the CI job [here](https://github.com/penumbra-zone/penumbra/actions/runs/6590202104/job/17906325476?pr=3204) which was executed on the second to last commit here: f548956c744086992590ce1f8bc73798138e8877.
I've used the [`workflow_dispatch` option](https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow) to only run this job on demand (will work once the CI job is on the default branch), and on merges into `main`. It may make sense later to run the job only nightly/weekly instead of every merge into `main`, but while the summoner is under active development I think running on merge into `main` is reasonable.
=> test: run e2e test of ceremony in CI

crates/bin/pcli/src/command/view/tx.rs
This fixes the first issue described in ticket #2547, wherein the trading pair was displayed as unknown, even though the relevant denoms might be available in the asset cache for display to the user.
=> fix display of trading pairs in opaque `SwapClaim`s

crates/bin/pcli/Cargo.toml, crates/bin/pcli/src/command/ceremony.rs, tools/summonerd/src/coordinator.rs, tools/summonerd/src/participant.rs, tools/summonerd/src/server.rs
=> Minor ceremony UX improvements

tools/summonerd/src/coordinator.rs, tools/summonerd/src/main.rs, tools/summonerd/src/participant.rs, tools/summonerd/src/queue.rs, tools/summonerd/src/server.rs
=> Simplify state management in summonerd

deployments/charts/penumbra-node/files/postgres-cometbft-schema.sql, deployments/charts/penumbra-node/templates/configmap-postgresql-cometbft-schema.yaml, deployments/charts/penumbra-node/templates/deployment.yaml, deployments/charts/penumbra-node/templates/pvc.yml, deployments/charts/penumbra-node/templates/service.yaml, deployments/charts/penumbra-node/values.yaml, deployments/helmfile.d/penumbra-preview.yaml
The penumbra-node chart now has opt-in support for storing CometBFT events in a postgres sidecar. See relevant docs at [0]. The sole downstream use case for this work to date is cuiloa [1], a block explorer for Penumbra. There are some shortcuts in this logic, mostly related to hardcoding db connection info, but the db is intra-cluster cluster only, so the risk is minimal. Prioritizing developer velocity right now.
[0] https://docs.cometbft.com/v0.37/app-dev/indexing-transactions#postgresql
[1] https://github.com/ejmg/cuiloa
=> deploy: add support for cometbft postgres indexing

.github/workflows/smoke.yml
=> Disable buildjet caching on smoketest workflows

Cargo.lock, tools/summonerd/Cargo.toml, tools/summonerd/src/main.rs, tools/summonerd/src/storage.rs, tools/summonerd/src/web.rs, tools/summonerd/templates/main.html
Towards #3220. 
Initial axum integration using the existing `Storage` database
Adds some initial docs (phase independent such that this can be used for phase 1 internally)
Next steps here are to implement #3230 and then display information about the queue itself
Summoner CI kicked off here: https://github.com/penumbra-zone/penumbra/actions/runs/6659842327
=> initial summonerd web view

deployments/charts/penumbra-network/templates/deployment.yaml, deployments/charts/penumbra-network/templates/job-generate.yaml, deployments/charts/penumbra-network/values.yaml
On Testnet 62 Iapetus, we experienced a chain halt at block height
279655. We recently removed debug logging from the testnet nodes, which caused problems for figuring out what went wrong. Full debug output generates a lot of text, which raises hosting costs. Here, we selectively re-enable debug just on the validator nodes, where it's most useful.
=> ci: enable debug logging for validators

deployments/charts/penumbra-network/files/validators.json, deployments/relayer/penumbra.tpl
The validator config injection is less than awesome: we're still generating a validator config json file as part of the "new-testnet" script, but the deployment logic overrides that with a custom config file. Until we clean up that confusing separation, we'll overlook tiny problems like #3247.
=> ci: update funding streams for new address

crates/crypto/proof-setup/benches/all.rs, crates/crypto/proof-setup/src/single/phase1.rs
There was some vestigial debugging aid code doing many pairings instead of a batched pairing checks; this was very slow. Removing this code, we get a verification time of 4s, rather than 2+ minutes.
=> Proof-Setup: Use faster verification method for phase1

.github/workflows/release.yml, Cargo.toml, crates/bin/pd/Cargo.toml
During release of Rhea 63, we encountered build errors for folks with outdated rust versions. Our CI jobs using 1.65 also failed. N.B. we're behind on `cargo-dist` versions; upgrading that tool may ease this change.
Refs #3182.
=> build: require rust 1.73

crates/bin/pcli/src/config.rs
Follow up to the new `pcli init` logic [0], adding a more informative error message, in case folks forget to rotate their address format, as required by Rhea 63.
[0] https://github.com/penumbra-zone/penumbra/pull/3239
=> feat(pcli): more informative error message

Cargo.lock, tools/summonerd/Cargo.toml
Downgrades clap in summonerd v4 -> v3, to match other CLI tooling. Essentially reverts 7bb3e800824a8cdc6fe866d6dbe146420ed4ca94. With clap v3, there's extra whitespace between long-arg descriptions, due to our use of long_about in summonerd help docs. A major downside to clap v4 is colorized output doesn't appear to be supported for derive-style (it may be for builder-style, but we don't use that).
There's upstream progress on stabling color support, but until then, let's just stick with v3 and put up with the whitespace.
=> fix(summonerd): colorized cli output, via clap v3

Cargo.lock, tools/summonerd/Cargo.toml, tools/summonerd/src/main.rs, tools/summonerd/src/queue.rs, tools/summonerd/src/storage.rs, tools/summonerd/src/web.rs, tools/summonerd/templates/main.html, tools/summonerd/templates/phase1.html, tools/summonerd/templates/phase2.html
Closes #3220
This splits the web app into three pages.
This currently displays the current phase, where the current phase info is determined by looking in the database to see if the transition between phase 1 and 2 has occurred. 
It also contains instructions for this phase, where the `--phase` CLI arg is populated using the information determined as above. 
Remaining TODOs:
- [-] Populate the text on the page with the COORDINATOR_URL and SUMMONER_ADDRESS - no longer needed as we will hardcode these in pcli to simplify the user's experience
These are identical pages, one per phase, that show the:
- The number of contributions in that phase
- The most recent 5 contributions: short address, hash, time of contribution completed
Remaining TODOs:
=> updates for summonerd webapp

deployments/scripts/smoke-summoner.sh
The summonerd smoke test is failing on main after #3258 - after that summonerd will by default use 8080, but that port is used by the devnet, so instead let's have the summoner use port 8082. This _should_ fix the smoke test 🤞
=> test: update summonerd smoke test for bind address change

tools/summonerd/src/config.rs, tools/summonerd/src/coordinator.rs, tools/summonerd/src/main.rs, tools/summonerd/src/phase.rs, tools/summonerd/src/storage.rs
=> Summonerd: Make bids and timeouts configurable

crates/bin/pcli/src/command/ceremony.rs, tools/summonerd/src/server.rs
The final URL will change, but the address is stable.
=> Hardcode summonerd values in pcli

crates/bin/pcli/src/command/ceremony.rs, crates/crypto/proof-setup/src/all.rs, crates/crypto/proof-setup/src/parallel_utils.rs, crates/crypto/proof-setup/src/single/phase1.rs, crates/crypto/proof-setup/src/single/phase2.rs
Because some of the circuits are smaller, you want a slightly more intrusive level of parallelization for some operations,
in order to more effectively distribute work. This PR does that in a couple places.
Deserialization, which needs to validate elements, now parallelizes the validation in each circuit. (The infamous scalar multiplications).
Parallelize phase1 contribution creation further, now it consistently utilizes all cores.
The client side part is less important, since we don't control it, but it's still nice if beefier contributors can finish making their contribution faster.
=> Further summonerd parallelization

crates/bin/pcli/src/command/ceremony.rs
Migrate away from a dev / test URL, and also avoid hardcoding a wallet address, since this might change more readily.
=> Ceremony: use hardcoded URL but not wallet address

.github/workflows/deploy-preview.yml, deployments/ci.sh
This reverts commit 155df60540ada18f8c4315d41b1a3bfad11dd76d, which itself reverted commit 25c4e6fd531136f97bbdee71aef269f05c35ccf0.
ci: use helmfile gha helper
For including helm-diff, required for running "helmfile apply"
Refs #3279.
=> ci: use apply rather than sync for deploys

deployments/charts/penumbra-node/templates/ingressroute.yaml, deployments/charts/penumbra-node/values.yaml
Ensures that the ad-hoc changes made to the HTTPS reverse proxy fronting the pd gRPC services persist. We want to ensure that the pd gRPC services is usable with https://buf.build/studio/, and now it is.
Refs #3281.
=> ci: set cors headers for buf studio

crates/view/src/worker.rs
This isn't a permanent fix, and it's not the right way to solve the robustness issue (more details TK) but it may help with the immediate problem with `summonerd`, and seems unlikely to add new failure modes.
=> view: hack attempting to mitigate split-brain GRPC failures

.github/workflows/buf-pull-request.yml
Also ensures we're using the most recent stable version of buf across all workflows, via the `v1` version specifier.
Closes #3292.
=> ci: only run buf lint on PRs against main

crates/bin/pd/src/main.rs, crates/narsil/narsil/src/bin/narsild.rs
Setting `default_value = "false"` to a boolean flag, actually makes it default to true.
=> pd: disable tokio console support by default
